### ISSUE TITLE
Error in release

### ISSUE THREAD

**Issue by markjacksonfishing** [jenkinsci/gitlab-plugin#1018]
Error in plugin release

**Comment by markjacksonfishing** [comment]
@omehegan I'll need to work with you to get this release out and also document the process for transparency

**Comment by omehegan** [comment]
@markyjackson-taulia in the past all we have needed to do was run `mvn release:prepare release:perform` as described in the README. I don't know what has gotten broken in recent times but I'm sure we can work it out.

**Comment by markjacksonfishing** [comment]
I worked on it this morning before surgery. Out of it for the next few hours but will pick debugging tomorrow.

**Comment by omehegan** [comment]
@markyjackson-taulia cool! I just tested the master branch and I am able to build and deploy a snapshot to the update center, so that suggests that the basics of auth and access are working. But ISTR that you and I both had the same failure when we tried to do a full release. I just can't remember what it was. If you can't get it working tomorrow, post the error here and I can raise it with the core infra/release maintainers and see if they can help.

**Comment by omehegan** [comment]
@markyjackson-taulia did you make any progress on this?

**Comment by markjacksonfishing** [comment]
No, I have been in a work outage for the last few hours. My goal is to try more tomorrow or Tuesday

**Comment by mat1e** [comment]
Hello, do you have any news on this issue? We are waiting for the next release...

**Comment by geraintwhite** [comment]
@markyjackson-taulia when can we expect to see the next release?

**Comment by reinholdfuereder** [comment]
I guess this issue explains why the non-latest v1.5.13 from 12 Sept 2019 (!) still appears as the latest in my Jenkins (cf. https://updates.jenkins-ci.org/download/plugins/gitlab-plugin/):
* Maybe someone like @oleg-nenashev -- also known as the guy who knows anything about Jenkins -- can give a broad hint?

**Comment by oleg-nenashev** [comment]
@reinholdfuereder The recent versions of the plugin require the 2.190.x baseline or above. If you use older Jenkins versions, the updates will not be available in the update center

**Comment by reinholdfuereder** [comment]
@oleg-nenashev Thanks for the hint, but I am using the latest and greatest v2.220 ;-)

I naively (?) thought that the GitLab plugin releasing is broken which I naively (?) thought is proven by the download site showing no new versions anymore (cf. https://updates.jenkins-ci.org/download/plugins/gitlab-plugin/)...

**Comment by markjacksonfishing** [comment]
The artifact in the update center is messed up. I will working to fix that
