### ISSUE TITLE
updateGitlabCommitStatus stuck at 'running'

### ISSUE THREAD

**Issue by pertrai1** [jenkinsci/gitlab-plugin#1042]
### Before submitting an issue I have first:

- [x] read the documentation on the [homepage](https://github.com/jenkinsci/gitlab-plugin) 
- [x] searched for similar already existing issue
- [x] confirmed that my GitLab webhook is using the http://JENKINS_URL/project endpoint and not the http://JENKINS_URL/job endpoint

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue

When my pipeline has completed, the message in the PR is stuck at `running`. I have a declarative jenkinsfile setup and have this as my `post`:

```
post {
    failure {
      updateGitlabCommitStatus name: 'build', state: 'failed'
      emailext (
        subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
        <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
        recipientProviders: [[$class: 'DevelopersRecipientProvider']]
      )
      addGitLabMRComment(comment: 'The Jenkins Pipeline Failed')
    }
    success {
      updateGitlabCommitStatus name: 'build', state: 'success'
      emailext (
        subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        body: """<p>SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
          <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
        recipientProviders: [[$class: 'DevelopersRecipientProvider']]
      )
      addGitLabMRComment(comment: 'The Jenkins Pipeline Passed')
    }
  }
```

Any help would be great. Thank you

**Comment by rsimpson2** [comment]
This no longer is an issue

**Comment by varrix** [comment]
@rsimpson2 Since when?

**Comment by pertrai1** [comment]
@varrix It was a particular issue that I was having that once I made a change in the configuration it no longer was stuck at running. Now the PR shows the steps that the pipeline is in.

**Comment by varrix** [comment]
@pertrai1 Ah, was hoping for information regarding updateGitlabCommitStatus :/

**Comment by mucst** [comment]
Is this issue still valid? I have experienced sometimes that jenkins is stuck at the very end of the script for unknown reasons. I advise that you check whether you are not running low on disk space or try to restart the jenkins application, clean workspace etc. 

What's the last line that is executed in this snippet again?

**Comment by varrix** [comment]
@tamasmucs I found that can be due to log rotation settings on the pipeline. Once I disabled it, I stopped getting stuck pipelines IN Jenkins.

**Comment by markjacksonfishing** [comment]
Yes, please disable as noted anove
