### ISSUE TITLE
addGitLabMRComment shows "No GitLab connection configured" but updateGitlabCommitStatus is fine

### ISSUE THREAD

**Issue by zdtsw** [jenkinsci/gitlab-plugin#1049]
### Context
- **Gitlab plugin version**: 1,5,13
- **Gitlab version**: 11.11.8 (1d18d065069
- **Jenkins version**: 2.190.3
- **Job type**: Pipeline

### Logs & Traces
14:11:30  Wed Apr 22 14:11:30 CEST 2020
[Pipeline] deleteDir
[Pipeline] addGitLabMRComment (hide)
14:11:30  No GitLab connection configured
[Pipeline] updateGitlabCommitStatus
[Pipeline] echo

com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
platform-mr/myaapp_mr triggered for note.
Apr 22, 2020 2:11:30 PM FINE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater println
failed to print message No GitLab connection configured due to null TaskListener
Apr 22, 2020 2:11:48 PM FINE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater println
failed to print message No GitLab connection configured due to null TaskListener

### Problem description
I only have one connection "gitlab_my' configed in Jenkins master 
Test Connection , return Success

I have a scripted pipeline which gets triggered by Merge Request from Gitlab.
I try to add/update information before and after build stage
snippet of my jenkins file:
        def p = new pipeline(this)
        addGitLabMRComment comment: "Merge Request build start"
        updateGitlabCommitStatus name: 'jenkins-mr', state: 'pending'
        p.buildStage(env.type)   //git checkout and mvn build
        ..... 
        addGitLabMRComment comment: "Merge Request build done"
        updateGitlabCommitStatus name: 'jenkins-mr', state: 'success'

I have not been able to identify in which case exactly this "No GitLab connection configured" happens, but from time to time I do see this in the output and there is no comments added into that MergeRequest's discussion. aka developers are missing notification.

My observation is 
1. if I create a new pipeline, it fails all the runs till I comment out "addGitLabMRComment" for a run, then put back addGitLabMRComment and run once again, it started to works. 
2. if I remove this pipeline, then create it once again, same symptom as 1.)

I suspect if there is a timeout or reconnection from jenkins slave to our gitlab. 
So I increased connection timeout and read timeout from 10sec to 20sec, still no help.
Also,  this cannot explain why updateGitlabCommitStatus works but not only addGitLabMRComment

I have tried to add either 
properties([gitLabConnection('gitlab_my')])
or 
gitLabConnection('gitlab_my')
ahead of addGitLabMRComment
none helps

From code:
both called GitLabClient client = getClient(build); and get 
build.getParent().getProperty(GitLabConnectionProperty.class);
I just cannot figure out how it has different behaviors for addGitLabMRComment and updateGitlabCommitStatus

Hope anyone can point me a way out!
Thanks

**Comment by jasonlll88** [comment]
Same here

**Comment by zdtsw** [comment]
close ticket for now since no action to continue with
