### ISSUE TITLE
How to use secret token inside jenkins job

### ISSUE THREAD

**Issue by s1mple-child** [jenkinsci/gitlab-plugin#1055]
## Issue
In jenkins job configuration page(`Advanced` -> `Secret token`), gitlab plugin can generate a secret token.But when I configured with jenkins url and secret token into gitlab, it didn't work.
### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**: 11.0.3
- **Jenkins version**: 2.230
- **Job type**: Pipeline

### Logs & Traces
Hook executed successfully but returned HTTP 500

### Problem description
- Configured webhook in gitlab with url: http://JENKINS_URL/project/jenkins-pipeline-job-name.(Just a url not configured user in jenkins and secret token)
- Configured secret token into `Secret Token` which generated in jenkins job configuration page.
- Triggered test->push event
- Error(message plz check Logs & Traces)

**Comment by s1mple-child** [comment]
Problem solved~close this issue

**Comment by lebtech** [comment]
@s1mple-child What was the solution to this issue?
