### ISSUE TITLE
empty GitLab connection is created in addition the one defined in jenkins.yml

### ISSUE THREAD

**Issue by choeffer** [jenkinsci/gitlab-plugin#1062]
## Issue

see https://github.com/jenkinsci/configuration-as-code-plugin/issues/1272 for more information. I was told to report it here.

An empty GitLab connection is created in addition to the one defined in `jenkins.yml` when using the `configuration-as-code` plugin.

![image](https://user-images.githubusercontent.com/33625292/82157859-37f30580-9884-11ea-9510-6b00d56de18a.png)

### Context
- **Gitlab plugin version**: 1.5.13 (latest available https://plugins.jenkins.io/gitlab-plugin/ )
- **Gitlab version**: 12.10.3-ee
- **Jenkins version**: 2.222.3

### Problem description

_Describe your problem in a meaningful way_:
- Using `configuration-as-code` plugin for adding a GitLab connection via a `jenkins.yml` file to Jenkins

**Comment by jetersen** [comment]
Looking at the code, it is still using a `configure` override.
Calls `save` and `super.configure` which is properly the issue.

Feels wrong for it use `super.configure` override it goes against the docs of `GlobalConfiguration` and JCasC

**Comment by markjacksonfishing** [comment]
Will take a look

**Comment by jetersen** [comment]
@markyjackson-taulia I looked too closely at the code and ended up fixing it 😓

**Comment by markjacksonfishing** [comment]
I will take a look later tonight and merge

**Comment by jetersen** [comment]
@choeffer I have added an export test, to demonstrate the fix :)

**Comment by choeffer** [comment]
@jetersen Thanks for fixing the issue :)
