### ISSUE TITLE
can't update to gitlab-plugin-1.5.17

### ISSUE THREAD

**Issue by caozhiyuan** [jenkinsci/gitlab-plugin#1067]
## Issue
can't update to gitlab-plugin-1.5.17

### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**: 13.0.5
- **Jenkins version**: 2.222.4
- **Job type**: Freestyle

### Problem description

can't update to gitlab-plugin-1.5.17 , only can download 1.5.13
https://plugins.jenkins.io/gitlab-plugin/#releases

**Comment by acevif** [comment]
~~@caozhiyuan Could you tell me how you fixed the problem?~~
@caozhiyuan
Sorry I've got more detailed information.

@ anyone interested
See https://github.com/jenkinsci/gitlab-plugin/issues/1018 and https://github.com/jenkinsci/gitlab-plugin/issues/1027 for more details.
