### ISSUE TITLE
What are the possible values for triggerOpenMergeRequestOnPush?

### ISSUE THREAD

**Issue by scottashipp** [jenkinsci/gitlab-plugin#1069]
## Issue

What are the possible values for triggerOpenMergeRequestOnPush? The readme only gives the "never" example. I'm wondering if there's an option for triggering a build on a merge request when someone pushes either a new additional commit to the branch in question, or force pushes an amend to it.

**Comment by ababushk** [comment]
From what you've described I can say that plugin works that way if you configured `triggerOnMergeRequest: true` - GitLab sends Merge Request update events on pushes to source branch of MR. I'd hazard a guess `triggerOpenMergeRequestOnPush` is for some obsolete functionality or old GitLab versions. Is behavior you see right now differs?

**Comment by scottashipp** [comment]
Hi @ababushk Sorry for the delay on my end. It does indeed seem that `triggerOnMergeRequest: true` behaves the way you describe. Thanks, closing this.
