### ISSUE TITLE
gitlabTargetBranch points to wrong branch on Push Hook

### ISSUE THREAD

**Issue by koeberlue** [jenkinsci/gitlab-plugin#1089]
### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**: 13.5.3
- **Jenkins version**: 2.249.3
- **Job type**: Pipeline

### Problem description

Whenever someone pushes to an open merge request in Gitlab, we can see, that the environment variable for `gitlabTargetBranch` is not set correctly. It always points to the same branch as the `gitlabSourceBranch`.

So when the Jenkins job is triggered by a Push Hook, we get the following env variables:

```
gitlabBranch=feature_xyz
gitlabSourceBranch=feature_xyz
gitlabTargetBranch=feature_xyz
```

When we trigger the same Webhook by commenting on the merge request, we get the following env variables:

```
gitlabBranch=feature_xyz
gitlabSourceBranch=feature_xyz
gitlabTargetBranch=dev
```

Both times it's the same Jenkins Job triggered by the same webhook, just different merge request events.

Note: I'm also using the env inject plugin with the following variables set:

```
gitlabSourceBranch=feature_xyz
gitlabTargetBranch=dev
```

Could this be a problem?

**Comment by shurkanTwo** [comment]
We are having the same issue. The `gitlabTargetBranch` and `gitlabSourceBranch` env variables have the same value.

Would be highly appreciated if it could be fixed soon :)
Thanks a lot.

**Comment by koeberlue** [comment]
Thinking of it there was a misunderstanding on my site. Of course the push hook can only know the branch someone pushed to. So we can not say for sure, which merge request this push belongs to. I will just have to rethink my Jenkins jobs.

@shurkanTwo I will close this issue because it is the expected behavior. (Kind of... `sourceBranch` and `targetBranch` could just not be set for push events to avoid confusion)
