### ISSUE TITLE
Failed to update Gitlab commit status for project

### ISSUE THREAD

**Issue by Voskov** [jenkinsci/gitlab-plugin#1092]
## Issue
When running a Jenkins job, occasionally when trying to update Gitlab using `gitlabCommitStatus` responds with the following error:
`Failed to update Gitlab commit status for project 'Project_id': RESTEASY004655: Unable to invoke request`

### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**: 13.4.3-ee
- **Jenkins version**: 2.251
- **Job type**: Pipeline

### Problem description

_Describe your problem in a meaningful way_:
- A simple Merge Request that triggered a Jenkins pipeline via webhook
- The pipeline should have updated GitLab successfully
- In the GitLab Pipeline we don't see the step status at all.

**Comment by elloku** [comment]
I also encountered this problem. Have you solved it?

**Comment by Voskov** [comment]
I don't think so.
I don't even work there or work with GitLab anymore :)

**Comment by TinyNing** [comment]
Is there a solution?

**Comment by Voskov** [comment]
[link](https://github.com/jenkinsci/gitlab-plugin/issues/1092#issuecomment-821526607)
