### ISSUE TITLE
GitLab 8.0 Commit Status Broken

### ISSUE THREAD

**Issue by ahaeber** [jenkinsci/gitlab-plugin#111]
Gitlab 8.0 integrates Gitlab CI inside Gitlab. One crucial change for this plugin is that the URL setting has been removed so we can no longer configure the Gitlab CI service to point to Jenkins.

I believe we need a separate Jenkins integration service for Gitlab now. See documentation at https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/integration. A starting point could be the previous version of the Gitlab CI service (from tag 7.14.3): https://gitlab.com/gitlab-org/gitlab-ce/blob/d321305c00f934db9becac1aa9726c3e9b400df5/app/models/project_services/gitlab_ci_service.rb

See also https://gitlab.com/gitlab-org/gitlab-ce/blob/master/app/models/project_services/ci_service.rb

**Comment by sgrassie** [comment]
I came here to post this. If I'd have known, I wouldn't have upgraded to 8.0.

**Comment by atropo** [comment]
I can still use this plugin in Gitlab > 8.0 by using only the web hook on push events.

**Comment by sgrassie** [comment]
@atropo Thanks for pointing that out, I'd forgotten all about web hooks completely.

**Comment by disengaged** [comment]
@atropo When only using web hooks, I guess you cannot get the build status icon and links on the merge request page?

**Comment by bassrock** [comment]
Looks like they added some documentation specifically for our plugin.  We won't be able to get the commit status until version 8.1

https://about.gitlab.com/2015/09/22/gitlab-8-0-released/

**Comment by ayufan** [comment]
@bassrock 

We recently implemented Commit Status API in GitLab. It will be shipped with 8.1 release on 22.10. Maybe you need any assistance to have it integrated in your plugin?

Best regards,
Kamil Trzciński
CI Lead, GitLab Inc.

**Comment by bassrock** [comment]
@ayufan

More than happy to accept anyassitanceor accept any pull request! Especially from the people at GitLab!

**Comment by ayufan** [comment]
@bassrock 

Would be happy to do it, but I don't have enough knowledge to write Jenkins plugins. However, if anyone decides to pick the topic I'll guide and help with the API to get it done :)

**Comment by tomelfring** [comment]
I'm currently writing something that implements the new gitlab 8.1 commit API. Currently I've got a draft which works with merge requests. After some minor fixes i'll make a pullrequest here so you can review it.
I'll continue the work so it will also work with normal pushes.
