### ISSUE TITLE
Plugin needs maintainers

### ISSUE THREAD

**Issue by omehegan** [jenkinsci/gitlab-plugin#1115]
This plugin is currently unmaintained. If you are interested in contributing, testing and merging PRs, etc., please comment here and I can give you access.

**Comment by ghost** [comment]
As said in my PR I am interested ;) thanks a lot

**Comment by omehegan** [comment]
@MaximeMazet you should have an invite in GitHub now to get access to the repo. Let me know if you have not received it.

**Comment by ghost** [comment]
@omehegan Thanks :D

**Comment by omehegan** [comment]
@MaximeMazet no problem! In order to perform a release, you will need to follow the steps here: https://www.jenkins.io/doc/developer/publishing/releasing/ That's if you have not already released other Jenkins plugins before. I can help with this, or can perform releases for now if need be. Just let me know.

**Comment by ghost** [comment]
Hi @omehegan I want to make an update but when i'm make mvn release:prepare release:perform

I have this error

https://pastebin.com/dTf2YgGg

you know why ?

**Comment by omehegan** [comment]
@MaximeMazet it looks like you don't yet have permissions to push the jar to Artifactory. Did you follow the setup steps in the link I shared? You will need to request that access via a PR, I can't grant it to you.

**Comment by Stikus** [comment]
Time to remove this badge?
![image](https://user-images.githubusercontent.com/41360525/113577853-9a82fa80-962a-11eb-80bd-89d4671a322c.png)


Just for info - Jenkins Update Center shows `1.5.20` version instead of `1.5.21`:
![image](https://user-images.githubusercontent.com/41360525/113578051-e46be080-962a-11eb-90df-590bd86e3db9.png)

**Comment by brd** [comment]
@omehegan Looks like the maintainer closed their github account..
