### ISSUE TITLE
The plugin is not redirecting the user to the jenkins build page

### ISSUE THREAD

**Issue by florentvaldelievre** [jenkinsci/gitlab-plugin#112]
**Jenkins: 1.609.1**
**Gitlab plugin 1.1.26**

**It works ok with gitlab plugin version 1.1.1 but not with the 1.1.26**
=> http://mirrors.jenkins-ci.org/plugins/gitlab-plugin/1.1.1/

I am trying to make the following working:

/project/PROJECT_NAME/builds/COMMIT_SHA1 redirects to build page of the last build containing COMMIT_SHA1 as last commit
/project/PROJECT_NAME/commits/COMMIT_SHA1 redirects to build page of the last build containing COMMIT_SHA1 as last commit

My tests are the following:

**GET call**
http://jenkins:8080/project/job_name/builds/26baaf48d4109089a73d7c4971fc5afe6855479b

**Jenkins logs**
Sep 30, 2015 9:30:10 AM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: /builds/26baaf48d4109089a73d7c4971fc5afe6855479b

------

**GET call**
http://jenkins:8080/project/job_name/commits/26baaf48d4109089a73d7c4971fc5afe6855479b

**Jenkins logs**
Sep 30, 2015 9:37:40 AM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: /commits/26baaf48d4109089a73d7c4971fc5afe6855479b

On both cases, I have a 200 OK as a response. No redirection and the response body is empty.
The others CI functions are working ok.

Have you been experiencing the same problem ?

Thanks

**Comment by bassrock** [comment]
What version of Gitlab do you have? With the change to GItlabCI inside of Gitlab a lot has changed.

**Comment by perpective2410** [comment]
Hello,

A month ago, I think I was trying with gitlab ee 8.0.2
However, the scenario above is simulating gitlab behavior with GET calls. It would be nice to understand why it does not work on the latest version of the plugin

**Comment by joshuajorel** [comment]
I also noticed an issue when a merge has failed. Gitlab only detects that the build is pending, when in fact the build already failed on Jenkins and Jenkins displays the correct failure message on the comments.
