### ISSUE TITLE
Changelog missing  recent releases

### ISSUE THREAD

**Issue by ite-jankl** [jenkinsci/gitlab-plugin#1126]
The CHANGELOG.md file was not updated for the recent releases.

The changelog does not contain release dates. I would prefer the changes to be listed in the GitHub releases too, but given that they seem to be written to the CHANGELOG file I would expect them there at least.

**Comment by Stikus** [comment]
Looks like https://github.com/jenkinsci/gitlab-plugin/blob/master/CHANGELOG.md contains all releases (without dates - its correct).

But Jenkins Update Center itself doesn't contain the latest release:
![image](https://user-images.githubusercontent.com/41360525/113726752-2c5b3800-96fd-11eb-9821-6e65a72d3257.png)

**Comment by ite-jankl** [comment]
Looks like 5ae0e8a1d3ae928a7fecd94355f543bbf6908916 which was commited 13 hours ago was pushed after I created this ticket. It updates the CHANGELOG.md file.
