### ISSUE TITLE
How to trigger Jenkins kick off a build after a GitLab merge request is accepted

### ISSUE THREAD

**Issue by IsabelLachin** [jenkinsci/gitlab-plugin#113]
Hello everyone,

I have spent days now trying different approaches to get Jenkins trigger when we accept a Merge Request. Unfortunately, I can't get anything to work on our system. I have tried different plugins from Jenkins side of things to trigger GitLab, but they seem not to work either. Adding parameterized strings and adding token to end of URL's, I have tried them all - maybe not in correct order, I'm not sure.

I would like a nice configuration to tell me exactly what settings I have to setup and which plugins to use. I have uploaded most plugins for webhooks and merge request plugins, but none of them really work.

Then, next question is how do I debug what is coming from GitLab over to Jenkins? Do you look at system logs? There seem to be a lot of stuff there, and the same with /var/log/Jenkins/jenkins.log file.

Any help/suggestions is very much appreciated.

**Comment by bassrock** [comment]
Can you look at the jenkins log file and see if the jenkins url is getting called? Do you have web hooks setup to trigger jenkins on a merge request event?

**Comment by omehegan** [comment]
@IsabelLachin did you ever resolve this issue? Accepting an MR should trigger a push to the target branch, so if you have a job configured to build on push to either all branches, or to a whitelist of branches which includes your source branch, this should work.
