### ISSUE TITLE
Prepare GitLab for core Guava upgrade

### ISSUE THREAD

**Issue by basil** [jenkinsci/gitlab-plugin#1149]
See [JENKINS-65988](https://issues.jenkins.io/browse/JENKINS-65988). Jenkins core is using [Guava 11.0.1](https://github.com/google/guava/releases/tag/v11.0.1), which was released on January 9, 2012. Jenkins core would like to upgrade to [Guava 30.1.1](https://github.com/google/guava/releases/tag/v30.1.1), which was released on March 19, 2021. Plugins must be prepared to be compatible with both Guava 11.0.1 and Guava 30.1.1 in advance of this core transition.

In particular, this plugin has been identified as using the `com.google.common.cache.Cache#get(K key)` API, which has been removed between Guava [11.0.1](https://guava.dev/releases/11.0.1/api/docs/com/google/common/cache/Cache.html) and [latest](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/cache/Cache.html). The removal took place in Guava 12.0.

To facilitate the Jenkins core transition, this plugin must be prepared and released such that it works with both Guava 11.0.1 and latest. The recommendation is for plugins to migrate from Guava's cache to [Caffeine](https://github.com/ben-manes/caffeine) via the Jenkins [Caffeine API](https://plugins.jenkins.io/caffeine-api/) plugin.

For the most part, the migration is a trivial matter of replacing imports of `com.google.common.cache.Cache` with imports of `com.github.benmanes.caffeine.cache.Cache` and imports of `com.google.common.cache.CacheBuilder` with imports of `com.github.benmanes.caffeine.cache.Caffeine`. For examples of how to do this, see these existing PRs:

 * jenkinsci/active-directory-plugin#109
 * jenkinsci/azure-ad-plugin#125
 * jenkinsci/configuration-as-code-plugin#1596
 * jenkinsci/kubernetes-plugin#991
 * jenkinsci/lockable-resources-plugin#242
 * jenkinsci/role-strategy-plugin#150

**Comment by MarkEWaite** [comment]
As far as I can tell, this has been completed and released in [1.5.30](https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.5.30) or earlier.  There are no references to `com.google.common.cache.Cache` in the current code and there are references to `com.github.benmanes.caffeine.cache.Cache`.  Likewise for the Caffeine class.
