### ISSUE TITLE
Want To Help Maintain? (Looking for helpers)

### ISSUE THREAD

**Issue by bassrock** [jenkinsci/gitlab-plugin#115]
Hi All,

I am looking for other more active with this plugin than I have been lately to help me maintain it. If you are interested and have some experience with Jenkins Plugins let me know in the comments!

Thanks!

**Comment by markus-mnm** [comment]
I have no relevant experience with Jenkins plugin development, but I am thankful for this plugin and willing to learn and help. 
I will submit two pull requests in the next 10 days.

**Comment by joshuajorel** [comment]
May I have access as well? I want to address the issue I encountered [here](https://github.com/jenkinsci/gitlab-plugin/issues/144).

**Comment by joshuajorel** [comment]
Also, is there a guide on how to compile the plugin? Thanks.

**Comment by omehegan** [comment]
@joshuajorel if you just want to address a specific issue, please fork, fix, and provide a pull request. To build the plugin, just run 'mvn install.' It will generate a gitlab-plugin-XXX.hpi file in the 'target' directory. Manually install that on a Jenkins system to test it (in the Jenkins plugin UI, click the Advanced tab and upload the .hpi file, not the .jar).

**Comment by joshuajorel** [comment]
@omehegan alright. I'm currently investigating an issue with the build open merge requests function. Is there a dev thread where I can ask questions specifically on the development of this plug-in? Or at least a thread where issues are commonly discussed so I don't have to ask answered questions? 

Thanks for the help. Looking forward to fixing some stuff here.

**Comment by joshuajorel** [comment]
@omehegan My current setup relies on pushing my changes to Github then have a remote test server pull my changes and build then install the plug-in to Jenkins. After which I perform either a new merge request or an update to an open merge request in Gitlab. My Gitlab is deployed on a remote server as well.

I completely rely on outputting the results of my tests and code changes on my server logs, even if it's just a simple check for variable values. Is there a better way of testing my plug-in changes?  It's really inconvenient to do it this way. So is there a better way for debugging the plug-in?

Thanks and I might be able to make a pull request for a fix soon.

**Comment by dblessing** [comment]
@bassrock Thanks for opening this up for other interested maintainers. Is there anyone else with access to this repo as a maintainer right now? Is there anything I can do to help? I'm very thankful for your work on this plugin and want to see it continue.

**Comment by bassrock** [comment]
@dblessing This was actually transferred to the Jenkins CI repo and I don't have admin access anymore. I think @omehegan is the one leading the charge now.

**Comment by omehegan** [comment]
@dblessing thanks for offering to help! I've been busy with other things but need to give some more attention to the plugin. I have an incomplete bug fix to get Workflow support working fully, which I need at work.

Somehow I seem to have lost my admin access to the repo, I will get someone from the Jenkins admin team to fix that tomorrow. Then I want to merge a bunch of the open PRs and do a release.

I can make you a committer. Do you have any specific features or bugs you want to work on?

**Comment by dblessing** [comment]
Hi @omehegan 

Thanks for your reply. Were you able to gain access again? 

I work for GitLab, Inc. and we recently began using this plugin underneath our new Jenkins service in Enterprise edition. Overall, our users (both community and enterprise) like this plugin better than the existing GitLab Hook Plugin. But there are a few things they liked about the other one - like multiproject support. I'll file a feature request about that one. Other than that, if I have committer access I would mostly be interested in small bug fixes. 

Thanks for your work. I look forward to helping in any way.

**Comment by omehegan** [comment]
@dblessing yes, the GitHub group which contains all the committers somehow lost access, it has been added back. I just gave you commit access. 

I want to encourage those with commit access to still submit changes as PRs that the rest of us can review and comment on. However, they should also feel free to respond to issues, comment on/request changes to other PRs, etc. 

I also want to make sure that changes are well-tested before we perform a release. My company still uses GitLab 7.14.3, so for example I'm always checking to make sure that changes which target GitLab 8.x are still compatible with 7.14.

**Comment by dblessing** [comment]
:+1: Thanks @omehegan I will definitely use a PR.

**Comment by bassrock** [comment]
@dblessing  and @omehegan  looks like Jenkins just fixed all the commit access and admin settings!

**Comment by omehegan** [comment]
Yeah, a bug was recently introduced in the bot that we use to manage github privileges in the Jenkins project. Attempting to add a user sets everyone's access to read only. A permanent fix is in the works but we should be good for now.

**Comment by omehegan** [comment]
@coder-hugo has stepped up to be the lead maintainer of the project. His Java and Jenkins plugin knowledge are far superior to mine. I think we can close this issue, but of course other contributors are still welcome to get involved!
