### ISSUE TITLE
Failed to update Gitlab commit status: No credentials found for credentialsId

### ISSUE THREAD

**Issue by TinyNing** [jenkinsci/gitlab-plugin#1155]
buil fail
Build step 'Execute shell' marked build as failure
Failed to update Gitlab commit status: No credentials found for credentialsId: 
Finished: FAILURE

my gitlab-plugin version is 1.5.20  jenkins version is 2.296

**Comment by brd** [comment]
Duplicate of #1129, not sure why the new release is not being published properly.

**Comment by ghost** [comment]
This is come today or tomorow ;)
