### ISSUE TITLE
Use custom workspace not work with GitLab plugin

### ISSUE THREAD

**Issue by afrostalin** [jenkinsci/gitlab-plugin#1171]
### Versions

Jenkins - 2.316 (also tested  2.303.2 LTS)
GitLab plugin -  1.5.22

### Operating System

Windows 10 x64

### Reproduction steps

- Clean install Jenkins
- Install "most used plugins"
- Install GitLab plugin
- Create new freestyle job
- Check "Use custom directory" and set it
- Save job

### Results

- Open job again, "Use custom directory" uncheked, directory is empty

### How to fix 

- Disable GitLab plugin

**Comment by afrostalin** [comment]
Also with GitLab plugin directory check not work:

Without plugin:
![without_plugin](https://user-images.githubusercontent.com/7895624/137615376-11cf7656-d11e-49de-a547-a688ee46e86b.png)

With plugin:
![with_plugin](https://user-images.githubusercontent.com/7895624/137615377-0b09bbbb-ed31-43c1-a379-90ea96528c80.png)

**Comment by lbp-code** [comment]
Same problem here. Deactivating the **GitLab plugin** is a workaround. But you might want to use the plugin.
Hopefully this will get fixed soon

**Comment by paran0i4** [comment]
The same thing just happened to me and I was looking for a solution, thank you very much.

**Comment by krisstern** [comment]
I can reproduce this issue on my side as well

**Comment by krisstern** [comment]
I found something strange in for the `Use custom workspace` setting for Freestyle projects with the help of @harsh-ps-2003, there seems to be duplicates of this field such that there are two `Use custom workspace` fields in the form, but only the second one is functional and where the directory name is cached and shown. 

<img width="977" alt="Screenshot 2023-03-13 at 9 24 13 PM" src="https://user-images.githubusercontent.com/88480540/224715690-9dd17a4c-cd64-438c-a572-f31a02f0155f.png">

Maybe we should hide the first `Use custom workspace` as a fix for this issue.

**Comment by krisstern** [comment]
Bug patched with PR #1429.
