### ISSUE TITLE
Checkbox acceptMergeRequestOnSuccess set to "checked" always

### ISSUE THREAD

**Issue by trunov-ms** [jenkinsci/gitlab-plugin#120]
When I open Jenkins Job Configure page, acceptMergeRequestOnSuccess checkbox set to "checked" state always even if there was unchecked earlier and option <b>acceptMergeRequestOnSuccess</b> in file Jobname/config.xml set to <b>false</b> too.

**Comment by gumallett** [comment]
+1

**Comment by jsyrjala** [comment]
I made a related issue to jenkins jira: https://issues.jenkins-ci.org/browse/JENKINS-31122. @kasper-f

**Comment by nerzhul** [comment]
The XML was okay, but everytime the plugin merge requests, it's anoying
