### ISSUE TITLE
Configure GitLab host url and API token at job level

### ISSUE THREAD

**Issue by WonderCsabo** [jenkinsci/gitlab-plugin#121]
Currently the GitLab host url and API token are configured globally. This means one Jenkins instance can only communicate to one, specific GitLab instance. It would be nice if we could override this setting at job level.

**Comment by mattiasb** [comment]
I'd propose to store this with the Credentials plugin if possible. So you could just have a drop down menu to choose what Gitlab instance to use.

**Comment by WonderCsabo** [comment]
Good idea. However i would be really glad for any solution which would move this setting to job level. :smile:

**Comment by omehegan** [comment]
https://github.com/jenkinsci/gitlab-plugin/pull/198 will resolve this I think.
