### ISSUE TITLE
Time estimation for gitlab 8.0 commit api integration

### ISSUE THREAD

**Issue by fontealpina** [jenkinsci/gitlab-plugin#122]
The readme says:
**Note**: Currently GitLab 8.0 does not have a commit status api. Once this is added we should be able to add the commit status to Gitlab.
This is basically related to the Gitlab issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/2595
Seems this issue will be fixed in GitLab 8.1 that will be released on 2015 October 22. 
I was wondering which is the time estimation for the integration of this feature in the plugin? Hours, days, or maybe weeks?
Many thanks.

**Comment by omehegan** [comment]
@fontealpina I'm working on testing https://github.com/jenkinsci/gitlab-plugin/pull/127 with Gitlab 7 to ensure it is backwards-compatible. Hopefully we can release this in the next week or so.
