### ISSUE TITLE
Restore detailed build cause description

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/gitlab-plugin#1309]
### What feature do you want to see added?

https://github.com/jenkinsci/gitlab-plugin/commit/24e9a99d8151b5345109ef12cddc1ab323baa4ee implements a security fix: The previous, detailed build cause description rendered raw HTML containing some user-specified elements, causing [SECURITY-2316](https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2316).

As this plugin is currently unmaintained (the [only person able to upload new releases](https://github.com/jenkins-infra/repository-permissions-updater/blob/c4b70c3d3f3a4db7da2aab2c685f5a1cf0748361/permissions/plugin-gitlab-plugin.yml#L11) [no longer has a GitHub account](https://github.com/jenkins-infra/repository-permissions-updater/pull/1983)/commit access) but very popular, the Jenkins security team decided to deliver a fix for this issue instead of [announcing it without a fix](https://www.jenkins.io/security/plugins/).

As we don't have the capacity or environment to test a "proper" fix, we opted to just remove all details from the build cause as a minimal, safe solution to address the vulnerability. This obviously isn't a great solution, and instead, build causes should provide all necessary details while properly escaping untrusted values from user input.

**Comment by impact-maker** [comment]
@MarkEWaite I would like to work on this issue

**Comment by krisstern** [comment]
Feel free to work on the issue @impact-maker

**Comment by impact-maker** [comment]
Hi @krisstern  I have some issues building the code. Is there any slack or gitter channel for this project. Also I am not able to see any build instructions in the readme or the contributing guidelines.

**Comment by krisstern** [comment]
Hi @impact-maker Sure, it is [here](https://gitter.im/jenkinsci/gitlab-plugin) on Gitter.

**Comment by impact-maker** [comment]
@krisstern Since I have started with project from scratch. Some inputs would help to provide valuable contributions
I had the following queries in this issue.
1. How could I reproduce this error.
2. How could do the testing in case I make some code changes
Also the contributing guidelines are somewhat not clear. I can go ahead work on it as well after I am able to do it.
