### ISSUE TITLE
unable to unintall plugins 

### ISSUE THREAD

**Issue by vanisree1** [jenkinsci/gitlab-plugin#1335]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

windows 10

### Reproduction steps

1. step1 

### Expected Results

uninstallation of plugins

### Actual Results

uninstallation of plugins

**Comment by MarkEWaite** [comment]
The expected results and the actual results reported in this issue are the same.  There is not enough information in the issue report for anyone to take further action.

The Gitlab plugin is not responsible for plugin uninstall.  That is a function of Jenkins core.  Closing as "not planned".
