### ISSUE TITLE
gitlabSourceRepoURL from hook request

### ISSUE THREAD

**Issue by gege-fr** [jenkinsci/gitlab-plugin#136]
Could $gitlabSourceRepoURL take it's value from the actual gitLab hook and not the job config and start the jenkins job even if no SCM is set.

``` json
repository": {
    "name": "Diaspora",
    "url": "git@example.com:mike/diasporadiaspora.git",
    "description": "",
    "homepage": "http://example.com/mike/diaspora",
    "git_http_url":"http://example.com/mike/diaspora.git",
    "git_ssh_url":"git@example.com:mike/diaspora.git",
    "visibility_level":0
  },
```

That would allow me to create a single, generic, jenkins job that would handle all of my maven builds  (git clone depending on the $gitlabSourceRepoURL value) and releases instead of creating one job per project that are all clones of each others.

**Comment by antoniolibrada** [comment]
We would really appreciate this
