### ISSUE TITLE
GitLabCommitStatusStepExecution raise NPE cause agent can't be deleted automatically

### ISSUE THREAD

**Issue by bbxfnet** [jenkinsci/gitlab-plugin#1405]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.375.2
OS: Linux - 4.18.0-372.9.1.el8.x86_64
---
ace-editor:1.1
apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
authentication-tokens:1.4
bootstrap5-api:5.2.1-3
bouncycastle-api:2.27
branch-api:2.1071.v1a_188a_562481
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.8.1
cloudbees-folder:6.800.v71307ca_b_986b
command-launcher:1.2
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-27.vb_fa_3896786a_7
configuration-as-code:1569.vb_72405b_80249
credentials:1214.v1de940103927
credentials-binding:523.vd859a_4b_122e6
display-url-api:2.3.7
durable-task:504.vb10d1ae5ba2f
echarts-api:5.4.0-1
email-ext:2.93
font-awesome-api:6.2.1-1
git:5.0.0
git-client:4.1.0
gitlab-plugin:1.7.4
instance-identity:142.v04572ca_5b_265
ionicons-api:31.v4757b_6987003
jackson2-api:2.14.2-319.v37853346a_229
jakarta-activation-api:2.0.1-2
jakarta-mail-api:2.0.1-2
javax-activation-api:1.2.0-5
javax-mail-api:1.6.2-5
jaxb:2.3.8-1
jdk-tool:1.0
jersey2-api:2.38-1
job-fan-in:1.1.4
join:1.21
jquery3-api:3.6.1-2
junit:1166.va_436e268e972
kubernetes:3842.v7ff395ed0cf3
kubernetes-client-api:6.3.1-206.v76d3b_6b_14db_b
kubernetes-credentials:0.10.0
mailer:448.v5b_97805e3767
matrix-project:785.v06b_7f47b_c631
metrics:4.2.13-420.vea_2f17932dd6
mina-sshd-api-common:2.9.2-50.va_0e1f42659a_a
mina-sshd-api-core:2.9.2-50.va_0e1f42659a_a
pipeline-build-step:2.18
pipeline-groovy-lib:629.vb_5627b_ee2104
pipeline-input-step:466.v6d0a_5df34f81
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2118.v31fd5b_9944b_5
pipeline-model-definition:2.2118.v31fd5b_9944b_5
pipeline-model-extensions:2.2118.v31fd5b_9944b_5
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2118.v31fd5b_9944b_5
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:2.20.0
popper2-api:2.11.6-2
role-strategy:587.v2872c41fa_e51
scm-api:631.v9143df5b_e4a_a
script-security:1229.v4880b_b_e905a_6
snakeyaml-api:1.33-90.v80dcb_3814d35
sonar:2.15
ssh-credentials:305.v8f4381501156
sshd:3.236.ved5e1b_cb_50b_2
structs:324.va_f5d6774f3a_d
token-macro:321.vd7cc1f2a_52c8
trilead-api:2.84.v72119de229b_7
variant:59.vf075fe829ccb
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1208.v0cc7c6e0da_9e
workflow-basic-steps:994.vd57e3ca_46d24
workflow-cps:3616.vb_2e7168f4b_0c
workflow-durable-task-step:1223.v7f1a_98a_8863e
workflow-job:1268.v6eb_e2ee1a_85a
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

In Kubernetes, Image is jenkins/inbound-agent:3077.vd69cf116da_6f-3-jdk11

### Reproduction steps

1 Use "gitlabCommitStatus" to start.
2 Execute logic in body.
3 Before finish "gitlabCommitStatus", stop the build.

### Expected Results

The agent should be deleted automatically as build is stopped.

### Actual Results

Build node in Kubernetes can't be deleted, it always running exception I delete the agent in Jenkins.

### Anything else?

Comment the code line 112 and 119 in file com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep.
As t.getMessage() is null here.

`                    public void onFailure(StepContext context, Throwable t) {
                        BuildState state = BuildState.failed;
                        //if (!t.getMessage().isBlank()) {
                            if (t instanceof FlowInterruptedException) {
                                FlowInterruptedException ex = (FlowInterruptedException) t;
                                if (ex.isActualInterruption()) {
                                    state = BuildState.canceled;
                                }
                            }
                        //}
`

**Comment by krisstern** [comment]
@bbxfnet Which version of the plugin have you been using?

**Comment by krisstern** [comment]
I think this bug is pesky because we do not have existing tests that can readily test it. Let me see if I could patch it though. Any PR would be much appreciated.

**Comment by bbxfnet** [comment]
@krisstern The version is gitlab-plugin:1.7.4. You can check more in description "environment".

**Comment by krisstern** [comment]
Thanks for the double confirmation! I have started a fix for this in #1407. If the problem persists after I will have cut a release over the next few hours please do let me know.

**Comment by bbxfnet** [comment]
Thanks for your kindly fix.

**Comment by krisstern** [comment]
You are welcome @bbxfnet
