### ISSUE TITLE
Duplicate or stuck pending build in Gitlab 8.2

### ISSUE THREAD

**Issue by djb61** [jenkinsci/gitlab-plugin#143]
I have recently upgraded Gitlab to 8.2 and in doing so started using the new 8.1+ features.

I saw some occasional odd behaviour, most of the time the build status for the commit would work fine, pending->running->success but sometimes I'd either see:
- Build stays in "pending" until it finishes, never showing as running
- Two builds would appear in Gitlab for the same commit, one under "Latest build" and one under "Retried builds". One of these would forever stay in pending or running.

After a bit of debugging I believe this is due to the "pending" and "running" status updates being sent either out of order or close enough together that they result in a race condition in Gitlab (the duplicate builds case).
Looking at the code this looks likely to me due to the "pending" update being sent after the build is scheduled in GitlabPushTrigger.onPost() Runnable. It is my understanding that once the build is scheduled it will actually get started in another thread, if Jenkins has no build queue and is responding quickly this then happens at the same time as the thread for the Runnable continues to post the pending status.

I can't immediately think of a fix to this since if the "pending" status was sent before scheduling the build then we may end up incorrectly setting a status for a build that fails to get scheduled.

I have worked around this by adding a 1 second "Quiet period" in the Jenkins job which delays the start of the scheduled build enough to ensure this doesn't happen. Since adding this I have not reproduced the problem at all.

**Comment by omehegan** [comment]
@thommy101 can you take a look at this?

**Comment by tomelfring** [comment]
I do believe there is a race condition like @djb61 says.. I'm going to take a look at the code where it's happening.

**Comment by omehegan** [comment]
@djb61 the plugin has been significantly refactored in the last few weeks. Can you update to the latest version and let us know if you are still having this issue?
