### ISSUE TITLE
Create two merge requests to different branches

### ISSUE THREAD

**Issue by onfiro** [jenkinsci/gitlab-plugin#145]
Hello,

I create two merge requests like:
     some_branch -> development
     some_baranch -> other_branch
In jenkins i have two builds numbers 1 and 2, but in gitlab merge status I have similar links to latest buld - 2. How can i fix it?

**Comment by joshuajorel** [comment]
@onfiro it's a best practice to make a separate Jenkins project for different branches. See this [link](https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Best+Practices).
