### ISSUE TITLE
web hooks/test hook issue

### ISSUE THREAD

**Issue by noelcapule** [jenkinsci/gitlab-plugin#148]
Hello,

I followed the steps to install and configure gitlab-plugin based on https://github.com/jenkinsci/gitlab-plugin.  I tried "TEST HOOK" in Web Hooks but the link I provided there is not getting triggered.  After clicking the "TEST HOOK" i see that "Hook successfully executed" but that's all.  I have a feeling that i have fundamental issue here.  I have check jenkins log (Manage Jenkins->System Log) but i don't see the log getting updated.  I am wondering if I have a fundamental issue here.  We just upgraded to Gitlab 8.2.1-ee with Jenkins ver. 1580.2 and GitLab Plugin v.1.1.28.  I tried this with and without the Gitlab Merge Request Builder.

thanks in advance,
Noel

**Comment by fontealpina** [comment]
Try to check if Manage Jenkins->Configure System: Gitlab host URL and API Token are properly configured.

**Comment by coder-hugo** [comment]
Can you provide us information about your configuration? How do you have configured the gitlab build trigger in your jenkins job? And the same for the GitLab side.

**Comment by omorillo** [comment]
@fontealpina Could you fix this issue? If you still are troubling with it, please let us know.
