### ISSUE TITLE
View build details link is not correct on merge request pages

### ISSUE THREAD

**Issue by JrCs** [jenkinsci/gitlab-plugin#153]
The status of a merge request is update correctly but the link to the build details refer to a gitlab page:

http://_gitlaburl_/_groupe_/_project_/commit/dfdb6c36e8fd68961b36ea655eede97d2808cf5a/builds

instead of the jenkins build page:

http://_jenkinsurl_/job/_project_/_buildnumber_/

![gitlab-issue](https://cloud.githubusercontent.com/assets/83008/11686613/28dbe37e-9e82-11e5-8160-ee5671d4a633.png)

**Comment by coder-hugo** [comment]
I assume you are using GitLab 8.1+. If so this is the correct behavior. On the build page you should see all builds that are available for this commit. If you click on the status button of one of the builds you will be redirected to the Jenkins build page.
