### ISSUE TITLE
gitlab merge button different behavior than jenkins-gitlab merge-before build option (was: no-ff Option )

### ISSUE THREAD

**Issue by ehaselwanter** [jenkinsci/gitlab-plugin#158]
gitlab is using  --no-ff. can I specify this option?

**Comment by sebastienbonami** [comment]
You can change the "Fast-forward mode" under "Merge before build" in your Jenkins jobs that are triggered by GitLab.
![ff_mode](https://cloud.githubusercontent.com/assets/7561088/11815907/f5041262-a31b-11e5-93f3-4cdb2f16d8df.jpg)

**Comment by ehaselwanter** [comment]
I have to find out why I do not see this option :-(

**Comment by ehaselwanter** [comment]
found it: it is a plugin dependency issue. this option comes from the git jenkins plugin. and this very option is a (recent ;-) addition: https://issues.jenkins-ci.org/browse/JENKINS-12402

**Comment by ehaselwanter** [comment]
so. still a question. I was able to use --no-ff for git now. BUT I still experience an issue.

expected:
- create merge request
  -> trigger jenkins, get back result

well. this works.

BUT

occasionally the target branch of the merge request changes (a push or another merge in parallel)
=> gitlab still shows the merge button but jenkins reports a not able to merge.

is there any known setting for git/gitlab in jenkins to behave exactly the same like the merge button? or is the merge button (which as far as I know reflects a not-able-to-merge state as well) wrong?

I'm talking about the default settings in the open source gitlab deployment. not a fancy change of merge strategy in gitlab in the paid version / aka rebase before merge, ...)

cheers
Edmund

**Comment by ehaselwanter** [comment]
@omehegan would you mind pointing me in the right direction?

**Comment by vinograd47** [comment]
Did you set `user.name` and `user.email` in "Git Plugin" configuration?

**Comment by omehegan** [comment]
@ehaselwanter sorry, I don't think I understand the problem you're having (we merge manually on the GitLab side so I haven't experimented with more advanced workflows). Can you spell out how you have things configured and what you expect vs. what you're actually seeing?

**Comment by ehaselwanter** [comment]
@omehegan I see different behavior of the merge button and the gitlab-jenkins plugin.
- open merge request
- triggers jenkins build
- reports back in merge request (+1 all good)
- NOW somebody changes the integration branch
- among other builds the build from before is triggered again and reports back "can not merge" but the merge button on gitlab is still able to (at least showing you) merge.

=> there is a different behavior. so I thought it is `--no-ff` but this is not enough. 

OR: this is false positive of the gitlab merge button. either way. it should be the exact same behavior!

**Comment by coder-hugo** [comment]
I can't reproduce this. Can you provide us information about your setup (used versions, config, ...)?

**Comment by ehaselwanter** [comment]
this was a false positive with settings in gitlab itself and the gitlab/jenkins-git settings. we can close this. I accidentally had a mixture of not setting the same merge strategy in gitlab itself (there are options in the commercial offering of gitlab in the project settings) and what I set for git in jenkins. obviously they have to match.
