### ISSUE TITLE
Merge request does not trigger build because it has been merged already

### ISSUE THREAD

**Issue by AndreasBoehme** [jenkinsci/gitlab-plugin#160]
1. create a Merge request for branch "feature_1" to "release_1" - Jenkins merges the branch. OK.
2. create a Merge request for branch "feature_1" to "master" - the gitlab plugin silently denies that one because: "_Last commit in Merge Request has already been built in build #1234_"

**Comment by coder-hugo** [comment]
Close this as #163 is merged back
