### ISSUE TITLE
Build status for first push to new branch does not get reported to GitLab

### ISSUE THREAD

**Issue by dblessing** [jenkinsci/gitlab-plugin#162]
If you create a new branch and push some changes, a build is triggered. However, no commit status is reported to GitLab. On subsequent commits/pushes to that branch the status is reported properly.

**Comment by mvhirsch** [comment]
Which plugin- and Gitlab-version do you use?

**Comment by mraditya** [comment]
GitLab:  8.2.2-ee c35f8be
GitLab Plugin: 1.1.28
