### ISSUE TITLE
After starting with hpi:run, you can only interact with localhost

### ISSUE THREAD

**Issue by tanglinyan** [jenkinsci/gitlab-plugin#1652]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

mac, Intel

### Reproduction steps

Try adding -Djetty.httpHost=0.0.0.0 
- Djetty. Host = 0.0.0.0 
-DhttpListenAddress=0.0.0.0, the problem is not solved

### Expected Results

Can be accessed through local area network (LAN), such as http://192.168.4.129:8080

### Actual Results

It can only be accessed using http://localhost:8080

**Comment by MarkEWaite** [comment]
The command that you need to use is:

```
mvn -Dhost=0.0.0.0 hpi:run
```

**Comment by tanglinyan** [comment]
Thanks a lot for

**Comment by tanglinyan** [comment]
I look at the log and see that hpi:run uses jetty server internally
Attempt to modify jetty server parameters
But it didn't work
Why does mvn-Dhost =0.0.0.0 hpi:run take effect

**Comment by MarkEWaite** [comment]
I believe that the details of the `hpi` plugin for Apache Maven are described in its [documentation](https://jenkinsci.github.io/maven-hpi-plugin/run-mojo.html).  In that documentation, it says:

> Specifies the host (network interface) to bind to. If connectors are configured in the Mojo, that'll take precedence.
> **Default:** `localhost`
> **User Property:** `host`

**Comment by tanglinyan** [comment]
Thank you. I think I got it
