### ISSUE TITLE
MR Voting Broken after Gitlab 8.2

### ISSUE THREAD

**Issue by orediggerco** [jenkinsci/gitlab-plugin#168]
As explained in https://gitlab.com/gitlab-org/gitlab-ce/issues/3672, after version 8.2 Gitlab CE no longer supports merge request votes in a comment. Giving a +1 or -1 (or certain other emoji's) in a comment's body will still cast a vote, but there can be no other text in the comment. The current version of the gitlab-plugin includes the vote and the build status comment all in one post back to gitlab.

In order for voting to work in a post-8.2 environment, the vote would need to be added as a separate comment with no other text. 

I haven't worked much with Java myself, but it looks like the `onCompleteMergeRequest` function in the `GitLabPushTrigger` class would need to be updated so that if `addVoteOnMergeRequest` is enabled from configuration, a separate comment is sent to the gitlab with the +/-1 indicator. The existing comment can be left as it is with the +/-1 so that the vote still looks the same as before 8.2, but in order for the vote to actually be cast with the MR, it would need a separate comment.

Maybe adding the vote comment prior to the existing logic in the function like this?

```
// This is new
if(addVoteOnMergeRequest) {
    StringBuilder msg = new StringBuilder();
    if (run.getResult() == Result.SUCCESS) {
        String icon = ":+1:";
    } else {
        String icon = ":-1:";
    }
    msg.append(icon);
    try {
        GitlabProject proj = new GitlabProject();
        proj.setId(cause.getMergeRequest().getObjectAttribute().getTargetProjectId());
        org.gitlab.api.models.GitlabMergeRequest mr = this.getDescriptor().getGitlab().instance().getMergeRequest(proj,cause.getMergeRequest().getObjectAttribute().getId());
        this.getDescriptor().getGitlab().instance().createNote(mr,msg.toString());
    } catch (IOException e) {
        e.printStackTrace();
    }
}

// This is existing
if(addNoteOnMergeRequest) {
    StringBuilder msg = new StringBuilder();
    if (run.getResult() == Result.SUCCESS) {
        String icon = addVoteOnMergeRequest ? ":+1:" : ":white_check_mark:";
        msg.append(icon);
    } else {
        String icon = addVoteOnMergeRequest ? ":-1:" : ":anguished:";
        msg.append(icon);
    }
    msg.append(" Jenkins Build ").append(run.getResult().color.getDescription());
    String buildUrl = Jenkins.getInstance().getRootUrl() + run.getUrl();
    msg.append("\n\nResults available at: ")
            .append("[").append("Jenkins " + buildUrl).append("](").append(buildUrl).append(")");
    try {
        GitlabProject proj = new GitlabProject();
        proj.setId(cause.getMergeRequest().getObjectAttribute().getTargetProjectId());
        org.gitlab.api.models.GitlabMergeRequest mr = this.getDescriptor().getGitlab().instance().getMergeRequest(proj,cause.getMergeRequest().getObjectAttribute().getId());
        this.getDescriptor().getGitlab().instance().createNote(mr,msg.toString());
    } catch (IOException e) {
        e.printStackTrace();
    }
}
```

**Comment by cnmcavoy** [comment]
It looks like Gitlab does support the voting in comments again in 8.3+, so maybe this issue can be closed?

**Comment by orediggerco** [comment]
It does again support voting from comments, but only if the emoji is the only text in the comment. Otherwise it is just treated as a normal emoji and comment, not as an actual vote in the MR. That's what my testing against the current version running on gitlab.com shows at least.

**Comment by sebastienbonami** [comment]
@oredigger8806 You're right, I have the same behavior on my side with GitLab 8.3.4 and GitLab Plugin 1.1.28 in Jenkins.

**Comment by coder-hugo** [comment]
Is this feature really necessary. We can fix this by adding a separate comment with a :+1: or :-1: but I don't see any advantage in the fact that the jenkins votes this MR up/down cause you already get the opinion of jenkins about the MR by the build status (success of failed).

**Comment by ghost** [comment]
I think that You're right with the idea of adding separate note (comment) after each build. It will work.
But it isn't as simple as it sounds. If this is the first build then everything is ok, but things go wrong if this is following build. In this case you can't simply add next comment.
If preceding build is different than following and you will add next comment you will have both - up and down vote. You should then modify existing vote note or remove old before add new one.

**Comment by coder-hugo** [comment]
Adding a separate comment would do exactly the same as it was before GitLab 8.2. IIRC the votes get reset by GitLab with each new commit added to a MR so we don't have to reset the votes on our own. But again, I don't see any advantage in this feature. Therefore it would be kind if somebody how wants this feature could name some good reasons for adding it.

**Comment by orediggerco** [comment]
Can't speak for anyone else of course, but my team and I find the actual voting far more beneficial than the message about the build passing or failing. I can tell with a quick look at the top of our MR's what the status is regarding Jenkins builds and code reviews from the appropriate team members just by looking at votes, without having to wade through what tends to turn into lengthy discussions to see if the last Jenkins comment is a pass/fail.

Also keep in mind this isn't adding a feature, it's _fixing_ one that used to work exactly as the option is described in the Jenkins project settings for this plugin. It no longer has that functionality due to an update to the gitlab platform.

**Comment by coder-hugo** [comment]
I know that this is an existing feature which was broken by some changes in GitLab. So things are changing over the time and you come to a point where you have to decide whether the value of a feature justifies the effort for fixing it/keeping it alive.
If we'll fix this by just adding a separate comment with :+1: or :-1: we'll waste unnecessarily the MR history of everybody that still uses for whatever reason GitLab < 8.2. So I see already the next open issues "Why there are always 2 comments of the Jenkins". As there is no way to retrieve the GitLab version via the API this needs to be somehow configurable. On the one hand this makes the code more complex and on the other hand it makes the UI even more complex. Which makes it even hard for newbies to get the first setup done and have just GitLab and Jenkins configured to communicate together. Cause adding the build trigger for GitLab webhooks brings up further settings that fill the whole screen.

Maybe it's a better idea to follow this approach #201 in a modified way. I'd see this in a post-build step where you can enter your own comment(s) for successful/failed builds. This provides you more flexibility by keeping the code and the UI as simple as possible.

Btw. in my previous comment I talked about the commit status API introduces with GitLab 8.1 which shows you the status of the build also at the top of the MR.
![build status](https://cloud.githubusercontent.com/assets/5196912/13403749/e022c1fe-df16-11e5-95e7-1e15a9d724bd.png)

**Comment by orediggerco** [comment]
That would work for me and my team's needs (re modification to #201)! That would give me the functionality I'm looking for at least.

Thanks!

**Comment by jostyee** [comment]
Is this function broken again? After upgrading to GitLab v9 the plugin send thumbs up/down comment instead of vote to MR now.

**Comment by omehegan** [comment]
@jostyee can you provide some more information? What version of the plugin are you using, what version of GitLab did you upgrade from, and how are you using this feature?

**Comment by jostyee** [comment]
@omehegan Jenkins 2.46.2/GitLab plugin 1.4.5, It's been a while after I upgraded GitLab from maybe 8.16.x to 9.0(right now 9.1.2), tried neither send `:+1:` "custom message" of "Add note of build status" nor "Add vote for build status" post step works, only add comment below MR.

I checked GitLab documents earlier, seems they've removed vote from `Note` API, add an `Award emoj` API to replace it, please have a look at: https://docs.gitlab.com/ce/api/award_emoji.html

**Comment by omehegan** [comment]
@jostyee yeah, I wrote some code to access the GitLab API and look for votes on MRs for an unrelated task, and I was confused by the fact that the schema had "votes," but when people hit the +1/thumbs up button, it didn't register as a vote, it registered as an award emoji. I was told that votes had been deprecated, and that happened in GitLab 8.6 or something. I'm on 8.10.

If the plugin is successfully sending thumbs up/down to GitLab, I have a feeling that is more or less "as designed" and that this is not really a bug.

**Comment by jostyee** [comment]
@omehegan I guess there were some changes recently & this function is totally replaced by award emoj?

**Comment by omehegan** [comment]
@jostyee well, the only thing I can say is that I think the UI was changed in an earlier 8.x version of GitLab, such that clicking the thumbs-up button did not register as a "vote" in the API, but rather as a "thumbs-up" award emoji. So in my case, my users were clicking that, and I had to write some Ruby code to check whether an MR had +1s. That was what I needed to check.

It's possible that the Jenkins plugin was still able to register "votes" via the API, and this was then surfaced in the UI. I can imagine that being broken now. What were you seeing in the UI before when a "vote" was sent? A comment saying "+1" from the Jenkins user or something?

**Comment by jostyee** [comment]
@omehegan Ooops, I can't even vote up/down even on the MR page, I have to find out why for now. :-(

**Comment by jostyee** [comment]
@omehegan 
click thumbs up/down emoji on webpage would send a https://gitlab.company.com/group/project/merge_requests/id/toggle_award_emoji request to the server, which functioning normally, no comment shows before it finishes.

GitLab plugin, add comments with emoji.
<img width="130" alt="screen shot 2017-05-19 at 8 11 29 am" src="https://cloud.githubusercontent.com/assets/88564/26228498/e78b5f0a-3c6c-11e7-894a-ccd71fa3570d.png">
<img width="138" alt="screen shot 2017-05-19 at 8 11 38 am" src="https://cloud.githubusercontent.com/assets/88564/26228499/e78b98ee-3c6c-11e7-9af9-e0f5c39b772c.png">

**Comment by omehegan** [comment]
@jostyee I am guessing that GitLab has changed what it does with a "vote" as of the 9.0 release. I don't know if we can or should change anything with the plugin to account for this.

**Comment by jostyee** [comment]
@omehegan Can't we support the new award emoji API in near future?

**Comment by omehegan** [comment]
@jostyee from reading your comments, I thought that is what was happening. Are you saying that now what happens in GitLab is that there is only a comment, but no award/thumbs up?

**Comment by jostyee** [comment]
@omehegan yes, it only adds a comment, sorry for my English. :-(

**Comment by omehegan** [comment]
That's OK. Now that I understand better, can you open a new issue for this? Describe the behavior as best you can, and I'll edit to make it clearer if I need to. Thanks!

**Comment by jostyee** [comment]
@omehegan Sure, I've issued https://github.com/jenkinsci/gitlab-plugin/issues/556 , hoping it'll help. Thank you again for your patience.
