### ISSUE TITLE
MR build not being triggered without "Push Events".

### ISSUE THREAD

**Issue by testark** [jenkinsci/gitlab-plugin#172]
I'm running GitLab `8.3.0`, Jenkins `1.643` and version `1.1.28` of the plugin, and I've successfully set up integration. However, I am noticing a strange behaviour while building MRs:
- If I create a web hook for both _push_ and _merge request_ events, multiple pushes to the same MR will be successfully built. However, two builds will be triggered on Jenkins for each push.
- If I create a web hook for "merge requests" events only, only the first push associated with the MR will be built. No more builds are triggered after that.

For the first case:

```
Jan 04, 2016 10:05:09 PM com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
INFO: WebHook called with url: 
Jan 04, 2016 10:05:09 PM com.dabsquared.gitlabjenkins.GitLabWebHook generateMergeRequestBuild
INFO: Existing Merge Request, build will be trigged by buildOpenMergeRequests instead
Jan 04, 2016 10:05:09 PM com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
INFO: WebHook called with url: 
Jan 04, 2016 10:05:09 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 run
INFO: dojo-gitlab triggered for push.
Jan 04, 2016 10:05:09 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 createActions
INFO: GitLab Push Request from branch feature/noop.
Jan 04, 2016 10:05:09 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 createActions
INFO: Trying to get name and URL for job: dojo-gitlab
Jan 04, 2016 10:05:09 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 run
INFO: GitLab Push Request detected in dojo-gitlab. Triggering  #35
Jan 04, 2016 10:05:09 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger$3 run
INFO: dojo-gitlab triggered for merge request.
Jan 04, 2016 10:05:09 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger$3 createActions
INFO: Trying to get name and URL for job: dojo-gitlab
Jan 04, 2016 10:05:10 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger$3 run
INFO: GitLab Merge Request detected in dojo-gitlab. Triggering  #35
Jan 04, 2016 10:05:34 PM hudson.model.Run execute
INFO: dojo-gitlab #35 main build action completed: SUCCESS
Jan 04, 2016 10:05:51 PM hudson.model.Run execute
INFO: dojo-gitlab #36 main build action completed: SUCCESS
```

For the second case:

```
Jan 04, 2016 10:09:04 PM com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
INFO: WebHook called with url: 
Jan 04, 2016 10:09:04 PM com.dabsquared.gitlabjenkins.GitLabWebHook generateMergeRequestBuild
INFO: Existing Merge Request, build will be trigged by buildOpenMergeRequests instead
```

Nothing happens whatsoever after this point. Can there be anything wrong with my setup? Can it be a bug?

**Comment by ehaselwanter** [comment]
seeing the same behavior which is a little bit strange. or is this intended?

**Comment by ramielrowe** [comment]
I'm seeing the same behavior, but I think I've found a good config. For this specific job, I want to run on just MRs, not on random branch pushes.

Jenkins:
Build on Merge Request Events: on
Build on Push Events: off
Rebuild open Merge Requests: on push to source or target

Gitlab Webhook:
Push events
Merge Request events

With those configs, I'm only seeing a single build get kicked off when MRs get updated with new pushes.

**Comment by ghost** [comment]
Thanks a lot @ramielrowe!

**Comment by cdenneen** [comment]
So while this helps MR behavior allow for first and subsequent updates it breaks builds for new branches getting created. 

I think the idea the gitlab mr plugin does that allows builds on assigning MR, label, and even comments is good idea. 

Plus fixing the push events that if triggered via MR only send one job to Jenkins instead of 2 would be nice fixes to these issues.

**Comment by coder-hugo** [comment]
Duplicate of #210
