### ISSUE TITLE
HTTP enable instead of SSH default

### ISSUE THREAD

**Issue by cdenneen** [jenkinsci/gitlab-plugin#176]
Can this plugin work over HTTP vs ssh?

git clone https://gitlab/project.git

vs 

git clone git@gitlab:project.git

**Comment by coder-hugo** [comment]
I don't get your issue. The git clone stuff isn't part of the plugin this is done by the git-plugin which can be configured using a HTTPS URL.

**Comment by cdenneen** [comment]
${gitlabSourceRepoURL} is not https and provides no way to do this.

**Comment by coder-hugo** [comment]
Duplicate of #211
