### ISSUE TITLE
Jenkins builds status are not listed in the Gitlab "Builds" menu

### ISSUE THREAD

**Issue by mbenalaya** [jenkinsci/gitlab-plugin#177]
Hello folks,

Jenkins builds status are listed correctly under "Merge Requests" and "Commits" pages in Gitlab. However the "Builds" page remains empty. 
How to show my jenkins builds status in the Gitlab "Builds" page  ?

I am using:
- Gitlab ver. 8.3.2
- Jenkins ver. 1.616

Best regards,
Mahdi

**Comment by coder-hugo** [comment]
This is an issue in GitLab. This plugin uses the GitLab commit status API to provide GitLab the results of the jenkins builds. AFAIK there is no special API to make this visible in the "Builds" page. 
@dblessing: As a member of GitLab Inc. do you know if it's planned for the future to show builds of external CIs also on the Builds page?

**Comment by dblessing** [comment]
The build page is being redesigned/repurposed. In the meantime, no, there's
no way to get Jenkins builds to show there.

**Comment by tonka3000** [comment]
@dblessing will this option (allow other CI systems reporting there state) be back after the redesign or will this be "blocked" forever?

**Comment by ghongadi** [comment]
@mbenalaya: You mentioned that, Jenkins builds status is showing in Merge Request and commits page.

Can you please let me know the step to configure the same.

I enabled the Gitlab -Jenkins integration, So when there is push event/Merge event Jenkins job is getting triggered but Jenkins build status is not displaying in Gitlab.

Can you please help.
