### ISSUE TITLE
Parameter gitlabMergeRequestTitle is always blank

### ISSUE THREAD

**Issue by alienspaces** [jenkinsci/gitlab-plugin#180]
It looks like a bunch of really useful merge request information was added in this commit

https://github.com/jenkinsci/gitlab-plugin/commit/58af7ef453fd06964a30ceaf2a837b6774b77c56

Will a new release be available for this plugin soon that includes the above additions?

Would it also be possible to add gitlabMergeRequestDescription?

**Comment by shwangste** [comment]
+1

**Comment by coder-hugo** [comment]
Duplicate of #211
