### ISSUE TITLE
Multiple Jenkins build results are not visible in Merge Request view

### ISSUE THREAD

**Issue by shochdoerfer** [jenkinsci/gitlab-plugin#185]
When a Jenkins build is triggered via the Merge Request one can see a comment after the build stating if the build was successful or not. In case the build was not successful and I add some more commits to the branch Jenkins will still get triggered but no further comment appears in the Merge Request view, neither will the original comment change. I would have expected to see a comment for each build run by Jenkins.

I am using the Jenkins Gitlab Plugin 1.1.28 and Gitlab 8.3.2

**Comment by coder-hugo** [comment]
Duplicate of #210
