### ISSUE TITLE
Multiscm plugin support

### ISSUE THREAD

**Issue by ibratoev** [jenkinsci/gitlab-plugin#187]
If a CI job is configured to use the multiscm plugin (https://wiki.jenkins-ci.org/display/JENKINS/Multiple+SCMs+Plugin) then builds are not triggered properly from GitLab pushes and Merge Requests.

**Comment by froque** [comment]
seems duplicate of #183

**Comment by ibratoev** [comment]
Yeah, it is a dupe.

**Comment by coder-hugo** [comment]
Fixed with version 1.1.31
