### ISSUE TITLE
Can this plugin build merge requests?

### ISSUE THREAD

**Issue by timmolter** [jenkinsci/gitlab-plugin#191]
Can this plugin build merge requests or only automatically merge from forked repositories?

Hi, It's unclear to me after reading the README if this plugin can build merge requests. I tried it and Jenkins built the source code after a merge request was triggered but it built the main fork's code and not the code from the fork from which the MR came from.

In the readme it says "To be able to merge from forked repositories", but I want to manually merge, but have the merge request fork's code built to test for compile errors and run the unit tests.  Can it do that?

Or do I need to use another plugin such as the one here to accomplish what I want: <https://github.com/timols/jenkins-gitlab-merge-request-builder-plugin?

**Comment by Christilut** [comment]
This is also unclear to me.

The gitlab-plugin documentation kind of implies that the merge request plugin is not needed anymore. But I can't find a definite answer to that anywhere.

**Comment by omehegan** [comment]
I spent the last day or so trying to get this working using Gitlab 7.14.3. The trick to getting MRs to trigger a build is to use the Settings -> Web Hooks UI and create a hook just for merge requests. Not very intuitive given that the rest of the GitLab configuration necessary with that version involves the GitLab CI stuff.

**Comment by mattiasb** [comment]
The configuration is overly complex, sure. But all the steps is there, right on the main page. :D

**Comment by omehegan** [comment]
The documentation really needs a refactor. I can do that.

**Comment by omehegan** [comment]
@timmolter @Christilut I tried to improve the documentation about this, please take a look and reopen this issue if you still can't get MR's to build.
