### ISSUE TITLE
Multiproject support

### ISSUE THREAD

**Issue by dblessing** [jenkinsci/gitlab-plugin#193]
Similar to the older 'GitLab Hook Plugin'. 

A user configures a 'master' project in Jenkins. All builds on the master(default) branch happen there. When multiproject is enabled, though, builds on another branch are executed within a copy of the master project that includes the branch name. If the master project is 'my_gitlab_project', for example, the branch project name would be 'my_gitlab_project_<branch_name>'.

This leads to many more projects in Jenkins but it makes the build history cleaner and makes it easier to follow the trend of build results for a branch over time.

**Comment by coder-hugo** [comment]
I think the better approach would be to support the [Multi-Branch-Project-Plugin](https://github.com/jenkinsci/multi-branch-project-plugin) instead of creating projects per branch. This has the same effect of keeping the build history clean but also keeps the project view manageable.

**Comment by bentruyman** [comment]
Agreed, @coder-hugo. There are plugins from Cloudbees to support GitHub and Stash which work great for this exact purpose.

**Comment by omehegan** [comment]
Yes, this is also now natively supported for Pipeline jobs in the Pipeline Mutibranch Plugin. I think that's the best way forward for support of something like this.
