### ISSUE TITLE
Multiple jobs triggered

### ISSUE THREAD

**Issue by Christilut** [jenkinsci/gitlab-plugin#194]
GitLab Community Edition 8.1.1
Jenkins 1.647 with latest versions of Gitlab / Git plugins

I have three webhooks in gitlab:
`http://127.0.0.1:8080/project/MyProject_Develop`
`http://127.0.0.1:8080/project/MyProject_Staging`
`http://127.0.0.1:8080/project/MyProject_Master`
They only have `Merge Requests Events` enabled.

Then I have 3 jobs like this in Jenkins:
They are set up pretty basic:
Repository name: `staging`
Branch specifier: `staging`
Merge before build is set to: `origin` and `${gitlabTargetBranch}`
And `Build when a change is pushed to GitLab.` is enabled.

Now when this MR happens `develop->master` then the master and staging jobs are triggered. Only the master job should be triggered.
When this MR happens `staging->master` then all 3 jobs are triggered.

I can't figure out what is going wrong. Why are too many jobs being triggered?

**Comment by omehegan** [comment]
#285 should fix this.

**Comment by jflow** [comment]
Jenkins 2.7.1
Gitlab 8.10.5 (current at time of writing)

Configured with Push Events only. For every push I get at least 3 builds and most time many more builds from the one push event. Our build slave is used by multiple projects and this is causing quite a bit of slow down and confusion for our QA team on what different between each build.

Any solutions for this????

**Comment by coder-hugo** [comment]
@jflow some more details about your Jenkins job configuration (what options are selected for the GitLabPushTrigger) and the [logs for the gitlab-plugin](https://github.com/jenkinsci/gitlab-plugin#user-support) would be helpful to see why multiple builds are triggered for a single push event.
