### ISSUE TITLE
Cross links in jobs, triggered by single event.

### ISSUE THREAD

**Issue by wl2776** [jenkinsci/gitlab-plugin#200]
If several Jenkins jobs are configured to run from a single push (several web hooks installed, for example, builds on linux and windows), it would be great to have a link on a build page, showing other builds, triggered in parallel to this one.
Gerrit Trigger provides such functionality. 
Each build triggered, with it, contains text like

**Other triggered build for this event.**
<Other job name> #<job build ID>

**Comment by coder-hugo** [comment]
We can't implement this as the plugin doesn't receive a single event if multiple web hooks are configured. It receives an event for each configured web hook. If the plugin gets called by GitLab there is no way the see if there are other web hooks for the same push to a repository.
