### ISSUE TITLE
Add default value for the radioblocks with name "branchFilterName"

### ISSUE THREAD

**Issue by omorillo** [jenkinsci/gitlab-plugin#202]
For none of the above mentioned radioblocks, a default value exists. By consequence, already existing jobs will end up with "branchFilterName" being null upon plugin update.

A default value for these radioblocks should be provided.

**Comment by coder-hugo** [comment]
IMHO a default value isn't the correct solution. We should migrate existing jobs according to their settings using an Initializer like this one https://github.com/coder-hugo/gitlab-plugin/blob/feature/multiple-gitlab-connections/src/main/java/com/dabsquared/gitlabjenkins/connection/GitLabConnectionConfig.java#L108

**Comment by WonderCsabo** [comment]
@coder-hugo yes, that way we can force users to choose in new jobs while migrating old jobs safely. However, is there a validation for that (for must selecting one of the options)? I do not see it in the PR #149 .

**Comment by coder-hugo** [comment]
@WonderCsabo I haven't found a way to validate this so I implemented a solution that just preselects the first radiobox for new jobs. Which in the end has the same effect.

**Comment by WonderCsabo** [comment]
@coder-hugo preselects the first radiobox? For me that sounds like it has a default value. :)

**Comment by coder-hugo** [comment]
Yes for new jobs a default value is ok but not for the existing once ;)

**Comment by WonderCsabo** [comment]
Great, and thanks for the fix. This issue can be closed, then?

**Comment by coder-hugo** [comment]
No as the migration for existing jobs isn't yet implemented. Which means that non of the existing jobs will be triggered by a GitLab push or merge event because of a NullPointerException.
