### ISSUE TITLE
I have just updated gitlab to 8.3.4, how do i intergrate with jenkins ?

### ISSUE THREAD

**Issue by vmintam** [jenkinsci/gitlab-plugin#204]
Dear Guys,

 In this documents of jenkinsci plugin for gitlab, only support gitlab 7.14.xx or 8.1.xxx because gitlab 8.3 intergrated gitlab CI into core.

 So, any other solitions for intergrate gitlab 8.3.4 and jenkins ?

thanks!

**Comment by ghost** [comment]
Hi,
In "Supported GitLab versions" chapter of README file you can read:

> 8.1.x and **newer** via the new commit status API that supports with external CI services like Jenkins 

This means that the 8.3 version is supported. Read "GitLab Configuration (>= 8.1)" chapter to see how to configure. 
You should also know that the plugin supports Jenkins 1.568 or higher (there is nothing about that in manual).
BR

**Comment by vmintam** [comment]
thank for support  pwl89. 

I will recheck README file.
