### ISSUE TITLE
Listen for update MR events instead of push events to rebuild open MRs

### ISSUE THREAD

**Issue by coder-hugo** [jenkinsci/gitlab-plugin#210]
Replace the "Rebuild open Merge Requests" select with a checkbox and use the update MR events to trigger a new build for open MRs.

**Comment by testark** [comment]
> Replace the "Rebuild open Merge Requests" select with a checkbox

@coder-hugo was this really implemented? I still see a select with 1.3.2. Also, I can't seem to get this to work without "Push Events" as I had reported on #172.

**Comment by coder-hugo** [comment]
@testark the issue is that GitLab doesn't send an update event for a MR if the target branch changes only for changes on the source branch. If you just want to rebuild MRs in the case that the source branch has changed it's enough to configure only MR events on the GitLab side. For rebuilding MRs also if the target branch has changed you need to configure the push events on the GitLab side as well.

**Comment by testark** [comment]
@coder-hugo yes, that's what I did, but when I push to the target branch Jenkins builds that target branch instead of the MR.
