### ISSUE TITLE
branch names with non-URL safe characters

### ISSUE THREAD

**Issue by froque** [jenkinsci/gitlab-plugin#212]
I was having problems with branches with a '#' character. 

The problem was in the java-gitlab-api and I submitted a fix: https://github.com/timols/java-gitlab-api/pull/115

I see that there is a work in progress to remove this library and use JAX-RS: https://github.com/jenkinsci/gitlab-plugin/pull/203

Whatever the strategy is, I just needed for the next version of the gitlab-plugin to work with weird characters in the branch names.

**Comment by coder-hugo** [comment]
First of all: why do you use such strange characters within your branch names? I assume this could cause trouble also with other tools around git.
I can't promise you that this (latest version of java-gitlab-api) will be in the next release of the plugin which hopefully takes place in the next days. After this release I'll go on with my code cleanups including #203 which I'll finish hopefully within the next 2 weeks. If the code cleanup which contains a lot of minor fixes is finished I'll do a new release which will definitively fix your issue.
IMHO the java-gitlab-api is a good example for how to not implement a java client for a "REST" (HTTP fits better) API. There are a lot of frameworks/libraries out there that do the most of the things that are implemented in the java-gitlab-api by hand automatically for you just by using JAX-RS. Among other things these frameworks do URL encoding wherever it's required. 
This is just one reason why I decided to replace the java-gitlab-api.
