### ISSUE TITLE
Hooks not working (Gitlab CE 7.11)

### ISSUE THREAD

**Issue by mhenrixon** [jenkinsci/gitlab-plugin#214]
![cubits-testenv gitlab 2016-03-04 14-32-31](https://cloud.githubusercontent.com/assets/106795/13528393/0515740a-e216-11e5-89d3-b7a5688d62f9.png)

Not sure what part of the information I got wrong but it seems like I am misreading something in the guides. If I go to `http://ci.cubits.staging/project/cubits-testenv` there is an error message and the job is under `http://ci.cubits.staging/job/cubits-testenv`. Any idea what I am doing wrong?

**Comment by omehegan** [comment]
The 'project' URL is correct, as specified when you configure that job to use the GitLab plugin. GitLab will POST to that URL - it is normal to see an error if you just try to GET it with a web browser. Are you sure your GitLab server can access Jenkins at that address?

I also have a vague memory that the "Test settings" does not work until you first click "Save," which is not intuitive. Or the test button may not work at all, but everything else does.

**Comment by omorillo** [comment]
@mhenrixon Any news on this issue? Could you figure out what is going wrong? Let us know if this issue can be closed.

**Comment by mhenrixon** [comment]
Not been able to get it to work unfortunately.

**Comment by omehegan** [comment]
Can you look at the Jenkins log? It should show the request coming in. If not, you have a network issue. If it does log something, please share that. 

Have you tried ignoring the test error and actually pushing a change to see if it triggers the build?

It could also be that GitLab 7.11 doesn't work with the plugin anymore.
