### ISSUE TITLE
Inconsistent code formatting

### ISSUE THREAD

**Issue by WonderCsabo** [jenkinsci/gitlab-plugin#217]
Currently the files are formatted with different options, for examples indentation with spaces vs tabs, spaces around braces vs. not. This makes contributing and reviewing code hard.

It would be nice to format the whole codebase to be consistent, and also provide Checkstyle and/or IDE formatting profile, so future contributors can use the same formatting settings.

**Comment by omehegan** [comment]
Yeah, we definitely want to do this. @omorillo and @coder-hugo and I have discussed this, maybe we should discuss here what formatting should be used.

**Comment by omorillo** [comment]
@WonderCsabo We were thinking about introducing Coding Guidelines which should cover beside a code formatting section some rule set to improve the code quality. Next to the guidelines, we thought of providing some code formatter settings.

**Comment by MarcelFortunato** [comment]
dasda
