### ISSUE TITLE
license within pom.xml and LICENSE is different

### ISSUE THREAD

**Issue by bufferoverflow** [jenkinsci/gitlab-plugin#218]
just figured out that you have the following situation from a licensing point of view:
- [LICENSE](https://github.com/jenkinsci/gitlab-plugin/blob/master/LICENSE) is [GPL-2.0](https://spdx.org/licenses/GPL-2.0)
- [pom.xml](https://github.com/jenkinsci/gitlab-plugin/blob/master/pom.xml#L22) says [MIT](https://spdx.org/licenses/MIT)

could you please clarify this?

**Comment by KostyaSha** [comment]
@bassrock placed GPL-2.0 in initial commit https://github.com/jenkinsci/gitlab-plugin/blob/master/LICENSE

**Comment by omehegan** [comment]
I think we'd have to say the current license is GPL-2.0, based both on the timeline of commits and the way the two licenses work. If @coder-hugo and @bassrock agree, then we can update pom.xml accordingly.

We may consider changing licenses, but this will be complicated by the need to gain approval from all previous committers, I think.

**Comment by bassrock** [comment]
If that helps work for project overall then that works for me.

**Comment by coder-hugo** [comment]
I personally prefer using the MIT license as this is short and easy to understand. But if this project started with the GPL-2.0 we should use this to prevent complications with all the previous committers.

**Comment by omehegan** [comment]
Fixed. It's GPL 2.0 everywhere!
