### ISSUE TITLE
Build Coverage

### ISSUE THREAD

**Issue by bassrock** [jenkinsci/gitlab-plugin#22]
With Gitlab 7.4 it looks like the api supports build coverage. Is it possible for someone to upload what this looks like in Gitlab 7.4 and if possible the output of what the merge request requests from the build service.

**Comment by zipleen** [comment]
Hi

It looks like when when requesting /projects/ID/commits/SHA-1/status.json , the response you should get is:
```
{"id":5,"sha":"c3202889d89d8d7ab70cd2c5adf9b721bcec85b6","status":"failed","coverage":42.0}
```

It seems it's just a matter of adding the additional "coverage" to the json response. 

I think it's fair to assume that if we add here https://github.com/DABSquared/gitlab-plugin/blob/8a9468afebda30d668f437810b2e3067861b5872/src/main/java/com/dabsquared/gitlabjenkins/GitLabWebHook.java#L225 ```object.put("coverage", the_float_percentage)``` we will get that code coverage number.

I don't know how to get this "percentage" though =) Gitlab CI gives them a regular expression to extract this value, which they'll pass as a float.

**Comment by bassrock** [comment]
Hmm it would seem we would need to calculate the percentage of successful builds correct?

**Comment by zipleen** [comment]
I think this "coverage" is for the "code coverage results". 
I just installed Cobertura and I have these values in jenkins: "Packages   83% Files   24% Classes   25% Methods   28% Lines   27% Conditionals   28%"
Problem is how to get these results and what result should be considered. For me I could use the percentage of "Lines", but I'm guessing the user should be able to specify which "code coverage" percentage (s)he wants to use.

**Comment by zipleen** [comment]
Just to be clear, this is related to "code coverage for the unit tests".

In GitLab we now see:
![screen shot 2015-02-03 at 18 31 53](https://cloud.githubusercontent.com/assets/1225055/6026467/1260e8a8-abd3-11e4-983f-e8c73874e13a.png)
That "coverage" value comes from gitlab ci. We can see it here:
![screen shot 2015-02-03 at 18 32 04](https://cloud.githubusercontent.com/assets/1225055/6026489/3ab99052-abd3-11e4-819f-5fb1a4982816.png)
And this was fed from a regexp that the user needs to build, against the whole output of the command that was run. 
You specify it in the settings of gitlab ci:
![screen shot 2015-02-03 at 18 32 11](https://cloud.githubusercontent.com/assets/1225055/6026509/54199a4c-abd3-11e4-943f-aac45c20df7a.png)

Then you'll get the "code coverage" value shown in the first screenshot...

**Comment by bobey** [comment]
This feature would be a major enhancement to the plugin. With jenkins, the cobertura plugin give some good metrics.
I will take a look tomorrow to see if I find a way to get these metrics via the API.

**Comment by bassrock** [comment]
We should also see what other metric plugins this could be used for or develop our own. For instance most of my projects are Obj-C?/Swift and and PHP

**Comment by zipleen** [comment]
![screen shot 2015-02-09 at 11 28 26](https://cloud.githubusercontent.com/assets/1225055/6105425/e86e913c-b04e-11e4-949f-7c9314804574.png)

If you hover the "health report", in the healthReportDetails we have lines that represent the various values of stability. They all have a global percentage.

We could have an option in the gitlab-plugin specifying which plugin name to get this percentage and publish it in the coverage number. I'm guessing via this way you would support any plugin.

**Comment by zipleen** [comment]
I'm probably completely out of my depth here, but this seems to work: https://github.com/zipleen/gitlab-plugin/commit/0621f9a29324055d029b1de7df46e2a93f370928
There's a lot of "health reports" so we need to specify which build report we want, mine is "CoberturaBuildAction". Can you add this as a settings per project? Is this acceptable ?

**Comment by omehegan** [comment]
I don't see a good way to support this feature, if it even still exists in GitLab. It requires an optional dependency on other Jenkins plugins which can provide code coverage, and we'd have to code various methods to extract that result from them and return it to GitLab.

**Comment by tomfun** [comment]
Will be some movement in this direction? Some groovy function like *updateGitlabCommitStatus*?

**Comment by sthuber90** [comment]
I'm also interested in how it is or could be able to send the coverage results - one percentage value - back to GitLab to be used in the coverage badge.

**Comment by thatsIch** [comment]
I think we should split the concerns. Providing a means to set the coverage is different than automatically calculating the coverage. For many, the first option would be more relevant because this would allow independent calculations of which coverage is relevant for them.
