### ISSUE TITLE
Changelog file out of sync

### ISSUE THREAD

**Issue by omorillo** [jenkinsci/gitlab-plugin#223]
The changes applied to the plugin since release version **1.1.28** are missing in the **CHANGELOG.md** file and needs therefore be added.

**Comment by omorillo** [comment]
@omehegan @coder-hugo Existing changelogs list the committers. However, IMHO this information does not belong to a changelog. The changelogs should list the changes applied since the previous version but not who was the contributor. This information can be retrieved from the commit info itself, if desired. Therefore, I left this information out.

What do you opt?

**Comment by jsyrjala** [comment]
Also https://wiki.jenkins-ci.org/display/JENKINS/GitLab+Plugin is not up-to-date with versions > 1.1.28.
Seems that 1.1.31 is the latest version currently.

**Comment by omehegan** [comment]
@omorillo I agree with you, the committer is not really relevant.

@jsyrjala I changed the wiki to reference the Changelog file included in the repo, that way we only have to keep one thing up to date.
