### ISSUE TITLE
Could not find GitSCM for project for workflow project?

### ISSUE THREAD

**Issue by cliles** [jenkinsci/gitlab-plugin#234]
Is there any tips/tricks/documentation for setup with a workflow project? Trying to trigger and build MRs.

I can see some recent PR's that "fixed" support, like #206, but when I setup a workflow job and point my hook to it I get something like

```
Mar 15, 2016 1:01:51 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger onPost
workflow-project-test triggered for merge request.
Mar 15, 2016 1:01:51 AM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger createAction
Trying to get name and URL for job: workflow-project-test
Mar 15, 2016 1:01:51 AM WARNING com.dabsquared.gitlabjenkins.GitLabPushTrigger$DescriptorImpl getSourceRepoNameDefault
Could not find GitSCM for project. Project = 2, next build = {2}
```

@omehegan - plz assist.

**Comment by omehegan** [comment]
@cliles we talked about this in IRC, but did you have any more luck with this? "Works on my machine!" :)

**Comment by cliles** [comment]
ok, so I started fresh.

New pipeline job set to pull Jenkinsfile from scm. Manually ran job, worked fine. Change configuration of  the job to build on gitlab MRs, following the directions in the README for single-repository setup.

Running the job via MR hook fails. You had previously stated something about manually running the job with parameters that "worked." This was required to be done 1 time before being able to build for MRs. What is this step?

**Comment by cliles** [comment]
When configured for MRs, I get something like the following

```
using GIT_SSH to set credentials 
 > git -c core.askpass=true fetch --tags --progress git@gitlab.server:org/repo.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/${gitlabSourceBranch}^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/${gitlabSourceBranch}^{commit} # timeout=10
 > git rev-parse origin/${gitlabSourceBranch}^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
```

**Comment by omehegan** [comment]
After much discussion in IRC, we have determined that @cliles is hitting this Jenkins bug: https://issues.jenkins-ci.org/browse/JENKINS-28447  The plugin will work OK with WorkFlow jobs which define the workflow script in the Jenkins UI. If you use the git checkout method of pulling the script, it does not work because these variables are not expanded.

**Comment by adumat** [comment]
i'm trying to configure a jenkins job using "multibranch pipeline", there is a mode to use this plugin for trigger the jobs?

**Comment by omehegan** [comment]
@adumat it should just work. Please update to version 1.2.1 of the plugin and report if you have any issues. Note the Jenkins bug I mentioned in https://github.com/jenkinsci/gitlab-plugin/issues/234#issuecomment-203644051. If you have any problems, please open a separate issue.
