### ISSUE TITLE
Improve handling of Merge Requests

### ISSUE THREAD

**Issue by pbendersky** [jenkinsci/gitlab-plugin#239]
Based on a question I asked on GitLab (see [here](https://gitlab.com/gitlab-org/gitlab-ce/issues/14181#note_4212485)), it turns out we can fetch the contents of a Merge Request from the `origin` repository. As I see it, this has several advantages:
1. You don't need to setup your forked repositories to use CI, nor set the deploy key to them.
2. We could configure GitLab projects with a single repository (and maybe with no parameters!).
3. As we'll have a single repository, the "Build" button in Jenkins will remain functional.

I've only reviewed the source code quickly, so I don't have a deep understanding of it (yet). Does anyone see a drawback of this? Is this an improvement that would be welcome? (I understand this might break for older versions of GitLab).

**Comment by omehegan** [comment]
Sounds pretty cool... we should look into it further. We especially need to understand what versions of GitLab support this.

**Comment by pbendersky** [comment]
Is there a minimum compatibility requirement? Or we can break the plugin for older versions of GitLab?

**Comment by omehegan** [comment]
GitLab changed a lot between version 7.14 and 8.1. As a result, the plugin has a "Use GitLab 8.1 features" check box in the config. If this feature is only available in 8.1+, we could enable it along with the other new features based on that check box status. IMO we need to support at least 7.14, it seems many people are still using that, including me :P

**Comment by pbendersky** [comment]
Here's the full documentation of these refs: http://doc.gitlab.com/ce/workflow/merge_requests.html

This was added in [8.0.0](https://gitlab.com/gitlab-org/gitlab-ce/blob/c790107854658a37d97b9a1c9066338eb12b06bf/CHANGELOG#L662), so it's safe to use it with the 8.1+ flag.

**Comment by omehegan** [comment]
@pbendersky you figured out a way to do this with just different Git configuration in Jenkins, right? No code changes needed? If this is ready to close, go ahead and do that. Thanks!

**Comment by pbendersky** [comment]
Yes. I still think there should be a better approach (with a single repo configuration in Jenkins). But I couldn't made it work this time. I'll try sometime else.
