### ISSUE TITLE
Provide section on how to use Docker for efficient setup of test environment

### ISSUE THREAD

**Issue by omorillo** [jenkinsci/gitlab-plugin#240]
Using **Docker** allows developers and the plugin admins to efficiently set up test environment for different **GitLab** and **Jenkins** versions. This is very helpful, in particular when a reported bug related to a different version of aforementioned services needs to be reproduced.

**Comment by omorillo** [comment]
Resolved with commit e0d541d.

**Comment by omehegan** [comment]
This is great, thanks for writing this!

**Comment by omehegan** [comment]
BTW @omorillo you should come back to the irc channel :)
