### ISSUE TITLE
Use gitlab user name and email instead of those belonging to the commit author

### ISSUE THREAD

**Issue by rhduwe** [jenkinsci/gitlab-plugin#243]
For push events, user name seems to be parsed from the first commit (https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/GitLabPushCause.java#L37). This seems counterintuitive, as the person who made the push is in any case responsible for the build.

There are some situations where you might require the name of the user who made the push. For example when teamlead rebases/merges branches of other people, when you amend commits of other people, etc. On the average I'd prefer it to be the default even. 

If this is the intended behavior, perhaps original name/email can be provided through variables?

**Comment by omehegan** [comment]
@rhduwe the plugin has been largely refactored in the latest release. Please update and let me know if the behavior is still not what you would expect. I think we are now mostly using input given to us by the GitLab hooks directly.
