### ISSUE TITLE
Add bash scripts to setup docker containers with the oldest and latest Jenkins and GitLab versions

### ISSUE THREAD

**Issue by omorillo** [jenkinsci/gitlab-plugin#247]
In order to allow contributors for testing their changes against the oldest and latest Jenkins and GitLab versions it would useful to provide bash scripts which setup docker containers running those services.

**Comment by coder-hugo** [comment]
@omorillo Do you know docker-compose? There is already a corresponding [YAML file](https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml) available. So I think it should be enough to just add this to the README.
Btw. yesterday I just added the first integration test to the release-1.2 branch which runs against a dockerized GitLab environment :wink:

**Comment by omorillo** [comment]
@coder-hugo Sure, I know docker-compose. Still running a no longer supported Ubuntu distribution on my machine I could not set up docker-compose so far and test myself if the provided **yml** configuration file really works properly. Therefore I preferred to come up with an intermediate solution which I am able to test until I found the time to set up docker-compose. However, since I have a day off today, I will take the opportunity and set up a more up-to-date Ubuntu version to get docker-compose installed and update README and resolve this issue here.

I was thinking of providing two docker-compose files which set up the latest supported versions of Jenkins and GitLab (**Jenkins 1.642.2 *_\+ *_GitLab 8.5.8**) and the oldest supported ones. It might not be so neat to have a docker-compose configuration file for both services, _GitLab_ and _Jenkins_ but this would simplify the interface for the users. Would do you think?

It's great that you are pushing the test coverage forward! :+1: We really need more tests and the refactoring  iteration is the best opportunity to increase code coverage and to get a synchronized documentation!

BTW: You created the release-1.2 branch along the milestone 1.2 and assigned most of the issues to that corresponding milestone. I did not want to apply changes or add features to that branch without discussing it with you but I would like to discuss with you in a moment how we can better distribute the tasks related to the upcoming release 1.2.

**Comment by omorillo** [comment]
@coder-hugo @omehegan I put in place a single docker-compose file for setup instances of the latest services versions,  **Jenkins v1.642.2** and **GitLab v8.5.8**.

Originally, I had in mind to provide two such docker compositions in different folders to allow users to test against the latest and the oldest supported versions. Still there are some questions left I would like to discuss with somebody before performing any further step here.

**Comment by omehegan** [comment]
I have no experience with Docker yet. This might be a good chance to get some. @omorillo let's discuss further in IRC at some point.

**Comment by omehegan** [comment]
Let's close this for now and discuss on IRC if we need to do anything else. @omorillo thanks for your work on this so far!
