### ISSUE TITLE
Branch name not sent by gitlab

### ISSUE THREAD

**Issue by kgoedert** [jenkinsci/gitlab-plugin#251]
Hi,

I installed gitlab ce 8.5.1 and jenkins 1.655. I followed the instructions in the readme file. First thing is that  on the gitlab webhook if I leave it as <jenkins-url>/job/<project> and test the hook, gitlab says it is successful, but nothing happens on jenkins. If I append /build, then the build is triggered but I get this error message:

> git rev-parse --is-inside-work-tree # timeout=10
> Fetching changes from the remote Git repository
> git config remote.origin.url git@git.host/hoarder-server.git # timeout=10
> Fetching upstream changes from git@git.host:host/hoarder-server.git
> git --version # timeout=10
> git -c core.askpass=true fetch --tags --progress git@git.host:host/hoarder-server.git +refs/heads/_:refs/remotes/origin/_
> git rev-parse refs/remotes/origin/${gitlabSourceBranch}^{commit} # timeout=10
> git rev-parse refs/remotes/origin/origin/${gitlabSourceBranch}^{commit} # timeout=10
> git rev-parse origin/${gitlabSourceBranch}^{commit} # timeout=10
> ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
> Finished: FAILURE

Can anybody help?

**Comment by omehegan** [comment]
As per the documentation, the URL you should be using for the GitLab hook is e.g. http://JENKINSURL:8080/project/JOBNAME  In other words, you must use /project rather than /job, and you must not append /build. Please change that and let me know if you still have problems.

**Comment by kgoedert** [comment]
The url was wrong, and there was also something wrong with gitlab itself. I fixed the url and restart gitlab and it worked. Thanks
