### ISSUE TITLE
merge request from a forked repository doesn't work

### ISSUE THREAD

**Issue by osamahf** [jenkinsci/gitlab-plugin#259]
Hi, 

merge request from a forked repository doesn't work for me, i get this ERROR, 

`Merging Revision 79851d8c0ff78fb6d71059d1fffe0ad491de2202 (user1/myproject/master) to origin/master, UserMergeOptions{mergeRemote='origin', mergeTarget='${gitlabTargetBranch}', mergeStrategy='default', fastForwardMode='--ff'}
' > git rev-parse origin/master^{commit} # timeout=10

> git config core.sparsecheckout # timeout=10
> git checkout -f origin/master
> git merge --ff 79851d8c0ff78fb6d71059d1fffe0ad491de2202 # timeout=10
> git config core.sparsecheckout # timeout=10
> git checkout -f 79851d8c0ff78fb6d71059d1fffe0ad491de2202
> ERROR: Branch not suitable for integration as it does not merge cleanly: Could not merge AnyObjectId[79851d8c0ff78fb6d71059d1fffe0ad491de2202]`

For single-repository it's work nicely.
I try refs/head/${gitlabSourceRepoName}/${gitlabSourceBranch} instead of ${gitlabSourceRepoName}/${gitlabSourceBranch}   but still not workig 

Gitlab version : 8.6.1
Jenkins: 1.655
Plugin: 1.1.32

Any help please ?

**Comment by osamahf** [comment]
solution :  add user.name  and user.email value to git plugin in configure system.

**Comment by omehegan** [comment]
I have updated the documentation to reflect this. Thanks!
