### ISSUE TITLE
git repository url - resolve env vars

### ISSUE THREAD

**Issue by abedwardsw** [jenkinsci/gitlab-plugin#260]
@omehegan I think there is one remaining bug relating to https://github.com/jenkinsci/gitlab-plugin/issues/58. Reading through the notes I was able to get it to work, but the only way I could get it to work was by NOT using a Jenkins environment variable in the name of the git Repository URL.

Currently, all my projects are setup as follows:
Repository URL: ${GIT_SERVER}:my-group/my-project.git

If I remove the ${GIT_SERVER} and replace with the exact contents of the environment variable then the list of branches populates properly. The repository url with/without the environment variable resolve to the exact same. Would you mind resolving the variables within the Git repository url?

I am using the latest Jenkins GitLab plugin.

**Comment by omehegan** [comment]
That's an interesting one. Where is the GIT_SERVER variable set?

**Comment by omehegan** [comment]
@abedwardsw can you update to the latest version of the plugin and test? If it is still not working, please try to print this variable in a shell script step so we can see if it is set there.

Has this ever worked correctly? It's not clear to me that this is one of the variables the plugin should be setting. Also, what Jenkins job type are you using?

**Comment by abedwardsw** [comment]
GIT_SERVER is set manually in the Jenkins configuration page.  It's not a built in, just one I set to make it easy to change the url of our git server.  No, this has never worked with this particular plugin from what I can see.  However git polling etc all work fine with variables defined globally in jenkins.

**Comment by omehegan** [comment]
What type of job is this? Freestyle or Pipeline or...?

**Comment by abedwardsw** [comment]
freestyle

**Comment by omehegan** [comment]
If I understand right, you are saying that you have the Git plugin configured to check out a repo, and you are trying to use the ${GIT_SERVER} job parameter in that configuration.

If that does not work, it's a bug with the Git plugin, not the GitLab plugin. The GitLab plugin only starts the Jenkins job when triggered from the GitLab service. It does not handle checking out the repo.
