### ISSUE TITLE
Gitlab CI integration does not work with jenkins pipeline projects, build remains in state "running"

### ISSUE THREAD

**Issue by rsommer** [jenkinsci/gitlab-plugin#262]
I started experimenting with the upcoming 2.0 release of jenkins and its pipeline projects. While all "normal" projects report their build states back to gitlab as expected, the test pipeline project completes in jenkins but never reports back its completion. The state in gitlab is always "running". I did not find any error in any logfile. I tried with gitlab-plugin 1.1.28 and 1.1.32.

To reproduce:
- Create a pipeline project in Jenkins
- Activate "build on gitlab push"
- Create webhook in gitlab
- push new commit
- Look at build state in gitlab

**Comment by omehegan** [comment]
@rsommer you will definitely need to use plugin version 1.1.32 for Pipeline support to work, so make sure you're on that. Earlier versions had a bug that produced the behavior you are seeing.

There should be SOME log entries in the Jenkins log showing what the plugin is doing when it receives a hook and when the build completes. Please check for those and paste them here if possible. Thanks!

**Comment by SirEdvin** [comment]
Strange, but 1.2 version also don't work.

**Comment by pyther** [comment]
In my case builds show as "pending". I'm using Jenkins 2.0 with the gitlab 1.1.32 plugin.

```
Apr 28, 2016 9:12:22 AM com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
INFO: WebHook called with url: /olcf
Apr 28, 2016 9:12:22 AM com.dabsquared.gitlabjenkins.GitLabPushTrigger onPost
INFO: website/olcf triggered for push.
Apr 28, 2016 9:12:22 AM com.dabsquared.gitlabjenkins.GitLabPushTrigger createActions
INFO: GitLab Push Request from branch msg31-test.
Apr 28, 2016 9:12:22 AM com.dabsquared.gitlabjenkins.GitLabPushTrigger createActions
INFO: Trying to get name and URL for job: website/olcf
Apr 28, 2016 9:14:32 AM hudson.model.Run execute
INFO: publish-rpm #8 main build action completed: SUCCESS
Apr 28, 2016 9:14:32 AM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: website/olcf #11 completed: SUCCESS
```

**Comment by omehegan** [comment]
If you are using Pipeline jobs, please update to version 1.2.1 of the plugin, just released today. Then report if you are still experiencing issues.
