### ISSUE TITLE
Access to jenkins fails

### ISSUE THREAD

**Issue by strowi** [jenkinsci/gitlab-plugin#263]
Hi,

what permissions do i need to set in jenkins to allow the webhook to http://jenkins/projects/XYZ to work? We have a active-directory authentication and jenkins serves only the login page...

regards,
roman

**Comment by omorillo** [comment]
@strowi Unfortunately, I do not have any experience with Active Directory authentication and Jenkins, but if you like we can have an IRC channel session. Maybe I still can help you out with your issue. Otherwise, maybe @coder-hugo  or @omehegan have some experience with.

**Comment by strowi** [comment]
thx for the offer, i'll be idling in #gitlab-plugin.. 
I guess active-directory or other authentication doesn't matter.
With the previously used gitlab-hook plugin i was able to just trigger the build without any authentication.
Now with the gitlab-plugin it seems i have to authenticate gitlab to jenkins (or alternatively allow anyone to trigger)...

**Comment by strowi** [comment]
sorry, my mistake.. found a typo after 6 hrs..
