### ISSUE TITLE
plugin not functioning

### ISSUE THREAD

**Issue by kevindashgit** [jenkinsci/gitlab-plugin#264]
Apologies for the vague issue summary - I'm not sure what's going on w/o any logging output. 
Essentially, I've followed the `Readme` guide as closely as possible. Any tips would be greatly appreciated!

**## Versions of things**
**Jenkins**: ver. 1.625.2
**gitlab-plugin**: ver. 1.1.32
**GitLab**: ver. 8.5.8 bb69923

**## Some facts**:
- I'm able to use the `filter branches by name` feature - and it's able to auto-complete branch names and identify frivolous ones. 
- On Jenkins main config page, I was able to `test connection` and it succeeds (and the user token is my own, which has owner access to my gitlab server)

**Comment by smithrs** [comment]
Set up a Jenkins job as per the instructions, add an "Execute shell" step that just runs the "set" command as follows, so you get a dump of your build environment:

``` bash
#!/bin/bash

echo "-- Show Environment --"
echo $(printf '=%.0s' {1..150})
set
echo $(printf '=%.0s' {1..150})
echo "-- Done --"

# end
```

Test the job by pushing actual code (not just testing the web hook).

Then you can post the output here.

**Comment by omorillo** [comment]
@kevindashgit Your description is truly too vague. Please, provide more information on what you tried out so far. You may also want to verify the correctness of your Jenkins job and GitLab webhook setup with a verified working Jenkins and GitLab version. In this case, check out our "Quick test environment setup using Docker" section in the wiki for further instructions on how to set up dockerized GitLab and Jenkins instances.

**Comment by omorillo** [comment]
@kevindashgit Should you be still struggling with the setup of the plugin with the verified working versions of Jenkins and GitLab, let me know and we can arrange an IRC channel session to guide you through the setup.

**Comment by kevindashgit** [comment]
@smithrs - hitting `test hook` from gitlab does not trigger the job as it should (which is the issue I'm having). before I could even get to running

**Comment by kevindashgit** [comment]
@smithrs - hitting `test hook` from gitlab does not trigger the job as it should (which is the issue I'm having). 

Also, before I could even get to running the script you mentioned - the build fails with:

`hudson.plugins.git.GitException: Command "C:\Program Files (x86)\Git\cmd\git.exe rev-parse "origin/${gitlabTargetBranch}^{commit}"" returned status code 128:
stdout: origin/${gitlabTargetBranch}^{commit}`

I believe I do not require the `Merge before build` under `Additional Behaviors` under `Source Code Mangement` in Jenkins job configuration - so i removed this and ran again.

here is the gist of env variables (zzz'd some stuff out) https://gist.github.com/kevindashgit/840b832e5090034c21ed048dd1019154

@omorillo I will look into the docker'd version of jenkins - but gitlab I'm stuck w/ the version I have.

**Comment by smithrs** [comment]
@kevindashgit Are you seeing any evidence in your Jenkins logs that the web hook is being received? You need to troubleshoot that part of it first. The output will look like this:

```
Mar 15, 2016 4:56:35 PM com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
INFO: WebHook called with url:
Mar 15, 2016 4:56:35 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger$3 run
INFO: CI_Merge_Build triggered for merge request.
```

Actually this raises a good question, does anyone know why the log line `WebHook called with url:` fails to return a URL?

**Comment by omehegan** [comment]
@kevindashgit it looks to me like the variable for target branch is not getting expanded. That may be the first problem. But I'm confused by the fact that you quote "C:\Program Files" in your most recent comment, but your list of env vars indicates you are running Linux. Is it a Linux master and Windows slave, or vice versa? 

What type of Jenkins job is this? Freestyle? Maven? Matrix? Workflow/Pipeline?

Can you look at the config.xml for the job on the filesystem of your Jenkins master, and gist/share the section between <scm> tags? That will help us understand how you have git configured to check out code.

Finally, as @smithrs says, the Jenkins service logs should give some output to help us understand what the plugin thinks is happening.

**Comment by kevindashgit** [comment]
I do _not_ see any log output in jenkins when testing the hook and/or committing actual code. So ya - I totally agree that the root of my troubles is around setting up that connection correctly. I will redo this now and maybe I'll have more luck.

@omehegan the job is supposed to run on win - but I switched a linux build slave for the purpose of spitting out the environment variables using the script provided by @smithrs 

here is the job's `config.xml` https://gist.github.com/kevindashgit/20890ccedde379e2160d450564043bf6  

The job is more than likely a `Freestyle project` but I'm not 100% on that. I'm surprised that I don't see this anywhere like in the config.

**Comment by smithrs** [comment]
@kevindashgit Freestyle is the default. If the first two lines of xml look like this it's freestyle:

``` xml
<?xml version='1.0' encoding='UTF-8'?>
<project>
```

It it's not Freestyle that `<project>` tag will look like something else, based on whatever plugin defines the project type.

**Comment by jsyrjala** [comment]
I have also problems with gitlab-plugin 1.1.32 (see #267), but version 1.1.28 works for me.

**Comment by kevindashgit** [comment]
fyi: I finally was able to get this working by changing the trigger in the jenkins job config to `poll` (leaving the field empty) - and add the webhook in gitlab to something like: `https://jenkins.domain.com/git/notifyCommit?url=git@gitlab.domain.com:user/project.git` (I checked only Push and unchecked secure ssl)

Ultimately this was the page that helped me: http://kohsuke.org/2011/12/01/polling-must-die-triggering-jenkins-builds-from-a-git-hook/

**Comment by omehegan** [comment]
@kevindashgit by doing that you have disabled this plugin completely. If that works for you, that's good, but you aren't using a method that we support.
