### ISSUE TITLE
No Merge ID (or iid) included as environment parameter

### ISSUE THREAD

**Issue by randyaa** [jenkinsci/gitlab-plugin#266]
the only fields this plugin seems to provide to the environment is:

```
gitlabSourceRepoName
gitlabSourceRepoURL
gitlabSourceBranch
gitlabTargetBranch
gitlabActionType
```

I'd like to use the plugin to drive commenting back to gitlab with custom build success/failures.  I can use the API to do this but without the merge request id or iid available to me, it seems my only option is to pull down open merge requests and search for the current one.

It would be a lot easier if I had an environment variable so i could just make a direct request to the merge request.

**Comment by smithrs** [comment]
That functionality definitely works for me. When I dump the environment I get all the variables (9 in total). Please provide more detail about the versions (Gitlab, Jenkins, etc.) and how you are setting up your test case. Thanks.

**Comment by pjagielski** [comment]
@randyaa I think you have outdated version of the plugin, we just updated it and now we have all the variables visible as parameters.
However, I don't get how Jenkins comments about build status. GitLab API requires merge request `id` but in params I only see `iid` which doesn't work with the API.

**Comment by smithrs** [comment]
Yes it's confusing. Per this page: http://doc.gitlab.com/ce/api/merge_requests.html

The id that's visible to normal users is the iid.
The value assigned to gitlabMergeRequestId is also the iid.

You must convert iid to id using this API call:

GET /projects/${projectId}/merge_requests?iid=${gitlabMergeRequestId}

It's best to use a tool like the Chrome Advanced REST client and play with the API until it makes sense.

**Comment by pjagielski** [comment]
@smithrs Thanks! It should work for me.

**Comment by randyaa** [comment]
You're right we had an outdated version & we're all set. Thanks!
