### ISSUE TITLE
Build history is reporting sometimes a wrong branch name

### ISSUE THREAD

**Issue by jsyrjala** [jenkinsci/gitlab-plugin#268]
Sometimes Build History box in http://jenkins-server/jenkins/job/jobname/ is reporting a wrong branch name for jobs.

E.g page http://jenkins-serveri/jenkins/job/jobname/1520/ reports that it build origin/branch-a and
page http://jenkins-serveri/jenkins/job/jobname/1521/ reports that it build origin/branch-b

When Iook at Build history on http://jenkins-server/jenkins/job/jobname/, it sometimes reports that job 1521 built branch origin/branch-a. It seems that Build history reports always the branch from previous build if it is incorrect.

I am not sure what triggers this behaviour, but we see this daily.
We are running long builds 15 mins. We also use locks (Locks and Latches plugin) to prevent simultaneous builds

Environment
- gitlab-plugin 1.1.28 (happened also in earlier versions)
  - I am unable to test this in newest gitllab-plugin version due to #267.
- Jenkins ver. 1.651.1

**Comment by jsyrjala** [comment]
I also tried replacing deprecated Locks and Latches plugin with newer https://wiki.jenkins-ci.org/display/JENKINS/Throttle+Concurrent+Builds+Plugin, but that didn't fix the problem.

**Comment by omehegan** [comment]
@jsyrjala please update to plugin version 1.2.1 and test. Are you seeing this behavior both with push builds and merge request builds?

**Comment by jsyrjala** [comment]
Version 1.2.1 doesn't trigger any builds for me, see #267.

**Comment by jsyrjala** [comment]
With 1.2.2 build history no longer has the branch name "GitLab ​Merge ​Request ​#3 ​: ​library-updates ​=> ​master" like it used to in earlier versions. 1.2.2 reports this "Started ​by ​GitLab ​push ​by ​Juha ​Syrj��l��".

**Comment by omehegan** [comment]
Yes, I guess we changed the message displayed here. If you want to display something different, for Freestyle jobs you can use the [Groovy Postbuild](https://wiki.jenkins-ci.org/display/JENKINS/Groovy+Postbuild+Plugin) plugin, add a post-build step, and call `manager.build.description = "foo"` to set the description to something. If you want to pull the branch name, you can use `def branch = manager.build.buildVariables.get("gitlabSourceBranch");` and then set description = branch.

If you are using Pipeline jobs, you can set `currentBuild.description = "foo"` or whatever you want.
