### ISSUE TITLE
Question about 1.1.32 version

### ISSUE THREAD

**Issue by Dtsr** [jenkinsci/gitlab-plugin#269]
Where is the button  "rebuild open merge request on push events" on new version of plugin?

I've been working with 1.1.24 and after the update my open merge requests dont start jenkins jobs when i commit something in origin branch.

I know there is a "Rebuild open merge request", but this is not working, even if i select "On push to source or target branch".

Can you guys help me?

Jenkins version 1.654
Current gitlab-plugin version 1.1.32

**Comment by omehegan** [comment]
@Dtsr please update to the latest version of the plugin, 1.2.1. Then, if you are still having problems, follow the instructions in the README for capturing logs and post them here. Thanks!
