### ISSUE TITLE
Tag Push Events not Starting Builds

### ISSUE THREAD

**Issue by kerlandsson** [jenkinsci/gitlab-plugin#280]
We are trying to get Tag push events to work in GitLab Community Edition 8.7.0. Using the latest code from master of this plugin. When a tag is pushed, our job is not started. We have enabled FINE logging and see the following logs in Jenkins:

```
May 02, 2016 9:09:32 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/test-pu-job
May 02, 2016 9:09:32 AM FINE com.dabsquared.gitlabjenkins.webhook.ActionResolver
Unsupported event header: Tag Push Hook
```

Looking at the code of `com.dabsquared.gitlabjenkins.webhook.ActionResolver.onPost(AbstractProject<?, ?>, StaplerRequest)` we see the following:

```
String eventHeader = request.getHeader("X-Gitlab-Event");
if (eventHeader.equals("Merge Request Hook")) {
    return new MergeRequestBuildAction(project, requestBody);
} else if (eventHeader.equals("Push Hook")) {
    return new PushBuildAction(project, requestBody);
}
LOGGER.log(Level.FINE, "Unsupported event header: {0}", eventHeader);
return new NoopAction();
```

I.e., when the header is `Tag Push Hook`, a `NoopAction` is returned. What is the intent - should a `PushBuildAction` be returned or is ? If so, I can submit a simple PR.

**Comment by omehegan** [comment]
Version 1.2.3 of the plugin was just released and has this fix.
