### ISSUE TITLE
how do you manage job for normal build and merge build

### ISSUE THREAD

**Issue by fabMrc** [jenkinsci/gitlab-plugin#291]
Hi

I am used to configure my job to execute sonar analysis every night on the master.
how can I configure my job to be able to build merge request (as described in the README of the gitlab plugin) and to build my sonar analysis.

I set build parameters gitlabSourceBranch and gitlabTargetBranch to "master" to be able to trigger normal build manually or by scripts but It is dirty.

**Comment by omehegan** [comment]
What type of job is this? If it is Freestyle, the parameters you have added is probably the best way to do it. Not sure why you think that is "dirty."

**Comment by fabMrc** [comment]
Ok it is a maven job and i use Maven release plugin too, I need to make some tests 
A merge master master is not really clean but if it can do the job...

**Comment by xasx** [comment]
If you base your Sonar analyses on merge request, I bet you run into trouble because Sonar stores the various projects under its Maven coordinates, i.e. uniquely.

If you want to distinguish the analyses of the merge requests, you need to employ a logic to tell Sonar that there's something different - it just has no concept of branches IIRC.

That said, why don't you just add `sonar:sonar` to the Maven goals you execute with regular merge request building?

**Comment by fabMrc** [comment]
Differents use cases for a job that use gitlab ci plugin
- Release version with Maven release plugin for jenkins
- Trigger manual or scripted sonar analysis

in two case we need to give some parameter without that the build fail with the log below :

```
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@my-server:namespace/sandboxproject.git # timeout=10
Fetching upstream changes from git@my-server:namespace/sandboxproject.git
 > git --version # timeout=10
 > git fetch --tags --progress git@my-server:namespace/sandboxproject.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/${gitlabSourceBranch}^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/${gitlabSourceBranch}^{commit} # timeout=10
 > git rev-parse origin/${gitlabSourceBranch}^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Retrying after 10 seconds

 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@my-server:namespace/sandboxproject.git # timeout=10
Fetching upstream changes from git@my-server:namespace/sandboxproject.git
 > git --version # timeout=10
 > git fetch --tags --progress git@my-server:namespace/sandboxproject.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/${gitlabSourceBranch}^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/${gitlabSourceBranch}^{commit} # timeout=10
 > git rev-parse origin/${gitlabSourceBranch}^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
```

So we add two build parameters gitlabSourceBranch & gitlabTargetBranch with "master" as default value;

It allow to release, execute sonar analysis but I wonder me if it is a clean practice or not.

**Comment by omehegan** [comment]
@fabMrc I think this practice is fine, nothing unusual about it. I suspect the "merge of master to master" is actually a complete NOOP from the perspective of Git, so nothing to worry about.
