### ISSUE TITLE
NPE during the build of a merge request

### ISSUE THREAD

**Issue by angely-dev** [jenkinsci/gitlab-plugin#295]
Hi,

I'm trying to get Jenkins building the source branch merged with the target branch of a Merge Request. Hence, I followed [these instructions](https://github.com/jenkinsci/gitlab-plugin#jenkins-job-configuration), including the _Additional Behaviours_ step.

When a Merge Request is created in GitLab, Jenkins runs the build as expected but then a NullPointerException is triggered:

```
Merging Revision 73bf4ee77234767a99467a60af19d700db98ad94 (origin/feature/something) to origin/develop, UserMergeOptions{mergeRemote='origin', mergeTarget='${gitlabTargetBranch}', mergeStrategy='default', fastForwardMode='--ff'}
 > git rev-parse origin/develop^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f origin/develop
 > git merge --ff 73bf4ee77234767a99467a60af19d700db98ad94 # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 73bf4ee77234767a99467a60af19d700db98ad94
FATAL: null
java.lang.NullPointerException
    at hudson.plugins.git.extensions.impl.PreBuildMerge.decorateRevisionToBuild(PreBuildMerge.java:88)
    at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1009)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1098)
    at hudson.scm.SCM.checkout(SCM.java:485)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Finished: FAILURE
```

My set up:
![jenkins1](https://cloud.githubusercontent.com/assets/4362224/15016983/051c602a-1214-11e6-92a8-b99e93f6f417.PNG)
![jenkins2](https://cloud.githubusercontent.com/assets/4362224/15016986/06d6c310-1214-11e6-85cd-ed414dd04af3.PNG)

Versions used:
- Jenkins 2.1
- GitLab Plugin 1.2.2
- GitLab 8.7.1

Do you have any idea about this exception?

Thanks.

**Comment by jakobwenzel** [comment]
Hi,

i also get a Null Pointer Exception, but different from yours:

`Checking out Revision 38b0de22b7c07a5a54af4e4bbf9bb71c33d49c19 (origin/libjconfig-rework)

> git config core.sparsecheckout # timeout=10
> git checkout -f 38b0de22b7c07a5a54af4e4bbf9bb71c33d49c19
> git rev-list 41fa1fcea1d81d4ba483c3133cd0101c2e996385 # timeout=10
> FATAL: null
> java.lang.NullPointerException
>     at org.jboss.resteasy.util.ReadFromStream.readFromStream(ReadFromStream.java:30)
>     at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.bufferEntity(ClientResponse.java:307)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:48)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
>     at com.sun.proxy.$Proxy91.headCommit(Unknown Source)
>     at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.existsCommit(CommitStatusUpdater.java:72)
>     at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:37)
>     at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.prebuild(GitLabCommitStatusPublisher.java:33)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:837)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:832)
>     at hudson.model.Build$BuildExecution.doRun(Build.java:144)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
>     at hudson.model.Run.execute(Run.java:1738)
>     at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
>     at hudson.model.ResourceController.execute(ResourceController.java:98)
>     at hudson.model.Executor.run(Executor.java:410)
> Build step 'Publish build status to GitLab commit (GitLab 8.1+ required)' marked build as failure`

Versions used:
- Jenkins 2.1
- GitLab Plugin 1.2.2
- GitLab 8.7.2

Regards,
Jakob

**Comment by coder-hugo** [comment]
@jakobwenzel this is the same as #284 which should be fixed by 85f415fe1f65282d9f0101e01fd414acb2a22bdc within the next release
@champidead can you add a logger for "com.dabsquared.gitlabjenkins" as described [here](https://github.com/jenkinsci/gitlab-plugin#user-support) and paste its output here.

**Comment by jakobwenzel** [comment]
Sorry, I did not check the closed issues...

Robin Müller notifications@github.com schrieb am Mi., 4. Mai 2016, 20:38:

**Comment by omehegan** [comment]
It looks like @champidead's log that he initially posted shows <pre>mergeTarget='${gitlabTargetBranch}'</pre>

The variable is not getting expanded for some reason?

**Comment by demaniak** [comment]
@omehegan @champidead ah - just have a look at the readme again, there is mention of some incompatibility introduced (and the work around): https://github.com/jenkinsci/gitlab-plugin#configuring-access-to-gitlab

Specifically  the _Git configuration for Pipeline/Workflow jobs_ section.

Not sure if this IS the problem, but it sounds plausible.

**Comment by omehegan** [comment]
I don't think @champidead is using Pipeline jobs, so it's unrelated.

**Comment by angely-dev** [comment]
@demaniak  Indeed, this is not a pipeline job but a freestyle job. Concerning the `mergeTarget` variable, I noticed too @omehegan but I don't know why it is not getting expanded...

@coder-hugo: I'll try that next Monday when I'm getting back to work and I'll post the result.

Thanks for the help.

**Comment by angely-dev** [comment]
@coder-hugo I added the logger and played the merge request again. Here is the log: http://pastebin.com/XBBu7jDK (see my first post for the Jenkins output, it is the same).

**Comment by strowi** [comment]
Hi,

just wanted to add, i'm getting the same error without using any gitlab/-variables.
I have set it to fixed branches:

```
Jenkins: 2.1
git-plugin: 1.2.2
Gitlab: 8.7
Branch specifier: origin/feature/*
Branch to merge to: develop
Merge strategy: default
Fast-forwarde mode: --no-ff
```

might be related to this: https://github.com/jenkinsci/git-plugin/pull/394 ?
regards,
strowi

**Comment by tpbowden** [comment]
I am also having this issue, Jenkins is not using any of the required parameters for gitlab merge requests to build causing null pointer exceptions.

**Comment by xasx** [comment]
Also seeing the NullPointerExceptions.

I guess that the constellation in all our cases is similar:

* We merge before build &rarr; this merge creates a new commit
* The GitLab plugin wants to set the commit status and must retrieve the commit beforehand  
```
java.lang.NullPointerException
...	at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.existsCommit(GitLabCommitStatusPublisher.java:93)
	at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.updateCommitStatus(GitLabCommitStatusPublisher.java:78)
	at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.prebuild(GitLabCommitStatusPublisher.java:48)
```
  confirmed in the logs:
```
Call GitLab:
HTTP method: HEAD
URL: https://server/api/v3/projects/grp%2Fprj/repository/commits/d6df701437eedc4e2bc1312a029f0570711e468d
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]
May 12, 2016 9:29:24 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Got response from GitLab:
URL: https://server/api/v3/projects/grp%2Fprj/repository/commits/d6df701437eedc4e2bc1312a029f0570711e468d
Status: 404 Not Found
```
* the mentioned commit is the merge commit:
```
$ git log

commit d6df701437eedc4e2bc1312a029f0570711e468d
Merge: 4708993 f5567b7
Author: jenkinsslave <jenkinsslave@somejenkins>
Date:   Thu May 12 09:29:23 2016 +0200

    Merge commit 'f5567b7e9fc422c3c7b24ba6eeac13d6256a7510' into HEAD
```

  *which is for sure not in the upstream GitLab but only in the local Jenkins workspace repo*

I don't know how to properly resolve this problem, probably the commit of `${gitlabSourceRepoName}/${gitlabSourceBranch}` is the one to be updated.

**Comment by angely-dev** [comment]
I still have the issue even if I use 1.2.2. Any idea?

**Comment by tpbowden** [comment]
I downgraded to 1.1.32 for now and everything is working fine.

**Comment by wangjingfei** [comment]
I met the same error with @jakobwenzel. Sometimes it works but some times the exception is thrown. 
I use: 
Gitlab plugin: 1.2.1
Jenkins: 2.3

**Comment by omehegan** [comment]
@wangjingfei that issue will be fixed in the next release.

**Comment by omehegan** [comment]
@champidead what version of the regular Git plugin are you using? Is there an update to it available? It seems to me that this plugin should be expanding the variable, and isn't. It does appear to be expanding the source branch variable though.

Can you try, temporarily, removing the "merge before build" configuration for Git, and then try to print/echo the gitlabTargetBranch variable in a shell script step, so we can see if it is actually set? Although if it isn't, the issue should be that Git tries to check out an empty value there.

**Comment by omehegan** [comment]
@strowi if you are hitting this issue when your Git configuration for the job is not using any of the parameters set by the GitLab plugin, then I definitely suspect the bug is with the Git plugin and not our plugin.

**Comment by angely-dev** [comment]
@omehegan I'm using the last version of Git plugin (2.4.4). When I remove the "merge before build" behavior, it works and the variable gets expanded (see last lines of the log) :

```
GitLab Merge Request #37 : feature/ARCHI-1162-1 => develop
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/jobs/build/jobs/projet_a_mr/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@int-pprd:root/projet_a.git # timeout=10
Fetching upstream changes from git@int-pprd:root/projet_a.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git -c core.askpass=true fetch --tags --progress git@int-pprd:root/projet_a.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse 73bf4ee77234767a99467a60af19d700db98ad94^{commit} # timeout=10
 > git branch -a -v --no-abbrev --contains 73bf4ee77234767a99467a60af19d700db98ad94 # timeout=10
Checking out Revision 73bf4ee77234767a99467a60af19d700db98ad94 (origin/feature/ARCHI-1162-1)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 73bf4ee77234767a99467a60af19d700db98ad94
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/hudson623987934981726591.sh
+ echo 'gitlabTargetBranch = develop'
gitlabTargetBranch = develop
...
```

**Comment by strowi** [comment]
@omehegan I hope i remember this currectly.. Have switched to a shell-script in the meantime. 
Yes, i have been using only the variables provided by the git-plugin.
Target-Branch is always "develop" and Source-Branch "${env.GIT_BRANCH}" (the currently pushed branch).

**Comment by omehegan** [comment]
@strowi GIT_BRANCH is not a variable that our plugin sets. See https://github.com/jenkinsci/gitlab-plugin/blob/master/README.md#parameterized-builds for the list of variables you should be able to use.

**Comment by omehegan** [comment]
@champidead OK, looks like a Git plugin bug. I suggest you file an issue against that, and please link to it here.

**Comment by chitraj8** [comment]
Hi,

I have below configurations: 
Git version 2.4.2 
Jenkins 1.642.18.1 (Cloudbees Enterprise) 
Stash Pull Request Builder Plugin 1.6.0

When I configured all the required details for Stash PR builder
I see the trigger and API calls done from Jenkins to update Stash, but merge branches before build throwed me error
Merging Revision 87d49e9a2d44e2b6387debe8da42f5d30058c010 (origin/bugfix/test) to origin/master, UserMergeOptions{mergeRemote='origin', mergeTarget='master', mergeStrategy='default', fastForwardMode='--ff'}
 > /usr/cisco/bin/git rev-parse origin/master^{commit} # timeout=10
 > /usr/cisco/bin/git config core.sparsecheckout # timeout=10
 > /usr/cisco/bin/git checkout -f origin/master
 > /usr/cisco/bin/git merge --ff 87d49e9a2d44e2b6387debe8da42f5d30058c010 # timeout=10
 > /usr/cisco/bin/git config core.sparsecheckout # timeout=10
 > /usr/cisco/bin/git checkout -f 87d49e9a2d44e2b6387debe8da42f5d30058c010
FATAL: null
java.lang.NullPointerException
	at hudson.plugins.git.extensions.impl.PreBuildMerge.decorateRevisionToBuild(PreBuildMerge.java:88)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:965)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1054)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1276)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Notifying upstream projects of job completion
Finished: FAILURE


Deleting the step Merge Branches before Build - gave success build.

I tried downgrading git plugin to 2.4.2, still it gives null pointer exception when trying to do Merge Branches before Build .

Any ideas?

**Comment by omehegan** [comment]
@chitraj8 you do not seem to be using the gitlab-plugin. That's what this repo is for. You should file your issue against https://wiki.jenkins-ci.org/display/JENKINS/Stash+pullrequest+builder+plugin
