### ISSUE TITLE
Could I use ${gitlabSourceRepoHttpUrl} ?

### ISSUE THREAD

**Issue by sak52jp** [jenkinsci/gitlab-plugin#296]
Hi,

We are using a git remote repository with a Git-lfs module.
Git-lfs requires a HTTP-BASED URL for a remote repository, not SSH-BASED one.

For being able to merge from a forked repository in a Jenkins project,  I added a second repository with ${gitlabSourceRepoURL} as a URL in the Source Code Management section.

But gitlab-plugin always set a forked repository  URL using SSH-BASED one, like this:
`> git config remote.TestPrj.url git@localhost:forked/TestPrj.git`

I studied a code and discovered below in CauseData.java.
`variables.put("gitlabSourceRepoHttpUrl", sourceRepoHttpUrl);`

I used ${gitlabSourceRepoHttpUrl} as a second repository URL and found everything goes well.
`> git config remote.TestPrj.url http://localhost:11111/forked/TestPrj.git # timeout=10`

I have found resolution, but I cannot decide to use it yet because ${gitlabSourceRepoHttpUrl} is not specified explicitly in the README.md.

Would you ensure this variable as a basic API of the Gitlab-plugin?

Versions used:
- Jenkins 1.609.1
- GitLab Plugin 1.2.1
- Git Plugin 2.4.1
- GitLab 8.6.6

Thanks.

**Comment by omehegan** [comment]
Yes, you can use it. I will update the doc with a current list of usable variables.

**Comment by sak52jp** [comment]
Hi @omehegan , thank you very much! :smile:
