### ISSUE TITLE
Variables sent from GitLab can no longer be forwarded to Parameterized Build Trigger in Post Build Actions in 1.2.1

### ISSUE THREAD

**Issue by patrickc91** [jenkinsci/gitlab-plugin#297]
I'm not sure if this is a bug or anything, but in version 1.1.32 all of the variables sent through the plugin would be listed in the 'Parameters' section of the job details. These variables could be forwarded to a Post-Build Parameterized build which I found very useful for keeping my CI and CD scripts generic and work with multiple repositories. My only issues with 1.1.32 were the inability to keep GitLab updated with Jenkins build status, and that the $gitlabSourceRepoName variable was formatted as '<group>/<repo_name>'. The second issue would be easily resolved if I were able to pass my own custom variables to the Jenkins job through the Webhook (which I haven't been able to figure out).

Now, in version 1.2.1, those variables are no longer listed in 'Parameters' and can no longer be forwarded to a Parameterized build. I tried creating a variable in the first script who's value was $gitlabSourceRepoName, then pass that variable into my second script once the first succeeds. But the variable ends up containing the value of ${gitlabSourceRepoName} in the first script, then evaluates to the literal string '${gitlabSourceRepoName}' when passed into my second script.

These changes removed the ability for me to have a single CI script and a single CD script that was generic enough to build, test and deploy the code for any repository I hooked up to the build scripts. I've gone from having 2 generic jobs, to requiring 2 jobs for every single repository I have.

What was the purpose of these changes? If it was intentional, does anyone have an alternate solution for keeping my CI/CD scripts generic? Even just the ability to pass my own custom variables into the webhook from GitLab would be extremely helpful.  
<br/>
Current Versions:
- Jenkins 1.651.1
- GitLab Plugin 1.2.1
- Git Plugin 2.4.4
- GitLab 8.7.0

**Comment by omehegan** [comment]
@patrickc91 the relevant GitLab variables are now environment variables rather than job parameters. To work around your issue, add a shell script build step which builds up a properties file containing the variables and their values that you want to use. For example:

`echo "gitlabUserName=$gitlabUserName" > buildproperties`

Then, in your post-build job trigger configuration, choose to send 'Parameters from properties file,' and specify the buildproperties file you created. Then, as long as the downstream job has those parameters defined, they will be passed through. I just tested this and it works.

Having said that, IMO the practice of having generic jobs that build all your projects is usually a bad one. First, it makes it harder to find the logs for the build of a given project when they're mixed in with the logs of all your other projects. Second, build status becomes worthless because you are mixing the status of all your disparate codebases into one job. I think these drawbacks, as well as others, outweigh the relative simplicity of a small number of jobs. 

If your job configurations really are identical, you might consider using the Job DSL plugin as an entry point to automatically generate jobs for you from a template. Many people use this approach, and auto-generate a Jenkins job each time a new git repo is created, for example. Then the repo has hooks which trigger the created job. With this approach you can also update all the created jobs simultaneously if you need to make a global change, so you get the best of both worlds in terms of generic job config but separate build metadata.

**Comment by patrickc91** [comment]
@omehegan Thank you for both providing an answer to the original question, as well as the advice on how to properly handle jobs for different repositories. Those are valid points and things I hadn't really thought of.

I'm in the middle of implementing CI and CD for the company I work for and this is my first time going through this process, so you've helped me immensely. I'll take your advise and look into Job DSL and individual jobs for each of our repositories.

Thanks again for the quick response, for all your hard work, and for saving me a ton of time in the future when everything would have inevitably fallen apart.

**Comment by omehegan** [comment]
@patrickc91 if you are early in the process, I can also highly recommend that you look into the Jenkins Pipeline plugin. This is IMO really the future of flexible CD for Jenkins. It can be challenging to switch over to it, but it's relatively easy to start with it from scratch. If you go that route now, you'll make your life much easier down the track as your builds and pipelines get more complex. I speak from experience :)

**Comment by patrickc91** [comment]
@omehegan I had been looking into Pipelines a little bit, but ended up going the route I did simply because I thought the generic CI and CD idea was going to work out great. It's good to hear from someone else who has experience with this stuff, especially this early in the process. I'm not far enough into getting my CI/CD stack set up that I would feel like I'm throwing a lot away by switching over to Pipelines, so I'll definitely look into what it takes to get that up and running.

I just upgraded to Jenkins 2.0 and I know they're making a big push for Pipelines, so I'm not sure why I didn't put more research into it. There are so many tools out there for CI/CD, it felt intimidating and took me forever to settle on a GitLab w/Jenkins setup. So far it's feeling like the right move.

Thanks again for all your help too. I'm glad I reached out for assistance on here instead of just struggling and hacking my way through a poor setup. You've probably saved me a ton of time.

**Comment by omehegan** [comment]
@patrickc91 I would recommend that you hang out in the #jenkins IRC channel on irc.freenode.org. It's a great resource for getting tips about best practices from other experienced Jenkins users. Always better to learn the right way the first time. The https://groups.google.com/forum/#!forum/jenkinsci-users mailing list is also great.

**Comment by patrickc91** [comment]
@omehegan I've joined the IRC channel (I didn't realize IRC channels were still so heavily used these days) and the mailing list you've suggested. Again, thank you for pointing me to helpful resources. I don't often reach out to others online for assistance, so this has been a great experience.

So far I'm not having much luck with integrating Pipelines with GitLab. It seems everything was designed to work with GitHub and all the material I can find on Pipelines seems to utilize the GitHub Organization Folder plugin. I haven't had any luck with authenticating against GitLab, and I'm not sure I see any way for Jenkins to keep GitLab in the loop on its current build status.

But I'll get this figured out and reach out to people in the IRC channel.

**Comment by patrickc91** [comment]
I found the DSL reference. This should definitely help.

**Comment by omehegan** [comment]
Also see this plugin's doc on using it with Pipeline. It's actually pretty easy. I'm using it. But it doesn't currently support story the Pipeline Groovy in your git repo. You have to define it in the Jenkins job config script editor.

**Comment by patrickc91** [comment]
Ah, that's good to know. I was intending to store the script in the repository. I can develop in the script editor for now though. I just need to learn some Groovy and I should be good to go!

**Comment by patrickc91** [comment]
@omehegan Hey, I know this isn't the appropriate place to reach out to you, but I've figured out the majority of my Pipeline with SCM checkout, build, tests and deployment all working. The only thing I'm still having an issue with is the gitlabCommitStatus step. The Pipeline always sits and hangs until I forcibly kill the step and job.

I've tried:

```
gitlabCommitStatus {
    node {
        <build steps>
    }
}
```

```
node {
    gitlabCommitStatus {
        <build steps>
    }
}
```

And even gitlabCommitStatus on its own just to see if it would process the step appropriately.

```
node {
    gitlabCommitStatus {}

    <build steps>
}
```

All with no luck. I also haven't had any luck with filtering branches by name, but have had success with filtering by regex.

If you have any insight, thanks. Otherwise, sorry to reach out to you through here!

**Comment by patrickc91** [comment]
@omehegan Of course, seconds after asking you I decided to play around with it again and have it working successfully. Perhaps it's because I upgraded to Jenkins 2.1 from 2.0, or perhaps I was mistaken about what options I had tried.

Anyway, thanks again for all the help you've given me. I'm still having issues filtering branches by name, but the regex solution works just fine for now.
