### ISSUE TITLE
Upgrading the plugin sometimes causes loss of configuration

### ISSUE THREAD

**Issue by omehegan** [jenkinsci/gitlab-plugin#299]
@jsyrjala reported this in https://github.com/jenkinsci/gitlab-plugin/pull/213 and I have seen it on my system as well. When I upgraded from 1.1.32 to 1.2.1, the jobs I had configured to for GitLab triggering lost that configuration. I'll try to reproduce this in my test Jenkins instance and see if I can figure out why it happens.

**Comment by cliles** [comment]
@omehegan - This is blocking my upgrade. :)

**Comment by hho** [comment]
I have this problem as well.

To me it seems that 1.2 is just not backwards compatible – it can't read the old settings on the job config and thus considers itself disabled. The JobDSL folks noticed the same issue: https://groups.google.com/forum/#!topic/job-dsl-plugin/KyvH15-EDtk

**Comment by Timbus** [comment]
1.2 uses a `<branchFilterType>` setting which is not present in old configs. It's a pity as I now need to use the raw XML in my JenkinsJobBuilder jobs.

**Comment by rocklan** [comment]
This happened to me and I had to sit down for an hour and re-configure all of my jobs. Very annoying.

**Comment by omehegan** [comment]
@clockwisemusic what version did you upgrade from and to?

**Comment by rocklan** [comment]
@omehegan from version 1.1.32 to version 1.2.5

**Comment by titilambert** [comment]
Hello, I'm using Gitlab plugin 1.4.5 with Jenkins 2.32.2 and I have this issue. Sometimes Gitlab build trigger config becomes empty...

**Comment by omehegan** [comment]
@titilambert this issue only happened when upgrading the plugin, not just at random. If you are seeing random unexpected changes to job configuration, I have to guess that it's not a plugin bug. But please open a separate issue for that.
