### ISSUE TITLE
Wrong URL to GET /repository/branches [500 Internal Server Error]

### ISSUE THREAD

**Issue by irobayna** [jenkinsci/gitlab-plugin#300]
It appears the URL being used to GET branches is wrong.  From the gitlab plugin logs in jenkins I see the following:

```
Call GitLab:
HTTP method: GET
URL: http://logan/api/v3/projects/jeremy.jensen%2Fiws/repository/branches
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]
```

```
Got response from GitLab:
URL: http://logan/api/v3/projects/jeremy.jensen%2Fiws/repository/branches
Status: 500 Internal Server Error
Response headers: [
Connection = [keep-alive],
Content-Length = [48],
Content-Type = [application/json; charset=utf-8],
Date = [Thu, 05 May 2016 14:53:57 GMT],
Server = [nginx],
Status = [500 Internal Server Error],
X-Request-Id = [e26e84f0-ee88-4af9-be2c-869c39945012],
X-Runtime = [2.083766]
]
Response body: {"status":"500","error":"Internal Server Error"}
```

Looking at gitlab [documentation](http://doc.gitlab.com/ce/api/branches.html) I found the URL should look like 

 `GET /projects/:id/repository/branches` 

where the plugin right now it appears is using `project name` instead of `:id`

**Comment by omehegan** [comment]
Can you explain what part of the trigger process you are seeing this behavior in? One thing I would say is that it's not good that GitLab responds with a 500. That indicates an error not being handled correctly on that side. Also, can you please look at the plugin README, User Support section, and add the versions and log info requested there? That will help us with debugging. Thanks!

**Comment by irobayna** [comment]
@omehegan Thank you... my bad.

I am trying to use the Gitlab plugin feature `Filter branches by name` which internally executes the output I posted above.  I got that output by following the instructions on how to turn logging in Jenkins for the plugin (very helpful)

Here you go:
`GitLab plugin version (1.2.2)`
`GitLab version (8.7.2)`
`Jenkins version (2.1)`

Let me know if I can be of any help or provide something else

**Comment by coder-hugo** [comment]
@irobayna the URL is correct. If you have a look to this [documentation](http://doc.gitlab.com/ce/api/projects.html#get-single-project) you will see that the id can be also the namespace combined with the project name. If the URL would be wrong GitLab would respond with a HTTP 4xx not a 500. So the error is on the GitLab server and you should have a look to the log files of GitLab to see what causes this error.

**Comment by irobayna** [comment]
@coder-hugo Thanks! 

Closing as this appears to be a gitlab issue, my guess something to do with how `gitlab-workhorse` is parsing the path
