### ISSUE TITLE
No credential found

### ISSUE THREAD

**Issue by ffrddrll** [jenkinsci/gitlab-plugin#301]
GitLab plugin version: 1.2.2
GitLab version: GitLab Community Edition 8.3.8 4c83880
Jenkins version: 1.651.1

I try to config GitLab plugin after upgraded from 1.1.28 to 1.2.2.
Manage Jenkins -> Configure System -> Gitlab -> GitLab connections -> API Token
Showed 'none' 

I try to add a new credential as well, but it did not work.
New credential was created but GitLab plugin can't fetch it.

Also I enable logging as described in [User support](https://github.com/jenkinsci/gitlab-plugin#user-support). No related log found even I set log level to ALL.

What should I check next to solve this issue?

**Comment by vills** [comment]
Looks like your job configuration have not connection settings in config. It should be like this:

```
    <com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty plugin="gitlab-plugin@1.2.2">
      <gitLabConnection>my-gitlab-instance</gitLabConnection>
    </com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty>
```

Try to select proper connection in section _GitLab connection_ in job configuration.

In my case, i got same problem. That was because i use jenkins-job-builder and didn't set up connection in job conf.

**Comment by ffrddrll** [comment]
Thanks for advice.
The GitLab connection section in job configuration displayed the right GitLab host URL.
API token is still 'none'. 😕

**Comment by vills** [comment]
@LukeJang in my case it shows me right connection setting, but just because there was no option like 'nothing selected', and it wasn't actually saved to job config file on disk. Try just 'save' job configuration again.

**Comment by coder-hugo** [comment]
@LukeJang what kind of credentials do you have added for the GitLab connection? At the moment only the "secret text" credentials are supported.

**Comment by ffrddrll** [comment]
Thank @vills for help, @coder-hugo find the true reason.
I used 'Username with password' for credential. Thanks for point it out.
I didn't know GitLab plugin use 'jenkins' as default username to connect GitLab.
It will be great if we can find those information from README.
Thank you very much!

**Comment by omehegan** [comment]
Updated the README to make this clearer.
