### ISSUE TITLE
Plugin 1.2.2 not publish build status

### ISSUE THREAD

**Issue by fabMrc** [jenkinsci/gitlab-plugin#305]
Hi

I upgraded to 1.2.2 with Gitlab 8.7.3 (the last) and now build are triggered on jenkins on Merge request event (and push on MR also as configured in webhooks & my job) but the build status is never pushed to gitlab UI.
furthermore there is no "build pending message" on gitlab.

The gitlab API Token is ok on jenkins and the connecion success.

**Comment by tpbowden** [comment]
I'm having the same problem, jenkins doesn't seem to be adding any parameters to my builds

**Comment by fabMrc** [comment]
Hi

I resolved this issue by adding a new after build action which allow jenkins to commit build status on gitlab.
It works nice but recents changes should be documented !

**Comment by coder-hugo** [comment]
This feature is documented in the [README](https://github.com/jenkinsci/gitlab-plugin#gitlab-configuration--81) and the [CHANGELOG](https://github.com/jenkinsci/gitlab-plugin/blob/master/CHANGELOG.md#120). Furthermore this build step should be added automatically during the first restart after the plugin upgrade for all jobs that had this feature configured previously.
