### ISSUE TITLE
GitLab [ci-skip] is ignored

### ISSUE THREAD

**Issue by cgumpert** [jenkinsci/gitlab-plugin#306]
Hi,

I have some trouble to understand how I can tell jenkins to skip the build for a particular commit or merge request. I configured the job to use the '[ci-skip]' feature from gitlab

![screenshot from 2016-05-10 13 41 24](https://cloud.githubusercontent.com/assets/10184162/15145284/f9903b0a-16b4-11e6-91ba-dc0711c3f4e1.png)

Nevertheless, a build is triggered even if I add '[ci-skip]' to the commit message. Here is a part of the gitlab-plugin log (I removed lines with URL and email information):

> "commits" : [ {
>     "id" : "0742e353ebf43bf4e930677a4941a33e7771a64d",
>     "message" : "follow HSF template for generating cmake configuration files\n",
>     "timestamp" : "2016-05-10T12:26:24+02:00",
>     "author" : {
>       "name" : "Christian Gumpert",
>      },
>     "added" : [ "cmake/ACTSConfig.cmake.in", "cmake/ACTSCreateConfig.cmake" ],
>     "modified" : [ "CMakeLists.txt", "Core/CMakeLists.txt" ],
>     "removed" : [ "cmake/ACTSConfig.cmake" ]
>   }, {
>     "id" : "3074b40ba1cfeddb9af121bed8316a872cf343bc",
>     "message" : "add header file with version number\n",
>     "timestamp" : "2016-05-10T13:05:36+02:00",
>     "author" : {
>       "name" : "Christian Gumpert",
>     },
>     "added" : [ "ACTSVersion.h" ],
>     "modified" : [ "CMakeLists.txt" ],
>     "removed" : [ ]
>   }, {
>     "id" : "7b7462cd9b7e86b3ed124e2044b5aef538cd4308",
>     "message" : "remove symbolic link\n",
>     "timestamp" : "2016-05-10T13:26:03+02:00",
>     "author" : {
>       "name" : "Christian Gumpert",
>      },
>     "added" : [ ],
>     "modified" : [ ],
>     "removed" : [ "Gaudi/Tests/ExtrapolationTest/run/PropagationEngineTest_jobOptions.py" ]
>   }, {
>     "id" : "f33c35953a54c91d69f3c89e26267df835b6f05c",
>     "message" : "fix permissions\n\ncloses ACTS-87 [ci-skip]\n",
>     "timestamp" : "2016-05-10T13:28:01+02:00",
>     "author" : {
>       "name" : "Christian Gumpert",
>     },

As you can see, the last commit contains '[ci-skip]' in its message. My guess is that this is related to
[this line](https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/trigger/handler/push/PushHookTriggerHandlerImpl.java#L33):

`return commits != null && !commits.isEmpty() && commits.get(0).getMessage() != null && commits.get(0).getMessage().contains("[ci-skip]");`

Could it be that for the situation where I push multiple commits at once, it looks only at the first commit and not the most recent one? If I understand correctly, the build job runs on the last commit. In my opinion the desired behavior for this situation is to run the build job for the latest commit which does not mention [ci-skip]. If all pushed commits contain [ci-skip] in their commit message, no build job is run.

I am using
- gitlab-plugin 1.2.2
- jenkins 1.656
- GitLab EE 8.5.12

Please let me know if you need more information.
Thanks,
Christian

**Comment by omehegan** [comment]
@cgumpert I think you're right about what is causing this. Personally I think the practice of putting [ci-skip] in commit messages is a bad one, it just pollutes the git history. If you expect to push a lot of known-broken changes, it seems preferable to configure the job to only trigger on Merge Requests, rather than pushes. Then you can set [ci-skip](and soon [WIP] as well, more commonly seen) in the MR description, and none of the commits pushed to that MR will build until you remove that from the desc. 

Otherwise, if you adopt a practice of only pushing sets of commits which SHOULD build successfully, then you don't need all this [ci-skip] stuff. If you occasionally have to push something known to be broken, let the build fail and move on. Just my two cents as far as best practices.

I will mark this as a bug for us to look at, though.

**Comment by cgumpert** [comment]
@omehegan Thanks for your feedback. I completely agree that pushing broken commits is something one should really try to avoid. In my case, it was actually something different: we updated the doxygen documentation of our code and we split the work among different developers. So there were quite a few commits which we knew would not affect the build results. In any case, I also agree that [ci-skip] does not look nice in the git log and running a few builds more is not a problem.

I thought I just report the behavior so that other people can comment/are aware of. It is certainly nothing urgent.
