### ISSUE TITLE
Problem filtering branches

### ISSUE THREAD

**Issue by claytonpiccinin** [jenkinsci/gitlab-plugin#307]
Hello all.

 I'd like to know if someone have the same issue: 

I'm using Gitlab to SCM and Webhook calls to build my project. When I push to a specific branch such as "dev-job0001", my build is called normally. I have a post-action that use "git publisher" to set a TAG to my project and publish the code in a specific branch called: "homologacao". 

PROBLEM: After publish in a branch: "homologacao", Gitlab sends the notification to Jenkins that rebuild my project. 

Shouldn't gitlab-plugin filter this branch? Not building when a branch is called "homologacao"? 

Thanks a lot.

**Comment by coder-hugo** [comment]
If you haven't configured any [branch filtering](https://github.com/jenkinsci/gitlab-plugin#branch-filtering) in the gitlab-plugin a build for each and every branch is triggered.

**Comment by claytonpiccinin** [comment]
I'm using a branch called "dev-0001", my question is: Why Jenkins is building my job when a push to a branch "homologacao" for example. It should be filtered by jenkins and ignored.

**Comment by mattiasb** [comment]
@claytopiccinin You need to specify what branches gitlab-plugin should build by filtering (just like @coder-hugo says) otherwise gitlab-plugin will build on every push to every branch.

**Comment by claytonpiccinin** [comment]
@mattiasb I'm filtering by regex: dev-\* as you can see on this image: 
![captura de tela 2016-05-11 as 17 47 37](https://cloud.githubusercontent.com/assets/13591059/15196127/49bcada6-17a1-11e6-9ea1-ef4200a5c7a8.png)

![captura de tela 2016-05-11 as 17 48 27](https://cloud.githubusercontent.com/assets/13591059/15196133/4c6c777a-17a1-11e6-9005-23a28407d59a.png)

Can you help me to understand what's wrong?

**Comment by claytonpiccinin** [comment]
I'll explain the flow:

1 - Devel push on branch dev-job0001 

2 - Gitlab Webhook send a call to build and test the app

3 - After test app, Jenkins publish on branch called "homologacao'

4 - GItlab identifies push TAG event and send my app to Amazon Opsworks SDK that published my app on testing environment. 

PROBLEM: On step 3, when Jenkins test the app an then publish in a branch called: "homologacao", gitlab is sending a call to Jenkins again, because it's a PUSH event. Jenkins receive this and SHOULD ignore, because it's not a branch "DEV-*". But Jenkins is building it again.

**Comment by Timbus** [comment]
I don't think that is a valid regex, if that has anything to do with it..

Maybe you want `^dev-.+`

e: or just ^dev- since you are only checking the start of the string anyway

**Comment by mattiasb** [comment]
@claytopiccinin does the tag push event web hook send to another Jenkins job or the same as above?

(and also, but probably not related, your regex is wrong. Just like @TiMBuS says).

**Comment by claytonpiccinin** [comment]
@mattiasb the same as above. But the push tag is not a problem. Jenkins takes 2 actions: 

First, jenkins push to a branch called "homologacao" and then push the TAG. V.{BUILD_ID} as you can see here: 

![captura de tela 2016-05-11 as 21 56 07](https://cloud.githubusercontent.com/assets/13591059/15201059/4dc39154-17c3-11e6-9234-4aa2b7c5dc19.png)

![captura de tela 2016-05-11 as 21 56 26](https://cloud.githubusercontent.com/assets/13591059/15201063/523d6d54-17c3-11e6-97fe-43c85472314d.png)

The problem is: Jenkins aways have to push to a branch "homologacao", and this event causes a new build.

**Comment by claytonpiccinin** [comment]
@TiMBuS I'll try with the regex you mentioned, but I think it's not the problem. Thanks a lot.

**Comment by coder-hugo** [comment]
@claytopiccinin you should get an error at all as your regex isn't valid. If I use this regex in a unit test I get the following exception:

``` java
java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.dev-*
^
```

Strange that a build was triggered in your case.

**Comment by claytonpiccinin** [comment]
@coder-hugo I tried to change to a regex you mentioned, but I have the same behavior. Do you know how can a debug it? This behavior started when I updated "gitlab-plugin".

**Comment by coder-hugo** [comment]
@claytopiccinin do you have any further build trigger configured for this job? Cause the GitLabPushTrigger of your job shouldn't trigger a build at all. You haven't checked neither "Build on Push Events" nor "Build on Merge Request Events" according to your added screen shots.

**Comment by claytonpiccinin** [comment]
@coder-hugo No, I don't. After build my app, Jenkins only push to a branch homologacao, Gitlab identifies that is a PUSH event e sends Webhook call again. Jenkins should ignore this step, because it's not a branch configured in regex to trigger a job. But is building again =/

**Comment by coder-hugo** [comment]
@claytopiccinin not sure if you understood my last comment. According to your screen shot the gitlab-plugin won't trigger any build for your configuration.
Can you please add a logger for "com.dabsquared.gitlabjenkins" (see [README](https://github.com/jenkinsci/gitlab-plugin#user-support)) so I can verify this.

**Comment by claytopiccinin** [comment]
@coder-hugo Sorry! I really don't understood. I changed the strategy to build my apps on Jenkins using a method described on this post:

http://stackoverflow.com/questions/21314632/how-to-exclude-git-branch-from-building-in-jenkins?answertab=votes#tab-top

But I have the same behavior on Jenkins. My configuration is: 

![captura de tela 2016-05-13 as 13 20 23](https://cloud.githubusercontent.com/assets/13591059/15254509/8e2ed4c4-190d-11e6-859f-bc49ed15f9e6.png)


![Uploading Captura de Tela 2016-05-13 às 13.20.36.png…]()

![captura de tela 2016-05-13 as 13 20 47](https://cloud.githubusercontent.com/assets/13591059/15254514/9541b8da-190d-11e6-8f88-d51d2113abbe.png)

Any kind of branch is building, could it be a Jenkins bug? 

I tried to configure log, but it's not logging anything. 

![captura de tela 2016-05-13 as 09 34 20](https://cloud.githubusercontent.com/assets/13591059/15254616/06aa3e3e-190e-11e6-859e-842666cf964a.png)

**Comment by claytonpiccinin** [comment]
@coder-hugo Sorry! I really didn't understand. I changed the strategy to build my apps on Jenkins using a method described on this post:

http://stackoverflow.com/questions/21314632/how-to-exclude-git-branch-from-building-in-jenkins?answertab=votes#tab-top

But I have the same behavior on Jenkins. My configuration is: 
![captura de tela 2016-05-13 as 13 20 23](https://cloud.githubusercontent.com/assets/13591059/15254707/8977280e-190e-11e6-9902-f2891c83ccba.png)
![captura de tela 2016-05-13 as 13 20 36](https://cloud.githubusercontent.com/assets/13591059/15254709/8c35071e-190e-11e6-8774-ab6b4052eec1.png)
![captura de tela 2016-05-13 as 13 20 47](https://cloud.githubusercontent.com/assets/13591059/15254712/90b85390-190e-11e6-9714-a08f1d6bacd1.png)

Any kind of branch is building, could it be a Jenkins bug? 

I tried to configure log, but it's not logging anything. 

![captura de tela 2016-05-13 as 09 34 20](https://cloud.githubusercontent.com/assets/13591059/15254616/06aa3e3e-190e-11e6-859e-842666cf964a.png)

**Comment by claytonpiccinin** [comment]
My Webhook configuration: 

When PUSH EVENT
http://example.com:8080/job/$project/build

**Comment by claytonpiccinin** [comment]
Hello all! First of all, thank you for help me on this issue! 

I changed the strategy following this link: 
http://stackoverflow.com/questions/21314632/how-to-exclude-git-branch-from-building-in-jenkins?answertab=votes#tab-top

Follow my configuration: 

![captura de tela 2016-05-13 as 16 15 07](https://cloud.githubusercontent.com/assets/13591059/15259156/0661c416-1926-11e6-8ddb-6e93c1e65dd9.png)

![captura de tela 2016-05-13 as 16 15 49](https://cloud.githubusercontent.com/assets/13591059/15259168/10108b96-1926-11e6-85cf-68b33f6e7ac7.png)

Everything is working fine. But I really would like to use Webhooks to call a build rather than use SCM controlled by "cron".

**Comment by omehegan** [comment]
@claytopiccinin I apologize, but your updates about this issue are really confusing. You're mixing a variety of information about different plugins - Git plugin, GitLab plugin, post-build git tags, etc. Now you've configured your job, on the Jenkins side, to build by polling SCM rather than "When a change is pushed to GitLab." Please understand that this plugin is only used when you check the "Build when a change is pushed to GitLab" box in your Jenkins job.

> My Webhook configuration:
> 
> When PUSH EVENT
> http://example.com:8080/job/$project/build

This is your problem. You have set up your web hook on the GitLab side to trigger the generic Jenkins job build endpoint. That is going to cause this job to build, no matter how you configure the "Build Triggers" part of the Jenkins job, whenever actions occur in the repo as configured in the GitLab hook (push, MR, tag, etc.).

If you want to use our plugin, please configure your GitLab web hooks using the URL that is displayed in your job configuration when you check "Build when a change is pushed to GitLab." As in your screenshot above, the URL would be something like http://yourjenkinshost:8080/project/BUILDNAME  That URL triggers our GitLab Jenkins plugin. If you use the /job/BUILDNAME/build URL, that is going to trigger the build every time, and anything that happens is unrelated to our plugin.

**Comment by claytonpiccinin** [comment]
@omehegan Sorry! I'm not sure that you follow this issue exactly as I explained. I was using the Gitlab-Plugin with follow steps: 

1 - Configuring Jenkins with "Build when change is pushed to Gitlab"
2 - FIlter branch by regex: "^dev-.+" as @TiMBuS said. 
3 - Configuring Gitlab Webhook with URL: "http://myjenkinshost:8080/job/BUILDNAME/build"

It's everything that I need to build my app. 

I've exaplained the flow used to build my app as follow: 

1 - Developer pushes to a branch called dev-job0001
2 - Gitlab Webhook identifies PUSH event and send a POST request to Jenkins in URL: http://myjenkinshost:8080/job/BUILDNAME/build
3 - Jenkins build my app and uses "Git Publisher" plugin to push a branch called "homologacao" and set a TAG version $V.{BUILD_ID}. <<< This branch is used by Aws Opsworks to deploy my app in "testing" environment. 
4 - After testing, an Analyst merge branch dev-job0001 to a master, that sends Webhook call to Aws Opsworks that published my app in production environment. 

The PROBLEM was: 
When "Git Publisher" pushes to a branch called homologacao, it was sent to Jenkins that should IGNORE, because it's configured to build only branches specified in regex. 

After test many times, and aways without success, I changed the method to use SCM Poll.

**Comment by omehegan** [comment]
My point is that by configuring your GitLab hook to hit the job/BUILDNAME/build URL, you are bypassing our plugin. Any problems you have with that approach are bugs somewhere else, possibly in the regular Git plugin.

**Comment by claytonpiccinin** [comment]
Hmmm... I'll try to use without /build that bypasses your plugin. Thanks

**Comment by omehegan** [comment]
Please follow my explanation in my comment from earlier today, and also the readme of this plugin, for configuring your job to use it. You can use the branch filter settings of our plugin (after you select trigger on push to GitLab) to achieve the same thing as the filter settings in the main Git checkout config.
