### ISSUE TITLE
Build history shows username with wrong encoding.

### ISSUE THREAD

**Issue by jsyrjala** [jenkinsci/gitlab-plugin#308]
Build history box shows this "Started ​by ​GitLab ​push ​by ​Juha ​Syrj��l��" in 1.2.2. It should show this "Started ​by ​GitLab ​push ​by ​Juha ​Syrjälä". This indicates typically some failure with character encoding. e.g. reading UTF-8 data as ISO-8859-1. The name shows up correctly in Gitlab UI.

**Comment by coder-hugo** [comment]
The current implementation used the system default encoding so I'd assume your system isn't configured properly. Nevertheless I changed the implementation to first look for the character encoding of the request and if this is not given it will use UTF-8 for decoding the request body of the web hook.

**Comment by jsyrjala** [comment]
Well, using the system default encoding for handling incoming data is usually wrong. The plugin is receiving data in some specific (e.g. UTF-8) and the plugin must use the same encoding when parsing the data.

**Comment by coder-hugo** [comment]
Of cause it's wrong to use the system default encoding for handling incoming data. This was just a hint for you that you should have a look at the system. Cause I can't imagine why a modern system should use a encoding different than UTF-8 as default encoding :wink:

**Comment by jsyrjala** [comment]
I tested this now. The encoding is working correctly. Thanks.
