### ISSUE TITLE
Could not activate Jenkins CI in GitLab itself

### ISSUE THREAD

**Issue by tonka3000** [jenkinsci/gitlab-plugin#315]
Hy,

my problem is not directly in this plugin, but i think it depends on a wrong config in the gitlab-plugin in my jenkins instance.
## My problem

I can't see the **Jenkins CI** under my GitLab services. I don't know why.
Is it only visilbe if the gitlab-plugin is configured correctly?
In Jenkins (under **Manage Jenkins** - **Configure System**) i configured my gitlab instance, but there are 2 strange things in the new version. I have to click the add button and use a secrect text to enter my api token. If i choose my API token (in the combobox) the "API Token for GitLab access reuired" disappears. But when i revisit the config section i will get the same reuqired message again.

Can anybody give me some advise what i'm doing wrong.

Jenkins: 2.3 on Windows
GitLab plugin: 1.2.2

Thanks in advance
Tonka

**Comment by eskobarba** [comment]
No it wont show up as a service, in CE at least, refer to the documentation, for each project in gitlab you will have to setup a webhook that triggers job

**Comment by tonka3000** [comment]
oh, good to know.

thx @eskobaba

**Comment by mingderwang** [comment]
good to know, thanks
