### ISSUE TITLE
Provide complete demo setup script

### ISSUE THREAD

**Issue by omorillo** [jenkinsci/gitlab-plugin#318]
Having a **full demo** setup with configured _Jenkins_ job and _GitLab_, put in place and launched with a single command, docker(-compose) for instance, would help in getting started with the plugin.

**Issues:**
- naive solution: provide configuration files for each service (:warning: several services involved (_PostgreSQL_, _Redis_, _Jenkins_, _GitLab_ etc.) &#8594; might be undesirably high memory consumption
- alternative approach: provide a script which sets up the complete demo (_Jenkins_ job, etc.)
- some combination of above approaches (e.g. store only configuration of _Jenkins_ job and use script to configure _GitLab_)
- another approach would be to provide _Docker images_ through **Docker Hub**
- where to store the scripts / configuration files? In _master_ branch or better a separate _demo_ branch?
- which _Jenkins_ and _GitLab_ versions to use? a single Jenkins-GitLab pair or different pairs?

**Comment by omorillo** [comment]
**Solution:**

For each of the required services _(PostgreSQL, Redis, Jenkins, GitLab)_ a docker image will be provided through **Docker Hub**.

A _docker-compose_ file will be added to the master which puts in place the complete setup.

To start with a simple _Freestyle job_ will be provided showing the configuration on Jenkins and GitLab, including the parameterization of the job using **EnvInjectPlugin**.

Later the example will be extended by a _pipeline job_ example.

**Comment by omorillo** [comment]
**Additional thoughts:**

For the first version of the _Docker images_ it won't be possible to customize the port of the services. Later we should think of either using some different ports for the diverse services and / or allowing to pass the desired ports as argument.

**Comment by omehegan** [comment]
@omorillo is this work still in progress?

**Comment by omehegan** [comment]
@omorillo ping!

**Comment by omehegan** [comment]
@omorillo haven't heard from you in awhile, are you still interested/able to work on this?

**Comment by omorillo** [comment]
@omehegan Hi owen, sorry for my delayed reply. Yes, it's true, I've been very busy and had therefore no time to work on the plugin. I hope to start working on the plugin from mid / end december on.

**Comment by omehegan** [comment]
@omorillo no problem, nice to hear from you :)
