### ISSUE TITLE
Job Parameters are ignored

### ISSUE THREAD

**Issue by bjoernwenzel-tommapps** [jenkinsci/gitlab-plugin#320]
Hi All,

We have a gitlab server running 7.7.0 and a jenkins server with version 1.651.2.
I tested to update the gitlab-plugin to 1.2.2 what failed, so we restore our old version of the plugin (1.1.28).
After this the jenkins won't build the job correctly. He ignores the parameters and says that there are no build parameters, like gitlabTargetBranch or else. When the job starts we can see this build parameters as tooltip, but when the job starts they will be ignored and removed.
In the Build overview the parameters are also not visible. Are there any ideas?

Cheers,
 Björn

**Comment by omorillo** [comment]
Hello @bjoernwenzel-tommapps,

honesty I do not have any idea yet. How did you restore the old plugin version, by downgrading? Have you tried to uninstall and reinstall the plugin (1.1.28) again?

**Comment by omehegan** [comment]
@bjoernwenzel-tommapps when you upgraded to Jenkins 1.651.2, you got hit with this: https://jenkins.io/blog/2016/05/11/security-update/

Follow the instructions there to work around this issue. It's not directly related to the plugin itself, but rather to a change in how Jenkins handles job parameters now.

I will update the README to reference this.

**Comment by danjee** [comment]
I've added the parameters 

`-Dhudson.model.ParametersAction.keepUndefinedParameters=true -Dhudson.model.ParametersAction.safeParameter=gitlabSourceBranch` but still the same error on jenkins log when making a push
