### ISSUE TITLE
Support NameSpace or ProjectName with dot in it

### ISSUE THREAD

**Issue by bulanovk** [jenkinsci/gitlab-plugin#326]
Support NameSpace or ProjectName with dot in it
According to Rails documentation(http://guides.rubyonrails.org/v3.1.3/routing.html section 3.2 Dynamic Segments) Rail use a dot as separator for formatted routes.
In this case if we have dot in ProjectId constructed from(namespace + projectname) all request except getSingleProject(http://docs.gitlab.com/ce/api/projects.html#get-single-project) fail with message
`Failed to update Gitlab commit status for project Name.Test/Repo': HTTP 500 Internal Server Error`

**Comment by omehegan** [comment]
Released in version 1.2.3 of the plugin.
