### ISSUE TITLE
Plugin always build master branch instead of speceified branch name

### ISSUE THREAD

**Issue by kha0s178** [jenkinsci/gitlab-plugin#330]
Hello, I have a job with exactly specified branch name ('mybranch' for example). On manual build all works fine. I've checked 'Filter branches by name' and set 'mybranch'. Build start on trigger only on push to this particular branch but Jenkins build master branch instead.

Jenkins 2.5, GitLab 8.7.2, GitLab Plugin 1.2.2

**Comment by coder-hugo** [comment]
Do you have configured your Jenkins job as described [here](https://github.com/jenkinsci/gitlab-plugin#git-configuration-for-freestyle-jobs)?

**Comment by kha0s178** [comment]
Oh, thanx. Now configured and works fine on webhook but now I can't build job manually:
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Because branch now 'origin/${gitlabSourceBranch}' instead of 'mybranch'.

**Comment by omehegan** [comment]
@kha0s178 do you still have a parameter defined for the job, named gitlabSourceBranch? If so, filling in a value when you run the job manually should work. If it does not, your Git plugin configuration is incorrect or there is a bug with that plugin. Please post a screenshot of that part of your job config if you are still having issues.

**Comment by kha0s178** [comment]
For example, jenkins git settings with specified branch:
![git](https://cloud.githubusercontent.com/assets/10846522/15496801/fae22194-219f-11e6-8d11-9901c340a78e.jpg)

In my case the best behavior for gitlab plugin if we have branch specified (GIT_BRANCH) could be: 
1) Automaticly filter branches by that name (GIT_BRANCH)
2) Build project on that branch (GIT_BRANCH)

It quite easy end not so complicated (we don't need any Additional Behaviours)
Now the best trick for me is just execute shell command: "cd $WORKSPACE && git checkout $GIT_BRANCH".

Anyway thanks for help, I'll try your suggestion today (with parameter gitlabSourceBranch).

**Comment by omehegan** [comment]
Configuring the parameter should work. Please reopen if not.
