### ISSUE TITLE
Jenkins build not getting triggered

### ISSUE THREAD

**Issue by danjee** [jenkinsci/gitlab-plugin#334]
Hello,
I have my Jenkins machine configured for using non-forked repository as mentioned in the tutorial like this: 

![image](https://cloud.githubusercontent.com/assets/3084216/15543940/7f40ee20-229f-11e6-93a3-38169231fed6.png)

![image](https://cloud.githubusercontent.com/assets/3084216/15543970/9e565eda-229f-11e6-8da3-47678d786283.png)

And the Gitlab hook points to the build action on the button 

![image](https://cloud.githubusercontent.com/assets/3084216/15543998/c6ce3e78-229f-11e6-97d0-5672b961ff56.png)

When triggering the build from `curl` I can specify the source branch and the parameterized build is OK.

`curl http://sisif.intranet.asf.ro:8001/view/CAPONE_AGENCY/job/Capone%20Agency%20DEV/build?delay=0sec --data-urlencode json='{"parameter": [{"name":"gitlabSourceBranch","value":"dev"}]}'`

My first thought is that is something I am missing but I cannot find a way to tell get the plugin to read the Gitlab payload values.

**Comment by omorillo** [comment]
@danjee First question: Does testing the hook through GitLab's _Test Hook_ button in the Webhook menu succeed?

**Comment by danjee** [comment]
Hello,
No, Jenkins throws an error:

`Caused by: javax.servlet.ServletException: 
This page expects a form submission but had only {delay=[0sec]}
        at org.kohsuke.stapler.RequestImpl.getSubmittedForm(RequestImpl.java:1007)
        at hudson.model.ParametersDefinitionProperty._doBuild(ParametersDefinitionProperty.java:154)
        at jenkins.model.ParameterizedJobMixIn.doBuild(ParameterizedJobMixIn.java:195)
        at hudson.model.AbstractProject.doBuild(AbstractProject.java:1745)`

My guess is that I don't send any parameters by this and I need the gitlabSourceBranch parameter

**Comment by omorillo** [comment]
Which _Jenkins_, _GitLab_ and _plugin_ versions are you using?

**Comment by omorillo** [comment]
See issue #320. I think this is your problem.

**Comment by danjee** [comment]
Gitlab is 8.4.4, Jenkins 2.5 and the latest plugin

**Comment by omorillo** [comment]
Please, let me know, if issue #320 helped you resolve your issue.

**Comment by danjee** [comment]
Thank you for your fast response. I will try it tomorrow and let you know.

**Comment by danjee** [comment]
I've added the parameters 

`-Dhudson.model.ParametersAction.keepUndefinedParameters=true -Dhudson.model.ParametersAction.safeParameter=gitlabSourceBranch` but still the same error on jenkins log when making a push

**Comment by danjee** [comment]
The plugin version is 1.2.3, just downloaded it this morning.

**Comment by omorillo** [comment]
Could you please post the log output. Follow the instructions in the **README** to add a _gitlab plugin_ logger and set level to _FINE_.

It would be also helpful if you could put in place a simple set up (_Freestyle job_ without additional parameters) and check if triggering through the test hook button in GitLab webhook page works for you.

If the log output does not give any clue and triggering through test hook for the simple setup works for you we can have a support session later in our #gitlab-plugin channel and I will try to reproduce.

**Comment by danjee** [comment]
I've modified the hook with buildWithParameters insted of build (at the end of the URL) and the trigger works now. But It's a deploy on the default branch, the new branch is not getting pulled from Gitlab. 
I have no log output in the logs. Seems like the plugin is not triggering the job, but the url itself.

**Comment by omorillo** [comment]
Can offer you support through _gitlab-plugin_ channel in 2 hours.

**Comment by danjee** [comment]
Yes, I can give you more info there, thanks.

**Comment by omehegan** [comment]
@danjee you are using the wrong hook URL for your trigger, and this is bypassing our plugin. Please use only the URL shown in the job config when you check the "trigger on pushes to GitLab" box. The URL will be http://JENKINSHOST/project/YOURBUILDNAME 

The URL should not include /build and should not be passing any parameters. The plugin will read these from the json sent by GitLab.

**Comment by danjee** [comment]
You are right! That was the problem. My url had `view` instead of `project` and I totally missed it. Thank again for the time and support @omorillo and @omehegan.
