### ISSUE TITLE
Error "Could not connect to the CI server. Please check your settings and try again." on Omnibus CE 8.8.x

### ISSUE THREAD

**Issue by cometjc** [jenkinsci/gitlab-plugin#336]
My jenkins version is 1.656
After upgrade gitlab-plugin from 1.1.28 to 1.2.2, and gitlab from 8.6.1 to 8.8.2.

The Merge Request page start showing error 

```
Could not connect to the CI server. Please check your settings and try again.
```

![image](https://cloud.githubusercontent.com/assets/84070/15599524/6be0968c-2416-11e6-82fc-bec9ecfb6a38.png)

There is a related issue on gitlab https://gitlab.com/gitlab-org/gitlab-ce/issues/17792

The ci_commit.status is never assigned in gitlab, but i don't know why.

**Comment by coder-hugo** [comment]
Can you please provide some more information about your Jenkins job configuration. Is the post build step "Publish build status to GitLab" activated for the corresponding job?

**Comment by cometjc** [comment]
I missed the part of adding post build step "Publish build status to GitLab". After added the post build step and let gitlab trigger webhook again, the MR status is fine now. thanks!

![image](https://cloud.githubusercontent.com/assets/84070/15625999/429d3ff6-24ec-11e6-8d87-6c3c2e7b8e0c.png)

**Comment by sunnywanggit** [comment]
@jcppkkk How did you handle it? I encountered the same problem？
