### ISSUE TITLE
Filter on affected paths of push event

### ISSUE THREAD

**Issue by alkersan** [jenkinsci/gitlab-plugin#339]
Is it technically possible to filter not branches, but paths affected by push event ?

Motivation: given a single repository with a bunch of modules (services or libraries), all in one branch (master), I'd like to have distinct build job for every module. At the same time it's undesirable to build them all on every push.

Jenkins Git plugin, for example, when configured to do polling, have notion of included/excluded path regions, to prevent unnecessary builds if pushed commit doesn't affect path, related to current build job.
And as far as I see in [web-hook reference](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md#push-events), push event contains affected paths information.

**Comment by coder-hugo** [comment]
IMHO adding such a feature would cause more trouble than benefit. E.g. only the push event contains the affected commits and with these the affected paths. The MR events don't contain this info. So the filtering won't happen all the time. Adding this somehow just for push events will make the UI even more complex. And I think there are only a few people that would use this feature at all. For everybody else we make the plugin more complicated than necessary.
Furthermore you should think about restructuring your git repository as your workflow is very uncommon for git. With this workflow you lose a lot of the jenkins gitlab integration. E.g you can't use the "Publish build status to GitLab" if you build only a sub module of you git repository. Cause the succeeded or failed build only represents a part of the repository not the whole one. This build status is for example helpful for MRs as you can see if the code is working before reviewing it.
