### ISSUE TITLE
Provide Troubleshooting section

### ISSUE THREAD

**Issue by omorillo** [jenkinsci/gitlab-plugin#341]
We need come up with some kind of **trouble shooting** section, basically a check list of steps to perform when facing some _unexpected_ or _wrong behaviour_.

**Background:**

Many of the submitted issues are related to wrong usage of the plugin _API_. In most of these cases the submitted issue or a similar one was already described by some user. Providing some guide lines what checks to perform before submitting a new issue would allow the user to trouble shoot and to find such sorts of issues himself by simply performing some simple checks.
## **Steps to include could be for instance:**

**Before submitting a new issue, please make sure you have performed the following checks:**
- Does the web hook url in _GitLab_  looks like https://_[GITLAB-ADDRESS]_/project/_[JOB-NAME]_
- **...**
- Check if a similar issue does already exist
- Make sure a very simple setup works for you (e.g. _Freestyle job_ with "echo" instruction in build shell)

**Comment by coder-hugo** [comment]
There is just one major issue remaining: At the moment it seems that almost nobody reads the README before submitting a new issue. E.g. the required information for a new issue described [here](https://github.com/jenkinsci/gitlab-plugin#user-support) are almost missing for every new issue.
IMHO a troubleshooting section only makes sense if this could be placed right before the "create new issue" page. Putting it just to the README won't change anything. Those who already read the README will find their answer or submit a new issue if the README doesn't answer their question. And those who don't read the README will still submit issues with questions that are already answered.

**Comment by omorillo** [comment]
I totally agree that most people don't read the README, and therefore won't read neither the  troubleshooting section on their own. But I think that the best thing that we can do on our side is to provide some typical issues catalog and to refer the issuers to such a troubleshooting section and hope that they "quickly" figure out what they did wrong. This won't solve the problem completely, but I believe that at least a few people will be able to solve their problems, especially those which are willing to address the problem but do not know what to do. And for other ones this section might be a help at least in limiting the search space of their problem. It certainly won't help those guys who expect the solution to be served in a golden plate and neither those who are facing a real issue, let's say an implementation issue which needs to be solved on our side.

**Comment by omorillo** [comment]
I think it won't take much time to prepare such kind of catalog and could be at least of little help in reducing the number of usage related issues.

**Comment by omehegan** [comment]
The issue template has helped at least collect useful info from people when they submit something. I feel like the volume of duplicate issues has gone down. I'm also planning to do a significant refactor of the docs, moving things into the wiki and adding screenshots, to hopefully make it easier for people to set up the plugin.
