### ISSUE TITLE
Missing build status for MR from forks

### ISSUE THREAD

**Issue by McFoggy** [jenkinsci/gitlab-plugin#344]
### Context
- **Gitlab plugin version**: 1.2.3
- **Gitlab version**: 8.8.2 CE
- **Jenkins version**: 1.651.2
### Problem description

Using a fork, having some updates in a branch I created a merge request for integration into upstream.
Jenkins correctly built the project and added some comment to the MR. Unfortunately no build status has been registered.

![image](https://cloud.githubusercontent.com/assets/1119660/15702099/5288918c-27de-11e6-8ce8-be60a3ff5e1f.png)

In gitlab `production.log` file, I can see that actions were received to set some status. But I have doubt about the git SHA1 IDs that are passed (probably the local merged SHA1)

```
    Completed 200 OK in 63ms (Views: 0.3ms | ActiveRecord: 5.5ms)
    Started POST "/api/v3/projects/devs%2Fgitlab-001/statuses/545e03a490fd4e4f28983dbbe47e1f2e9ffdcc50?state=running&ref=awxgx-doc&context=jenkins&target_url=http%3A%2F%2Fmy-jenkins-server%2Fjob%2FSANDBOX%2Fjob%2Fgitlab-001%2F9%2F" for 127.0.0.1 at 2016-06-01 09:04:49 +0200
    Started GET "/api/v3/projects/devs%2Fgitlab-001/repository/commits/545e03a490fd4e4f28983dbbe47e1f2e9ffdcc50" for 127.0.0.1 at 2016-06-01 09:04:56 +0200
    Started POST "/api/v3/projects/devs%2Fgitlab-001/statuses/545e03a490fd4e4f28983dbbe47e1f2e9ffdcc50?state=success&ref=awxgx-doc&context=jenkins&target_url=http%3A%2F%2Fmy-jenkins-server%2Fjob%2FSANDBOX%2Fjob%2Fgitlab-001%2F9%2F" for 127.0.0.1 at 2016-06-01 09:04:56 +0200
    Started POST "/api/v3/projects/6/merge_requests/8/notes?body=%3A%2B1%3A+Jenkins+Build+Success%0A%0AResults+available+at%3A+%5BJenkins+%5Bgitlab-001+%239%5D%5D%28http%3A%2F%2Fmy-jenkins-server%2Fjob%2FSANDBOX%2Fjob%2Fgitlab-001%2F9%2F%29" for 127.0.0.1 at 2016-06-01 09:04:57 +0200
    Started GET "/devs/gitlab-001/merge_requests/4/ci_status" for 127.0.0.1 at 2016-06-01 09:04:58 +0200
```

If I do a MR starting from a branch in the origin repository it works as expected.

![image](https://cloud.githubusercontent.com/assets/1119660/15702247/43563574-27df-11e6-8ee6-f90e13aaf525.png)

Did I missed something to have it working?

I have seen that big changes are pending in #285 , would you suggest to use this PR?

**Comment by McFoggy** [comment]
An here is my Jenkins config

![image](https://cloud.githubusercontent.com/assets/1119660/15702513/b263a482-27e0-11e6-87ad-7c76237e37f8.png)

![image](https://cloud.githubusercontent.com/assets/1119660/15702516/b639020a-27e0-11e6-9279-2373d991970a.png)

![image](https://cloud.githubusercontent.com/assets/1119660/15702509/ad1eb32c-27e0-11e6-8954-6f75b7b4983c.png)

**Comment by omorillo** [comment]
@McFoggy I observed the same behaviour with **GitLab 8.8.2**.  But I think this issue needs to be fixed on GitLab side. An issue for that already exists. (see **https://gitlab.com/gitlab-org/gitlab-ce/issues/17757**).

**Comment by McFoggy** [comment]
@omorillo thanks I admit that I overlooked gitlab issues because I wrongly thought such a 'normal' behavior was working & tested on gitlab side.

**Comment by omorillo** [comment]
I tested a few days ago with **GitLab 8.8.2** and **GitLab 8.7.6** and could verify that this issue is only occurring in the latest _GitLab_ version. **Still** I cannot completely exclude a fault on our side yet, since I had not the time yet to test the **GitLab 8.8.2 REST API** manually (let's say using **curl**) to check whether the API is really wrongly behaving. I hope to get to test it within the next two days.

**Comment by omorillo** [comment]
@McFoggy Please, keep this issue open.

**Comment by pbendersky** [comment]
This works with the changes I submitted in #285. The issue was that the plugin was only using the Build Status API on the source repository, while GitLab expected it on the target repository (the user's fork).

**Comment by McFoggy** [comment]
@pbendersky I am new to gitlab and evaluating it for a choice in our company.

> the plugin was only using the Build Status API on the source repository, while GitLab expected it on the target repository (the user's fork).

How can this be the case? I expect the build status to be on the upstream project, the one that receives the MR not the one from which it originates. 
In Github when you do a PR, you see nothing in the fork ; everything related to the PR is on the upstream.
I'll try your plugin version coming from #285 that looks more to something I'd expect.

**Comment by pbendersky** [comment]
I found it while coding the PR. On builds triggered by pushes on upstream, GitLab expects the build status on that project. If the build was triggered by a MR, it expects the build status to be set on the forked project. I think it makes sense, as the main project has not been affected yet (the MR is not yet merged).

**Comment by McFoggy** [comment]
@pbendersky ok technically speaking the API expects info from the fork, but at UI level I expect to see the build status in the MR inside the upstream project. Am I wrong?

**Comment by pbendersky** [comment]
That's correct. On the UI you see it on the upstream project. But since the commit is on the fork, we need to call the API to the forked project.

**Comment by McFoggy** [comment]
@pbendersky I tested the #285 PR with _**modern**_ MR handling. Unfortunately I could not have it working when the MR is coming from a fork.

What I have observed _(using the docker test setup from src/docker/docker-compose.yml)_:
1. jenkins build is fired when the MR is created from fork
2. the user configured in jenkins to notify need to have rigths on both upstream and fork project otherwise a 403 is sent back when status API is called on fork
3. on build success (from a MR webhook), inside gitlab MR page:
   - I see a comment from jenkins regarding build success
   - **but no build status is created on the MR**

![image](https://cloud.githubusercontent.com/assets/1119660/15749231/df1e883c-28e1-11e6-859f-c5f0f1ee09f8.png)

I have perhaps wrong expectations on how it should work.
Can someone clarify?

**Comment by pbendersky** [comment]
I'll check it. Your expectations on how it should work are ok.

**Comment by pbendersky** [comment]
@McFoggy it's working fine for me in my installation. The user I have configured in Jenkins has permissions for all projects though. It even updates the status (in GitLab) without reloading the page. I'm using GitLab 8.8.2

**Comment by McFoggy** [comment]
@pbendersky how do you exactly configure your git settings in jenkins. Do we still need to define additional behaviors , especially regarding a merge policy. Looking at the refspec you ask to setup in the README inside the PR I would say no.

Here is my setup:
- git
  ![image](https://cloud.githubusercontent.com/assets/1119660/15752353/fe588548-28ed-11e6-901c-ab4c19a63eca.png)
- trigger
  ![image](https://cloud.githubusercontent.com/assets/1119660/15752366/09ddd1f2-28ee-11e6-9cde-f1bf91a4fc4b.png)
- build and post build
  ![image](https://cloud.githubusercontent.com/assets/1119660/15752372/1597ea82-28ee-11e6-881a-dd1c00d936e2.png)

The user I use "Bob the builder":
- in git credentials using its login/password
- in gitlab connection using its user key
- the user is ADMIN on gitlab 
- the user is also MASTER on both the group project and the fork project

I have tested with gitlab 8.8.2, I just changed the version in docker-compose and recreated my containers.

![image](https://cloud.githubusercontent.com/assets/1119660/15752469/93560526-28ee-11e6-8101-b085b9fc13df.png)

I am still in the exact same situation. Comment is pushed to the MR, but I cannot see any build status on the MR.

If I accept the MR, jenkins builds correctly the merge and set a build status on the resulting commit
![image](https://cloud.githubusercontent.com/assets/1119660/15752744/c244bb60-28ef-11e6-8b24-4396031a86ed.png)

If I push a commit to a feature branch directly in the upstream project, no build status is referenced against the commit
![image](https://cloud.githubusercontent.com/assets/1119660/15752822/1e752dc0-28f0-11e6-9890-d618d4320f2f.png)
because due to the current configuration, the branch specifier builds only master
![image](https://cloud.githubusercontent.com/assets/1119660/15752850/3fdf14bc-28f0-11e6-8318-18fb99f08dda.png)

And now if I start a MR for the feature branch inside the upstream project, I have teh same result than for the fork:
- jenkins build is fired
  ![image](https://cloud.githubusercontent.com/assets/1119660/15752908/96271eb4-28f0-11e6-979c-5ac5fdb21d99.png)
- it succeeds and add a comment to the MR
  ![image](https://cloud.githubusercontent.com/assets/1119660/15752928/ac14bd8a-28f0-11e6-9754-daadfd4d8ba7.png)
- but no build status is created

Something I find weird...
This is my git project
![image](https://cloud.githubusercontent.com/assets/1119660/15752996/013a306a-28f1-11e6-91f4-d3cd60aebaaf.png)
looking at the application.log, I see the jenkins notification and comment that are executed

```
    Started GET "/bdx/gitlab-001.git/info/refs?service=git-upload-pack" for 127.0.0.1 at 2016-06-02 22:02:21 +0530
    Started GET "/api/v3/projects/bdx%2Fgitlab-001/repository/commits/676e663636759b2bba310aaec6176c90501058c1" for 127.0.0.1 at 2016-06-02 22:02:22 +0530
    Started POST "/api/v3/projects/bdx%2Fgitlab-001/statuses/676e663636759b2bba310aaec6176c90501058c1?state=running&ref=featureX&context=jenkins&target_url=http%3A%2F%2Fdocker%3A8080%2Fjob%2Fgitlab-001%2F7%2F" for 127.0.0.1 at 2016-06-02 22:02:22 +0530
    Started GET "/api/v3/projects/bdx%2Fgitlab-001/repository/commits/676e663636759b2bba310aaec6176c90501058c1" for 127.0.0.1 at 2016-06-02 22:02:23 +0530
    Started POST "/api/v3/projects/bdx%2Fgitlab-001/statuses/676e663636759b2bba310aaec6176c90501058c1?state=success&ref=featureX&context=jenkins&target_url=http%3A%2F%2Fdocker%3A8080%2Fjob%2Fgitlab-001%2F7%2F" for 127.0.0.1 at 2016-06-02 22:02:23 +0530
    Started POST "/api/v3/projects/1/merge_requests/5/notes?body=%3A%2B1%3A+Jenkins+Build+Success%0A%0AResults+available+at%3A+%5BJenkins+%5Bgitlab-001+%237%5D%5D%28http%3A%2F%2Fdocker%3A8080%2Fjob%2Fgitlab-001%2F7%2F%29" for 127.0.0.1 at 2016-06-02 22:02:23 +0530
    Started GET "/bdx/gitlab-001/merge_requests/5/ci_status" for 127.0.0.1 at 2016-06-02 22:02:26 +0530
```

but looking at the commit IDs, I would say that the SHA1 is perhaps wrong, isn't it?
It is the one from the master branch ; how does it relates to the MR? shouldn't it be the SHA1 of the merge?

Sorry for such a long post ;-)

**Comment by McFoggy** [comment]
and finally I tested with the merge in additonal behaviors
![image](https://cloud.githubusercontent.com/assets/1119660/15753325/baba1824-28f2-11e6-9b15-50b8a1f84ec4.png)

It did not changed the result neither for the MR from a branch inside the upstream project or from a fork.

**Comment by omorillo** [comment]
I will curl the **API** today and check if the changeset in PR #285 really fixes the issue.

**Comment by pbendersky** [comment]
@McFoggy your setup looks fine to me. I can't reproduce it in my environment. Just tried with the docker setup, to see if I had better luck, but I get an error 500 when creating a MR there.

**Comment by McFoggy** [comment]
@pbendersky I faced some errors 500 also when my docker machine VM was low in memory. I raised it to 4GB and everything went back to normal... with the behavior described above ;-)

**Comment by McFoggy** [comment]
also I faced issues when I mounted docker volumes for which I had some mapping between my window host and my virtual box VM. I had to let the volumes to point only to disks visible by the linux virtual box VM (not accessible from the host). This is due to redis I guess, I already saw that in other docker contexts.

**Comment by omorillo** [comment]
This issue should be closed when a fix for the issue is in master.

**Comment by McFoggy** [comment]
oups sorry, I might have clicked the wrong button

**Comment by omorillo** [comment]
Since these features were working with any _GitLab_ version I tested but version **8.8** (with the same plugin version installed), I'm inclined to assume the missing _"builds" tab_ and the other mentioned symptoms are caused by some change in _GitLab_, not saying that there may not be some issue on our side. For me with **GitLab 8.8**, it did not work at all. I used the same simple single repository setup which worked for me with **GitLab 8.7.6** but it did not work. I also tried the same example with the change set of @pbendersky but this did not work neither.
However, not having a good documentation of how the feature is expected to behave in which setup, complicates the identification of the cause.

**Comment by McFoggy** [comment]
@omorillo do you expect something more? a formal description of the need/requirement from the user point of view? at a functional level (expected integration behavior & benefits) and at a technical level (what is acceptable to do/setup in jenkins).

**Comment by omorillo** [comment]
@McFoggy No thanks, I don't need anything else from your side, thanks. I need more information from the _GitLab_ community.

**Comment by omorillo** [comment]
@pbendersky @McFoggy After testing and verifying the correct behaviour of the feature with _single_\- and  _two_-repositories _Freestyle job_  with below setup, I cannot confirm this issue.
- **GitLab** 8.8.3
- **Jenkins** 2.3
- **GitLab Plugin** 1.2.3

I strongly believe the cause of this misbehaviour to be some configuration issue.

**Note:** I fixed an existing issue in the _docker-compose_ file and performed all my tests with it. So, it is expected to work for you as well now. I suggest getting a setup running with the dockerized services first.

@McFoggy I will close this issue now. Should you still having trouble to get the integration to properly work, let me know and we can arrange for an IRC chatting session to guide you through the correct setup of **Jenkins**,  **GitLab** and plugin.

**Comment by McFoggy** [comment]
@omorillo did you tested with or without @pbendersky PR?

**Comment by omorillo** [comment]
@McFoggy I tested with version **1.2.3** of the plugin, the version that is currently available in the Jenkins' plugin manager. i.e. without @pbendersky's changes.

**Comment by McFoggy** [comment]
@omorillo I probably have a bad setup or I have too much expectations of the gitlab plugin.

Since this morning I have tried to re-setup something working but I have to say that I have failed (using GitLab-8.8.3, Jenkins-2.3 & GitLab Plugin 1.2.3 like you).

Here is what I want to achieve (nothing extraordinary, it is what travis-ci is doing for github for example):
- single jenkins project for a given GIT project
- jenkins automatically builds any PUSH to any branch from original repository
- jenkins automatically builds any MR from any repo, this includes
  - MR from original repo (MR created for reviews)
  - MR from forks (external contributions)

Having the previous requirements exposed, I do not see how to do that with the plugin (or at least I have failed to setup my jenkins build correctly).

Am I asking too much or is that possible?

**Comment by omorillo** [comment]
@McFoggy I haven't had such a setup with both MR between a _single_ and between _original and fork repositories_ in the same Jenkins job yet, but I would expect it to work.

BTW, I actually was about to provide a full docker-based demo and already started working on it but it is not yet done. Maybe I manage over the weekend to complete it, then you can have a look at it.

Anyway, I can offer you an IRC channel session on Saturday to guide you through the setup, if you like. Let me know and we can agree to one time.

**Comment by sigmavirus24** [comment]
I'm seeing this behaviour with a project on gitlab.com and gitlab-plugin v1.3.0 with Jenkins 2.14.

**Comment by isarkisov** [comment]
Same here, I can reproduce this issue on freestyle projects with GitLab EE 8.10.0, gitlab-plugin 1.3.0, and Jenkins 2.14.  Here is the odd thing, two of our projects experiencing this problem, whereas another one works as expected.  All three projects are freestyle projects.

**Comment by DavidAntliff** [comment]
I have this issue with gitlab-plugin v1.3.0, GitLab CE 8.10.4, and Jenkins 2.7.3. I set up Jenkins and the plugin as per the documentation, for a fork-based workflow.

I've noticed in the Jenkins log that the plugin is referring to the **fork** project via the GitLab API, when attempting to update the build status with a POST to:

```
http://gitlab.example.org/api/v3/projects/<project-id>/statuses/<commit-id>
```

That project-id is not the upstream (target) project, it's the forked project.

Because the fork is outside of the Group that the project is originally part of, there is no automatic access granted to the Jenkins user, even if this user is part of the Group. This causes the POST to fail with a 403 error. If I explicitly add Jenkins "Developer" access to the fork then the POST succeeds and the build status is updated. This also makes the Build tab reappear.

It is not clear to me whether there is a way to automatically assign access to a Jenkins user to all projects, including all forks of those projects. I've not had this problem with GitHub because it seems the merging takes place entirely on the upstream and there's no need for Jenkins to access the fork.

**Comment by McFoggy** [comment]
at least I was not alone...
Even if the issue has been closed it does not sounds to be resolved or we are several not configuring things correctly.

**Comment by coder-hugo** [comment]
GitLab doesn't use the commit status of the target project for displaying the build status in a MR. So for now the only way to have the build status for MRs of a fork is the add the Jenkins as developer to this fork. I'll have a look to the GitLab issues if there is existing issue for this or open a new one if necessary within the next days.

**Comment by sigmavirus24** [comment]
I filed an issue [here](https://gitlab.com/gitlab-org/gitlab-ce/issues/22238)

**Comment by omehegan** [comment]
No traction on the issue on GitLab's side, I'm closing this. Someone can reopen if they really want to.

**Comment by eyal0** [comment]
@DavidAntliff This is a screw up on the part of GitLab.  They decided that the commit's status belongs to the commit and then they decided that the commit belongs just to the source repo in an MR.

What they should have done is realize that a single commit can belong to multiple forks.  And the commit status should belong separately to each fork because the source fork's idea of pass/fail might not be the same as the target's.  For example, say I write an MR that is no good and then I use the gitlab API to set the MR to passing.  The target fork is not able to change the commit status.  We'll letting the *source* fork's owner decide if CI passed instead of letting the *target* fork's owner.  This is at best perverse and at worse, a security risk.

Really bad move on Gitlab's part.  I'm not sure how Github does it but they seem to be doing it better.
