### ISSUE TITLE
Configurable "Add note with build status on merge requests"

### ISSUE THREAD

**Issue by sauliusgrigaitis** [jenkinsci/gitlab-plugin#345]
Thanks a lot for such great plugin!

I'm trying to reduce Jenkins noise, so it only sends notifications when somebody needs to react. I'm happy to get Jenkins comments on failed builds, but comments for successful builds is simply noise for me. Would be great to have options for  "Add note with build status on merge requests" feature:
- All build statuses
- Only failed builds

Or there is other way to achieve this?

**Comment by omorillo** [comment]
Thank you for your kind words @sauliusgrigaitis.

I would like to understand if this is a feature which could be of interest for other plugin users. Therefore, I try to understand what kind of scenario this feature would fit in? You want some kind of mute function which avoids "unnecessary" success notifications when a merge request is accepted upon success, don't you?

Maybe you can precise a little more your exact scenario?

**Comment by sauliusgrigaitis** [comment]
@omorillo exactly, I just don't want to get extra notification from Gitlab when build passes (gitlab-plugin adds comment to Gitlab, then Gitlab sends email), but I want notification when build doesn't pass. Now I get both success and failure email notifications when I select "Add note with build status on merge requests" option.

**Comment by sauliusgrigaitis** [comment]
Thanks @coder-hugo !
