### ISSUE TITLE
why will a build be skipped?

### ISSUE THREAD

**Issue by norricorp** [jenkinsci/gitlab-plugin#347]
### Context
- **Gitlab plugin version**: 1.2.3- **Gitlab version**: 8.6.6
- **Jenkins version**: 2.1
  ### Logs & Traces

I have setup a Jenkins job that integrates with gitlab. My workflow is to push change to issue branch, create merge request, review and then perform merge.
I have set the plugin to merge on build request events and push events on all branches. What I have seen is that pushing the change to the issue branch cause a build but the when the merge is done (and it is a merge, not a fast forwards), the resulting merge is not built - the commit in gitlab shows "build skipped". 
So I guess my question is what causes a "build skipped" message. Or another way, why is the build skipped - should not Jenkins pick this up?
Regards,
John

**Comment by omehegan** [comment]
Do you have GitLab configured to send a hook for both pushes and merge requests? The action of merging is a push, so if you only build on MR, once it is merged a build will not happen.

Otherwise, the plugin will skip a build if that specific git ref has already been built. But you're saying this is not a fast-forward merge, so I would expect it to be a new unique ref and thus trigger a build.

We would need some more information, maybe the git refs before and after, to get a sense of what is happening.

**Comment by norricorp** [comment]
Hi Owen,
thanks for this.
If I was to set the plugin to only build on the integration branch when 
there is a push or merge request, would that work? As then it would not 
build on the issue branch with jenkins?
Regards,
John

**Comment by omehegan** [comment]
@norricorp correct.

**Comment by omorillo** [comment]
@norricorp Any news on this issue?

**Comment by norricorp** [comment]
@omorillo So this has been raised as a defect.
My current workaround is to create another Jenkins job using just git to poll the SCM every 15 minutes, watching the integration branch. Then if a delivery is made, a build is done and the results are on Jenkins. They are not integrated with Gitlab but that is OK.

**Comment by omorillo** [comment]
@norricorp Ok, thanks for the update.

**Comment by coder-hugo** [comment]
@norricorp the status "build skipped" of GitLab is kind of confusing as this is shown if no build ran for a commit. Which means for this case the Jenkins either wasn't notified or the corresponding job isn't configured properly. To find the reason for this is would be helpful if you'd provide the gitlab-plugin log as described [here](https://github.com/jenkinsci/gitlab-plugin#user-support)
