### ISSUE TITLE
Way to allow a single commit to trigger different Jenkins jobs?

### ISSUE THREAD

**Issue by olhado** [jenkinsci/gitlab-plugin#348]
### Context
- **Gitlab plugin version**: 1.2.3
- **Gitlab version**: 8.8.3
- **Jenkins version**: 2.7
### Problem description

I have multiple jobs pointing to multiple repositories (I use the MultipleSCMs plugin) that are often listening for changes on the same branch or set of branches. According to the documentation, it appears the _Services_ -> _Jenkins CI_ setting for the project/repository can only accept one build. Is there any way (like using vanilla Gitlab webhooks) to allow a push that should trigger multiple builds to do so?

To be clear, this is 2 different Jenkins jobs, looking at the same branches, not one job looking at different branches.

**Comment by omorillo** [comment]
Well, if I correctly understand what you mean then it should be possible to realize such kind of setup as follows:

Assuming you have a _GitLab_ project (git repo) and you want 2 different _Jenkins jobs_ to be triggered when something is pushed to that project. Then you must add two web hooks in _GitLab_ for this project, each one pointing to the _URL_ of one Jenkins job as described in the [Readme](https://github.com/jenkinsci/gitlab-plugin/blob/master/README.md)

**Comment by olhado** [comment]
So basically ignore all the documentation around the _Services_ -> _Jenkins CI_ setting? Okay, I can work with that. The big issue will be the large number of jobs there might be, and keeping the webhooks up to date with new jenkins jobs.

**Comment by omehegan** [comment]
You do need the Jenkins CI setting enabled, but don't check push or merge request there. This part allows Jenkins to tell GitLab the build status. Then, also create web hooks accordingly for all jobs you want to trigger.

An easier solution would probably be to trigger one parent job, which then fans out to all Jenkins jobs you want to trigger. A Pipeline job would be especially useful for this because it would allow you to run all those jobs in parallel.

**Comment by omorillo** [comment]
@omehegan @olhado Indeed, the pipeline solution should be preferable. Not being familiar with pipeline jobs yet, I did not consider this solution. :+1:

**Comment by olhado** [comment]
Thanks all! Closing now.

**Comment by SaimonL** [comment]
Actually the correct way is to set the project service to use Jenkins master service.
Then that Jenkins master service connects to Jenkins slave services. This was if you have lots of tests then the slave Jenkins will take the load off the master.

**Comment by toralMevada** [comment]
With multiple webhooks, one for each jenkins project, it creates multiple pipelines on single commit, one for each project. And in this case, only latest pipline gets executed and remaining stays in PENDING state and never gets executed. How to resolve this?

**Comment by gilberttu** [comment]
> With multiple webhooks, one for each jenkins project, it creates multiple pipelines on single commit, one for each project. And in this case, only latest pipline gets executed and remaining stays in PENDING state and never gets executed. How to resolve this?

+1， I have met this situation too,  does anyone know how to deal with this problem?
