### ISSUE TITLE
 gitlabCommitStatus usage not clear

### ISSUE THREAD

**Issue by pyther** [jenkinsci/gitlab-plugin#357]
### Context
- **Gitlab plugin version**: 1.3.2
- **Gitlab version**:  8.8.3
- **Jenkins version**: 2.9
### Problem description

The documentation says

> For pipeline jobs surround your build step with the gitlabCommitStatus step like this

I took 'build step' to mean the entire pipeline script. Looking back, this is a misunderstanding on my part, but it took me a long time figure out what was going on. I think it would help to make the example more obvious. 

```
node() {
    stage 'Checkout'
    checkout changelog: true, poll: true, scm: [$class: 'GitSCM', branches: [[name: "origin/${env.gitlabSourceBranch}"]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'PreBuildMerge', options: [fastForwardMode: 'FF', mergeRemote: 'origin', mergeStrategy: 'default', mergeTarget: "${env.gitlabTargetBranch}"]]], submoduleCfg: [], userRemoteConfigs: [[name: 'origin', url: 'git@mygitlab:foo/testrepo.git']]]

    gitlabCommitStatus {
       stage 'Test'
       sh 'echo test'
       stage 'Build'
       sh 'echo build'
    }    
}
```

When gitlabCommitStatus encapsulates the entire script, the pipeline job hangs and needs to be forcefully aborted. Ideally, the gitlabCommitStatus pipeline step should fail in the event it is used improperly.
#### Good

note `node`/`checkout` is not encapsulated by the `gitlabCommitStatus`

```
node('x86_64') {
    stage 'Checkout'
    checkout([
        $class: 'GitSCM',
        branches: [[name: "goodbye"]],
        doGenerateSubmoduleConfigurations: false,
        extensions: [
            [$class: 'RelativeTargetDirectory', relativeTargetDir: 'src'],
            [$class: 'WipeWorkspace']
        ],
        submoduleCfg: [],
        userRemoteConfigs: [[credentialsId: '2f021efd-770f-4fce-bbfa-b63f0538b2f2', url: 'gitlab@gitlab.example.com:pyther/test-project.git']]
    ])

   gitlabCommitStatus {
       stage 'Echo'
       sh 'echo hi'
    }
}
```
#### Bad

Note: gitlabCommitStatus encapsulates the entire script.

```
gitlabCommitStatus {
    node('x86_64') {
        stage 'Checkout'
        checkout([
            $class: 'GitSCM',
            branches: [[name: "goodbye"]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [
                [$class: 'RelativeTargetDirectory', relativeTargetDir: 'src'],
                [$class: 'WipeWorkspace']
            ],
            submoduleCfg: [],
            userRemoteConfigs: [[credentialsId: '2f021efd-770f-4fce-bbfa-b63f0538b2f2', url: 'gitlab@gitlab.example.com:pyther/test-project.git']]
        ])

       stage 'Echo'
       sh 'echo hi'
}
}
```

**Comment by samskiter** [comment]
Can I ask what we should be doing for pipeline jobs with parallel steps?

Is this the correct usage?

```
gitlabCommitStatus("test") {
    parallel 'Unit Tests':{
        node {
            checkout()
            //unit tests
        }
    }, 'UI Tests':{
        node {
            checkout()
            //ui tests
        }
    }, 'Integration Tests':{
        node {
            checkout()
            //integration tests
        }
    }
}
```

**Comment by coder-hugo** [comment]
@samskiter There is no correct or wrong usage of this pipeline step for parallel steps. But this step requires a `checkout scm` executed before to work. As a `checkout scm` adds some information to the build (repository URL, commits SHA1) that are required for updating the GitLab commit status.
I personally would surround each parallel step by a gitlabCommitStatus.

**Comment by samskiter** [comment]
@coder-hugo will this translate properly to gitlab pipeline stages though?

**Comment by Djangofs** [comment]
I'm encountering similar issues with this pipeline step - `gitlabCommitStatus` is causing the job to hang indefinitely and needs to be forcefully aborted. As far as I'm aware I'm using it correctly, `checkout scm` executing beforehand and not wrapping nodes. Any idea what I'm doing wrong here? The below executes fine without the `gitlabCommitStatus` wrappers

```
node () {

  checkout()

  stage "codestyle"
  gitlabCommitStatus("codestyle") {
    sh './jenkins/codestyle.test.sh'
  }

  stage "unit test"
  gitlabCommitStatus("unit test") {
    sh './jenkins/unit.test.sh'
    junit healthScaleFactor: 5, testResults: 'reports/**/*.xml'
  }

}
```

This leads to:

```
[Pipeline] stage (codestyle)
Entering stage codestyle
Proceeding
[Pipeline] gitlabCommitStatus
[Pipeline] {
```

**Gitlab plugin version:** 1.3.2
**Gitlab version:** 8.8.3
**Jenkins version:** 1.651

Is this older version of Jenkins causing the issue?
