### ISSUE TITLE
Avoid rebuild merge request if assignee changes

### ISSUE THREAD

**Issue by klausbayrhammer** [jenkinsci/gitlab-plugin#361]
### Context
- **Gitlab plugin version**: 1.2.3
- **Gitlab version**: 8.8.4-ee
- **Jenkins version**: 1.625.1
### Problem description

We are using the gitlab-plugin to build all our merge requests (include building merge requests when new changes are pushed to the source branch). Since upgrading to the gitlab plugin 1.2.3 we see that builds are also triggered if we just change the assignee of a merge request. Is it possible to specify to only trigger builds by new commits rather than changing the assignee?

BTW: Thanks for your great work on this plugin! We really appreciate it!

**Comment by omorillo** [comment]
The change of an assignee should not trigger the build of a merge request. There is no reason why to rebuild upon such change. Labelling this issue as bug.

**Comment by coder-hugo** [comment]
@klausbayrhammer can you provide some more details about your job configuration. E.g. is there a "Discard old builds" strategy configured?
If the plugin gets notified by GitLab about a change of a MR it looks if there is already an existing build for the last commit of the MR. In the case of the change of the assignee the last commit should be the same as for the last build for this MR and you should see the following message in the Jenkins log:

```
Last commit in Merge Request has already been built in build ...
```

But this is only possible if the last build for this MR is still available in the Jenkins.
Prior to version 1.2 the plugin used the push hook for rebuilding open MRs. Since version 1.2 the plugin uses the MR hook for rebuilding open MRs (at least for changes on the source branch). So before version 1.2 the plugin wasn't notified in the case the assignee has been changed. Using the MR hook the plugin gets also notified for this case and there is no way to see if the hook was just sent caused by changing the assignee without having the information about the previous builds of the Jenkins job.

**Comment by klausbayrhammer** [comment]
Thanks for your feedback. We discard builds older than two days, but even if the old build is still present (e.g. create a new MR and change the assignee a minute later) the build is triggered twice. The "Last commit in Merge Request has already been built in build" does not show up in the logs.

The (probably) relevant parts of my config look like this:

```
Execute concurrent builds when necessary: checked

GIT:
  RepoURL: ${gitlabSourceRepoHttpUrl}
  Branches to build: refs/remotes/origin/${gitlabSourceBranch}

  Merge before build options:
    name of repo: origin
    branch to merge to: ${gitlabTargetBranch}
```

Just let me know if there is anything I can do to support you

**Comment by klausbayrhammer** [comment]
Works perfectly! Thanks for the fast fix!

**Comment by Bconteh** [comment]
hello @klausbayrhammer  @coder-hugo,  I'm having exactly this problem in our jenkins job (pipeline) that always triggers if the assignee of the Merge Request changes. I'm trying to avoid that. I'm currently using Gitlab plugin v1.4.4.

Can you please guide me how to solve this issue. I understood you did solve yours and i was trying to follow your steps but i was unsuccessful.

**Comment by omehegan** [comment]
@BubacarrC this was a bug in the plugin that was fixed, so you should not need to do anything to have it work correctly. Can you please post:
- some details of how you have Git and the GitLab trigger configured in Jenkins
- what webhooks you have defined in GitLab
- some logs when a build is run after an assignee changes (see User Support section of the README)

Thanks!

**Comment by Bconteh** [comment]
@omehegan I have managed to change my build step in the "merge before build" and that solves the issue for me. Thanks for your assistance on the issue. :)

**Comment by josh-barker** [comment]
Hi @coder-hugo and @omehegan, I've found the same problem.

I've tried versions 1.4.5 and 1.4.7, however both have the same behaviour.

I have a webhook defined in Gitlab for Merge Request Events only. - `
 http://jenkins.server.com:8080/project/some_project
`

The Jenkins job retrieves a library from Gitlab.
```
@Library('generic_pipeline') _

genericPipeline {

}
```

When I change the assignee, logging shows:
```
Aug 05, 2017 11:04:07 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle

some_project triggered for merge request.

Aug 05, 2017 11:04:15 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
```

I copied my code from the generic library into the Jenkins Job, changed the assignee which triggered the Jenkins job. When I changed the assignee the 2nd time, the job was not triggered.

This lead me to putting the checkout into the Jenkins job and then using the genericPipeline, but that didn't work.
```
@Library('generic_pipeline') _

node() {
  checkout changelog: true, poll: false, scm: [
    $class: 'GitSCM',
    branches: [[name: "origin/${env.gitlabSourceBranch}"]],
    doGenerateSubmoduleConfigurations: false,
    extensions: [
        [$class: 'CleanBeforeCheckout'],
        [$class: 'LocalBranch', localBranch: "${env.gitlabSourceBranch}"]
    ],
    submoduleCfg: [],
    userRemoteConfigs: [[
        credentialsId: 'jenkins_ssh_keys',
        name: 'origin',
        url: "${env.gitlabSourceRepoSshUrl}"
    ]]
  ]
}

genericPipeline {

}
```

**Comment by omehegan** [comment]
Will have to see if I can reproduce.

**Comment by ababushk** [comment]
We're experiencing the same issue with GitLab Community Edition 11.3.1 and 1.5.12. Our builds are also triggered when MR's description changed
