### ISSUE TITLE
Gitlab Plugin calls http when adding api token

### ISSUE THREAD

**Issue by bert2002** [jenkinsci/gitlab-plugin#365]
### Context
- **Gitlab plugin version**: 1.2.3
- **Gitlab version**: 8.8.4-ee
- **Jenkins version**: 2.10
### Problem description
- when configuring the gitlab plugin and adding the "API Token" as a "Secret Text" it cannot save it because it gets blocked by the browser. 
- its using http instead of https
- changing the post url to https in the code and its possible to save the credentials
- not sure if its a problem of the jenkins credentials provider or the plugin

Many Thanks.

bert2002

**Comment by coder-hugo** [comment]
The form for saving credentials is part of the "Jenkins Credentials Plugin". So if this generates a wrong URL for the form please open an issue for this plugin.
