### ISSUE TITLE
Build Trigger: wrong URL for GitLab CI Service

### ISSUE THREAD

**Issue by ghost** [jenkinsci/gitlab-plugin#367]
### Context
- **Gitlab plugin version**: 1.2.5
- **Gitlab version**: Community Edition 8.8.5 68cd138
- **Jenkins version**: 1.651.3
### Logs & Traces

N/a
### Problem description

I'm set up to run builds on request OK. 

However setting a project's Build Triggers section to "build when a change is pushed..." doesn't work. 

The option shows a URL of "http://my-gitlab.com/**project**/my-build", but the actual URL is "http://my-gitlab.com/**job**/my-build"

<img width="806" alt="screenshot 2016-06-27 17 41 05" src="https://cloud.githubusercontent.com/assets/1935287/16387818/61741ecc-3c8e-11e6-9bca-c78edcb8644a.png">

<img width="372" alt="screenshot 2016-06-27 17 44 54" src="https://cloud.githubusercontent.com/assets/1935287/16387952/ec9ae9e0-3c8e-11e6-9603-1b65cd98bcac.png">

**Comment by coder-hugo** [comment]
The shown URL is correct. GitLab has to send its requests to this URL. The `project` within the URL comes from the beginning of the plugin as it just emulates the GitLab CI. And GitLab CI listened exactly on this URL for changes and provided information about the build status using this URL.
Furthermore the plugin can't use the URL containing `job` for listening to incoming push or MR events as this URL is already used by Jenkins itself.

**Comment by ghost** [comment]
I understand.

Is there any troubleshooting info in this area? I read your readme and googled, but at this point I'm stuck.

**Comment by omehegan** [comment]
@laughingblade where you wrote "N/A" under "Logs and Traces," for us, those are actually "A." As in, applicable. Please gather logs as described in https://github.com/jenkinsci/gitlab-plugin#user-support so we can see what the plugin and Jenkins are seeing.

**Comment by coder-hugo** [comment]
@laughingblade I don't understand at what point you stuck. What steps of the [GitLab configuration section](https://github.com/jenkinsci/gitlab-plugin#gitlab-configuration--81) do you have done yet? What is not working?

**Comment by ghost** [comment]
**@omehegan** :) thanks. I do have the dabsquared logger running, but there's nothing in it following a push to the repo when I'm expecting the trigger to run. Hence the N/A.

**@coder-hugo** So far I have on-demand building of my project. Handling forks didn't work immediately so I rolled back. Next step is to build on commit to the repo, hence the Build Triggers setting I asked about originally.

A thought: Does this even work with a straight push, or specifically with MR?

Thanks for your responses.

**Comment by coder-hugo** [comment]
@laughingblade If nothing appears within the logger for the gitlab-plugin you haven't configured the webhooks properly in your GitLab. Or your GitLab instance can't talk with your Jenkins for whatever reason.
Can you just try the following:
- Go the the settings of your GitLab project
- Go to the webhook settings
- Add a webhook for push events and enter the URL displayed in your jenkins job
- Click 'Save'
- Click 'Test'

If everything is fine GitLab should show you a corresponding message at the top of the page. In case of an error GitLab will show this as well.

**Comment by ghost** [comment]
Cool. I'm up and running with a local setup (I don't have access to the on-prem pieces at work, but they're very similar). Thanks very much for your help.

The GitLab CI service URL shown in Jenkins/plugin is definitely wrong - it's showing here as 192.168.1.198:8080 when I've got GitLab on 192.168.1.163 and Jenkins on 192.168.1.164:8080. The webhook works on 192.168.1.164:8080 which is what I'd expect. It was a fresh project in Jenkins too.

**Comment by omehegan** [comment]
@laughingblade Jenkins seems to be confused about what its IP is. Check your main configuration page at http://192.168.1.164:8080/configure and look at what is specified in the field for 'Jenkins URL.'

**Comment by ghost** [comment]
**@omehegan** Yes, that was set incorrectly and the GitLab CI URL has updated accordingly.  I'm sure I did that myself early on, although a little surprised that's user-modifiable.\

Cheers!

**Comment by omehegan** [comment]
@laughingblade the value of that setting is what populates most things in Jenkins. The reason for that is, maybe you're running Jenkins behind a NAT with a VIP and a domain name pointed at that - the hostname of the local system it is running on is nearly irrelevant to any user in that case. So you're expected to set it correctly, or else strange behavior will result.
