### ISSUE TITLE
Please make the GitLab API token configurable for every build job.

### ISSUE THREAD

**Issue by schlauch** [jenkinsci/gitlab-plugin#369]
### Context
- **Gitlab plugin version**: 1.2.3
- **Gitlab version**: 8.9.3
- **Jenkins version**: 2.10
### Problem description

This is a feature request. As different groups use GitLab and Jenkins, we would like to avoid that they need to share the same user to be able to display their build status in the corresponding GitLab project.

**Comment by coder-hugo** [comment]
They don't need to share the same user for updating the commit status in GitLab. You can configure multiple GitLab connections in the global Jenkins configuration for the same GitLab instance but with different credentials. One of these connections can (must) then be selected for a Jenkins build. This should be exactly what you need.

**Comment by schlauch** [comment]
Ah ok. I think I missed the "Add button". I think this is basically ok for our use case. Ideally, this could be done in the build job configuration to avoid involving the Jenkins administrator. But anyway, it is ok. Thank you very much for your quick answer :)
