### ISSUE TITLE
2x Build when pushing to merge request branch

### ISSUE THREAD

**Issue by StefanKoenen** [jenkinsci/gitlab-plugin#372]
### Context
- **Gitlab plugin version**: 1.4.2
- **Gitlab version**: 8.9.3
- **Jenkins version**: 2.7
## 
### Problem description

I've followed the guidelines on this github page  and I've setup the webhook with for push and mergerequest event. When i create a new branch, i.e. "test", I push a change to it and make a merge request the branch is getting build. But when I make a new push request to the branch (which is still pending to be merged), the build is triggered 2 times. the first gets a "retried" status and the second is building. [Screenshot](https://postimg.org/image/oetr3qt1d/)
Ofcourse, this looks a little bit strange for me, why is it build  triggered twice and is this the correct way, or did i do something wrong in my setup?

**Comment by qrsty** [comment]
It's technically not a rebuild.

As far as I'm aware, the branches that are actually built are different. A push web-hook only builds the pushed branch, whereas a merge request web-hook builds a merged version with the branch you're trying to submit the merge request for.

A workaround to clarify this could be to create two different Jenkins jobs for pushes and merge requests, and specify the build name in the post-build action.

**Comment by coder-hugo** [comment]
It's exactly how @qrsty has described it.
The gitlab-plugin receives in this case 2 events from GitLab. One for the push to your branch and another for the update of the MR. If you have configured your job to be build for both push and MR events the plugin will schedule 2 builds. If you don't want your MR branch to be build for a push event you can configure a branch filter in the GitLab trigger configuration. In case of a MR event this filter is applied against the target branch. Which means you don't need to specify the MR branch itself within the filter.
