### ISSUE TITLE
Enable publisher to poste additional information to gitlab (for example link to built artifacts)

### ISSUE THREAD

**Issue by fetzerch** [jenkinsci/gitlab-plugin#373]
Hi and thanks for the great plugin. I'm reaching out to you with a feature request.

It would be useful if the plugin could push additional comments back to gitlab when building a merge request. There are a couple of use cases where this could be helpful:
- Post links of collected build artifacts
  - When building a static web page in Jenkins, it would be great if the link to the page could be send back to GitLab to view the results without having to open the Jenkins Dashboard.
  - Same could be useful for testresults, codecoverage, etc. 
- Long running builds: Here it could be nice to post back comments after every stage to GitLab.

I'm not sure what's the best way to do this. A flexible solution might be offering a method that can be called via a groovy script. Additionally a publisher that can be configured with a textbox might be good.

Would be great if this could be added to the plugin. Any thoughts?

**Comment by omehegan** [comment]
@fetzerch the plugin already has the ability the post comments on the MR, which can contain arbitrary text. I think you could use this to post links as you describe. If you are using a Pipeline job type, look at the snippet generator to see examples of this.

In terms of sending status of long-running builds, you can use multiple gitlabCommitStatus() blocks to do this, again assuming you are using a Jenkins Pipeline job. This is documented in the plugin's README on GitHub.

If this satisfies your needs, please close the issue. Thanks!
