### ISSUE TITLE
Using "Multiple SCMs" with two different repos in the same job will fail

### ISSUE THREAD

**Issue by tomachi** [jenkinsci/gitlab-plugin#379]
## Issue

I'm trying to use the plugin in order to start a job in Jenkins.
The job contains "Multiple SCMs" plugin and I configured two different repos as I need to build both for the same job, and one is depending the other.
The issue is that when trying to push it triggers the job but immediatley fail due to an error:

> Fetching changes from the remote Git repository
> git config remote.origin.url git@gitlab.xxx.com:yyy/androidlibraries.git # timeout=10
> Cleaning workspace
> git rev-parse --verify HEAD # timeout=10
> Resetting working tree
> git reset --hard # timeout=10
> git clean -fdx # timeout=10
> Fetching upstream changes from git@gitlab.xxx.com:yyy/androidlibraries.git
> git --version # timeout=10
> using GIT_SSH to set credentials Jenkins Build User
> git -c core.askpass=true fetch --tags --progress git@gitlab.xxx.com:yyy/androidlibraries.git +refs/heads/_:refs/remotes/origin/_ # timeout=30
> skipping resolution of commit 229235ade8464f77bf9d0ba27880717d69432855, since it originates from another repository
> git rev-parse refs/remotes/origin/^{commit} # timeout=10
> git rev-parse refs/remotes/origin/origin/^{commit} # timeout=10
> git rev-parse origin/^{commit} # timeout=10
> ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
> Warning: this build has no associated authentication, so build permissions may be lacking, and downstream projects which cannot even be seen by an anonymous user will be silently skipped
> Finished: FAILURE

As you can see, the branch name is empty.
The push I trigger is in the second repo I need to build (usually I do not push to the first one but its still pulling it to jenkins) so the first repo will not recognize the git branch I'm using (both have the same name) this is why it says "since it originates from another repository".
### Context
- **Gitlab plugin version**: 1.3.0
- **Gitlab version**: Enterprise Edition 8.8.5-ee 54d1c4f
- **Jenkins version**: 1.651
### Logs & Traces

Jul 14, 2016 7:58:28 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/yyy_Android?BUILD_TYPE=FULL&ENVIRONMENT=TEST&DEPLOY_TO_HOCKEY=false/project/yyy_Android
Jul 14, 2016 7:58:28 AM FINE com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction
Push: {
  "object_kind" : "push",
  "event_name" : "push",
  "before" : "f37651a8fdc18ceb65a16665844a804114ba2263",
  "after" : "fdada47d20b3b31b2832f3d86568704e86cb775f",
  "ref" : "refs/heads/yyy_1.7",
  "checkout_sha" : "fdada47d20b3b31b2832f3d86568704e86cb775f",
  "message" : null,
  "user_id" : 87,
  "user_name" : "Noam",
  "user_email" : "nmayafit@xxx.com",
  "user_avatar" : "xxx",
  "project_id" : 92,
  "project" : {
    "name" : "AndroidAccessClient",
    "description" : "",
    "web_url" : "https://gitlab.xxx.com/yyy/androidaccessclient",
    "avatar_url" : null,
    "git_ssh_url" : "git@gitlab.xxx.com:yyy/androidaccessclient.git",
    "git_http_url" : "https://gitlab.xxx.com/yyy/androidaccessclient.git",
    "namespace" : "yyy",
    "visibility_level" : 10,
    "path_with_namespace" : "yyy/androidaccessclient",
    "default_branch" : "master",
    "homepage" : "https://gitlab.xxx.com/yyy/androidaccessclient",
    "url" : "git@gitlab.xxx.com:yyy/androidaccessclient.git",
    "ssh_url" : "git@gitlab.xxx.com:y/androidaccessclient.git",
    "http_url" : "https://gitlab.xxx.com/yyy/androidaccessclient.git"
  },
  "commits" : [ {
    "id" : "fdada47d20b3b31b2832f3d86568704e86cb775f",
    "message" : "Testing Gitlab -> Jenkins push jobs\n",
    "timestamp" : "2016-07-14T16:58:19+03:00",
    "url" : "https://gitlab.xxx.com/yyy/androidaccessclient/commit/fdada47d20b3b31b2832f3d86568704e86cb775f",
    "author" : {
      "name" : "Noam",
      "email" : "nmayafit@xxx.com"
    },
    "added" : [ ],
    "modified" : [ "fastlane/Fastfile" ],
    "removed" : [ ]
  } ],
  "total_commits_count" : 1,
  "repository" : {
    "name" : "AndroidAccessClient",
    "url" : "git@gitlab.xxx.com:yyy/androidaccessclient.git",
    "description" : "",
    "homepage" : "https://gitlab.xxx.com/yyy/androidaccessclient",
    "git_http_url" : "https://gitlab.xxx.com/yyy/androidaccessclient.git",
    "git_ssh_url" : "git@gitlab.xxx.com:yyy/androidaccessclient.git",
    "visibility_level" : 10
  }
}
Jul 14, 2016 7:58:28 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
yyy_Android triggered for push.
### Problem description

_Describe your problem in a meaningful way_:
- what were you doing (simple push, merge request, MR with fork, ...): simple push in one repo.
- what was expected: both repos will build with the same branch name received in the payload from Gitlab
- what occured finally: first repo was failing to build as it didn't recognize the branch name that came from the second repo push.

**Comment by coder-hugo** [comment]
The plugin schedules a new build for an incoming Gitlab push event with a `RevisionParameterAction`. This action provides the git-plugin the revision and the repo URL of the push event. If the git-plugin isn't able to checkout this revision I'd assume you haven't configured you Jenkins job properly. Is there a branch specifier configured that prevents the gitlab-plugin from checking out the given revision?

**Comment by tomachi** [comment]
Thanks @coder-hugo for the response.
Yes, I have a specifier as users can fire the job manually and need to insert the branch as a parameter: */${gitlabSourceBranch}
I thought that it can take both ways: If user starts manually it will be entered into the gitlabSourceBranch (I put it as a string parameter in the job) and if its starting automatically it will receive this parameter from the gitlab-plugin.
I use the same branch name for both repos but they have different revision and URL.

**Comment by stevejensen22** [comment]
@coder-hugo I am running into a similar issue. I have multiple git scms configured in a single jenkins job and want to get the LastBuiltRevision for each individual repo so that I can leverage the `Bitbucket Build Status Notifier` to notify every repo for each revision `SHA` that a regression test build has either passed or failed.

Are you aware of any way to get all of the `LastBuiltRevision`'s in this scenario?

And I'd just like to say thanks to the jenkins community at large for all the great work that goes into making this tool so powerful and awesome.

**Comment by coder-hugo** [comment]
@tomachi it's possible to trigger a build manually but you can't set the parameters as described in the README since version 1.2 of the plugin (see #356 for more information)

@stevejensen22 AFAIK the `LastBuiltRevision` isn't attached to any repo. To determine the GitLab project corresponding to a built commit this plugin calls the GitLab API for all configured repositories and checks if the commit belongs to this repository.

**Comment by tomachi** [comment]
@coder-hugo is there a solution for this issue? We still need it.

**Comment by coder-hugo** [comment]
@tomachi just have a look to the linked issue of my last comment. There you can find ways how to set these parameters for manually triggered builds.
