### ISSUE TITLE
FileNotFoundException when connecting with Gitlab and lack of PRIVATE_TOKEN parameter in URI

### ISSUE THREAD

**Issue by mrosinski** [jenkinsci/gitlab-plugin#381]
## Issue

I'm having a FileNotFoundException when saving job configuration. Job is meant to build and test merge requests and then return results to Gitlab as comment. What i noticed is that queried Gitlab URI lacks of PRIVATE_TOKEN parameter like it was before (see log below) - maybe this causes an issue?

**Comment by coder-hugo** [comment]
You are definitively not using this plugin. From the given stacktrace I'd say it's [this one](https://github.com/timols/jenkins-gitlab-merge-request-builder-plugin).
