### ISSUE TITLE
Require Admin Approval before testing

### ISSUE THREAD

**Issue by sigmavirus24** [jenkinsci/gitlab-plugin#384]
## Issue

Presently, other SCM plugins (e.g., GitHub Pull Request Builder) allow for there to be a list of "administrators" who can allow Jenkins to start a build. This ostensibly allows the administrator to prevent Jenkins from running malicious code submitted via pull request/merge request.

I'm hoping similar behaviour can be added to this excellent plugin.
### Context
- **Gitlab plugin version**: 1.3.0
- **Gitlab version**: 8.10.?? (gitlab.com)
- **Jenkins version**: 2.14

**Comment by omehegan** [comment]
@sigmavirus24 I'm not sure I understand how you would want this feature to work. Where would these users be defined? Would they map to users in GitLab? E.g. only commits by certain people could trigger a build? 

This seems like a strange trust issue to have. People can write code which presumably is deployed to production, but there is a risk of letting them build that code on Jenkins?

**Comment by sigmavirus24** [comment]
@omehegan so it's one part "not allowing malicious code" it's another part not allowing someone to send pull requests that cause your jenkins to slow down and back up with a ton of work. Several projects with expensive set-ups use the feature with the GitHub Pull Request Builder plugin. In many cases it simply comments asking that an administrator comment to the effect that the jobs may be run. Some people pay to maintain their own Jenkins infrastructure for open source projects. There's no reason this plugin should allow someone to cost us more money.

**Comment by omehegan** [comment]
OK, I guess I take your point, but it just seems like in that case you would not automatically trigger jobs at all.

If you're using Jenkins Pipeline jobs I can explain a couple of ways, from simple to more elaborate, that you could accomplish this.

**Comment by sigmavirus24** [comment]
So, again, let me use a concrete example [pyca/cryptography](/pyca/cryptography) has some very intricate and expensive jobs. They're using ghprb and they maintain a whitelist for people who they know won't abuse their Jenkins setup. They also have the list of administrators. Automatically triggering jobs would be wonderful.

I am using pipeline jobs, but I'm kind of abusing them to run one set of jobs or another for each project because the merge request functionality for GitLab isn't as mature as ghprb.

**Comment by omehegan** [comment]
In a Pipeline job, you could just put an 'input' step at the start of it, which serves as a checkpoint. If your Jenkins security is configured appropriately then only logged-in users would be able to proceed with the build.

To limit it further, the input step takes an optional list of Jenkins users who are allowed to approve it to continue. 
`input message: 'An administrator must approve this job.', submitter: 'omehegan@foo.com'`

You could also examine the contents of e.g. `env.gitlabUserEmail` and compare with a list of approved users, so only those committers could auto-trigger a build. If the user isn't in the list, pause it with an input step. This way non-admins can still start a build, but it won't proceed until someone approves it.
