### ISSUE TITLE
Hook doesn't work when CSRF is enabled

### ISSUE THREAD

**Issue by dblessing** [jenkinsci/gitlab-plugin#385]
### Before submitting an issue to I have first:
- [x] read the documentation on the [homepage](https://github.com/jenkinsci/gitlab-plugin) 
- [x] searched for similar already existing issue

_(if you have performed all the above, remove the paragraph and continue describing the issue with template below)_
### Context
- **Gitlab plugin version**: 1.3.0
- **Gitlab version**: 8.9
- **Jenkins version**: 2.1.4
### Logs & Traces

Hook executed successfully but returned HTTP 403 <html> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> <title>Error 403 No valid crumb was included in the request</title> </head> <body><h2>HTTP ERROR 403</h2> <p>Problem accessing /job/TestCiWorkflowProduction/build. Reason: <pre> No valid crumb was included in the request</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/> </body> </html>
### Problem description

When CSRF protection is enabled in Jenkins, the Web Hook from GitLab fails with the above message. I see some code in this plugin that suggests it should be excluding it's endpoints from CSRF protection but I'm not 100% sure. Is this supposed to work or is it something that needs to be added?

**Comment by coder-hugo** [comment]
You are using the wrong URL. `/project/TestCiWorkflowProduction` would be the correct one for your case. The URL mentioned by you is an internal URL of the Jenkins and has nothing to do with this plugin.

**Comment by dblessing** [comment]
@coder-hugo 😞  Derp. Thanks for pointing that out.

**Comment by Kannan1015** [comment]
Thanks @coder-hugo
