### ISSUE TITLE
Status reports from independent jobs overwrite each other

### ISSUE THREAD

**Issue by sharwell** [jenkinsci/gitlab-plugin#389]
### Context
- **Gitlab plugin version**: X.Y.Z
- **Gitlab version**: 8.9.5-ee 42dceaa
- **Jenkins version**: X.Y.Z
### Problem description

I have two jobs that are triggered from the same repository. I'm interested in marking the build status as successful pending the successful completion of _both_ of these jobs. Unfortunately, GitLab is currently unable to differentiate between the two jobs in its external builds UI. For example, the job results might appear as follows:

![image](https://cloud.githubusercontent.com/assets/1408396/17567588/a2f70f14-5f05-11e6-8be9-5d72e20b5053.png)

My guess is the GitLab commit status API treats two builds as equivalent when their `name`/`context` (an API parameter) is the same. The Jenkins plugin always reports the commit status with the name `jenkins`, as shown in the image.

:question: If two builds report status with different values for `name`, will GitLab correctly differentiate between them? If so, would it be possible to have the Jenkins plugin report the commit status with the name set to the Jenkins job name instead of always using `jenkins`?

**Comment by coder-hugo** [comment]
You can already change the build name for exactly this purpose.
For this you just need to click the `Advanced` button of the post-build step `Publish build status to GitLab commit (GitLab 8.1+ required)` then you will see a input field where you can specify a name for the build.

**Comment by sharwell** [comment]
I don't have a way to see the current plugin version, but since there is no Advanced button visible I'm assuming it's before 1.2.4. I've requested an upgrade from the team that manages our instance. :smile:

Duplicate of #362, added in plugin release 1.2.4.
