### ISSUE TITLE
gitlab-plugin always uses TLSv1 when attempting to connect a gitlab server on IBM JDK

### ISSUE THREAD

**Issue by mkutter** [jenkinsci/gitlab-plugin#394]
## Issue

gitlab-plugin on IBM JDK always uses TLSv1 when attempting to connect a gitlab server.
This makes gitlab-plugin unusable with gitlab servers using TLSv1.1/TLSv1.2 only.
### Context
- Gitlab Plugin version: 1.3.1-SNAPHOT (built from source) and older
- Gitlab Version: Any
- Jenkins Version: Any (tested with 2.7.2-LTS)
- Java version: IBM JDK7, IBM JDK8
  ### Logs & Traces

There's almost no usable logging.

When Jenkins is running with -Djavax.net.debug=ssl:handshake:verbose, the handshake triggered when clicking "Test Connection" on the configure Jenkins Page includes the line

```
     *** ClientHello, TLSv1
```
### Problem description

Due to using resteasy's default SSLSocket, gitlab-plugin always connects to https URLs using TLSv1.
In security aware network environments, where the gitlab server is using only TLSv1.1 or TLSv1.2, this leads to TLS handshake failures when connecting to gitlab.

The default SSLSocket used by resteasy does not respect the JVM JSSE System Properties.
Setting -Dhttps.protocols=TLSv1.2 or -Djdk.tls.client.protocols=TLSv1.2 has no effect.

**Comment by coder-hugo** [comment]
I'd say this has to be somehow related to your Jenkins or Gitlab setup. My GitLab is also just accessible using TLSv1.2 and I don't get any TLS handshake failures. If I run the Jenkins with -Djavax.net.debug=ssl:handshake:verbose I also get the following message:

```
*** ClientHello, TLSv1.2
```

**Comment by mkutter** [comment]
Hi Robin,

thank you so much for testing & getting back - you pointed me in the right direction.

IBM JDK differs from Oracle JDK in the default meaning of `SSLSocket("TLS")`

While Oracle JDK interprets `SSLSocket("TLS")` as `SSLSocket("TLSv1.2")`, IBM JDK interprets it as `SSLSocket("TLSv1")`. This behavior can be changed by setting the System property`com.ibm.jsse2.overrideDefaultTLS=true`.

https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/matchsslcontext_tls.html has details on the issue.

I changed the problem description to point to IBM JDK, so other users can find the issue (and resolution) easier.

**Comment by rahst12** [comment]
How was this setup to use TLS?  I don't see any connections being made with SSL right now...
