### ISSUE TITLE
"Filter branches by name" does not filter source as documented

### ISSUE THREAD

**Issue by g-w** [jenkinsci/gitlab-plugin#398]
The documentation of "Filter branches by name" states that 

> Comma-separated list of source branches allowed to trigger a build […].

 The current Implementations in [AbstractWebHookTriggerHandler line 45](https://github.com/jenkinsci/gitlab-plugin/blob/1acb7d003102ee3d4f68de102b697436469d5e41/src/main/java/com/dabsquared/gitlabjenkins/trigger/handler/AbstractWebHookTriggerHandler.java#L45) and in [OpenMergeRequestPushHookTriggerHandler line 96](https://github.com/jenkinsci/gitlab-plugin/blob/3cf5f312e623fda085ce7087ccb59c8955b861ea/src/main/java/com/dabsquared/gitlabjenkins/trigger/handler/push/OpenMergeRequestPushHookTriggerHandler.java#L96) use this value to filter on the target branch. Which is not as documented. On the other hand the regexp filter is documented to use the source branch. Is the documentation wrong or the code?

**Comment by coder-hugo** [comment]
I'd say the documentation is not wrong just outdated :wink:
If you read the complete documentation you'll see the following sentence:

> For **Merge Request events** only the target branch name is filtered out by the include and exclude lists

But we should update the documentation to prevent any confusions.

**Comment by g-w** [comment]
Ok, lets call it outdated. So will send you an PR that fixes this issue. Is it intended that the branch names are interpreted as ant pattern? Should this be documented?

But: I need the described feature. A filter on the source branches that are allowed to trigger the build. I want to use this to limit some jobs to special branches. Do you think this is a useful change?

**Comment by coder-hugo** [comment]
@g-w could you please describe your desired workflow so we can decide whether this change is useful or not.
The common workflow that is currently used by most of the users of this plugin that have enabled builds for MRs is the following:
- build the master (or main development) branch for all push events
- build all MRs that shall be merged to this branch (by adding the git behavior "Merge before build")
- re-build open MRs for a push their target branch

For this workflow I don't see any reason for filtering for the source branch.

**Comment by g-w** [comment]
@coder-hugo: We've split our build job into multiple jobs. One of them is quite time and resource consuming (think of a complex integration test). Hence we decided to run this job only for changes that  that might break these job. Our goal was to establish a naming convention that makes it possible to identify branches that should trigger the job and use source branch filters to implement this restriction.

**Comment by coder-hugo** [comment]
@g-w wouldn't it be possible in this case to listen for Push events and filter them for the corresponding branches?

**Comment by coder-hugo** [comment]
@g-w Would this #406 fit also your needs? As changing the behavior of the branch filtering would break the workflow for everybody that currently uses it to filter only for the target branches.
