### ISSUE TITLE
Merge Requests from forks are not recognized

### ISSUE THREAD

**Issue by jk** [jenkinsci/gitlab-plugin#4]
First things first: Thanks for your work.

I installed it on our corporate CE instance and found that it's working as long as the Merge Requests references local branches. But when the MR comes in from a fork of the project that will not trigger the jenkins build.

Did I miss something? Do I neet to set `origin/${gitlabSourceBranch}` to `remote/*/${gitlabSourceBranch}` or something similar?

**Comment by Downchuck** [comment]
I hit this issue on running "Build Now", test connection was a success.
This is in association with using Docker slaves.

Same issue, the variable is not being populated.
