### ISSUE TITLE
Add include/exclude of merge requests based on gitlab merge request labels

### ISSUE THREAD

**Issue by Tetradeus** [jenkinsci/gitlab-plugin#406]
It would be very helpful to process only certain merge request and I think that the easiest/cleanest way to do it is via merge request labels.

**Comment by omorillo** [comment]
@Tetradeus We already have a feature to _ignore merge requests_ which are marked as **WIP**. Why not using this feature?

**Comment by Tetradeus** [comment]
It is not exactly the same meaning: my merge request may be ready to merge, but for any reason I may not want to launch CI on it.
It's more like the option of include/exclude a specific branch name. Right now this is the solution I use.

I am not sure if it's a personal use case or if any people may be interested in this.

**Comment by omorillo** [comment]
Ok, now I understood what you mean. Yes, this feature is indeed interesting.
