### ISSUE TITLE
Failed to update the commit status with CI-Pipelines

### ISSUE THREAD

**Issue by Alien2150** [jenkinsci/gitlab-plugin#407]
### Context
- **Gitlab plugin version**: 1.4.0
- **Gitlab version**: GitLab Community Edition 8.10.6
- **Jenkins version**: 2.2.1
### Logs & Traces

Logs: https://gist.github.com/Alien2150/af096e99cdb09eb7f39e89ab24968961
### Problem description

I setup a pipeline snippet (https://gist.github.com/Alien2150/4b300102fae862e86fce08281c7f6b38) and as soon as it reaches the "gitlabCommitStatus" it fails with the exception "Failed to update Gitlab commit status for project '135': java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens" (See logs). Let me know If I forget to attach missing information. 

Regards,
Thomas

**Comment by qrsty** [comment]
Try restarting your jenkins instance. I had this issue, and it went away after reboot.

**Comment by Alien2150** [comment]
Thanks will try

**Comment by Alien2150** [comment]
Still did not help. Did you restarted the whole server or only the service (Like /etc/init.d/jenkins restart)?

**Comment by qrsty** [comment]
I used `http://jenkinsUrl.com/safeRestart`.

I am also using Jenkins 2.19, GitLab CE 8.11.2 with GitLab plugin 1.3.2 currently.

**Comment by Alien2150** [comment]
So did:
- Rebooted the machine
- Restarted service with /etc/init.d
- Used safeRestart - url 

Did you put your build-scripts into scm? Might that be an issue or maybe permissions for the Gitlab User?

**Comment by qrsty** [comment]
I was getting the json parsing error with any usage of the plugin, be it a FreeStyle job or pipeline. Can you check if a post-build action on a FreeStyle job works?

**Comment by Alien2150** [comment]
Good point. Will try

**Comment by Alien2150** [comment]
With the Freestyle-Job I got: 

is allowed between tokens
 at [Source: ????n?0%???$[?=??e?#??,fi?/?E;e??T??S?A?o?Z??p??^??!???_?e???+?r?d????p?G?E?g?<]??e??r???R?4 ????L#f?P?%?VB??#?e@?=?{?'?:k:k+x??????????????????4Dp?!????????s{r??z??%??[C??;_~>~?_?&Y?Js?n???R?; line: 1, column: 2]

**Comment by Alien2150** [comment]
Ok downlaoding, packing and uploading the plugin fixed the issue. Will try reinstalling it. Maybe the updatePlugin process messed around with it

**Comment by Alien2150** [comment]
Reinstalling worked for me. So guess that issue can be closed

**Comment by Alien2150** [comment]
Think I found the issue now :) Looks like the http-client does (by default?) send out "Accept-Encoding: GZIP,Deflate". So if the server sends back the result in GZIP - Format it will result in the message mentioned mentioned above. I tried regising the "GZIPDecodingInterceptor" on the GITBuilder but that did not fix it :(

**Comment by Alien2150** [comment]
At least managed to have a temp-workaround: Created a RemoveAcceptEncodingFilter (https://gist.github.com/Alien2150/943ae0d5af4463be42948fcb8a7c325d) and add it to "buildClient" method (.register(new RemoveAcceptEncodingFilter())

**Comment by sturmf** [comment]
@Alien2150 I am hitting the same bug. I think I understand where to put this code from the gist. It seems it is in the plugin source GitLabClientBuilder.java and if yes, how can you build and install this patched plugin?

**Comment by Alien2150** [comment]
@sturmf Yes place the register & class in your GitLabClientBuilder.java. You do run maven package in your IDE/CLI. That will generate a "HPI" File in target. That one can be installed in "http://YOURCIDOMAIN/pluginManager/advanced". I think I will provide a patch file :) 

Ps.: I also tried to intercept the reading with GzipReader etc. But seems like the Client-Invoke will be triggered first. I also could not find out who is setting the Accept-Encoding Flag :(

**Comment by sturmf** [comment]
Thanks a lot, after this change the commit status is successfully passed to GitLab! I hope this or a similar solution will be integrated soon.

**Comment by Alien2150** [comment]
I think the best fix would be to make it work with compression on as well.

**Comment by coder-hugo** [comment]
@Alien2150 I think I found the error. At least this header was gone for me with the patch of df36214d2dc46ad548132895fcb09b105fef195f. Could you please test this patch. Maybe you have to uninstall the plugin before installing the patched version. For some reason just updating didn't worked for me.

**Comment by Alien2150** [comment]
Thanks for providing the patch. Will try/comment later

**Comment by Alien2150** [comment]
testing now ....

**Comment by Alien2150** [comment]
@coder-hugo does not seem to be fixed with the latest patch :(

**Comment by coder-hugo** [comment]
This is a real strange bug. There is nothing in the code that should add the `Accept-Encoding` header to any of the requests. While running the plugin in debug mode this never happened. Yesterday I did some tests with a clean (dockerized) Jenkins 2.7.2 and this header was always added to all requests til I installed the patched version of the plugin. Today I did the same tests and the header wasn't included in any of the request neither while using the current release version nor the patched one.

**Comment by Alien2150** [comment]
Yes that is exactly what i also found out do far. Just a thought: are some Kind of Head requests done to figure out the Server config? I read this in some config (either it was Apache http or easyrest client)

**Comment by anicolas** [comment]
I had the exact same problem, and @Alien2150 solution to add a `ClientRequestFilter` which filters the `Accept-Encoding` header does fix the issue (thanks !)

**Comment by Alien2150** [comment]
What is the current status @coder-hugo? Shall I provide a patch / MR?

**Comment by cliles** [comment]
@coder-hugo and/or @omehegan - Please merge!
