### ISSUE TITLE
Multiple branches pushed, Only one job triggered.

### ISSUE THREAD

**Issue by rahvee** [jenkinsci/gitlab-plugin#408]
## Issue

When a single push to gitlab contains multiple branches, gitlab correctly hits the webhook multiple times, but gitlab-plugin only processes one.
### Context
- **Gitlab plugin version**: 1.2.3
- **Gitlab version**: 8.10.4
- **Jenkins version**: 1.651.3
### Logs & Traces

Please notice: gitlab-test was triggered 7 times, each trigger for different branches, but the job only ran 1 time for 1 branch.

```
Sep 08, 2016 11:29:53 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/gitlab-test
Sep 08, 2016 11:29:53 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
gitlab-test triggered for push.
Sep 08, 2016 11:29:53 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/gitlab-test
Sep 08, 2016 11:29:53 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
gitlab-test triggered for push.
Sep 08, 2016 11:29:54 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/gitlab-test
Sep 08, 2016 11:29:54 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
gitlab-test triggered for push.
Sep 08, 2016 11:29:54 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/gitlab-test
Sep 08, 2016 11:29:54 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
gitlab-test triggered for push.
Sep 08, 2016 11:29:55 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/gitlab-test
Sep 08, 2016 11:29:55 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
gitlab-test triggered for push.
Sep 08, 2016 11:29:55 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/gitlab-test
Sep 08, 2016 11:29:55 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
gitlab-test triggered for push.
Sep 08, 2016 11:29:56 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/gitlab-test
Sep 08, 2016 11:29:56 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
gitlab-test triggered for push.
Sep 08, 2016 11:29:59 AM INFO hudson.model.Run execute
gitlab-test #2 main build action completed: SUCCESS
```
### Problem description

If you use a GUI git client such as SourceTree or GitKraken, there is a convenient checkbox to "Push all branches" when you push. This results in a single push to the git server containing multiple refs. Gitlab correctly handles that, and calls the webhook multiple times.

The above log message confirms that jenkins triggered the job 7 times, but the job only ran 1 time, for 1 branch.

**Comment by omehegan** [comment]
@rahvee Can you increase the log level for the plugin, by following the directions here: https://github.com/jenkinsci/gitlab-plugin#user-support and then trigger this issue again and paste the logs? I think that will give some additional insight.

**Comment by rahvee** [comment]
Thank you for your response. Below is the verbose log. In this test, I pushed three branches simultaneously. "master", "foobranch", and "barbranch". Only one job was triggered.

```
Sep 09, 2016 10:12:22 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/gitlab-test
Sep 09, 2016 10:12:22 AM FINE com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction
Push: {
  "object_kind" : "push",
  "event_name" : "push",
  "before" : "98ec9cf7d5c91485cb32b09270d93c259244531c",
  "after" : "ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
  "ref" : "refs/heads/barbranch",
  "checkout_sha" : "ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
  "message" : null,
  "user_id" : 2,
  "user_name" : "Edward C Harvey",
  "user_email" : "edward.harvey@tufts.edu",
  "user_avatar" : "https://secure.gravatar.com/avatar/48d32aa4dc092ce6d74975c96028dca9?s=80&d=identicon",
  "project_id" : 1,
  "project" : {
    "name" : "sandbox",
    "description" : "",
    "web_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox",
    "avatar_url" : null,
    "git_ssh_url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "git_http_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox.git",
    "namespace" : "eharve03",
    "visibility_level" : 20,
    "path_with_namespace" : "eharve03/sandbox",
    "default_branch" : "master",
    "homepage" : "https://gitlab.it.tufts.edu/eharve03/sandbox",
    "url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "ssh_url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "http_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox.git"
  },
  "commits" : [ {
    "id" : "ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
    "message" : "asdf\n",
    "timestamp" : "2016-09-09T10:12:09-04:00",
    "url" : "https://gitlab.it.tufts.edu/eharve03/sandbox/commit/ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
    "author" : {
      "name" : "Edward Ned Harvey",
      "email" : "edward.harvey@tufts.edu"
    },
    "added" : [ ],
    "modified" : [ ],
    "removed" : [ ".testcommit" ]
  } ],
  "total_commits_count" : 1,
  "repository" : {
    "name" : "sandbox",
    "url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "description" : "",
    "homepage" : "https://gitlab.it.tufts.edu/eharve03/sandbox",
    "git_http_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox.git",
    "git_ssh_url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "visibility_level" : 20
  }
}
Sep 09, 2016 10:12:22 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
gitlab-test triggered for push.
Sep 09, 2016 10:12:22 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/gitlab-test
Sep 09, 2016 10:12:22 AM FINE com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction
Push: {
  "object_kind" : "push",
  "event_name" : "push",
  "before" : "98ec9cf7d5c91485cb32b09270d93c259244531c",
  "after" : "ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
  "ref" : "refs/heads/foobranch",
  "checkout_sha" : "ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
  "message" : null,
  "user_id" : 2,
  "user_name" : "Edward C Harvey",
  "user_email" : "edward.harvey@tufts.edu",
  "user_avatar" : "https://secure.gravatar.com/avatar/48d32aa4dc092ce6d74975c96028dca9?s=80&d=identicon",
  "project_id" : 1,
  "project" : {
    "name" : "sandbox",
    "description" : "",
    "web_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox",
    "avatar_url" : null,
    "git_ssh_url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "git_http_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox.git",
    "namespace" : "eharve03",
    "visibility_level" : 20,
    "path_with_namespace" : "eharve03/sandbox",
    "default_branch" : "master",
    "homepage" : "https://gitlab.it.tufts.edu/eharve03/sandbox",
    "url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "ssh_url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "http_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox.git"
  },
  "commits" : [ {
    "id" : "ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
    "message" : "asdf\n",
    "timestamp" : "2016-09-09T10:12:09-04:00",
    "url" : "https://gitlab.it.tufts.edu/eharve03/sandbox/commit/ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
    "author" : {
      "name" : "Edward Ned Harvey",
      "email" : "edward.harvey@tufts.edu"
    },
    "added" : [ ],
    "modified" : [ ],
    "removed" : [ ".testcommit" ]
  } ],
  "total_commits_count" : 1,
  "repository" : {
    "name" : "sandbox",
    "url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "description" : "",
    "homepage" : "https://gitlab.it.tufts.edu/eharve03/sandbox",
    "git_http_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox.git",
    "git_ssh_url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "visibility_level" : 20
  }
}
Sep 09, 2016 10:12:22 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
gitlab-test triggered for push.
Sep 09, 2016 10:12:23 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/gitlab-test
Sep 09, 2016 10:12:23 AM FINE com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction
Push: {
  "object_kind" : "push",
  "event_name" : "push",
  "before" : "98ec9cf7d5c91485cb32b09270d93c259244531c",
  "after" : "ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
  "ref" : "refs/heads/master",
  "checkout_sha" : "ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
  "message" : null,
  "user_id" : 2,
  "user_name" : "Edward C Harvey",
  "user_email" : "edward.harvey@tufts.edu",
  "user_avatar" : "https://secure.gravatar.com/avatar/48d32aa4dc092ce6d74975c96028dca9?s=80&d=identicon",
  "project_id" : 1,
  "project" : {
    "name" : "sandbox",
    "description" : "",
    "web_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox",
    "avatar_url" : null,
    "git_ssh_url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "git_http_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox.git",
    "namespace" : "eharve03",
    "visibility_level" : 20,
    "path_with_namespace" : "eharve03/sandbox",
    "default_branch" : "master",
    "homepage" : "https://gitlab.it.tufts.edu/eharve03/sandbox",
    "url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "ssh_url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "http_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox.git"
  },
  "commits" : [ {
    "id" : "ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
    "message" : "asdf\n",
    "timestamp" : "2016-09-09T10:12:09-04:00",
    "url" : "https://gitlab.it.tufts.edu/eharve03/sandbox/commit/ec576fcd95ccf28ac2dbcbd8ac2b0936401d2bc6",
    "author" : {
      "name" : "Edward Ned Harvey",
      "email" : "edward.harvey@tufts.edu"
    },
    "added" : [ ],
    "modified" : [ ],
    "removed" : [ ".testcommit" ]
  } ],
  "total_commits_count" : 1,
  "repository" : {
    "name" : "sandbox",
    "url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "description" : "",
    "homepage" : "https://gitlab.it.tufts.edu/eharve03/sandbox",
    "git_http_url" : "https://gitlab.it.tufts.edu/eharve03/sandbox.git",
    "git_ssh_url" : "git@gitlab.it.tufts.edu:eharve03/sandbox.git",
    "visibility_level" : 20
  }
}
Sep 09, 2016 10:12:23 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
gitlab-test triggered for push.
```

**Comment by coder-hugo** [comment]
@rahvee in your example all 3 branches point to the same commit. The gitlab-plugin schedules for each push event a new build with a `RevisionParameterAction` to tell the git-plugin which revision should be built. If there are several builds scheduled with a `RevisionParameterAction` that have all the same commit the git-plugin skips all but one of the scheduled builds. IMHO it also makes no sense to build the same thing 3 times.
Could you please tell us if this was the same for your first push or provide us logs for another push event that is similar to the one of the issue description.

**Comment by rahvee** [comment]
Well, it sounds like you found the explanation for the problem, but you are not convinced that it's a problem. When we're talking about a literal build of compiled software, you may be right, it may not make sense to build the same thing three times (although I can think of some use cases where people might want to control that behavior). But gitlab and jenkins are not merely automated build systems; they're versioning and continuous deployment tools. For example, if you're coding PHP, CSS, or JavaScript for a website, there is no such thing as a "build." You commit your code, and gitlab triggers jenkins to "git pull" on the web server. This is in fact, the way Tufts is using it (where I work), and that's the reason I noticed the problem. We have a production web server and a develop web server. (And a lot more. I'm just keeping things simple in this description). When a user pushes code, here's what jenkins is supposed to do: If the push was on the "master" branch, do a "git pull" on the production server. If the push was on the "develop" branch, do a "git pull" on the develop server. In fact, this works great, as long as users only push one branch at a time. I also confirmed the behavior you described - if the branches are at different commit levels, there's no problem. The problem only occurs if multiple branches are at the same commit level, and pushed at the same time.

**Comment by coder-hugo** [comment]
As already written in my last comment the `RevisionParameterAction` of the plugin causes this behavior so there is no way to solve this for normal jobs. Multibranch Pipeline jobs work in a different way so the Jenkins would build each branch at the same time no matter if they are at the same commit level or not.
But could you please explain why you want to deploy your application to the dev and the prod stage at the same time? IMHO you should perform some integration tests on your dev stage before deploying the application to the prod stage.

**Comment by rahvee** [comment]
Thanks for your reply. In the Tufts IT dept, we offer a service to our users. We run gitlab and jenkins servers for them, we help them configure webhooks, etc. We tell our users "just push to a branch, and your push will be automatically deployed." (Most users' development work is PHP. Drupal and wordpress for Tufts websites). We work with them to identify which branch should be pushed to what server, and so on, and then we help configure those jobs. It's not our job to tell them how to do their work. Some of them behave as you would expect - they push to a branch called "dev", they test it, then they push to "stage", they test again, and then they push to "prod" or "master" and test again. Some other users develop and test on their own local laptops, in vagrant or xampp local development environments, and then they push directly to "stage" & "dev" at the same time, to test before pushing to "master". Sometimes, if it's a simple change, or the site hasn't publicly launched yet, etc, they might develop and test on their laptop, and push to all branches simultaneously. Some sites have a master, stage, and multiple dev branches (dev-jon, dev-andy, dev-mary, etc) and amongst their team they've decided, that anything pushed to master should be merged to all the other branches too, so master is never ahead of anyone. So they sometimes do a single push simultaneously to 4-6 branches.

I may have misunderstood your previous comment. I thought you were telling me `RevisionParameterAction` squashing was something the gitlab-plugin was squashing, but if I understand correctly now, `gitlab-plugin` doesn't squash it. You're using `RevisionParameterAction` which comes from `git-plugin`, so it is the git-plugin that's doing the squashing.

From here, it seems, I have three directions to go: (1) Do you think this is a bug in git-plugin, or perhaps a feature enhancement, that I should go talk to them about? (2) Thanks for the suggestion of using a pipeline job. I'll look into it, and maybe that will give us an easy solution. (3) Our usage of gitlab-plugin is tiny, simple. We're not using most of its features; we just use it because it gives us a simple checkbox to enable a webhook URL, which will listen for and parse the gitlab JSON into environment variables, and then we execute shell commands using those variables. Simple stuff like `if [ "$gitlabBranch" = "master" ] ; then cd /foo/$gitlabSourceRepoName ; git pull ; elif [ "$gitlabBranch" = "develop" ] ; then cd /bar/$gitlabSourceRepoName ; git pull ; else echo "error" ; fi` ... So all I want is a simple way to create a webhook URL that parses gitlab json into environment variables. I've never tried writing a jenkins plugin before, but I'm ok at java. Maybe I can write a new plugin that doesn't depend on `git-plugin`. 

Thanks again for your help.

**Comment by coder-hugo** [comment]
@rahvee I just figured out that the commit for the `RevisionParameterAction` mustn't be its SHA1. See documentation:

``` java
/**
* SHA1, ref name, etc. that can be "git rev-parse"d into a specific commit.
*/
public final String commit;
```

So I'll change the code for push events to use the ref of the web hook instead of the commit id for triggering builds. With this it will be possible to push multiple branches at the same commit level at the same time and each push will trigger a build.
