### ISSUE TITLE
Small error in Readme which cost me some time to figure out

### ISSUE THREAD

**Issue by sturmf** [jenkinsci/gitlab-plugin#409]
The example Jenkinsfile in Readme.md has this line:

`properties properties: [[$class: 'GitLabConnectionProperty', gitLabConnection: '<your-gitlab-connection-name>']]`

but it should be this:

`properties: [[$class: 'GitLabConnectionProperty', gitLabConnection: '<your-gitlab-connection-name>']]`

Note the extra properties.

**Comment by omehegan** [comment]
Fixed, thanks!
