### ISSUE TITLE
Build on specific tag push

### ISSUE THREAD

**Issue by andrewcharnley** [jenkinsci/gitlab-plugin#412]
I'd like instead to build a specific tag only when the tag name is of a specific value string/regex.

So if I perform;

git tag qa02 -f && git push origin qa02 -f

Only the tag "qa02" will be built. Presently it is possible to build on push but not on tag only (and to filter by tag name so any tag push will rebuild qa02).

Thanks! Andrew

**Comment by qrsty** [comment]
This can already be done.

If you've modified the refspec of the repository to be `+refs/tags/*:refs/remotes/origin/tags/*` like in the docs, the `Filter branches by regex` should parse the tag. 

`refs/tags` must be part of the regex.

As an example I use this regex to only build `release/x.y.z` tags:

`refs\/tags\/release\/([0-9]+\.[0-9]+\.[0-9]+)$`

**Comment by andrewcharnley** [comment]
Just to confirm, in source code management -> "Branches to build" I have: refs/tags/qa02 and refspec is: +refs/tags/_:refs/remotes/origin/tags/_ (although this shouldn't matter, it's just faster to only fetch)

Within Build triggers "Allowed branches" I have -> refs\/tags\/qa02

Which should be the missing link to only trigger on that tag push?

**Comment by andrewcharnley** [comment]
Great it's working. I wasn't passing the token correctly in the Gitlab webhook (needs to use basic auth not ?token=). There's no documentation for this but perhaps the reference URL can include the 

http://user:token@ciserver/project/job

To make it obvious.

**Comment by qrsty** [comment]
Ah, I wasn't using tokens to auth as our GitLab and Jenkins servers are not connected to the internet.
