### ISSUE TITLE
Need to document GitLab -> Jenkins authentication setup

### ISSUE THREAD

**Issue by omehegan** [jenkinsci/gitlab-plugin#418]
We need to document how to set up the optional authentication between GitLab and Jenkins for triggering jobs.

**Comment by coder-hugo** [comment]
Btw. we should start moving the documentation from the full-blown README where nobody finds what he's looking for to the wiki. There we can create pages for different use-cases which should make it easy to find the thing you are looking for.

**Comment by omehegan** [comment]
I agree. I can try to work on that.

**Comment by coder-hugo** [comment]
Maybe we should also add them screenshots to the documentation. IMHO it's easier to tell somebody what he needs to click or where he has to enter something if you show him a picture of the UI.

**Comment by omehegan** [comment]
Note to self: the way to configure this is:
1. Jenkins global configuration -> require authorization for /project endpoint
2. Copy userid and API key for a Jenkins user who has authorization to run the job
3. Create a webhook on GitLab to trigger the job, and use HTTP basic auth: http://user:apikey@gitlab/project/jobname

**Comment by leoniscsem** [comment]
Great! The `user:apikey` was the missing configuration step which drove me nuts. Since I am just working on our internal documentation I could / would like to contribute to the wiki. I am nearly done with the doc, just needs English translation. Have you decided on the wiki pages already? Our use case is a Jenkins behind nginx reverse proxy, with authentication / without anonymous read permissions (no public projects), GitLab 8 (most recent).

**Comment by coder-hugo** [comment]
@omehegan btw. with 59ee882b8d65dc58b29e0cf21c04be98df3b2496 I added the functionality to configure secret tokens per Jenkins job which then can be configured in the corresponding GitLab web hook in the `Secret Token` field.

**Comment by jmcgeheeiv** [comment]
I did some work on clarifying the [documentation](https://github.com/jmcgeheeiv/gitlab-plugin/blob/gitlab-connection-doc/README.md) in PR #414.  You might give that a read.

**Comment by omehegan** [comment]
I should also look at https://github.com/jenkinsci/gitlab-plugin/issues/375#issuecomment-295761116 when updating this doc.

**Comment by Ian-T-Price** [comment]
Not sure if this is a documentation issue or a bug:

    https://gitlab.com/Ian-T-Price - this fails to connect

    http://gitlab.com/Ian-T-Price - this works

Given that the first one is the correct URL and that HTTPS is becoming / has become the standard, then the first line should connect.

**Comment by omehegan** [comment]
After 18 months, this is finally documented.
