### ISSUE TITLE
Display build in Commits section but not in Builds on Gitlab

### ISSUE THREAD

**Issue by algorys** [jenkinsci/gitlab-plugin#419]
### Context
- **Gitlab plugin version**: 1.4.0
- **Gitlab version**: 8.1.4
- **Jenkins version**: 2.7.4
### Logs & Traces

The GitLab log does not show anything for the submit step, only the trigger event of the build is logged.
### Problem description
- **Resume**

I've a pipeline job who trigger other jobs in Jenkins. When I push to gitlab, pipeline job is trigger (only for specific branch) the wanted job. In each I've added "Publish build status to Gitlab commit...")
- **Known problem**

For your information, I've the following issue #411 and try all the syntax in my pipeline but anyway, always `No GitLab connection configured`. And before I've nothin in builds on Gitlab server.

But I've a connection for gitlab already configured. So it's very strange...
- **What I try**

I've searched on your repo and see the following step for pipeline : https://github.com/jenkinsci/gitlab-plugin#gitlab-configuration

I've added some syntax in my pipeline and now I've a build in my commit message (on the right branch), like this: 

![gitlab_build](https://cloud.githubusercontent.com/assets/8926922/18667230/fd330f7e-7f2f-11e6-9a41-8c6c0c79be5e.png)

But if I go on Builds (ex: `http://gitlab.com/group/repos/builds`) there is always 0 builds, Finished and All.

Here is my pipeline:

``` groovy
def core = [name: "core", jobName: "build_core"]
def graphs = [name: "graphs", jobName: "build_graphs"]

gitlabSourceBranch = [
    [$class: 'StringParameterValue', 
    name: 'gitlabSourceBranch',
    value: "${env.gitlabSourceBranch}"]
    ]

properties([[$class: 'GitLabConnectionProperty', gitLabConnection: 'connection-name']])

try {
    gitlabCommitStatus("build") {
        stage ('Compilation'){
            node{

                println("Compilation of Core")
                build(
                    job: core.jobName, 
                    parameters: gitlabSourceBranch,
                )
                println("Compilation of Graphs")
                build(
                    job: graphs.jobName, 
                    parameters: gitlabSourceBranch
                )
                }
            }
    }
}  
catch (err) {
    <Other code for Sending mails>
}
```

I want to know how I can update "Builds" on Gitlab server via my pipeline ?

Does I've to precise something else in my pipeline for it ?

Thanks for help.

**Comment by coder-hugo** [comment]
The `gitlabCommitStatus` step must be after a `checkout` step. (see [example Jenkinsfile](https://github.com/jenkinsci/gitlab-plugin#git-configuration-for-multibranch-pipelineworkflow-jobs)) otherwise it doesn't no the revision that is currently built. The revision/commit sha1 is necessary to update the build status.
Furthermore if the following line `No GitLab connection configured` you will see also no builds in GitLab. As this error means that the plugin can't find any configured GitLab connection for the current job.
Btw. you are talking just about a pipeline but use the properties step to configure the GitLab connection which is meant to be used for multibranch pipelines. If you use just a pipeline job instead of a multibranch pipeline you should remove the properties step for the script and configure the GitLab connection in the job settings itself.

**Comment by qrsty** [comment]
Context
- Gitlab plugin version: 1.3.2
- Gitlab version: 8.11.2
- Jenkins version: 2.19

The builds page shows 0 builds for me as well-- though I believe it's a shortcoming on GitLab's part. The many recent changes to their build statuses changing from commit "builds" to "pipelines" doesn't mesh well with external CI providers. I'm not sure if there's an available API.

By default, my project doesn't have the builds checkbox enabled:

![settings](http://i.imgur.com/BOFn1z2.png)

However enabling it shows the Pipelines tab:

![pipelines](http://i.imgur.com/lcKApja.png)

Tabbing over to `Builds`, it is also empty as @algorys is experiencing:

![builds](http://i.imgur.com/TVUQi0u.png)

I have both freestyle and multi-branch pipeline jobs updating build statuses to our local GitLab.

A simplified version of my `Jenkinsfile` is as follows:

``` groovy
properties([[$class: 'GitLabConnectionProperty', gitLabConnection: 'myGitLab']])

node('labels') {
  checkout scm

  gitlabCommitStatus('my build') {
    // do build
  }
}
```

**Comment by algorys** [comment]
@coder-hugo 

> If you use just a pipeline job instead of a multibranch pipeline you should remove the properties step for the script and configure the GitLab connection in the job settings itself.

Ok, that's working (I've added the `checkout` step too).

The problem comes from the job I trigger : it's a matrix job, so it doesn't work (as I see here https://github.com/jenkinsci/gitlab-plugin#matrixmulti-configuration-jobs :cry: ). 

If I trigger a simple freestyle job, `No GitLab connection configured` disappears.

But for the `Builds` gitlab page, there is still nothing and I have no "Builds" section in Webhook like @qrsty  on Gitlab 8.1...

**UPDATE:** I'll try to update my gitlab to 8.11 to see if it's working.

**Comment by tonka3000** [comment]
Same Problem here. Everything works fine, but after updating to 8.11/8.12 I have no builds. The job is triggered via webhook. I can see that the correct data is send back to GitLab, but no builds visible at all.
It seems that something has changed inside GitLab itself.

I opened an issue https://gitlab.com/gitlab-org/gitlab-ce/issues/22515

Greetings

**Comment by algorys** [comment]
After update to the last version (`1.4.2`) and with the following syntax:

`properties properties: [[$class: 'GitLabConnectionProperty', gitLabConnection: 'gitlab-connection-name']]`

 I still do not have my builds in **Builds** Gitlab page. Only available on **Commits** page. But `No GitLab connection configured` disappear (also for Matrix job). I've now the following message on my pipeline job:

``` bash
WARNING: The properties step will remove all JobPropertys currently configured in this job, either from the UI or from an earlier properties step.
This includes configuration for discarding old builds, parameters, concurrent builds and build triggers.
WARNING: Removing existing job property 'GitLab connection'
WARNING: Removing existing job property 'Build triggers'
```

What does that means ? 

I do not use other properties steps.

Greetings

**Comment by qrsty** [comment]
@algorys If you're using a normal Pipeline job, there are properties you can specify in the Job configuration. The `properties` groovy step is meant for multi-branch Pipelines.

**Comment by algorys** [comment]
Yes sorry @qrsty I've forget that.

**Comment by tonka3000** [comment]
@algorys are your builds now visible in gitlab?

**Comment by algorys** [comment]
@tonka3000 No :sob: 

I've tried with:
-  simple pipeline who checkout and build Freestyle job
-  simple pipeline who checkout and build Matrix job

But I still have the build only on **Commits** gitlab page. And nothing in **Builds** Gitlab page. Here is my sample pipeline job:

``` groovy
gitlabSourceBranch = [string(name: 'gitlabSourceBranch', value: 'dev')]

node {
    stage("Checkout")
    checkout([
        $class: 'GitSCM', 
        branches: [[name: 'dev']], 
        doGenerateSubmoduleConfigurations: false, 
        extensions: [[$class: 'CleanBeforeCheckout']], 
        submoduleCfg: [], 
        userRemoteConfigs: [[credentialsId: 'aaaaa-bbbb-ccccc-ddddd', url: 'git@mygitlab.com:gourp/project.git']]
        ])

    gitlabCommitStatus("build") {
    stage("Module CORE") {
        build(
            job: "Job_TEST",
            parameters: gitlabSourceBranch
            )
        }
    }
}
```
- Gitlab plugin version: 1.4.2
- Gitlab version: 8.1.4
- Jenkins version: 2.7.4

Maybe I've make an error in the steps and how use it :thinking: ?

**Comment by m-ruhl** [comment]
https://github.com/jenkinsci/gitlab-plugin/issues/177 Comments:

> The build page is being redesigned/repurposed. In the meantime, no, there's no way to get Jenkins builds to show there.

**Comment by omehegan** [comment]
Closing because this is not supported on the GitLab side.
