### ISSUE TITLE
Is a checkout required before i can use gitlabCommitStatus

### ISSUE THREAD

**Issue by tonka3000** [jenkinsci/gitlab-plugin#420]
Hey,

Is a checkout from a scm required before i can use gitlabCommitStatus?  
I have a build which trigger itself other jobs, so the root-job does not checkout anything, but i want a commit status to gitlab, but it seems that does not work.

I can not find a clarification in the documentation, so if the answer to my question is true, can anybody drop some lines in the docs.

Greetings
Tonka

**Comment by omehegan** [comment]
Yes, per @coder-hugo:
"The gitlabCommitStatus step must be after a checkout step. Otherwise it doesn't know the revision that is currently built. The revision/commit sha1 is necessary to update the build status."

I will update the doc for this.
