### ISSUE TITLE
Merge request build trigger not working for pipeline job and push to source branch

### ISSUE THREAD

**Issue by berni2288** [jenkinsci/gitlab-plugin#425]
### Context
- **Gitlab plugin version**: 1.4.2
- **Gitlab version**: 8.8.3 CE
- **Jenkins version**: 2.23
- **Job type**: Pipeline job
### Logs & Traces

``` log
Oct 03, 2016 3:02:14 PM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/testjob
Oct 03, 2016 3:02:15 PM FINE com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction 
Push: { /* pushdata removed */ }
```
### Problem description

I have enabled "Merge Request Events" and "On push to source branch" in the job settings. I pushed a new commit to the source branch of an already open Merge Request. However the pipeline job does not get triggered when "Push Events" is not activated in the Job settings. When I activate "Push Events" the job gets triggered, however this is not what I want because I want to build merge request branches only.

I tried to build the gitlab-plugin in Eclipse in order to debug it myself, however there are unresolvable errors like "The import com.dabsquared.gitlabjenkins.cause.CauseDataBuilder cannot be resolved".

**Comment by omehegan** [comment]
@berni2288 GitLab only fires Merge Request webhooks when you open, merge, or close an MR. Pushes, whether to an MR or not, only fire the Push webhook. If you want to build MR branches only, perhaps the branch filtering feature of the plugin would help.

**Comment by berni2288** [comment]
While this might be technically correct, from the perspective of the Jenkins setting UI it's not clear that when you set the setting "Rebuild open Merge Requests" to the value "On push to source branch" that you would have to enable Push Events also.

The Gitlab documentation for Merge request events says the following:

> Triggered when a new merge request is created, an existing merge request was updated/merged/closed or a commit is added in the source branch.

Therefore it would actually make sense that enabling "Merge Request Events" would trigger also when you push to the source branch of a MR. I don't understand the "Rebuild open Merge Requests" setting, when you have to use branch filtering anway.

**Comment by coder-hugo** [comment]
@omehegan this is wrong. GitLab fires a MR update event for pushes to the source branch. Just tested it with GitLab 8.11. So there is no need to configure push events on GitLab side for rebuilding open merge request.
@berni2288 if this isn't working for you can you please add a logger to your Jenkins as described [here](https://github.com/jenkinsci/gitlab-plugin#user-support) and post the log output here. Btw. the unresolvable imports are auto-generated classes that are generated by an annotation processor. This should be invoked by the java compiler maybe you have to configure something special in eclipse to do this.

**Comment by omehegan** [comment]
Oh, my mistake, I asked @dblessing before answering this. Sorry!

**Comment by berni2288** [comment]
This was an issue with our Firewall and has nothing to do with the gitlab-plugin, sorry!
I close this issue.
