### ISSUE TITLE
Plugin should have secure defaults

### ISSUE THREAD

**Issue by omehegan** [jenkinsci/gitlab-plugin#427]
Now that we have implemented a couple of methods for authenticating access for the GitLab webhooks, it would be a best practice to enable that authentication by default on new installs. This is in keeping with the Jenkins 2 philosophy of being secure by default.

My understanding is that we have two options for authentication. One is a global option where all access to the /project endpoint must use HTTP basic auth with a username and password that already have authorization to trigger jobs. The other is a per-job/per-project option where the user can specify a token on the GitLab webhooks page and the Jenkins job configuration page.

I would suggest that we enable the global security option by default. In concert with this, we should create a "Getting Started" section of the documentation (as part of refactoring all of the doc into the wiki) which explains how to use auth in the webhooks, as well as how to disable the auth if desired. I can handle the documentation work.

**Comment by omehegan** [comment]
@daniel-beck when you have time, can you comment briefly on how I could implement a backward-compatible "enable security by default" setting? We talked about this once but I don't remember the details. The point being that I would only want to enable security on new installs of the plugin, not force-enable it when people upgrade. Thanks!

**Comment by daniel-beck** [comment]
@omehegan 

> We talked about this once but I don't remember the details. The point being that I would only want to enable security on new installs of the plugin, not force-enable it when people upgrade. Thanks!

Sorry, drowned in GH notifications.

Have a `Boolean` (uppercase, i.e. nullable) field that's `true` by default, but gets set to `false` in `readResolve` if it's `null` (or the other way around). Databind a form field to it, and done.

The reason this works is that an instance of your persisted descriptor (or whatever you have) gets loaded on startup, going through `readResolve` rather than constructors/field initialization. It's `null` by default, so you know you loaded a pre-existing config. OTOH if someone sets up the configuration from scratch, the field default is used.

**Comment by omehegan** [comment]
@mreichel or @colourmeamused would either of you want to make a pass at implementing this? It's been an unfortunate bug for quite awhile now that the plugin by default will allow unauthorized users to trigger builds. We want to change the default settings to be secure, but make sure we don't break anyone who is currently relying on the insecure configuration when they upgrade.

**Comment by mreichel** [comment]
@omehegan, I can try. Just let me get this right: the "Enable authentication for '/project' end-point" functionality for the GitLab plugin settings in the global settings should be enabled by default, but only if it is not `null`. The authentication method  doesn't need to be changed.

**Comment by omehegan** [comment]
@mreichel that's right. Valid tests:

1. If you install the plugin for the first time on a Jenkins host, 'Enable authentication...' should be checked
2. If you already have the plugin installed, and 'Enable authentication...' is NOT checked, upgrading the plugin should not change that setting; it should stay disabled

We should also update the doc accordingly, so that new users know they will need to either set up a token and use it in their webhooks, or disable auth. I can handle the documentation if you want, I already have an open issue to add a section explaining how to do authentication.

**Comment by mreichel** [comment]
Works well in my tests, unfortunately I can't see a way to write automated test. @omehegan: I did not add any documentation, since you already have your open task.

**Comment by omehegan** [comment]
@mreichel it looks like you opened the PR against your fork of the repo, I don't think we can merge that directly to this one can we?

**Comment by mreichel** [comment]
@omehegan sorry, my fault. I changed the PR

**Comment by omehegan** [comment]
This was released today in version 1.4.8 of the plugin.
