### ISSUE TITLE
Error in Readme for forked repositories

### ISSUE THREAD

**Issue by pbendersky** [jenkinsci/gitlab-plugin#428]
When configuring for forked repositories, the Readme specifies:

```
3. To be able to merge from forked repositories:  <br/>**Note:** this requires [configuring communication to the GitLab server](#configuring-access-to-gitlab)
  * Add a second repository with:
    * *URL*: ``${gitlabSourceRepoURL}`` 
    * *Name* (in Advanced): ``${gitlabSourceRepoName}``
4. In *Branch Specifier* enter:
  * For single-repository setups: ``origin/${gitlabSourceBranch}``
  * For forked repository setups: ``merge-requests/${gitlabMergeRequestIid}``
```

However, `merge-requests/${gitlabMergeRequestIid}` is available in `origin` and not in `${gitlabSourceRepoURL}`. Even more, the Jenkins user may not have permissions to fetch from `gitlabSourceRepoURL` (that's the neat thing about fetching a reference in origin: we don't need Jenkins to have a deploy key on every user fork).

**Comment by omehegan** [comment]
@pbendersky ok, so I'm a bit late... I think I've just fixed this. Please let me know if it looks right, assuming you still care :)
