### ISSUE TITLE
Number format is added at merge requests > 1000

### ISSUE THREAD

**Issue by d4nj1** [jenkinsci/gitlab-plugin#429]
Hi.
- **Gitlab plugin version**: 1.4.2
- **Gitlab version**: 8.11
- **Jenkins version**: 1.642

I just upgraded to the last version of the plugin (1.1.28 -> 1.4.2) and the links to GitLab have an issue when getting bigger than 1000. When this happens the link starts to get a thousand separator. I attached screenshots below. The link is actually ok and refers to the MR when accessed without seperator

Build overview:
![triggercomment3372_1](https://cloud.githubusercontent.com/assets/5252490/19188678/a3bf5da0-8c93-11e6-9983-5913f4b1b90f.png)

Job overview:
![triggercomment3372_2](https://cloud.githubusercontent.com/assets/5252490/19188677/a3bb2c4e-8c93-11e6-8cb2-04161d624470.png)

My question:

Is this a bug in the plugin, or is the thousand separator added by Jenkins somehow?
Thanks in advance.

**Comment by alan-schwarzenberger** [comment]
I also have this behaviour with Gitlab 8.11.4, Jenkins 1.658 and gitlab-plugin 1.4.2
To be clear this is not just a display issue as is mentioned above. The link when clicked on does not work first time. You have to edit out the comma, and then it works.

**Comment by omehegan** [comment]
I am guessing that this is a plugin bug, maybe this value needs to be cast to a string or something?

**Comment by omehegan** [comment]
This was released in version 1.4.4 of the plugin.
