### ISSUE TITLE
 Gitlab-Plugin /project endpoint do not work

### ISSUE THREAD

**Issue by ghost** [jenkinsci/gitlab-plugin#432]
### Context

-**gitlab Version**: 8.12
-**jenkins version**: 2.16
-**gitlab-plugin version**: 1.4.2
### Problem description

In almost every setup example of the gitlab plugin like here https://medium.com/@teeks99/continuous-integration-with-jenkins-and-gitlab-fa770c62e88a#.byii26kal the gitlab webhook configuration part indicates that the url to record should look like this http://jenkins-host:port/project/<merge-request-job>/ where 'project' is the literal word 'project'.

 After many attempts, i have failed to have a working url with a project endpoints in my jenkins instance and thus i can't make gitlab triggers jobs on push and merge requests events. when i use as web-hooks classic addresses for jenkins job i.e.
 http://jenkins-host/job/folder_name/job/merge-request-job/ the trigger calls are made, returning http code 200 but the jobs don't start.

If anyone here has had the same issue or has any investigating path for me to solve this, i would like to thank you in advance for your help.

**Comment by omehegan** [comment]
The literal word 'project' is necessary in the URL. That's the endpoint that the GitLab trigger plugin takes input from. Any other URL will bypass this plugin.

Please post logs from your Jenkins, following the user support instructions here, after you have set up your GitLab webhooks to use the http://JENKINS_URL/project/JOBNAME form of the URL: https://github.com/jenkinsci/gitlab-plugin/blob/master/README.md#user-support  This will help us figure out why your job is not triggering.
