### ISSUE TITLE
Gitlab-Plugin seems to mixup builds and pipelines when publishing results in Gitlab MR

### ISSUE THREAD

**Issue by ghost** [jenkinsci/gitlab-plugin#434]
## Issue

Gitlab-Plugin seems to mixup builds and pipelines when publishing results in Gitlab MR
### Context

-**gitlab Version**: 8.12
-**jenkins version**: 2.16
-**gitlab-plugin version**: 1.4.2
### Problem description

The Jenkins and Gitlab instance seem to integrate very well thanks to the gitlab-plugin, jobs are triggered smoothly after a merge request event or a push to the said merge request. But when publishing the results of the build, it seems that the build data are published under pipeline tab while the pipeline status is published under the builds tab.

I was wondering if i missed something during the setup or is this a known issue or maybe the notion of pipeline and builds are different in gitlab-ci?

**Comment by omehegan** [comment]
This is a known issue with GitLab. They have changed where this information appears when we send it from Jenkins. I am using GitLab CE 8.10 and I see build results under the Builds tab. I do not have a Pipeline tab. Maybe @dblessing can comment?

**Comment by ghost** [comment]
thanks for the explanation

**Comment by dblessing** [comment]
This is expected behavior AFAICT. External builds (reported via the commit status API) are not part of a pipeline. Pipelines are a GitLab CI-specific thing.

**Comment by omehegan** [comment]
I'll add a note to the README about this.

**Comment by milani** [comment]
Mine appears in pipeline but stages are not set correctly. I have 5 `gitlabCommitStatus` in my Jenkinsfile, but only 3 of them appear as builds under a single pipeline (Builds panel is empty).

![screen shot 2016-12-26 at 4 32 50 pm](https://cloud.githubusercontent.com/assets/508130/21482417/09ea5f7e-cb89-11e6-8d1c-485e8442f1f4.png)

![screen shot 2016-12-26 at 4 34 02 pm](https://cloud.githubusercontent.com/assets/508130/21482428/29fd1194-cb89-11e6-82a1-42c84ca22394.png)


Context:
**Gitlab CE**       8.15.1
**Gitlab Plugin**  1.4.3
**Jenkins**           2.38

**Comment by omehegan** [comment]
Not a plugin bug.
