### ISSUE TITLE
Build pipeline job for MR from fork

### ISSUE THREAD

**Issue by Cosaquee** [jenkinsci/gitlab-plugin#435]
## Issue

Right now if MR is created everything works fine. My setup is simple, webhook from Gitlab on merge request and normal pipeline job with `Build when a change is pushed to GitLab` checked. if someone creates MR from fork to origin/master of base project, Jenkins cannot checkout on good revision `unknown revision or path not in the working tree`. 

Probably because it should build revision not from master but from this fork. I do not know how to setup it so everything will work as is should.  I have to use Pipeline job not Freestyle.

Any idea how should i do it ?
### Context
- **Gitlab plugin version**: 1.4.0
- **Gitlab version**: 8.13.0
- **Jenkins version**: 9.7.4

**Comment by omehegan** [comment]
@Cosaquee can you share your Pipeline script? That might help us come up with a working example for you.

Also there is no Jenkins version 9.7.4...
