### ISSUE TITLE
Feature request: is there a plan to add handlers also for "Comment events"

### ISSUE THREAD

**Issue by cgumpert** [jenkinsci/gitlab-plugin#440]
Dear developers,
so far, the Gitlab plugin only handles "Push events" (tags and commits) as well as "Merge requests events". Is there a plan to also add support for "Comment events"? 
We have a quite distributed review process in our team and we would love to be able to trigger longer running validation tests per comment on the merge request. So we are curious whether there are any plans in this direction?

Thanks

**Comment by rfelgent** [comment]
Vote +1

I'd like to have such a feature, too

**Comment by cgumpert** [comment]
It seems like a NoteHandler already exists. I must have overlooked it. Sorry for the noise. I am closing this ticket now.
