### ISSUE TITLE
API token is not displaying in configure system

### ISSUE THREAD

**Issue by hemanthsridhar** [jenkinsci/gitlab-plugin#443]
OS: OSX Sierra 10.12.1
GitLab Plugin : 1.4.3

Steps:
Download Git Plugin
Download GitLab Jenkins Plugin
Restart Jenkins
navigate to Configure System

PFA for screenshot.
<img width="1086" alt="screen shot 2016-11-08 at 2 30 31 am" src="https://cloud.githubusercontent.com/assets/13584014/20075780/ac7ca598-a55b-11e6-813f-04f8713748cd.png">

**Comment by omehegan** [comment]
@hemanthsridhar have you followed the instructions in this section of the README? https://github.com/jenkinsci/gitlab-plugin#configuring-access-to-gitlab

**Comment by gmaghera** [comment]
I have followed the instructions you linked.  Jenkins can connect to GitLab successfully through the system configuration, using the private token of my GitSwarm user.  When I go to configure a job's Git connection credentials it only shows the two SSH keys I have set up, although there are a handful of GitLab API tokens (from repeated attempts).

**Comment by tony612** [comment]
I have same problem with @gmaghera .

**Comment by hemanthsridhar** [comment]
I was able to invoke from gitlab.
The thing is you need to add the api token. There's no option of the api token textbox.
Please Close the issue.

**Comment by gmaghera** [comment]
@hemanthsridhar How did you add the API token?  I've added it through the system configuration, but it does not show up in the credentials selector in the job's Git configuration section.  I've also tried to add the token directly via the Git configuration section, by clicking the "Add" button (with a little key icon on it).  That key does not show up in the selector either, and it seems to have no effect on the job's Git authentication, although it does show up in my credentials list under system config.

**Comment by omehegan** [comment]
@gmaghera I think you might be mixing two different issues here. @hemanthsridhar was having problems with the global configuration of the GitLab plugin to access his GitLab API. You need a GitLab token for that.

You seem to be referring to the configuration of the Git plugin in each job, not the GitLab plugin. The Git plugin needs credentials to clone repos, and that is why you only see the SSH keys there. If those keys are valid for cloning a repo, you should be all set. Is there something else not working for you?

**Comment by gmaghera** [comment]
@omehegan That was it!  I was under the impression that the API token could also be used to access the repos too.  I've been able to access the repos using SSH keys successfully.  Thanks for the explanation.

**Comment by hemanthsridhar** [comment]
@omehegan : Issue exists after I add the api token. The api token does not appear in the dropdown.
Jenkins version : 2.45
