### ISSUE TITLE
Double commit statuses created when using "Publish build status to Gitlab commit"

### ISSUE THREAD

**Issue by Bjoern-Hegstam** [jenkinsci/gitlab-plugin#451]
## Issue
Double commit statuses created when using "Publish build status to Gitlab commit" with build that is not triggered directly from gitlab webhook.

### Context
- **Gitlab plugin version**: 1.4.0
- **Gitlab version**: 8.13.3-ee
- **Jenkins version**: 1.650

### Logs & Traces

Example of two commit statuses created from the same job, when only one should have been created and then updated:
```json
{
    "id": 73,
    "sha": "74a3c7dce0cdf7210e514cc6e8008591dcb2bded",
    "ref": "ar21890/scheduler",
    "status": "running",
    "name": "jenkins-Dev",
    "target_url": "https://<jenkins>/job/Test171Dev/106/",
    "description": null,
    "created_at": "2016-11-09T10:49:39.908Z",
    "started_at": "2016-11-09T10:49:39.921Z",
    "finished_at": null,
    "allow_failure": false,
    "author": {
        "name": "Administrator",
        "username": "admin",
        "id": 1,
        "state": "active",
        "avatar_url": "https://<gitlab>/uploads/user/avatar/1/avatar.png",
        "web_url": "https://<gitlab>/admin"
    }
},
{
    "id": 74,
    "sha": "74a3c7dce0cdf7210e514cc6e8008591dcb2bded",
    "ref": "release/17.1",
    "status": "success",
    "name": "jenkins-Dev",
    "target_url": "https://<jenkins>/job/Test171Dev/106/",
    "description": null,
    "created_at": "2016-11-09T11:03:59.355Z",
    "started_at": null,
    "finished_at": "2016-11-09T11:03:59.357Z",
    "allow_failure": false,
    "author": {
        "name": "Administrator",
        "username": "admin",
        "id": 1,
        "state": "active",
        "avatar_url": "https://<gitlab>/uploads/user/avatar/1/avatar.png",
        "web_url": "https://<gitlab>/admin"
    }
}
```

### Problem description
At my job we have one jenkins build setup for each release-branch in our repo. The builds are triggered by using a gitlab webhook that call the notifyCommit-service of the jenkins git plugin (`https://<jenkins>/git/notifyCommit?url=<repo-url>`) or by starting a build manually. The branch to build is specified in each job like so `refs/heads/release/${releaseNumber}`.

In the future we would like to require a passing build before a merge request can be accepted. I therefore turned on "Publish build status to Gitlab commit" to see if it would work. It did, but after a while I noticed that some commit statuses were never updated to passed/failed. They simply stayed marked as running.

Looking into it more I noticed that a "stuck" commit status always came paired with a passed/failed one. In the example above you can see that the ref-attribute is what differs between the two. Looking at the source for the gitlab plugin I saw that the ref is only specified if a `GitLabWebHookCause` is found. I assume we don't get that since our jenkins job is only indirectly triggered via a webhook (and sometimes manually). I followed the instructions for turning on finer logging and verified that the ref is not included in the POST to gitlab. I assume that gitlab then chooses the first branch it encounters for the given sha as the ref, which might differ between when the build starts and completes.

I would be very thankful if there was a way to solve our problem. Maybe a new attribute (alongside "Build name") where we can specify a (parameterized) ref to use if a `GitLabWebHookCause` is not found?

**Comment by omehegan** [comment]
This is a strange use case I guess. You are essentially triggering the build based on MR events, but you are not using the GitLab plugin as the trigger. Why not?

**Comment by Bjoern-Hegstam** [comment]
Let me describe our setup:
* We have release branches and feature branches. When a feature branch is complete it is merged into a release branch. The release branches are named by version (e.g. release/1.0), so a new release branch is created for each new version. At the moment we have two active release branches and about 60 feature branches.
* There are two jenkins projects setup for each release branch. One that builds on push and runs a fast test suite, and one that runs every night with all integration tests.
* To test our feature branches we have a pool of about a dozen identical jenkins projects that can be run manually for a given branch. Here we would like to start using the Gitlab Hook plugin to dynamically create and delete projects based on feature branches (a workflow supported out-of-the-box by e.g. Bamboo). We will try to have these projects trigger on push to begin with, but will probably move to having them be manually triggered.

Correct me if I'm wrong, but if I'm understanding the plugin documentation correctly, then to use the GitLab plugin as the trigger we need to add a gitlab webhook that points to the specific jenkins project we want to trigger. Using the git plugin notifyCommit-service allows us to define a single webhook and configure the projects to only build certain branches, whereas the gitlab webhook would require us to continuously add/remove webhooks based on which jenkins projects we currently have. Also the reliance on the gitlab webhook payload means that we cannot use manual builds to post the build status back to gitlab (least we risk running into the double status problem).

I know our current workflow isn't perfect, and I'll gladly accept pointers and suggestions, but I do believe that we are moving the right direction.

**Comment by Bjoern-Hegstam** [comment]
It always helps to get a second opinion. A colleague had a look and came up with a solution that will probably work for us. It might be obvious to some, but we needed some time to ge there. :)

We'll simply setup a single jenkins project for building all merge requests (with *Execute concurrent builds if necessary* enabled). Then there's no problem with having to define a specific webhook in gitlab, since we'll only ever need one.

**Comment by Bjoern-Hegstam** [comment]
Well this is interesting. The setup has been working very well, except that we've again encountered a problem with double commit statuses being created, but for a different reason. I'm gonna create a new issue to avoid muddling this one. From our perspective this issue can be closed, but I'll leave the final decision up to you.

**Comment by omehegan** [comment]
I will close this. I do want to say that the plugin assumes a 1 to 1 relationship (more or less) between GitLab projects and Jenkins builds. In my opinion it is not a very good practice to have many GitLab projects triggering one generic Jenkins build. That means that the status of that build is kind of meaningless, and it will always have to be generic. You would really want the status of that build, including tests etc., to be what informs the status of a Merge Request in GitLab. Just my opinion of what the best practice is. If this works for you, that's fine.

**Comment by Bjoern-Hegstam** [comment]
Sorry, but just to clarify, that is exactly what we have setup now. The jenkins build is only used to build all merge request for one gitlab project.

**Comment by ghost** [comment]
I ended up finding that the problem was the "Quiet Period" in Jenkins which by default is 5 seconds. I put it to 1 and the problem went away. Described here: https://github.com/jenkinsci/gitlab-plugin/issues/487
