### ISSUE TITLE
Extension for "Add message only for failed builds"

### ISSUE THREAD

**Issue by sauliusgrigaitis** [jenkinsci/gitlab-plugin#452]
Thanks a lot for resolving #345 !

We started to use Unstable status for builds that passes tests and doesn't pass linters. This is very convenient way to indicate what is wrong with not passing build. So now we need to add message to Gitlab for both Unstable and Failed builds (#345 allows to add message only for Failed builds). 

So would be great to have one of these options:
1) Checkbox "Add message only for failed *and unstable* builds" instead of current "Add message only for failed builds"
2) Two checkboxes "Add message only for failed builds" and "Add message only for unstable builds". Labels need some work, because if both are checked, then "only" words doesn't make sense.

**Comment by omehegan** [comment]
It looks like you're working on a fix, we would be happy to merge it or help with the design if you need it.

**Comment by sauliusgrigaitis** [comment]
Thanks @omehegan, feel free to merge this fix until somebody implements full configurable feature.

**Comment by omehegan** [comment]
@sauliusgrigaitis can you submit it as a PR?

**Comment by omehegan** [comment]
This was released today in version 1.4.8 of the plugin.
