### ISSUE TITLE
Same merge request is built multiple times

### ISSUE THREAD

**Issue by cgumpert** [jenkinsci/gitlab-plugin#456]
## Issue

A Jenkins project is triggered multiple times for the same merge request.

### Context
- **Gitlab plugin version**: 1.4.3
- **Gitlab version**: 8.13.6-ee
- **Jenkins version**: 2.27

### Problem description

Our CI setup consists of a Jenkins master which marshals 13 slave nodes. Our Gitlab project is configured with **two** web hooks to different Jenkins projects (a multi-job project and a normal shell project) which gets triggered on merge request events. The multijob project performs the usual build steps like:
- cmake
- make
- make test

The other project is only there to dynamically assign labels to the merge request (which we use internally for our approval process). The problem I am running into is now that the job assigning the labels runs very quickly (<10s) while the build job runs quite long (~4h). The label update itself is interpreted as _Merge request event_ (because the MR is updated) which in turn leads to another build job being triggered (because the first one for the same commit hash is not yet done).

Is there a way to avoid this behavior? Maybe an option could be added to disable builds for "updated" MR?

**Comment by cgumpert** [comment]
Just to metnion: if #439 were implemented, I would be able to deal with this inside the Jenkins build scripts myself.

**Comment by omehegan** [comment]
This is interesting. From my reading of the code, we only react to the MR webhook if the state is 'opened' or 'reopened,' not 'updated.' Can you follow the README instructions to increase logging, and paste some logs of what Jenkins is seeing when one of these erroneous triggers comes through?
