### ISSUE TITLE
Connect jenkins deploy with gitlab "environments"

### ISSUE THREAD

**Issue by tomfun** [jenkinsci/gitlab-plugin#458]
### Context
- **Gitlab plugin version**: 3.0.0
- **Gitlab version**: 8.13.0-rc4
- **Jenkins version**: 2.30

### Links

https://gitlab.com/help/ci/environments

### Problem description

- I have pipeline and in the end jenkins does deploy the project
- I want to let gitlab know about deploy fact and commit/branch
- I can't find any information how to [use environments](https://gitlab.com/help/ci/environments)

**Comment by omehegan** [comment]
@tomfun GitLab Environments appears to be a feature of GitLab CI, which is not something we support. CI is effectively a competitor to Jenkins. 

I think if you are using Jenkins Pipeline jobs, and you wrap your build steps in gitlabCommitStatus("foo"){} blocks, you may be able to achieve something similar.
