### ISSUE TITLE
Jenkins Pipeline Project Build Triggers reset

### ISSUE THREAD

**Issue by fduranti** [jenkinsci/gitlab-plugin#460]
### Before submitting an issue to I have first:

- [X] read the documentation on the [homepage](https://github.com/jenkinsci/gitlab-plugin) 
- [X] searched for similar already existing issue

## Issue
The Build Triggers: 
- Build when a change is pushed to GitLab. GitLab CI Service URL: https://jenkinsserver/project/jenkins 
get reset after a push to gitlab repository and a run of the the pipeline Jenkinsfile 

### Context
- **Gitlab plugin version**: 1.4.3
- **Gitlab version**: 8.14.3-EE
- **Jenkins version**: 2.19.4

### Logs & Traces
Dec 09, 2016 1:34:09 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/jenkins
Dec 09, 2016 1:34:09 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
jenkins triggered for push.
Dec 09, 2016 1:34:09 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/jenkins
Dec 09, 2016 1:34:09 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
jenkins triggered for push.
Dec 09, 2016 1:34:22 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Dec 09, 2016 1:34:22 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Dec 09, 2016 1:34:22 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Dec 09, 2016 1:34:22 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Dec 09, 2016 1:34:23 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Dec 09, 2016 1:34:24 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Dec 09, 2016 1:34:25 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Dec 09, 2016 1:34:25 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Dec 09, 2016 1:34:26 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Dec 09, 2016 1:34:27 AM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
jenkins #4 completed: SUCCESS

### Problem description

I've configured a pipeline job on jenkins following the instruction for the gitlab-plugin. 
I've configured the Build Triggers and git integration:
![immagine](https://cloud.githubusercontent.com/assets/1173084/21033215/4a9e04a4-bdaf-11e6-9b31-d178fc4b4259.png)
![immagine](https://cloud.githubusercontent.com/assets/1173084/21033258/8b6dfd36-bdaf-11e6-807e-3949fe7191c6.png)

After I push a new build on GitLab (configured with Jenkins CI integration) Jenkins run the build correctly and after the start of the run If i edit the configuration I get the Build Triggers reset so It will not work for a second push or merge or other operation:
![immagine](https://cloud.githubusercontent.com/assets/1173084/21033337/e160cb60-bdaf-11e6-9c6a-ad9e3d3f5a2f.png)

**Comment by fduranti** [comment]
After some testing I discovered where the problem was: 
I was reusing a jenkinsfile from a multibranch pipeline that has the property at the start to set  the gitlabconnection as explained in the readme of the gitlab plugin and it was resetting my normal pipeline job.

> properties([[$class: 'GitLabConnectionProperty', gitLabConnection: '<your-gitlab-connection-name']])

**Comment by stashedUp** [comment]
How did you resolve this problem?
How did you prevent it from resetting?

**Comment by dkder3k** [comment]
@NathanArmstrong84 I resolved this issue by adding `pipelineTriggers` option to properties
Something like this:
`properties([gitLabConnection('<gitlabConnection>'), pipelineTriggers([triggerOnPush: true])])`
If it is still matters :)
