### ISSUE TITLE
Can the gitlab plugin handle the gitlab's pipeline event？

### ISSUE THREAD

**Issue by junguchina** [jenkinsci/gitlab-plugin#461]
### Before submitting an issue to I have first:

- [Yes] read the documentation on the [homepage](https://github.com/jenkinsci/gitlab-plugin) 
- [Yes] searched for similar already existing issue

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

### Context
- **Gitlab plugin version**: 1.4.3
- **Gitlab version**: GitLab Community Edition 8.14.0
- **Jenkins version**: 2.19.3

### Logs & Traces
NA

### Problem description
We want to handle the pipeline events from gitlab webhooks, but the gitlab plugin can not listen the pipeline event.
Does anybody have the same idea?

**Comment by omehegan** [comment]
Under what circumstances would the Pipeline web hook be triggered in GitLab?

**Comment by junguchina** [comment]
@omehegan Our team use gitlab's pipeline to complete continuous integration work,the details:
1.After merge the code into master branch the pipeline of master will auto run.
2.The stage of master's pipeline contains unit test, build, **deploy** and so on.
3.But our e2e test was deployed in jenkins.
4.We want the jenkins can handle the success state of gitlab's pipiline, and this will trigger the jenkins job.
But the gitlab plugin can not handle the pipeline webhooks, so we have this requirement of this issue.
I‘m developing an agent to handle the pipeline of gitlab now,but I think the the gitlab plugin of jenkins should have this feature.

**Comment by omehegan** [comment]
I'll mark it as a feature request, but we currently don't have an active maintainer who could add this. If you would like to submit a PR, we would consider it though!

cc @dblessing

**Comment by valeryq** [comment]
Hello guys. Have you found an active maintainer for add this feature?
It's a very necessary feature, because GitLab team doesn't want develop Webhook for separate GitLab CI pipeline status.
@omehegan

**Comment by omehegan** [comment]
@trance1st @colourmeamused do you have any interest in looking at this?

**Comment by colourmeamused** [comment]
Hi,
Sorry I have been out of action Back now and will have time later this week
to look at this one and other pull requests, just assign me as reviewer for
The ones I should look at first.
Cheers,
Abir aka  @colourmeamused <https://github.com/colourmeamused>

**Comment by valeryq** [comment]
@colourmeamused Can you develop this? Or only review?

**Comment by mreichel** [comment]
Can you take a look at my PR @colourmeamused ?

**Comment by omehegan** [comment]
This was released today in version 1.4.8 of the plugin.

**Comment by faikabouthalja** [comment]
I'am having this issue with GitLab Plugin 1.5.12 , test with pipeline event returns code 200 but no build is launched on Jenkins and when new pipeline event happens I see return code 200 when pipeline is still running but when it finish on success and is supposed to trigger Jenkins Job I get return code 500 and error seems to be in response body: java.lang.NullPointerException: sourceProjectId must not be null.

**Comment by n111ke1** [comment]
The same problem  GitLab Plugin 1.5.13, Please fix this, because i have waiting it almost 1 year!!! 
And i think u know what about this problem, i mean about sourceProjectId...  You had much same issues and this wasnt fix... Sooo pleasse guys be cool!

**Comment by omehegan** [comment]
@n111ke1 if this feature is no longer working, please open a new issue for it so we can track it accordingly.
