### ISSUE TITLE
Access to files changes in Pipeline

### ISSUE THREAD

**Issue by vramanlal** [jenkinsci/gitlab-plugin#463]
Hi 

We are using the gitlab-plugin with Jenkins pipeline.
When we use check scm a bunch of enviroment variables are set and we can access these as follows:

def branch = env.gitlabBranch 
def mergeId = env.gitlabMergeRequestId

What we also what to have access to is the list of files that have been added, updated or deleted.  How can we get access to these?

**Comment by omehegan** [comment]
You can try using the env.gitlabBefore and env.gitlabAfter variables. Then you would need to use a shell command to perform a 'git diff,' get that into another variable, and go on from there. Not the most convenient thing, but I don't think GitLab sends this information in a more direct way.
