### ISSUE TITLE
client error: null when attempting to use Gitlab API token in system configuration.

### ISSUE THREAD

**Issue by markfaine** [jenkinsci/gitlab-plugin#464]
### Context
- **Gitlab plugin version**: 1.4.3
- **Gitlab version**: GitLab Community Edition 8.14.3
- **Jenkins version**: 2.3.6
- **Job type**: Freestyle/NA

### Logs & Traces
Dec 13, 2016 11:47:53 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Call GitLab:
HTTP method: HEAD
URL: https://my.gitlab.server:8443/api/v3/user
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]

### Problem description

Attempting to configure integration with GitLab to allow for Jenkins notification upon commit.  Chose credential and pressed "Test Connection"
Expected "Success"
Got message: Client error: null

There seems to be no way to actually see what is going on under the hood.   I believe I have eliminated proxy issues and SSL issues as a possible cause but have no where to go from here.

**Comment by omehegan** [comment]
Can you elaborate on where you were attempting to do this? In the Jenkins global configuration, GitLab section?

**Comment by markfaine** [comment]
Yes, exactly.  In the global configuration for GitLab.

**Comment by AndreaCrotti** [comment]
I had a Null pointer exception as well today, but I could see the whole stacktrace.
However I think it was just a wrong token, or at least I can't reproduce it anymore..
@markfaine make sure the token is correct and give it another try.
(It's strange though however since I also got a 401 when it was wrong another time so not 100% sure it's just that really)

**Comment by markfaine** [comment]
I have an update on this.  

Seems to be caused by:
https://issues.jenkins-ci.org/browse/JENKINS-31464

After setting values for no proxy in manage plugins proxy settings, I was able to get a success response.

**Comment by omehegan** [comment]
Not a plugin bug.
