### ISSUE TITLE
Access Build ID from gitlab

### ISSUE THREAD

**Issue by samskiter** [jenkinsci/gitlab-plugin#467]
## Issue
It would be great if we could access the build ID presented in the gitlab interface from our jenkins jobs. I realize this would probably only be available inside a `gitlabCommitStatus` block (as that creates a build ID on gitlab). This would mean gitlab can become a central authority on build numbers

### Context
- **Gitlab plugin version**: 1.4.3
- **Gitlab version**: 8.14.x
- **Jenkins version**: 2.19.3
- **Job type**: Pipeline

**Comment by omehegan** [comment]
I understand the desire for this, but if you make GitLab the central authority for build numbers (I assume you would like GitLab and Jenkins to have matching ones), what happens when someone runs the Jenkins build manually?

**Comment by samskiter** [comment]
Good point - you could disallow manual build and try and comment on a
commit in gitlab?.... :/

On Sat, 17 Dec 2016 at 06:00 Owen Mehegan <notifications@github.com> wrote:

I understand the desire for this, but if you make GitLab the central
authority for build numbers (I assume you would like GitLab and Jenkins to
have matching ones), what happens when someone runs the Jenkins build
manually?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jenkinsci/gitlab-plugin/issues/467#issuecomment-267745509>,
or mute the thread
