### ISSUE TITLE
Plugin should support ci-skip in opened MR comments

### ISSUE THREAD

**Issue by tomachi** [jenkinsci/gitlab-plugin#468]
## Issue
We open a merge request which makes a trigger to automation tests in jenkins.
If automation fails we comment back into the MR. This will trigger a new build and continue in a loop.

### Context
- **Gitlab plugin version**: 1.4.3
- **Gitlab version**: GitLab Enterprise Edition 8.14.4-ee 8c04d01
- **Jenkins version**: 1.650
- **Job type**: Freestyle

**Comment by omehegan** [comment]
As far as I know, the MR hook should only trigger a build when:
- the MR is created
- there is a push to the MR branch
- if you check Comments and enter a string in the associated text box, it will trigger when a matching comment is posted

Can you screenshot your trigger configuration for a job and send it, so I can see exactly what you are doing?

**Comment by tomachi** [comment]
Thanks @omehegan for the answer.
Yes, we are pushing the new build version on each build, even if it fails, but we do it with [ci-skip]. From looking at the source code the ci-skip is ignored in MR push, What makes a new trigger if ci-skip is in the comment.

**Comment by omehegan** [comment]
I just want to be sure I understand: when you use the word 'comment,' are you talking about the message you submit with a change in git? In other words, you push a change to the branch with [ci-skip] in the commit message? Or are you talking about a comment on the merge request UI in GitLab?

**Comment by tomachi** [comment]
Sorry,

I meant commit message.

**Comment by omehegan** [comment]
I've reviewed the code, and from what I can see, it should skip the build if the following conditions are met:
* A push webhook is configured, not just a merge request hook
* The newest commit in the push contains the string '[ci-skip]' - note the brackets and hyphen

If that is not working for you, I would need to test and see if I can replicate.

**Comment by tomachi** [comment]
But if I'll add a push hook it will trigger on every push where I need it only for MR.

**Comment by omehegan** [comment]
This was released in version 1.5.9 of the plugin.
