### ISSUE TITLE
Exclude 

### ISSUE THREAD

**Issue by idokaplan** [jenkinsci/gitlab-plugin#469]
Hi,

Is it possible to exclude files/folder when initiate a merge request?

Thanks!
Ido

**Comment by omehegan** [comment]
Can you explain what you are asking for in more detail, maybe with an example? Thanks.

**Comment by idokaplan** [comment]
I'm using SaltStack for the deployment and using branches (dev, qa, prod, etc).
Each branch (environment) contain 2 folders - state and pillar.

I would like to merge from dev branch to qa only the state folder (without the pillar folder).

Ido

**Comment by omehegan** [comment]
This is really just a Git question, it's nothing to do with this plugin. But a Git merge is just combining a set of changes to files. If you change files in the 'pillar' folder in a branch, it would not make sense to then merge that branch into another but exclude those changes.
