### ISSUE TITLE
Building merge requests only builds closed merge requests

### ISSUE THREAD

**Issue by AndreaCrotti** [jenkinsci/gitlab-plugin#482]
## Issue

Conflicting state of build status seen.

### Context
- **Gitlab plugin version**: 1.4.3
- **Gitlab version**: 8.14.1 e45bf3d
- **Jenkins version**: 2.19.4
- **Job type**: Freestyle.

### Problem description

I was trying to split between merge requests and pushes into master into separate jobs.
For the merge request job I just configure it as in the picture attached:
![selection_018](https://cloud.githubusercontent.com/assets/53640/21770378/ebac7f04-d67a-11e6-964b-1638890df600.png)

the problem is that if I do a merge request with a certain branch it seems to work and Jenkins reports back information to gitlab, *but* it's not building the right branches!
It builds other already closed merge requests that have not been touched maybe for a while and have nothing to do with the latest MR..
Is that a known issue maybe?

The hook in the gitlab side is also configured very simply as attached.

**Comment by omehegan** [comment]
I would need to see how you have the git checkout configured, to see what Jenkins will actually do when you trigger this job.

**Comment by AndreaCrotti** [comment]
Mm I think the problem was just related to multiple builds for the same commit generally, which is something that messes it up as seen from another issue as well.

However another very weird thing I see is that if I have a job that builds only merge requests, if I kick the build *manually* it will go and build all the *already closed* merge requests.

So it gets mental with many branches.. Is that desired? I can't really see an option to discard closed merge requests here:
![selection_024](https://cloud.githubusercontent.com/assets/53640/21897503/ac2e15b8-d8e1-11e6-9bc0-65bc74de6939.png)
