### ISSUE TITLE
Build pending if two pushes in very short interval of time

### ISSUE THREAD

**Issue by mhagnumdw** [jenkinsci/gitlab-plugin#487]
## Issue
When making two pushes in a very short interval of time, the second commit is eternally with pending build status.

### Context
- **Gitlab plugin version**: 1.4.4
- **Gitlab version**: 8.7.2
- **Jenkins version**: 2.19.3
- **Job type**: Maven project

### Logs & Traces

[GitLab_Jenkins_Plugin.log.txt](https://github.com/jenkinsci/gitlab-plugin/files/712693/GitLab_Jenkins_Plugin.log.txt)

The above log only refers to the execution of git commands described below.

### Problem description

Perform two pushes in sequence:
`echo '<!-- 1 -->' >> pom.xml && git add pom.xml && git commit -m "Test - Push 1" && git push && echo '<!-- 2 -->' >> pom.xml && git add pom.xml && git commit -m "Test - Push 2" && git push`

And the second commit is **eternally pending build status**:
![status_build](https://cloud.githubusercontent.com/assets/17688846/22045838/928766f0-dcfb-11e6-8118-25525cea1199.PNG)

Test - Push 1: 501c1a0d97b80c33313e99fe1335e3dd11dd8cce
Test - Push 2: 7bc71f7add0dff01cc1c03aa64201a998c2235e8

Any idea?
In advance, thank you for your attention!

**Comment by omehegan** [comment]
Duplicated by #489 and we have a bit more detail there.

**Comment by mhagnumdw** [comment]
Resolution issue #489 did not solve my problem. I ended up finding that the problem was the "Quiet Period" in Jenkins which by default is 5 seconds. I put it to 0 and the problem went away.
