### ISSUE TITLE
"Pending" commit status is never updated, instead new status is created

### ISSUE THREAD

**Issue by Bjoern-Hegstam** [jenkinsci/gitlab-plugin#489]
### Context

- **Gitlab plugin version**: 1.4.0
- **Gitlab version**: 8.15.4-ee
- **Jenkins version**: 1.650

### Logs & Traces

target_url when creating "pending" status:
```json
"target_url" : "https://server:443/jenkins/job/GitlabMergeRequests/25"
```
target_url when creating/updating "running" status:
```json
"target_url" : "https://server:443/jenkins/job/GitlabMergeRequests/25/"
```

### Problem description

We have a jenkins job setup to build all merge requests (triggered via a gitlab webhook with the GitLab CI Service URL). The job also has the post-build steps **Publish build status to gitLab commit** and **Add note with build status on GitLab merge requests**. This is working very well, except that for every build a "pending" commit status is left behind. The "pending" status is created at the start of the build, but once the build starts a new commit status with status "running". That commit status is then updated with the result of the build once it finishes.

I looked through the logs and think the problem is that the `target_url` has a trailing slash when creating/updating the second status, but when the initial "pending" status is created there is no such trailing slash.

**Comment by Bjoern-Hegstam** [comment]
Looking over existing issues (which I should have done a better job of before hand, sorry) it seems to me like this could be the same reason for issues #487 and #478.

**Comment by trydis** [comment]
Same issue here with:
* Gitlab plugin version: 1.4.2
* Gitlab version: 8.16.1-ce
* Jenkins version: 2.24

All builds that are marked as pending in GitLab does not have a trailing slash, the ones marked as passed have a trailing slash.

**Comment by sgautrin** [comment]
I checked (I posted other details in #478) and I also see the same thing with the trailing slash: not present in the response to the first POST to gitlab (which results in the pending build), present in the other two (which results in the build which starts as “in progress” and then is updated to “complete”).

For memory, tools versions:

* jenkins 2.40
* gitlab 8.15.0 (54850bf)
* gitlab-plugin 1.4.4

**Comment by AlexGreg** [comment]
Same issue here

**Comment by sgautrin** [comment]
I can confirm that after updating the plugin, it fixed the issue for me.

**Comment by Bjoern-Hegstam** [comment]
I can also confirm that the update fixed our issue. Thank you very much!
