### ISSUE TITLE
GitLab plugin should support Folders

### ISSUE THREAD

**Issue by eriklogtenberg** [jenkinsci/gitlab-plugin#490]
### Context
- **Gitlab plugin version**: current
- **Gitlab version**: current
- **Jenkins version**: 2.41.1
- **Job type**: Multibranch

### Problem description
GitLab plugin provides Webhook targets for GitLab to trigger builds. These URL's only support projects that are located at the "root" of Jenkins. The documentation says:
> Unlike other job types, there is no 'Trigger' setting required for a Multibranch job configuration; just create a webhook in GitLab for push requests which points to http://JENKINS_URL/project/PROJECT_NAME

However, there is no syntax for a project that is inside a Folder. The URL should be something like https://JENKINS_URL/project/FOLDER_NAME/PROJECT_NAME but currently that doesn't seem to be implemented. In fact, Folders can also be nested so there should be support for multiple levels of Folders.

**Comment by omehegan** [comment]
Saying "current" doesn't help us a few months from now when we don't know what versions of this plugin or GitLab were "current" right now. Please include the specific versions you are using.

**Comment by eriklogtenberg** [comment]
Gitlab version: gitlab-ce-8.15.5-ce.0.el7.x86_64
Jenkins version: jenkins-2.44-1.1.noarch
Gitlab plugin version: 1.4.4

**Comment by wingedfox** [comment]
Have the same issue, +1
Gitlab: 8.16.3 d225908
Jenkins: 2.19.1
Gitlab plugin: 1.4.4

**Comment by jgeorgeson** [comment]
This is working for me for Push events.

GitLab: 8.16.5 
Jenkins: 2.47
GitLab Plugin: 1.4.4

The Web Hook URL has the job folder and name in it: http://server.example.com:8080/project/folder/job. I have not setup Merge Request events yet.

**Comment by omehegan** [comment]
@jgeorgeson what type of job are you successfully able to trigger within folders?

**Comment by wingedfox** [comment]
I can confirm, upgrade to Jenkins 2.47 fixes the problem.
FreeStyle jobs are running pretty well now for all kind of events.

**Comment by jgeorgeson** [comment]
@omehegan I have Pipeline (regular, not multibranch) jobs.

**Comment by omehegan** [comment]
@eriklogtenberg can you verify that Jenkins 2.47 works for you with Multibranch jobs now?

**Comment by jgeorgeson** [comment]
Adding another working combination that's working for me:

Jenkins 2.32.3
Plugin 1.4.5
GitLab 8.16.7
Standard Pipeline job.

**Comment by omehegan** [comment]
Closing as seems to be resolved for others.
