### ISSUE TITLE
Filter branches by name

### ISSUE THREAD

**Issue by hos7ein** [jenkinsci/gitlab-plugin#492]
### Context
- **Gitlab plugin version**: 1.4.4
- **Gitlab version**: 8.16.3
- **Jenkins version**: 2.32.1-1.1
- **Job type**: Filter branches by name

### Problem description

how can use "Filter branches by name " by gitlab plugin on jenkins?
when i write " */master,*/dev " on "Include" box,show me this massege :

> Following patterns don't match any branch in source repository: */master, */dev

http://s1.picofile.com/file/8284122976/gitlab.png

how can determination branch ?

tnx

**Comment by hos7ein** [comment]
hi
my problem is solved :) 
in "Filter branches by name " box just must be write branch name whitout */ 
(master,dev)

**Comment by nerffei** [comment]
@hos7ein  i can't understand what you say,  I got the same problem. I have tried /*(master) , (master), master. there are not work :(

**Comment by hos7ein** [comment]
@Pipikachu look at the below picture : 
http://s9.picofile.com/file/8292321584/git_branch.png

**Comment by ethyaan** [comment]
I have the same issue here

**Comment by hos7ein** [comment]
hi @ehsanagh 
look at this link : 
http://s9.picofile.com/file/8292321584/git_branch.png

**Comment by ethyaan** [comment]
Hi, I have the same issue, 
please  look here.
https://ibb.co/iuUk2F

**Comment by hos7ein** [comment]
don't worry @ehsanagh , it's okay and working :)

**Comment by ethyaan** [comment]
so it means that errors  comes without any specific reason, am I right?

**Comment by ethyaan** [comment]
I'm using regex instead of this, that works fine.

**Comment by dayanstef** [comment]
Just type the name without */ in filter by branch name

The warning stays but it works without problem

**Comment by aemonge** [comment]
Does any one knows how to filter by branch name using the plugin thought a jenkinsFIle ?

**Comment by feengqi** [comment]
I have the same problem with you, I have no way to solve it，I'm using regex instead of this, that works fine.

**Comment by aemonge** [comment]
I know... the regex can work. but it triggers tons of Jenkins-Slaves just because xD
