### ISSUE TITLE
Comment to trigger build triggers for all comments

### ISSUE THREAD

**Issue by samskiter** [jenkinsci/gitlab-plugin#493]
## Issue

We have our trigger set to build when we comment "ci retry" on a merge request, but EVERY comment seems to trigger a build, including checking text boxes or adding/removing the WIP label.

### Context
- **Gitlab plugin version**: 1.4.4
- **Gitlab version**: 8.16.1
- **Jenkins version**: 2.32.1
- **Job type**: Pipeline

**Comment by omehegan** [comment]
Please attach some logs, following the instructions in the User Support section of the README. That will help us see what exactly is triggering the builds.

**Comment by Dmitry-SigmaSW** [comment]
Hi. The issue is still actual. Any comment on any language triggers a job. Can I get some help?
