### ISSUE TITLE
How to clear the secure token in build triggers?

### ISSUE THREAD

**Issue by abcfy2** [jenkinsci/gitlab-plugin#496]
![image](https://cloud.githubusercontent.com/assets/5327677/22616544/9710a6fe-eae9-11e6-95a0-ac0a8f69f16d.png)

I can't find the way to clear this secure token.

**Comment by omehegan** [comment]
Ooh. That is a bug! Thanks for noticing.

If you need to clear it, for now I suspect you are going to have to edit your job's config.xml on the filesystem to remove it, and then run 'Reload Configuration fro Disk' from the Manage Jenkins page.

**Comment by abcfy2** [comment]
Thanks.

**Comment by omehegan** [comment]
This was released today in version 1.4.6 of the plugin.
