### ISSUE TITLE
Feature Request: Build Log Snippet on MR Comment

### ISSUE THREAD

**Issue by jharshman** [jenkinsci/gitlab-plugin#500]
### Context
- **Gitlab plugin version**: 1.4.0
- **Gitlab version**: 8.16.4
- **Jenkins version**: 1.17
- **Job type**: Any

### Problem description

On a Merge Request, particularly during a long build where multiple cases can fail the build, I would like to be able to have Jenkins include not only a comment with the build status, but also include a small formatted log snippet to highlight exactly where it failed without having to navigate to the console output within Jenkins.

Interestingly enough, a plugin called build_name_setter implements this as an environment variable where you can specify a pattern to match against and include a certain amount of lines above and below the matched pattern.

i.e: `${BUILD_LOG_REGEX regex="FATAL", linesBefore="4", linesAfter="2"}`

I personally don't see the value of setting the build name to anything from the logs, but in the case of Jenkins making a comment on a Merge Request with this information, I can see great value.

**Comment by omehegan** [comment]
I think this feature request is probably outside the scope of our plugin. It's getting into providing an interface for the user to define this pattern we will match, and then scraping the logs after every build. This doesn't have anything to do with triggering builds and reporting basic status.

If you used Pipeline jobs, you could hack this together relatively easily with some Groovy or shell commands to grep the console log. Then use the addGitLabMRComment step to send it to the MR. I suspect this will only work with MR triggered jobs, not push-triggered ones.

addGitLabMRComment comment: 'This is my comment!'

**Comment by jharshman** [comment]
Well, not all workflows conform easily into Pipeline workflows.  Furthermore, often in production ecosystems, builds are executed on Jenkins slaves with their logs being stored on the master.  Hacking together some groovy code to read this would need to execute on the master or have access to some sort of shared storage in order to read the log.

So the only solution would be __IF__ working with a pipeline workflow you could just catch the error and then `addGitLabMRComment comment: 'failed foo'`.

My opinion is that if it can be solved cleanly in the plugin, that is a better solution that adding extra bash or groovy to every single job I want this feature on when it could be as simple as specifying a custom template with an environment variable.
