### ISSUE TITLE
Retry on failed merge request

### ISSUE THREAD

**Issue by asyncwise** [jenkinsci/gitlab-plugin#507]
## Issue
It's possible to be failed for building because of the reason regardless of commit, like timeout.
I couldn't find any way to retry for the failed building anywhere.
And I found this: https://gitlab.com/gitlab-org/gitlab-ce/issues/13738.
It looks there's a way to make it.

### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: CE 8.16.4
- **Jenkins version**: 2.32.2
- **Job type**: Freestyle

### Logs & Traces

None

### Problem description

None

**Comment by omehegan** [comment]
IMO this feature should not be implemented in the GitLab plugin. The appropriate places are either in GitLab itself, as in the issue you linked to (open feature request on their end), or in a separate Jenkins plugin, such as Naginator: https://plugins.jenkins.io/naginator
