### ISSUE TITLE
GitlabUpdateCommitStatus creates sometimes two builds in Gitlab

### ISSUE THREAD

**Issue by pgeorgiev333** [jenkinsci/gitlab-plugin#511]
### Before submitting an issue I have first:

- [x] read the documentation on the [homepage](https://github.com/jenkinsci/gitlab-plugin) 
- [x] searched for similar already existing issue

## Issue
Incorrect update of the gitlab commit from jenkins multibranch pipeline

### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: GitLab Community Edition 8.11.2 
- **Jenkins version**: 2.4.7
- **Job type**: Pipeline (Multi-Branch)

### Problem description
I have a Gitlab Server configured with a webhook for push events that triggers a multibranch jenkins pipeline. The pipeline updates the gitlab commit status with just one build/stage. In most cases everything is ok but sometimes i see two builds in Gitlab that point to the same jenkins job and the overall state is IN PROGRESS although the job has passed

Here's the relevant part of the pipeline:

        gitlabBuilds(builds: ['Jenkins Pipeline']) {

            gitlabCommitStatus(name: 'Jenkins Pipeline') {

                executeTestsStageHelper(pipelineConfigurationJson)

            }
        }

Attach is a screenshot of one problematic commit:
![gitlabcommitstatus](https://cloud.githubusercontent.com/assets/16955574/23164812/b6d68a5c-f841-11e6-8aa0-4cae67985fee.png)

Both builds in the screenshot refer to the same jenkins build. Another thing to note is that all commits are merges (i,e, this is the master branch and all commits are related to merging a branch in the master branch)

**Comment by omehegan** [comment]
Can you give the correct version of the gitlab-plugin? There is no 3.05 version. 1.4.5 is the latest, released last week.

**Comment by pgeorgiev333** [comment]
Updated - it's 1.4.5

**Comment by omehegan** [comment]
Hmm. I haven't seen this reported before. I did just notice something about your Pipeline code snippet - you don't need to use the gitlabBuilds block if there is only one stage within the build that is going to send status to GitLab. You can simply wrap that one step of the build in the gitlabCommitStatus block. This is how I do my builds. I wonder if this might be causing a problem. If I'm understanding your setup correctly, I would suggest you try removing the gitlabBuilds block and see if the problem goes away.

**Comment by pgeorgiev333** [comment]
I removed and i still see the issue.  The difference is that now i do not see "running" on the overall commits page which is better. This is what i see now sometimes:
![gitlabcommitstatus2](https://cloud.githubusercontent.com/assets/16955574/23302154/3b6468c4-fa96-11e6-886b-bb7e069c52c7.png)

**Comment by omehegan** [comment]
@pgeorgiev333 did you ever resolve this?

**Comment by pgeorgiev333** [comment]
No. I switched to a different approach. Now i just use  
`updateGitlabCommitStatus(name: 'Build and Test', state: 'failed')` and it works fine.

**Comment by omehegan** [comment]
Do you think we need to update the documentation to make this clearer?

**Comment by pgeorgiev333** [comment]
Well, what i am using is just a different approach. Both should work
