### ISSUE TITLE
Trigger build remotely throw 404

### ISSUE THREAD

**Issue by rroblik** [jenkinsci/gitlab-plugin#513]
### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 2.47
- **Jenkins version**: 2.47
- **Job type**: Freestyle

### Logs & Traces

```
févr. 23, 2017 2:52:41 PM INFOS com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving gitlab project ids

févr. 23, 2017 2:52:41 PM INFOS com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving the gitlab project id from remote url https://myrepository/macheb/ci.git

févr. 23, 2017 2:52:41 PM LE PLUS PRÉCIS com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: GET
URL: https://myrepository/api/v3/projects/macheb%2Fci/repository/commits/70ecddc317affe1e70a9a55bf24f873469ec97c5
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]

févr. 23, 2017 2:52:41 PM LE PLUS PRÉCIS com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://myrepository/api/v3/projects/macheb%2Fci/repository/commits/70ecddc317affe1e70a9a55bf24f873469ec97c5
Status: 404 Not Found
Response headers: [
Connection = [Keep-Alive],
Content-Length = [377],
Content-Type = [text/html; charset=iso-8859-1],
Date = [Thu, 23 Feb 2017 13:52:41 GMT],
Keep-Alive = [timeout=5, max=100],
Server = [Apache/2.2.22 (Debian)],
Vary = [Accept-Encoding]
]
Response body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/v3/projects/macheb/ci/repository/commits/70ecddc317affe1e70a9a55bf24f873469ec97c5 was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Debian) Server at myrepository Port 443</address>
</body></html>

févr. 23, 2017 2:52:41 PM PRÉCIS com.dabsquared.gitlabjenkins.util.CommitStatusUpdater

Project (macheb/ci) and commit (70ecddc317affe1e70a9a55bf24f873469ec97c5) combination not found

févr. 23, 2017 2:52:41 PM INFOS com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving gitlab project ids

févr. 23, 2017 2:52:41 PM INFOS com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving the gitlab project id from remote url https://myrepository/macheb/ci.git

févr. 23, 2017 2:52:41 PM LE PLUS PRÉCIS com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: GET
URL: https://myrepository/api/v3/projects/macheb%2Fci/repository/commits/70ecddc317affe1e70a9a55bf24f873469ec97c5
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]

févr. 23, 2017 2:52:41 PM LE PLUS PRÉCIS com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://myrepository/api/v3/projects/macheb%2Fci/repository/commits/70ecddc317affe1e70a9a55bf24f873469ec97c5
Status: 404 Not Found
Response headers: [
Connection = [Keep-Alive],
Content-Length = [377],
Content-Type = [text/html; charset=iso-8859-1],
Date = [Thu, 23 Feb 2017 13:52:41 GMT],
Keep-Alive = [timeout=5, max=99],
Server = [Apache/2.2.22 (Debian)],
Vary = [Accept-Encoding]
]
Response body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/v3/projects/macheb/ci/repository/commits/70ecddc317affe1e70a9a55bf24f873469ec97c5 was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Debian) Server at myrepository Port 443</address>
</body></html>

févr. 23, 2017 2:52:41 PM PRÉCIS com.dabsquared.gitlabjenkins.util.CommitStatusUpdater

Project (macheb/ci) and commit (70ecddc317affe1e70a9a55bf24f873469ec97c5) combination not found

```

### Problem description

Hi all,

I try to manually trigger a job within a gitlab `post-receive` hook calling a simple shell script :
```bash
#!/bin/bash

while read oldrev newrev refname
	branch=$(git rev-parse --symbolic --abbrev-ref $refname)
        # do stuff
	curl -v -X POST --user USER:NAME --data "token=test" https://myjenkins.net/job/test_gitlab/build
done
```

But as you can see in the log posted above... build status is success on Jenkins side, but the gitlab plugin log show me 404 errors :( 

NOte : If I choose `Build when a change is pushed to GitLab. GitLab CI Service UR` the build working fine (One webhook enabled on Gitlab side) without 404 errors BUT I'm trying to trigger build remotely to have only one (maybe parametrized) Jenkins job that can build commits on many repo in near future.

Am I missing something ? Some `curl` parameter ? Some ``gitlab-plugin` configuration ?

Regards

**Comment by omehegan** [comment]
First, I really don't recommend the practice of having one Jenkins job which builds code from many git repos. The best practice is to have a 1:1 mapping of jobs to repos (or possibly many:one if you want to build a few different things from one repo). In your case this post-receive trigger is not going to send the GitLab plugin any of the information it expects for the build, whereas if you use the GitLab webhook as designed, it will POST a JSON object for the plugin to use.

I'm not positive as to why you would see 404s in your test. Do you also get 404s if you manually run the build? I notice that the plugin is trying to access 'URL: https://myrepository/api/v3/projects/macheb%2Fci/repository/commits/70ecddc317affe1e70a9a55bf24f873469ec97c5'  %2F is the URL encoding for a forward slash. That should actually just be a / character; I just tried something similar just viewing a page in my GitLab server, and if I use the %2F I get a 404.

**Comment by rroblik** [comment]
Thanks for answering !

My idea is to call a kind of wrapper Jenkins job that will in turn call a specific one, based on parameters (no parameter except token in my example). 

But for now I need to know why plugin replace "/" by "%2F" ; I used "/" in git repository Jenkins configuration, as my repository is namespaced (‘username/projectname.git‘). 

Nb : I try to use "manual" job triggering to add some message directly on user console when pushing to repo. 

Any idea ?

Regards

**Comment by omehegan** [comment]
I understand, but I maintain that it's not a good practice to use a wrapper Jenkins job to call all your other jobs. It just adds a level of indirection between GitLab and Jenkins which should not be necessary, and which is likely to limit you and/or cause problems. 

It's not clear from your reply if the job works OK if you trigger it manually by clicking the button in the UI. If that works, and triggering it from a GitLab webhook works, then I have to assume that there is something unexpected happening when you try to trigger it using your curl post-receive hook.

**Comment by jamroks** [comment]
Hello, 
I'm having the same issue here :
Jenkins 2.46.2 ( long term support)
Gitlab 9.1
the setup is as follow: 
1 vm with Jenkins inside a docker container 
1 vm with gitlab inside a docker container 
1 vm with traefik inside a docker container

everything works well except for the 404 I get when I setup the webhook url  and click "test" on gitlab side.

**Comment by omehegan** [comment]
@jamroks please attach logs (look at the User Support section of the README) and also note what URL you are using in your GitLab webhook to trigger the job.
