### ISSUE TITLE
Is it possible to filter branches by owner

### ISSUE THREAD

**Issue by NagarajMasub** [jenkinsci/gitlab-plugin#517]
I am using gitlab in our company, we have number of branches,  I need to delete my own branches alone.

is it possible to filter the branches by owner? or created by me alone.

Thanks in advance.
Regards,
Nagaraj M.

**Comment by omehegan** [comment]
This sounds like a GitLab question, not a question about the Jenkins plugin. Deleting branches is just a matter of Git usage. Please explain further if you think I am misunderstanding.
