### ISSUE TITLE
Status pending build status not available for pipeline jobs

### ISSUE THREAD

**Issue by czoellin** [jenkinsci/gitlab-plugin#520]
### Context
- **Gitlab plugin version**: 1.4.6
- **Gitlab version**: 8.16.1
- **Jenkins version**: 2.45
- **Job type**: Pipeline

### Problem Description

The immediate pending status is hard-coded to reference the gitlab build status publisher.
However, the publisher cannot be added for pipeline jobs when the pipeline is from a file in the repository.

For merge request jobs, it would be nice to have an immediate pending status, otherwise jobs can look OK even though they are already queued and will ultimately fail.

I've added an advanced option to supply a build name and force the pending build status. While this is a kludge, I really don't see any other way.
Please let me know if you want me to submit a pull request for the advanced configuration option.

**Comment by omehegan** [comment]
@czoellin a PR would be good, I don't fully understand the problem as you describe it. Maybe we can make your fix less hacky with some review :)
