### ISSUE TITLE
Build result sent to Pipeline library repo instead of project repo after upgrading workflow-multibranch-plugin to 2.13

### ISSUE THREAD

**Issue by pgeorgiev333** [jenkinsci/gitlab-plugin#523]
## Issue

https://issues.jenkins-ci.org/browse/JENKINS-42535 

This is the issue i submitted for the multibranch plugin. Unfortunately no one has commented on it. 

### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 8.11.2 (community edition)
- **Jenkins version**: 2.32.3
- **Job type**: Multi-Branch Pipeline

### Logs & Traces

```
Retrieving the gitlab project id from remote url https://gitlab server 1/myusername/pipeline-shared-library.git
Mar 07, 2017 1:38:49 PM FINE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater
Project (myusername/pipeline-shared-library) and commit (af88dcda9dc5e6a2eb06c563e6ec410b191893d6) combination not found
```

### Problem description

This is the link to the suspected pipeline defect:

https://issues.jenkins-ci.org/browse/JENKINS-33273

This defect makes some changes to the changelog so this may affect the gitlab plugin. Not sure where the fix should be...

And This is a copy paste from the pipeline defect:

> 
> I have a setup where a gitlab commit will trigger via webhook a jenkins Multi-Branch pipeline. The pipeline uses the CPS library, i.e. the Jenkinsfile starts like this:
>  
> @Library('mylib@master')
> import ....
> import ....
>  
> When the pipeline is triggered it checks out the library from a git repo. So we have several checkouts:
> Checkout the repository that contains the code to build (the webhook trigger) to read the Jenkinsfile (gitlab server 1)
> After the Jenkinsfile is parsed the repository that contains the library is checked out (gitlab server 2)
> Inside the pipeline i checkout the main repository one more time to build it (gitlab server 1)
> With Pipeline: Multibranch vesion 2.12 the gitlab commit status was updated correctly - i have a code similar to this in the pipeline: 
> gitlabCommitStatus(name: 'Build Repository') {
> ......
> }
>  
> However after i updated Pipeline: Multibranch to  version 2.13 and restarted jenkins the commits in GitLab are no longer updated. In the jenkins logs i see this:
>  
> Retrieving the gitlab project id from remote url https://gitlab server 1/myusername/pipeline-shared-library.git
> Mar 07, 2017 1:38:49 PM FINE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater
> Project (myusername/pipeline-shared-library) and commit (af88dcda9dc5e6a2eb06c563e6ec410b191893d6) combination not found
>  
> 'pipeline-shared-library.git' is the repo that contains the pipeline cps library, but it is located on the gitlab server 2 not the gitlab server 1 (that's why the repo + commit combinations cannot be found in the message above). Just to note that af88dcda9dc5e6a2eb06c563e6ec410b191893d6 is the last commit id in the pipeline-shared-library.git repo.
> Teh main problem is that this is the wrong commit/repo to update .... 
> I think this is somehow related to Jenkins-33273  but i'm not sure.

**Comment by chizmeeple** [comment]
I believe we are seeing similar behaviour in our setup.

We had working jenkins->gitlab notifications for build.commit status.

This week we've been trying to work out why we're not seeing any updates, and looking at the logs we are (also) seeing:

```
POST /api/v3/projects/«global library»/statuses/«Commit SHA»
```

We've tried scoping at all various levels.
We've tried the newer `pipeline { ... }` syntax.

Nothing.

The *only* time we see the _correct_ request in the gitlab logs is if we completely remove the:

```
@Library('Acme') _
```

statement from the Jenkinsfile.

We're seeing this with `2.13` and `2.14` versions of "Pipeline: Multibranch" (https://plugins.jenkins.io/workflow-multibranch).
Downgrading to `2.12` is non-trivial (i.e. not offered by the UI) so we've been unable to test this downgrade.

**Comment by chizmeeple** [comment]
Downgraded to `2.12`.
Correct URI seen in gitlab's nginx logs.

**Comment by chizmeeple** [comment]
```
cd /var/lib/jenkins/plugins/

# remove existing
mkdir ~/plugins
sudo mv workflow-multibranch* ~/plugins

# grab older plugin
sudo -u jenkins curl -OL http://updates.jenkins-ci.org/download/plugins/workflow-multibranch/2.12/workflow-multibranch.hpi
# then restart jenkins
```

**Comment by 0megam** [comment]
~~Downgrade doesn't help. Still having same issue. gitLab plugin trying to update commit in @Library git repo. GitLab plugin 1.4.5, Pipeline Multibranch 2.12~~
Update: Downgrading works.

**Comment by pgeorgiev333** [comment]
Downgrading works for me. However after doing this my git changelog got messed up (each build reports some of the old commits as new changes...) and i just delete the mulribranch pipeline and re-created it. But with Multibranch 2.12 my gitlab is updated correctly.

**Comment by pcornelissen** [comment]
I have the same problem. I'm also using the multibranch jenkinspipeline plugin and in the production log I see things like:

```
Started GET "/api/v3/projects/kulinariweb%2Fjenkinspipeline/repository/commits/dfce57344e5fdae6f0f9c7caf00ecXXXXXX4a" for 88.XX.YY.136 at 2017-03-20 06:30:44 +0100
Started POST "/api/v3/projects/kulinariweb%2Fjenkinspipeline/statuses/dfce57344e5fdae6f0f9c7caf00ecb9d0XXXXXXXXXX4a" for 88.XX.YY.136 at 2017-03-20 06:30:44 +0100
```

I have found no way to provide the correct gitlab project somewhere. I tried
`properties([gitLabConnection('gitlab'), [$class: 'GitlabLogoProperty', repositoryName: "${params.GITLAB_PROJECT}/${params.GITLAB_NAME}"]])`

But I'm having trouble to define the project and name globally so I don't have to pass it around everywhere. :-/

**Comment by marius-balteanu** [comment]
Same problem here using Jenkins Multibranch 2.14 and GitLab plugin 1.4.5.

**Comment by marius-balteanu** [comment]
I can confirm that downgrading the Multibranch plugin to 2.12 fixes the issue.

**Comment by hubermi** [comment]
Same problem here with Multibranch 2.14 and Gitlab plugin 1.4.5

Using a shared library that is configured to load implicit in jenkins global configuration

**Comment by 0megam** [comment]
It's impossible to use latest Blue Ocean with gitlab and multibranch plugins. It requires Multibranch 2.14 or later  ;``(

**Comment by omehegan** [comment]
@stephenc is there any chance you could take a look at this? I really don't know anything about the interaction between our plugin and workflow-multibranch-plugin. Just wondering if you can think of an obvious reason why this would be broken when multibranch-plugin is updated.

**Comment by raynigon** [comment]
Same problem here with Multibranch 2.14 and Gitlab plugin 1.4.5

Using a shared library that is configured to load implicit in jenkins global configuration

**Comment by omehegan** [comment]
Is this only affecting people who use the `@Library` function of Pipeline?

**Comment by tsutsarin-fuib** [comment]
@omegarus Yes. I'm using `@Library` function of Pipeline only and also affected.
Same Multibranch 2.14 and Gitlab plugin 1.4.5 versions.

**Comment by sbrassely** [comment]
I'm also facing this issue with implicit load of library.
When looking at the [https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/util/CommitStatusUpdater.java#L129](https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/util/CommitStatusUpdater.java#L129) and build file (build.xml), we can see there's more than one BuildData tags (hudson.plugins.git.util.BuildData). build.getAction() return the first instance of build data....
Maybe the problem come's here....

Edited : link corrected

**Comment by chizmeeple** [comment]
Weirdly in the previous comment:
* https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/util/CommitStatusUpdater.java#L129
(incorrectly) linked to
* https://github.com/jenkinsci/gitlab-plugin/issues/url

Just in case you're clicking and wondering where the destination vanished to.

**Comment by omehegan** [comment]
Per Jesse's comment in https://issues.jenkins-ci.org/browse/JENKINS-42535, it seems like we need to switch to looking up the revision using SCMRevisionAction rather than BuildData. @mreichel or @colourmeamused maybe you would like to look into this? Or I may try to do so for fun this week.

**Comment by lalmeras** [comment]
Here is a quick and very dirty fix that works for me: https://github.com/lalmeras/gitlab-plugin/commit/56809f324e3017d1fdc8c297cacc4144898554bf

My problem is that my way to lookup repository's url is not consistent with SHA lookup, but maybe I missed clever way to fix it with SCMRevisionAction.

**Comment by mreichel** [comment]
@omehegan did you look into this? Otherwise I could start this week...

**Comment by neurolabs** [comment]
Is anyone working on this? I'm eagerly waiting for a fix. This blocks me from using blue ocean, as well as from freely updating jenkins.

**Comment by pgeorgiev333** [comment]
Thanks. Do you have any idea when a new release will be published?

**Comment by neurolabs** [comment]
Could you be so kind and release a new version including this fix? Or communicate when there will be a new release?

**Comment by chizmeeple** [comment]
Yes please release this! We've been struggling with this bug at work for some weeks now. It's frustrating when it appears to have been debugged and resolved, but not released (in close to three weeks now).

**Comment by marius-balteanu** [comment]
Indeed, please release a new version of the plugin.

**Comment by omehegan** [comment]
This was released today in version 1.4.6 of the plugin.

**Comment by neurolabs** [comment]
Not yet accessible in update manager, also broken link on https://wiki.jenkins.io/display/JENKINS/GitLab+Plugin (to 1.4.6)

**Comment by neurolabs** [comment]
Here's a working link to the hpi file: http://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/gitlab-plugin/1.4.6/gitlab-plugin-1.4.6.hpi

**Comment by omehegan** [comment]
@neurolabs there was a wider issue with the Jenkins update center last night, it has since been resolved.
