### ISSUE TITLE
Support API v4 (v3 is deprecated)

### ISSUE THREAD

**Issue by binarious** [jenkinsci/gitlab-plugin#530]
GitLab has deprecated the API version which is [used by this plugin](https://github.com/jenkinsci/gitlab-plugin/blob/3ea5fad7c5df4e88940ba9e67828a938db1a98a2/src/main/java/com/dabsquared/gitlabjenkins/gitlab/api/GitLabApi.java#L28):

> We will continue to support v3 of the API until August 2017 and so we encourage you to make any necessary changes to applications that use the v3 API.

https://about.gitlab.com/2017/03/22/gitlab-9-0-released/

It should be upgraded to support v4.

**Comment by tomasbjerre** [comment]
I would suggest moving to [java-gitlab-api](https://github.com/timols/java-gitlab-api) to support this.

https://github.com/timols/java-gitlab-api/issues/201

**Comment by omehegan** [comment]
There was a reason that we moved away from that API library, @coder-hugo would have to refresh my memory about what it was.

**Comment by Bradmoon** [comment]
GitLab is currently on 9.1.3 and appear to be deleting V3 support in 9.3.  Do you see this issue being addressed soon?

**Comment by aundrus** [comment]
Just to note that the ATLAS CI system heavily relies on GitLab plugin (while ATLAS software workflow is based on the CI system)

**Comment by dblessing** [comment]
I can confirm that GitLab will support API v3 until August 2017, per the blog post. I think the text at https://docs.gitlab.com/ce/api/v3_to_v4.html caused confusion so we will update it. Is there another place you saw that we will remove in 9.3?

**Comment by omehegan** [comment]
@tomasbjerre from what I can see, the java-gitlab-api library would only support API v4, not mixed use of v3 and v4. So I don't think that will work for us, because we will need to be compatible with older versions of GitLab. Here is the PR where we moved away from that library, with explanations for the reasoning. https://github.com/jenkinsci/gitlab-plugin/pull/203

We will work on an implementation of this soon, but it's not yet urgent.

**Comment by isugimpy** [comment]
Has anyone revalidated that this isn't a more critical thing?  We upgraded to 9.3 on Monday and the direct feedback from Jenkins on Gitlab merge requests no longer works, with a message of "Could not connect to the CI server. Please check your settings and try again."  Is it possible that they began disabling portions of the v3 API already?

**Comment by mcg** [comment]
Possibly related.... https://gitlab.com/gitlab-org/gitlab-ee/issues/2763

**Comment by crussell52** [comment]
Gitlab document currently cites `9.5` and `August 22, 2017`

https://docs.gitlab.com/ce/api/v3_to_v4.html
>API V3 will be removed in GitLab 9.5, to be released on August 22, 2017. In the meantime, we advise you to make any necessary changes to applications that use V3.

**Comment by crussell52** [comment]
@omehegan 

What is the status on this... we are less than 2 months from the v3 api from disappearing.

Also, what is the concern with `java-gitlab-api` only supporting v4?  Given the time left, using a package which has already done the tedium seems like the way to go.

**Comment by derholle** [comment]
@isugimpy Looks like the problem you're running into is not gitlab-plugin related. It's being tracked as a GitLab issue that's supposedly already been fixed and ready for release into a GitLab 9.3.x patch:
(https://gitlab.com/gitlab-org/gitlab-ce/issues/34130)

**Comment by crussell52** [comment]
@derholle Thanks for digging up that gitlab-ce bug.  Some of us also have an open gitlab-ee ticket for the same issue which has seen no action. :heart:

I think the fact that we've just felt the pain of integration breaking has brought this issue back to the foreground.

**Comment by omehegan** [comment]
@mreichel or @colourmeamused do you have bandwidth to look at this?

**Comment by omehegan** [comment]
Might help with #556.

**Comment by omehegan** [comment]
We now have a PR which adds support for the v4 API. If you are able to help us test this, please head over to #596 where there is a link to download a snapshot release of the plugin with this patch. Please use the PR to provide any feedback about the patch. Thank you!

**Comment by mreichel** [comment]
The PR looks good and I tested some key functionality. Maybe we should wait for some feedback before we merge it, though. We also need a documentation change, since the Gitlab plugin won't work with the old API anymore

**Comment by omehegan** [comment]
When we are ready to release, I will handle the merge, bump the version number, specify it as a breaking change, etc. I may do two separate releases, and try to merge as many of the other open PRs first, in order to get as many fixes into the final v3-API/GitLab 8.x supporting release as possible.

**Comment by omehegan** [comment]
Is anyone who is using GitLab 9.0+ planning to test the proposed v4 patch in their install?

**Comment by aundrus** [comment]
I plan to test v4 patch on the ATLAS CI system test bed this week.

**Comment by stefanandres** [comment]
So, August 22, 2017 was yesterday :)

**Comment by Argelbargel** [comment]
Hi, I have enhanced the patch #596  from @	ZJvandeWeg so that it's possible to support both apis (given that the original patch contained all required changes).

I am not sure how to proceed, though. Should I open a new merge-request for this or is there a way to integrate my changes into #596 ?

**Comment by Argelbargel** [comment]
Hi. I've opened a new pull request (#614) for my changes...

**Comment by iamwyza** [comment]
FYI - APIv3 will be removed in Gitlab 11: https://about.gitlab.com/2017/09/22/gitlab-10-0-released/#api-v3

**Comment by binarious** [comment]
Seems to be fixed via https://github.com/jenkinsci/gitlab-plugin/pull/614.
