### ISSUE TITLE
Current git plugin throws 'Failed to update Gitlab commit status: No (git-plugin) BuildData associated to current build' for gitlabCommitStatus

### ISSUE THREAD

**Issue by stefanandres** [jenkinsci/gitlab-plugin#531]
### Context
- gitlab-plugin 1.4.5
- gitlab 8.16.8
- jenkins 2.52
- Multibranch Pipeline

### Problem description

When using a job with gitlabCommitStatus(...) the initial status cannot be sent to gitlab because of the error Failed to update Gitlab commit status: No (git-plugin) BuildData associated to current build`. It is able to send the final result of the job to gitlab though.

This breaks with git-plugin-3.1.0
When downgrading to git-plugin-3.0.1 this feature works without errors (though now jenkins has dependency problems with other plugins).

**Comment by omehegan** [comment]
@stefanandres that's interesting, I haven't heard of this issue before. Do you think it's possible you were affected by this: https://jenkins.io/blog/2017/01/17/scm-api-2/ Have you tested with later 3.0.x versions of the Git plugin? The last was 3.0.5.

@markewaite do you have any guesses about what might cause this problem with the latest version of the Git plugin? Looks like a bad interaction between that and gitlab-plugin.

**Comment by MarkEWaite** [comment]
I'm not aware of any functionally interesting changes in the git plugin BuildData handling between git plugin 3.0.1 and git plugin 3.1.0.

I ran a comparison between those two tags and saw only the addition of a warning message in cases where BuildData risks becoming unwieldy.  However, it is just a logged warning message, not anything which should change behavior.

**Comment by omehegan** [comment]
@MarkEWaite thanks for checking!

@stefanandres can you do some more debugging to try and isolate this? There's only one place in the code where we log this exact message, catching one of three possible exceptions. I wonder if your Jenkins log would show some more detail.

**Comment by stefanandres** [comment]
Thansk for the quick replies! The jenkins.log didn't show any errors. I've even upgraded _all_ plugins to their recent version. (and also updated jenkins to the recent version)

I'll get to that issue again in a week or so. I'll leave it with the 3.0.1 release for so long as this is currently working.

**Comment by stefanandres** [comment]
I've updated Jenkins and all plugins again it and it now works, thanks!
