### ISSUE TITLE
Problem accessing /project/Jenkins_Project_name/. Reason:  404

### ISSUE THREAD

**Issue by Mistu3** [jenkinsci/gitlab-plugin#533]
### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 8.17 CE
- **Jenkins version**: 2.32.3
- **Job type**:  Freestyle

### Logs & Traces

mar 27, 2017 2:05:07 PM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/Jenkins_Project_name/
mar 27, 2017 2:05:07 PM FINE com.dabsquared.gitlabjenkins.webhook.ActionResolver
Unknown GET request: 

### Problem description

Hi guys,
i have a problem with my webHook/Jenkins . I have GitPlugin set right because when i make commit and push and  click build i got status of jenkins builded in my GitLab(Pusher build status working well).
But my webhook link  /project/Jenkins_Project_name/ send me message 404  
HTTP ERROR 404

Problem accessing /project/Jenkins_Project_name/. Reason:

    Not Found
Powered by Jetty://
In the log i get WebHook called with url: /project/Jenkins_Project_name/ and Unknown GET request: .
in the GitLab side on the test the link i got Hook execution failed: execution expired. My /project/ link is not working well do u know why?

**Comment by omehegan** [comment]
Did you use the literal string 'jenkins_project_name' in your webhook, rather than the actual name of the Jenkins job you want to build?

**Comment by Mistu3** [comment]
Yes Thats it when i change project for job i am in right project .

**Comment by Yura-Savchuk** [comment]
I have the same issue. I am just select checkbox "Build when a change is pushed to GitLab. GitLab CI Service URL: http://my.domain/project/SuperAvia" in setting section for an jenkins job. I am sure that I config job correctly because another Build Triggers works well. When I go to the http://my.domain/project/SuperAvia it return:

HTTP ERROR 404
Problem accessing /project/SuperAvia. Reason:
    Not Found
Powered by Jetty://

**Comment by omehegan** [comment]
You won't be able to perform a GET on the /project/SuperAvia URL. It only responds to a POST from a GitLab webhook. How have you both configured GitLab to trigger the job? Make sure you have followed the instructions under https://github.com/jenkinsci/gitlab-plugin#gitlab-configuration to create the webhook.

**Comment by matsch01** [comment]
@Mistu3 did you resolve this issue? I'm have the same problem. Jenkins 2.46.2, Gitlab Plugin 1.4.5, GitLab CE 9.0.4

**Comment by algorys** [comment]
**Jenkins 2.46.2
Gitlab 9.1.2
Gitlab-plugin 1.4.5**

FYI, I was having the same problems. My mistakes were:

- I use the wrong syntax and thinking that `project` is the folder of project. But not.
- I have to add jenkins item folder to URL to get it work and remove `job` from it.

So for a Jenkins item url like : 

`http://my-jenkins.com/job/Folder/job/Item/`

I've to write:

`http://my-jenkins.com/project/Folder/Item/`

Don't forget to uncheck `ssl` if you don't use it.

Then it works.

**Comment by matsch01** [comment]
Thanks. My issue was that I was running in dev and my Jenkins url was http://localhost:8080. Gitlab didn't accept localhost. When I changed to my ipaddress it worked fine.

**Comment by predmijat** [comment]
I'm having this issue...

Errors I get after I test webhook in GitLab:
- In Jenkins (GitLab log recorder) - `Unsupported X-Gitlab-Event header: Push Event`
- In GitLab right after I press "test" - 
```
Hook executed successfully but returned HTTP 404 <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 404 Not Found</title> </head> <body><h2>HTTP ERROR 404</h2> <p>Problem accessing /project/${jenkins_job_name}. Reason: <pre> Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/> </body> </html>
```

(I've edited ${jenkins_job_name}, not a literal value)

Webhook is in https://${jenkins_url}/project/${jenkins_job_name} format (copied from Jenkins' job configuration page, build triggers section - GitLab CI Service URL).

GitLab plugin version 1.4.7
Jenkins version 2.75
GitLab version 9.5.1

edit: @omehegan I'm not sure if people are getting notifications on comments if issue is closed, can you help with that? :)

**Comment by mariachini** [comment]
I also have the same issue. I can test e.g. Push Hook from Gitlab (by commit) but I'm not able to test Push Event.

**Comment by nonleggouncazzo** [comment]
I had exactly the same Issue ... after 3 hours I realized that, what is not working, is simply the test of push event from gitlab.
What draw me crazy has been that result obtained was a 404 not found that was the same kind of error first obtained with a mistake in webhook url!
While after have fixed the url, using the test from gitlab, the real error is (fine log on server):
_FINE: Unsupported X-Gitlab-Event header: Push Event_
A real push is instead working fine
Is this is the case for you too? Not a gitlab-plugin Issue, but a gitlab issue with webhook test headers?

**Comment by predmijat** [comment]
I'm not really sure. I moved from https://${jenkins_url}/project/${jenkins_job_name} to https://user:password@${jenkins_url}/job/${jenkins_job_name}/build?delay=0sec for the time being.

**Comment by nonleggouncazzo** [comment]
This means you're not using anymore gitlab-plugin to trigger build, but putting password in the url you're exposing it with no encryption, while using gitlab-plugin you can use a dedicated token sent encrypted with https post.
Also @mariachini declared only having problem with "push event test" button.
So I would make a test with a real push using the trigger url introduced by gitlab-plugin with token.
Bye,
Stefano

**Comment by omehegan** [comment]
Are you all using GitLab 9.5? If so I think you might be hitting https://github.com/jenkinsci/gitlab-plugin/issues/608  If that looks right, please comment in that issue. We have a PR to fix this.

**Comment by cuky23** [comment]
I experienced this issue today using jenkins(VM) and gitlab(docker) found that a refresh of the docker gitlab instance resolved my issue.

**Comment by webartoli** [comment]
I have the same problem:

### Context
- Gitlab plugin version: 1.5.2
- Gitlab version: 9.5.3 CE
- Jenkins version: 2.96
- Job type: Multibranch Pipeline

I have tried to test gitlab webhook with:
`http://{{alias_dns}}:{{port}}/project/{{projectname}}`
and
`http://{{hostname}}:{{port}}/project/{{projectname}}`
and
`http://{{ip_addr}}:{{port}}/project/{{projectname}}`

I have also tried to do a post action with postman with the following headers:
```
Content-Type:application/json
X-Gitlab-Event:Push Event
```

and the json body

``` json
{
  "object_kind": "push",
  "event_name": "push",
  "before": "384fedb6efdb69893ad54cd00e410c4f70b6c7eb",
  "after": "018bec43034a1cb61ad0e2f9e58261edf923f9ac",
  "ref": "refs/heads/master",
  "checkout_sha": "018bec43034a1cb61ad0e2f9e58261edf923f9ac",
  "message": null,
  ...
}
```

**Comment by Andrewpk** [comment]
This issue should not be closed - still occurring with plugin v 1.5.2 and jenkins 2.97

**Comment by grazielegs** [comment]
It was working for me, but it's returning a similar to the error described in this topic:
`Hook executed successfully but returned HTTP 403`

I'm using the following url:
`http://JENKINS_URL/buildByToken/build?job=JOB_NAME&token=TOKEN_NAME`

I have the right permissions to work in the project and I already test creating a new token but sounds a little bit strange.

_GitLab Plugin Version: 3.6.4_

**Comment by omehegan** [comment]
@grazielegs the latest version of this plugin is 1.5.2. And you should not be using 'buildByToken' to trigger your jobs, that is a Jenkins feature and will totally bypass this plugin. Please read the README on how to set up the trigger, you should be hitting a URL like http://jenkins/project/your_project

**Comment by omehegan** [comment]
@webartoli @Andrewpk please see my comment here. https://github.com/jenkinsci/gitlab-plugin/issues/533#issuecomment-326064354

**Comment by grazielegs** [comment]
@omehegan Strange, cause the url are working well now for trigger my jobs and the pushed events also worked. Anyway, thank you.

**Comment by Andrewpk** [comment]
@omehegan was on 10.6 something, just updated to 10.7.2 and still having the issue. `/project/myJob_name` is still 404'ing with "not found" as the only descriptor.

**Comment by omehegan** [comment]
@Andrewpk if you get a 404, either you don't have the plugin configured for your job, or something between Jenkins and GitLab is filtering and mangling the requests. Because GitLab POSTing to /project/jobname is the only way this plugin triggers builds. If this didn't work, it would not work for anyone who uses it.

**Comment by RyanYans** [comment]
@matsch01 it done!Thanks!~  

I found that the WebhooksURL can not be "localhost" or "127.0.0.1".
please find your IPv4 address.

**Comment by omehegan** [comment]
The issue with localhost not being accepted is due to a change in GitLab. See #730

**Comment by mora123456** [comment]
Hey, 
I'm having the same problem. 

Gitlab plugin version: 1.5.6
Gitlab version: ce-10.6.0-ce 
Jenkins version: 2.121.1
Job type: pipline

When I push changes to gitlab or test the webhook with "Push events" option, this line appears in the jenkins log:
Jul 02, 2018 10:07:54 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/run_auto_test-dev

That's the url in the web hook: http://jenkins:8080/project/run_auto_test-dev

This is my plugin configuration in the project:
         [$class: 'GitLabPushTrigger',
             branchFilterType: 'NameBasedFilter',
             branchFilterName: 'dev',
             triggerOnPush: true,
         ]

Is there something I'm missing?

**Comment by omehegan** [comment]
@mora123456 it would help if you could share more of the Pipeline code you're using. Also, did you see this note in the README: "NOTE: You will need to run this job manually once, in order for Jenkins to read and set up the trigger configuration. Otherwise webhooks will fail to trigger the job."

**Comment by mora123456** [comment]
@omehegan I ran the job manually several times, didn't help. 
This is how the configuration looks like in the gui after i ran the job manually:
 
![image](https://user-images.githubusercontent.com/40754606/42152092-d0b3eda2-7de7-11e8-8560-27a9ce4ca910.png)

**Comment by omehegan** [comment]
@mora123456 I don't see how you're getting a 404 in GitLab if Jenkins logs that it received the webhook request. What behavior are you seeing exactly?

**Comment by omehegan** [comment]
@mora123456 also it looks like you have 'Filter branches by name' set, but nothing in the include or exclude sections. If you want to allow all branches to trigger the build, select the other radio button.

**Comment by DRicciardi** [comment]
Same problem here. Clicking test results in a 404. In the Jenkins log I get this:
`Aug 31, 2018 3:25:06 PM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/TESTING-Website_All-GIT`

Browsing to the url also results in a 404, while /job/TESTING-Website_All-GIT brings me to the project page as expected. I'm not sure how else to debug this.

**Comment by DRicciardi** [comment]
For some reason trying a push hook instead of a repository update hook gives me a 500 error. This is on GitLab 11.2.3 and Jenkins 2.121.3

` <!DOCTYPE html><html><head resURL="/static/2377777d" data-rooturl="" data-resurl="/static/2377777d">
    

    <title>Jenkins [Jenkins]</title><link rel="stylesheet" href="/static/2377777d/css/layout-common.css" type="text/css" /><link rel="stylesheet" href="/static/2377777d/css/style.css" type="text/css" /><link rel="stylesheet" href="/static/2377777d/css/color.css" type="text/css" /><link rel="stylesheet" href="/static/2377777d/css/responsive-grid.css" type="text/css" /><link rel="shortcut icon" href="/static/2377777d/favicon.ico" type="image/vnd.microsoft.icon" /><link color="black" rel="mask-icon" href="/images/mask-icon.svg" /><script>var isRunAsTest=false; var rootURL=""; var resURL="/static/2377777d";</script><script src="/static/2377777d/scripts/prototype.js" type="text/javascript"></script><script src="/static/2377777d/scripts/behavior.js" type="text/javascript"></script><script src='/adjuncts/2377777d/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/static/2377777d/scripts/yui/yahoo/yahoo-min.js"></script><script src="/static/2377777d/scripts/yui/dom/dom-min.js"></script><script src="/static/2377777d/scripts/yui/event/event-min.js"></script><script src="/static/2377777d/scripts/yui/animation/animation-min.js"></script><script src="/static/2377777d/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/static/2377777d/scripts/yui/container/container-min.js"></script><script src="/static/2377777d/scripts/yui/connection/connection-min.js"></script><script src="/static/2377777d/scripts/yui/datasource/datasource-min.js"></script><script src="/static/2377777d/scripts/yui/autocomplete/autocomplete-min.js"></script><script src="/static/2377777d/scripts/yui/menu/menu-min.js"></script><script src="/static/2377777d/scripts/yui/element/element-min.js"></script><script src="/static/2377777d/scripts/yui/button/button-min.js"></script><script src="/static/2377777d/scripts/yui/storage/storage-min.js"></script><script src="/static/2377777d/scripts/hudson-behavior.js" type="text/javascript"></script><script src="/static/2377777d/scripts/sortable.js" type="text/javascript"></script><script>crumb.init("Jenkins-Crumb", "0b23819763499ab8dd3e4ec0654c7447");</script><link rel="stylesheet" href="/static/2377777d/scripts/yui/container/assets/container.css" type="text/css" /><link rel="stylesheet" href="/static/2377777d/scripts/yui/assets/skins/sam/skin.css" type="text/css" /><link rel="stylesheet" href="/static/2377777d/scripts/yui/container/assets/skins/sam/container.css" type="text/css" /><link rel="stylesheet" href="/static/2377777d/scripts/yui/button/assets/skins/sam/button.css" type="text/css" /><link rel="stylesheet" href="/static/2377777d/scripts/yui/menu/assets/skins/sam/menu.css" type="text/css" /><meta name="ROBOTS" content="INDEX,NOFOLLOW" /><meta name="viewport" content="width=device-width, initial-scale=1" /><script src="/static/2377777d/jsbundles/page-init.js" type="text/javascript"></script></head><body data-model-type="hudson.model.Hudson" id="jenkins" class="yui-skin-sam two-column jenkins-2.121.3" data-version="2.121.3"><a href="#skip2content" class="skiplink">Skip to content</a><div id="page-head"><div id="header"><div class="logo"><a id="jenkins-home-link" href="/"><img src="/static/2377777d/images/headshot.png" alt="title" id="jenkins-head-icon" /><img src="/static/2377777d/images/title.png" alt="title" width="139" id="jenkins-name-icon" height="34" /></a></div><div class="login"> <a href="/login?from=%2Fproject%2FTESTING-Website_All-GIT"><b>log in</b></a></div><div class="searchbox hidden-xs"><form method="get" name="search" action="/search/" style="position:relative;" class="no-json"><div id="search-box-minWidth"></div><div id="search-box-sizer"></div><div id="searchform"><input name="q" placeholder="search" id="search-box" class="has-default-text" /> <a href="https://jenkins.io/redirect/search-box"><img src="/static/2377777d/images/16x16/help.png" style="width: 16px; height: 16px; " class="icon-help icon-sm" /></a><div id="search-box-completion"></div><script>createSearchBox("/search/");</script></div></form></div></div><div id="breadcrumbBar"><tr id="top-nav"><td id="left-top-nav" colspan="2"><link rel='stylesheet' href='/adjuncts/2377777d/lib/layout/breadcrumbs.css' type='text/css' /><script src='/adjuncts/2377777d/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class="top-sticker noedge"><div class="top-sticker-inner"><div id="right-top-nav"></div><ul id="breadcrumbs"><li class="item"><a href="/" class="model-link inside">Jenkins</a></li><li href="/" class="children"></li></ul><div id="breadcrumb-menu-target"></div></div></div></td></tr></div></div><div id="page-body" class="clear"><div id="side-panel"><div class="task"><a href="https://jenkins.io/" class="task-icon-link"><img src="/static/2377777d/images/24x24/next.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-next icon-md" /></a> <a href="https://jenkins.io/" class="task-link">Jenkins project</a></div><div class="task"><a href="https://jenkins.io/redirect/report-an-issue" class="task-icon-link"><img src="/static/2377777d/images/24x24/gear2.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-gear2 icon-md" /></a> <a href="https://jenkins.io/redirect/report-an-issue" class="task-link">Bug tracker</a></div><div class="task"><a href="https://jenkins.io/redirect/mailing-lists" class="task-icon-link"><img src="/static/2377777d/images/24x24/search.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-search icon-md" /></a> <a href="https://jenkins.io/redirect/mailing-lists" class="task-link">Mailing Lists</a></div><div class="task"><a href="https://twitter.com/jenkinsci" class="task-icon-link"><img src="/static/2377777d/images/24x24/user.png" style="width: 24px; height: 24px; width: 24px; height: 24px; margin: 2px;" class="icon-user icon-md" /></a> <a href="https://twitter.com/jenkinsci" class="task-link">Twitter: @jenkinsci</a></div></div><div id="main-panel"><a name="skip2content"></a><h1 style="text-align: center"><img src="/static/2377777d/images/rage.png" width="154" height="179" /><span style="font-size:50px"> Oops!</span></h1><div id="error-description"><p>A problem occurred while processing the request.
        Please check <a href="https://jenkins.io/redirect/issue-tracker">our bug tracker</a> to see if a similar problem has already been reported.
        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.
        If you think this is a new issue, please file a new issue.
        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.
        <a href="https://jenkins.io/redirect/users-mailing-list">The users list</a> might be also useful in understanding what has happened.</p><h2>Stack trace</h2><pre style="margin:2em; clear:both">java.lang.NullPointerException
	at com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerImpl.retrieveCauseData(PushHookTriggerHandlerImpl.java:54)
	at com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerImpl.retrieveCauseData(PushHookTriggerHandlerImpl.java:23)
	at com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.createActions(AbstractWebHookTriggerHandler.java:84)
	at com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler.handle(AbstractWebHookTriggerHandler.java:53)
	at com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerImpl.handle(PushHookTriggerHandlerImpl.java:30)
	at com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerImpl.handle(PushHookTriggerHandlerImpl.java:23)
	at com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerList.handle(PushHookTriggerHandlerList.java:24)
	at com.dabsquared.gitlabjenkins.trigger.handler.push.PushHookTriggerHandlerList.handle(PushHookTriggerHandlerList.java:13)
	at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onPost(GitLabPushTrigger.java:424)
	at com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction$1.performOnPost(PushBuildAction.java:72)
	at com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction$TriggerNotifier.run(BuildWebHookAction.java:54)
	at hudson.security.ACL.impersonate(ACL.java:273)
	at com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction.execute(PushBuildAction.java:69)
	at com.dabsquared.gitlabjenkins.webhook.build.BuildWebHookAction.execute(BuildWebHookAction.java:31)
	at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook.getDynamic(GitLabWebHook.java:44)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:372)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:784)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at com.dabsquared.gitlabjenkins.webhook.GitLabWebHook$GitlabWebHookCrumbExclusion.process(GitLabWebHook.java:53)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:73)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.success(BasicHeaderProcessor.java:140)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:82)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:289)
	at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:149)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></div></div><footer><div class="container-fluid"><div class="row"><div class="col-md-6" id="footer"></div><div class="col-md-18"><span class="page_generated">Page generated: Aug 31, 2018 4:05:03 PM UTC</span><span class="rest_api"><a href="api/">REST API</a></span><span class="jenkins_ver"><a href="https://jenkins.io/">Jenkins ver. 2.121.3</a></span></div></div></div></footer></body></html>`

**Comment by DRicciardi** [comment]
Never mind! I was creating a system hook rather than a web hook. In case anyone stumbles across this, web hooks are located on the project page under Settings > Integrations.

**Comment by panostzemis** [comment]
@DRicciardi 

First of all have a look o Jenkins logs in order to check if it receives the Hook.
You should see something like this 
> INFO: WebHook called with url: /ci/project/content-fetch

In case you are accessing your Jenkins/Git with **HTTP**, add your webhook as provided by Jenkins on project  settings
`http://domain/ci/project/<project-name>`

and uncheck 
`Enable SSL verification`

In case you have **HTTPS**
Use your Jenkins project URL but this time add **https** instead of **http**``

`https://domain/ci/project/<project-name>`
And check
`Enable SSL verification`

Also on Jenkins project configuration on **Build Triggers/Build when a change is pushed to GitLab.**
by pressing the advanced button you will find **Secret Token**
Generate a token and insert it on the GitLab Webhook settings.
 
That should work for you.

**Comment by ulflunde** [comment]
Having the same problem with GitHub here.
I've been using Jenkins daily for a long time, but since last weekend I suddenly get the error above
for all "job" urls (even if I remove the "/job" part).

I tried upgrading to Jenkins v2.151, but still I get the same issue.

Did GitHub change how they handle Jenkins? (Just like that, on Nov 9, 2018?)

**Comment by ShankarSumanth** [comment]
Bumping an old topic but I figured out a way for the webhook to work. Although it is mentioned in the README, it's quite unclear and a bit of circus to get this setup up and running. 

The reason (at least for multi-branch pipeline ) why the endpoint does not work is, the inability to set `Build when a change is pushed to GitLab` from the UI and **SAVE IT**. This has to be done declaratively and then everything works.

This is for declarative pipeline setup and works for multibranchpipeline (tested). 
Gitlab : `11.4.5` (installed EE but using only the CE version)
Jenkins: `2.138`
Jenkins Endpoint: `jenkins.mydomain.com`

For the `/project/project_name` endpoint to work as a webhook endpoint, you need to create an initial pipeline and trigger it manually (Will show how this can be done from gitlab) 

### STEP 1: Add the below code to your jenkinsfile and checkin the code
```
pipeline {
    agent any
    post {
      failure {
        updateGitlabCommitStatus name: 'build', state: 'failed'
      }
      success {
        updateGitlabCommitStatus name: 'build', state: 'success'
      }
    }
    options {
      gitLabConnection('your-gitlab-connection-name')
    }
    triggers {
        gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All')
    }
    stages {
      stage("build") {
        steps {
          echo "hello world"
        }
      }
    }
}

```

The important line above is ` triggers {
        gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All')
    }` which will enable `Build when a change is pushed to GitLab`. 

**NOTE**: Don't forget to change the gitLabConnection Name to your gitlabConnectionName

### STEP 2:  Setup Webhook Bypass (For Initial Trigger)

Go to Gitlab > Project > Integrations > Webhook and setup a bypass trigger as shown below 
```
Webhook Url: `https://user:apiToken@jenkins.mydomain.com/job/webhook/build?delay=0`
Secret Token : <LEAVE IT BLANK>
Verify SSL: Uncheck
```
Save the Webhook and Click on Test Push. 
Verify that a build has been triggered on your jenkins.


### STEP 3: Change the Webhook Url 

Now that the `gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All')` has been recorded by Jenkins pipeline, remove the previous webhook and replace it with `https://jenkins.m ydomain.com/project/<your_project_name>`, leave the token secret empty, verifySSL unchecked. 

Make a change to your Jenkinsfile, change `echo hello world` to `echo hello webhook` and push it. 

The build should be automatically trigged on Jenkins.

**Comment by omehegan** [comment]
@ShankarSumanth you are doing exactly what is in the documentation at https://github.com/jenkinsci/gitlab-plugin#declarative-pipeline-jobs except you are going through an unnecessary 'step 2.' As the doc says, you just need to build the job manually once in order to set the trigger. You don't need to do this dance of changing the webhook in GitLab and forcing GitLab to trigger the job.

**Comment by RandalTeng** [comment]
I have the same problem, but the webhook is work fine. I get this error is that when I access the jenkins home page in my Chrome Mobile, if i access the home in Chrome for Mac/Windows and it work fine.
The error found: 
### HTTP ERROR 404

```
Problem accessing /job/PROJECT/ws/frontend/.Reason
    Not Found

Powered by...
```

And my jenkins running a docker environment, login a normal user of worker.

**Comment by DatzAtWork** [comment]
Knowing that this issue is already closed, I want to report the same error:

Jenkins: https://<mydomain>/jenkins/
Pipeline project with "Gitlab trigger" enabled.
Webhook: https://<mydomain>/jenkins/project/Test

Jenkins-Log:
```
Apr 30, 2019 1:35:44 PM INFORMATION com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /jenkins/project/Test
```

Triggering the webhook manually with `curl -X POST https://jenkins-hafrcms.itd-intern.de/jenkins/project/Test -d "x" -k`
gets me

**Response 404:**
```
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /jenkins/project/Test. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>
```

Triggering a GitLab webhook (Gitlab 11.x CE) gives me 
` 500 - Whoops, something went wrong on our end.`

And no build is triggered.

**Comment by wsgggws** [comment]
It could POST normally when use `//{JENKINS_URL}/project/{PORJECT_NAME}` + secret_token, plz care about what is your Jenkins server URL?  it started with `HTTP` or `HTTPS`?
if it is `HTTP`, the URL should be `http://{JENKINS_URL}/project/{PORJECT_NAME}`
else the URL should be `https://{JENKINS_URL}/project/{PORJECT_NAME}`

**Comment by camara-dds** [comment]
bonjour j'ai un problème lorsque j'essaie de créer un node voilà le message qu'on m'affiche 
HTTP ERROR 403
Problem accessing /descriptorByName/hudson.plugins.sshslaves.SSHLauncher/checkCredentialsId. Reason:

    Forbidden
Powered by Jetty:// 9.4.z-SNAPSHOT
merci de m'aider
