### ISSUE TITLE
Feature Request: Make config more approachable from groovy

### ISSUE THREAD

**Issue by ehaselwanter** [jenkinsci/gitlab-plugin#534]
Hi there. First of all thanks for the improvements in this plugin.
I'm automating Jenkins deployments and I would like to have an idempotent way of updating the gitlab connections. 

It would be great if there were a `create_or_update` for connections.

Here is a workaround for such a thing. One of the issues is, that a connection object can not be updated but has to be deleted and re-added with new values (which might have side effect?! for jobs using that connection)

``` 
   connections_with_this_name = connections.count { it.name == name }
    connection_not_configured = connections_with_this_name == 0 ? true : false
    // only remove if one of the properties changed
    removed = connections.removeAll() { 
      it.name == name &&
		(it.url != url ||
        it.apiTokenId != apiTokenId ||
        it.ignoreCertificateErrors != ignoreCertificateErrors ||
        it.connectionTimeout != connectionTimeout ||
        it.readTimeout != readTimeout)
    }
    if (removed || connection_not_configured) {
      println("create or update ${name}")
      connections.add(new com.dabsquared.gitlabjenkins.connection.GitLabConnection(name,
                                        url,
                                        apiTokenId,
                                        ignoreCertificateErrors,
                                        connectionTimeout,
                                        readTimeout))
      gitlab.save()
    }
```

**Comment by omehegan** [comment]
Just to make sure I understand correctly: you're wanting to use this as part of an automation process for setting up new Jenkins instances and/or managing the configuration of running instances?

**Comment by ehaselwanter** [comment]
yes. at the moment the only way to change a connection (e.g. token-id, timeouts) is to delete the connection and re-add a new one. I'm not so sure about the side effects of this.

**Comment by omehegan** [comment]
Take a look at #559 and let me know if you think this would give you what you want.

**Comment by omehegan** [comment]
Reopen if this feature is still desired and #559 does not work for you.

**Comment by durgesh7503** [comment]
wwww
