### ISSUE TITLE
Word missing in README?

### ISSUE THREAD

**Issue by alex-harvey-z3q** [jenkinsci/gitlab-plugin#537]
In section [Git configuration for Freestyle jobs](
https://github.com/jenkinsci/gitlab-plugin/blob/master/README.md#git-configuration-for-freestyle-jobs) is there a word missing here:

> In the Advanced settings, set Name to origin and Refspec to `+refs/heads/*:refs/remotes/origin/*` `+refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*`

I do not understand what this wants me to put in the Refspec?

**Comment by omehegan** [comment]
I don't think there is anything missing, but you're right that it is not clear what this accomplishes. You are expected to put that whole string, with the space, in the Refspec. And, if I remember right, the point of this is that it tells Jenkins that pushes to branches and merge requests are valid to consider for building. I believe if you don't do this, and you use the Merge Request webhook in GitLab, it will not always trigger correctly. If you only use the Push trigger, it is irrelevant. I think.

Please reopen if you have further questions.

**Comment by omehegan** [comment]
I did some more digging. We added this to fix https://github.com/jenkinsci/gitlab-plugin/pull/370, and what it does is allow Git to fetch merge requests from the upstream.

**Comment by alex-harvey-z3q** [comment]
So my confusion arises because we seem to be using both a space and a colon as a delimiter. I wasn't sure if Jenkins even supports that.

Shouldn't it be:

```
+refs/heads/*:refs/remotes/origin/*:refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*
```

**Comment by omehegan** [comment]
I'm not sure, TBH. I don't use this exact workflow in my installation. My assumption from reading it closely was that it's two different Refspecs, hence the space. 

I've just gone and read https://git-scm.com/book/id/v2/Git-Internals-The-Refspec  The colon separates the location where something found on the remote should be written on the local host. So >1 colon without a space doesn't make sense. What we're saying is:

`+refs/heads/*:refs/remotes/origin/*` - Anything found in refs/heads/* on the remote, write to refs/remotes/origin/* on the local
`+refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*` - Anything found in refs/merge-requests/&ast;/head on the remote, write to refs/remotes/origin/merge-requests/* on the local

**Comment by jayeshkhairnar** [comment]
Hi

I want to run jenkins job once PR merge with master to remove PR ID s3 bucket. Could anyone help me on it.
