### ISSUE TITLE
Cannot update commit-status of project in subgroup

### ISSUE THREAD

**Issue by avonengel** [jenkinsci/gitlab-plugin#538]
### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 9.0.5-ee
- **Jenkins version**: 2.7.2
- **Job type**: multibranch pipeline

### Logs & Traces

Added Jenkins logger for `com.dabsquared.gitlabjenkins`, level `ALL`. Replaced host and group names with `on.premises`, `groupname`, `subgroupname`, `projectname`:
```
Apr 18, 2017 8:17:02 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Apr 18, 2017 8:17:02 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving the gitlab project id from remote url git@on.premises:groupname/subgroupname/projectname.git
Apr 18, 2017 8:17:02 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Call GitLab:
HTTP method: GET
URL: https://on.premises/api/v3/projects/subgroupname%2Fprojectname/repository/commits/904cdaa399aeae7ef8e96b94e884658d11879962
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]
Apr 18, 2017 8:17:08 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Got response from GitLab:
URL: https://on.premises/api/v3/projects/subgroupname%2Fprojectname/repository/commits/904cdaa399aeae7ef8e96b94e884658d11879962
Status: 404 Not Found
Response headers: [
Cache-Control = [no-cache],
Connection = [keep-alive],
Content-Length = [35],
Content-Type = [application/json],
Date = [Tue, 18 Apr 2017 06:16:44 GMT],
Server = [nginx],
Vary = [Origin],
X-Request-Id = [fbb2d8c9-1bf4-42cf-a5f6-ca5e70e96256],
X-Runtime = [0.034847]
]
Response body: {
  "message" : "404 Project Not Found"
}
Apr 18, 2017 8:17:08 AM FINE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater
Project (subgroupname/projectname) and commit (904cdaa399aeae7ef8e96b94e884658d11879962) combination not found
```

### Problem description

The plugin does not use the group's name, only the subgroup's name to try and update the commit-status at Gitlab: `.../projects/subgroupname%2Fprojectname/repository/...`
This should be: `.../projects/groupname%2Fsubgroupname%2Fprojectname/repository/...`

**Comment by omehegan** [comment]
Likely a plugin bug, subgroups were only introduced in GitLab 9.0, which is recent.

**Comment by zeewell** [comment]
the same issue.

**Comment by hWorblehat** [comment]
Can the proposed PR be merged? This bug is affecting me too.

**Comment by hWorblehat** [comment]
Also, I believe the only change that's actually needed to fix this issue is the change to the regular expression in ProductIdUtil.java. Would it help to expedite this if I prepared a PR with just this change in?

**Comment by omehegan** [comment]
I'll look at this soon.

**Comment by hWorblehat** [comment]
Thanks

**Comment by ospector** [comment]
Issue still alive and kicking. Any idea when can we expect PR to be merged?
Thanks!

**Comment by omehegan** [comment]
@ospector I will do a release next week which will include this.

**Comment by jgeorgeson** [comment]
Is there an updated ETA on releasing this?

**Comment by weakcamel** [comment]
Hello,
I've reviewed https://github.com/jenkinsci/gitlab-plugin/blob/master/CHANGELOG.md and haven't seen this fix released (yet). Pretty please? :-)

**Comment by omehegan** [comment]
My apologies for the delay on releases, life has gotten in the way. I am at Jenkins World this week and will be dedicating some time to merging PRs and getting a release or to done.

**Comment by omehegan** [comment]
This was released today in version 1.4.8 of the plugin.

**Comment by avonengel** [comment]
Thanks for fixing this :)

**Comment by hila3000** [comment]
@omehegan I experience the same issue, on plugin version 1.5.20. Any idea why?

**Comment by hila3000** [comment]
@omehegan It doesn't let me edit the previous comment, so creating new one.
I tried to move the project to the root group instead of the sub group, and it doesn't work either.
Full plugin log can be found here: https://gist.github.com/hila3000/7b341c4463f363c8a9925e14da2723fa

**Comment by hila3000** [comment]
@omehegan I'm experiencing the same issue, on plugin version 1.5.20. Any idea why?
I tried to move the project to the root group instead of the sub group, and it doesn't work either.
Full plugin log can be found here: https://gist.github.com/hila3000/7b341c4463f363c8a9925e14da2723fa
