### ISSUE TITLE
Redirect to Jenkins Build Page Issue

### ISSUE THREAD

**Issue by matt-imgd** [jenkinsci/gitlab-plugin#54]
I have an issue related to Builds being initiated by Gitlab Merge Request creation:
The Jenkins Build Page URL in Gitlab Merge Request Page, similar to "commits/5b3be24cb184e3698fc0cec9dd7c8ca2d1fc857e", does not redirect to the Jenkins build details page. 

It just shows white page at Jenkins side.

What could be the issue?

**Comment by bassrock** [comment]
Can you post any logs?

**Comment by thatarchguy** [comment]
I believe he's referring to #56

**Comment by omehegan** [comment]
This sometimes happens if the action on the GitLab side does not trigger a build in Jenkins. Then the link has nothing to refer to. Otherwise, it works as designed in the latest version of the plugin.
