### ISSUE TITLE
Multi-branch pipeline ignores build trigger configuration

### ISSUE THREAD

**Issue by probaton** [jenkinsci/gitlab-plugin#547]
### Context
- **Gitlab plugin version**: 1.4.4
- **Gitlab version**: Enterprise Edition 8.17.4-ee ba6d2a1
- **Jenkins version**: 2.32.3
- **Job type**: Multi-branch pipeline

### Logs & Traces

I couldn't think of anything meaningful to log. Feel free to reply with requests if you can think of anything pertinent. 

### Problem description

We have a multi-pipeline project, set to create a Jenkins job for every GitLab branch. Every time something is pushed to the branch in GitLab, Jenkins triggers a build in the branch job. The job is configured by means of a JenkinsFile in the project root. 

Things start to go awry while tweaking the pipeline trigger behavior. Adding a pipelineTriggers property to the JenkinsFile properties seems to work: after the new property is pushed, the job configuration correctly reflects the submitted properties under Build Triggers. In practice, however, the build seems to completely ignore these properties. As an example, I disabled Push Events. Nevertheless, when I push to the branch in question, a build is started as normal. This behavior remains through multiple push-build cycles, so the problem is not due to Jenkins running the build for the JenkinsFile push with its old configuration. 

We have a number of jobs running on a single pipeline using the same configuration, all of which work exactly as intended. The multi-branch set-up was the only variable we could think of that separated this Jenkins project from the others. 

Below is a copy-paste of the JenkinsFile properties sections, as well as a screen grab of the settings as displayed in Jenkins.  
```
properties properties: [
	[$class: 'GitLabConnectionProperty', gitLabConnection: 'https://our-gitlab-server'],
	pipelineTriggers([[
		$class: "GitLabPushTrigger",
		triggerOnPush: false,
		triggerOnMergeRequest: true,
		triggerOpenMergeRequestOnPush: "both",
		triggerOnNoteRequest: true,
		noteRegex: "REBUILD!",
		skipWorkInProgressMergeRequest: true,
		ciSkip: false,
		setBuildDescription: true,
		addNoteOnMergeRequest: true,
		addCiMessage: true,
		addVoteOnMergeRequest: true,
		acceptMergeRequestOnSuccess: false,
		branchFilterType: "NameBasedFilter",
		targetBranchRegex: "master",
		includeBranchesSpec: "master",
		excludeBranchesSpec: ""
	]])
]
```
![image](https://cloud.githubusercontent.com/assets/13566991/25657993/e63f5002-3000-11e7-95ae-20a7f80bba5c.png)

**Comment by omehegan** [comment]
I'm not surprised that this doesn't work, the plugin pays no attention to these settings when it is a multibranch project. Multibranch assumes that you want to build for each commit to each branch. If you don't want to do that, I think you should use a regular Pipeline job.
