### ISSUE TITLE
How Can I Get Tag Name In Jenkins Job

### ISSUE THREAD

**Issue by gilgameshs** [jenkinsci/gitlab-plugin#557]
### Before submitting an issue I have first:

- [-] read the documentation on the [homepage](https://github.com/jenkinsci/gitlab-plugin) 
- [-] searched for similar already existing issue

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
How Can I Get Tag Name In Tag Push Event Webhook In Jenkins Job

### Context
- **Gitlab plugin version**: 2.5.2
- **Gitlab version**: 8.17.4
- **Jenkins version**: 2.12
- **Job type**: Freestyle

### Logs & Traces
```
Started by GitLab push by xxx
Building remotely on x.x.x.x in workspace /qqq/jenkins/workspace/qqq/xxx-build-xx
Cloning the remote Git repository
Cloning repository http://xxxx.git
 > git init xxxx # timeout=10
Fetching upstream changes from xxxxx
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.username xxx # timeout=10
 > git config --local credential.helper store --file=.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress http://xxx/xxx/xxx.git +refs/tags/*:refs/remotes/origin/tags/*
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url http://xxx/xxx/xxx.git # timeout=10
 > git config --add remote.origin.fetch +refs/tags/*:refs/remotes/origin/tags/* # timeout=10
 > git config remote.origin.url http://xxx/xxx/xxx.git # timeout=10
Fetching upstream changes from http://xxx/xxx/xxx.git
using .gitcredentials to set credentials
 > git config --local credential.username xxx # timeout=10
 > git config --local credential.helper store --file=/tmp/xxx.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress http://xxx/xxx/xxx.git +refs/tags/*:refs/remotes/origin/tags/*
 > git config --local --remove-section credential # timeout=10
skipping resolution of commit xxxx, since it originates from another repository
 > git rev-parse refs/remotes/origin/tags/${TAGNAME}^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/refs/remotes/origin/tags/${TAGNAME}^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/tags/${TAGNAME}^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
Sending email to: xxxx
Finished: FAILURE
```
### Problem description

_Describe your problem in a meaningful way_:
- what were you doing (simple push, merge request, MR with fork, ...)
tag push 
- what was expected
get the pushed tag commit snapshot and build 
- what occurred finally
can not get the pushed tag name

**Comment by omehegan** [comment]
The latest version of the plugin is 1.4.5, you have written that you are using 2.5.2. Can you check this again?

Our plugin doesn't create a variable for tag name, but given that the tag is just a reference to a commit SHA1, I think you could use the gitlabAfter variable, which should be set to the right SHA1 of the tag when it is pushed.

**Comment by gilgameshs** [comment]
sorry, that version is Git Plugin. GitLab Plugin version is 1.3.0
you mean
` refs/remotes/origin/tags/${TAGNAME}`
change to
`refs/remotes/origin/tags/${gitlabAfter} `?
i don't know what does gitlabAfter variable mean.

**Comment by gilgameshs** [comment]
I just got it! Thank you!
just use `gitlabAfter` other than `refs/remotes/origin/tags/${gitlabAfter}`
but these two variables confuse me : 
- gitlabBefore
- gitlabTriggerPhrase
what do they mean?

**Comment by omehegan** [comment]
gitlabBefore is the git commit ref before the latest. gitlabAfter is the latest/HEAD.

gitlabTriggerPhrase is, IIRC, a phrase someone can put in an commit message to trigger a build.

**Comment by gilgameshs** [comment]
Thank you so much！！
