### ISSUE TITLE
Jenkins 404 on webhook url

### ISSUE THREAD

**Issue by jamroks** [jenkinsci/gitlab-plugin#558]
Hello,
I'm having the same issue here :
Jenkins 2.46.2 ( long term support)
Gitlab 9.1
Gitlab plugin : 1.4.5
Job type: pipeline job
the setup is as follow:
1 vm with Jenkins inside a docker container
1 vm with gitlab inside a docker container
1 vm with traefik inside a docker container ( listening on port 80) and forwarding request to both Jenkins and gitlab 

I configured everything following the plugin documentation.
Everything works well when triggering the build manually but not when i do a push , merge or any other event ( I configured on gitlab side) I keep on getting the 404 http error on webhook url even after a  click on "test" button on gitlab side.

The log on Jenkins side where not very helping in fact. the only thing appearing is the 404 from jetty server which Jenkins runs on .

but I noticed that if I have I include the port in the webhook url  http://jenkins_dns_url:8080/project/testjob than that is working. is it mandatory to include the port ?
or am I missing something here ?

thanks

**Comment by omehegan** [comment]
Yes you have to include the port, unless there is some process that is redirecting Jenkins port 80 to port 8080.

**Comment by jamroks** [comment]
Ok, so my setup is wrong then ? because this is what is happening: 

webhook url: http://jenkins_dns_url/project/testjob
Gitlab request ( via webhook)  --> traefik  (proxy 80 ) --> Jenkins (Port 8080) 

I taught putting a reverse proxy ( like nginx, apache, traefik on port 80)  in front of Jenkins was recommended so that we could avoid adding port number in url ?

**Comment by omehegan** [comment]
I don't understand how traefik is directing port 80 to both jenkins and gitlab. I can only tell you that e.g. in my install, I use an nginx reverse proxy to terminate SSL and then direct the request to Jenkins on port 8080, and this works fine with the GitLab plugin. But I sense that maybe your traefik proxy is doing something wrong. Regardless, I don't think it is a plugin bug.
