### ISSUE TITLE
Feature Request: when merge request improvement will be released

### ISSUE THREAD

**Issue by clarkdo** [jenkinsci/gitlab-plugin#560]
### Context
- **Jenkins Gitlab Plugin version**: 1.4.5

### Problem description

I have seen that  in https://github.com/jenkinsci/gitlab-plugin/commit/a61a6c77be85b89a5f8b6d37cc382fb474ea5262 introduced build triggering when merge request has been merged or closed.

I want to ask when this feature will be released?

**Comment by omehegan** [comment]
Next week maybe?
