### ISSUE TITLE
Same repo multiple directories creating build problems

### ISSUE THREAD

**Issue by vpolisetti** [jenkinsci/gitlab-plugin#563]
Hi,

I have one repository A, it has multiple directories(solutions) b,c,d,e.   I configures b,c,d,e as separate jenkins jobs, Now If I modify any thing in project b , All c,d,e Jenkins job got triggered. Build should happens to only modified projects.

**Comment by omehegan** [comment]
You have one GitLab repo with separate webhook triggers for Jenkins jobs b, c, d, e? If so, then yes, when you commit to that repo, it is going to trigger all the jobs. If you want to filter this, you would need to use a single parent job which determines what was changed, and then triggers the appropriate downstream job.

**Comment by vpolisetti** [comment]
We are not seeing this single parent job option in jenkins,  For each
solution I have created separate jenkins job under repo A
A
    b  jenkins job b
    c jenkin job c
    d jenkin job d

If I modified any code in project b ,   all jenkin job b,c,d all got
triggered.

**Comment by omehegan** [comment]
If you have one GItLab repo with three webhooks configured to trigger three different Jenkins jobs, then those three jobs will be triggered for any commit to that repo. This is not a bug.
