### ISSUE TITLE
GitLab connection : property not set in a simple pipeline job (not multibranch)

### ISSUE THREAD

**Issue by squalou** [jenkinsci/gitlab-plugin#566]
## Issue

'GitLab connectio' property doesn't sem to be set in a simple piepline job, making gitlabCommitStatus fail

### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: CE 9.2.4
- **Jenkins version**: 2.46.3
- **Job type**: Pipeline.

### Logs & Traces

Nothing more than the sentence 'GitLab connection not set' in jenkins logs

### Problem description

I have a pipeline kind of job described in a 'Jenkinsfile'. The job itself has some minor properties set : discard old jobs, triggers from gitlab, etc.
In particular I can see the dropown 'GitLab connection' with the correct name I filled in Jenkins.

In the jenkinsfile I call the 'gitlabCommitStatus' step.

Nothing happens : jenkins complanis that 'GitLab connection is not set'

As a workaround I can ue the 'properties step', as described for multibranch issues, but then : all the properties already set on job disapear !
(including the trigger from gitlab)

So as a workaround I may end up redefining all the job's properties inside the jenkinsfile, (which is painful and verbose... and should not be there), and my jobs get 'reset' at each run.

**Comment by squalou** [comment]
Also, believe it or not but : setting this in the first line of the Jenkinsfile make thing work :+1: 
```
properties(currentBuild.getRawBuild().getParent().getAllProperties())
```
it doesn' really make sense, does it ?

This prevent the removal of prepoerties, and makes GitLabConnection visible.

Withtou it , the clear message is :

> "No GitLab connection configured"

which is clear enough and is easy to find in the sources of the plugin, in CommitStautsUpdater

Still, ugly warnings issued in the job' s console at runtime.

**Comment by squalou** [comment]
Erf, doesn't work at first run on a ne branch :/
Will probably have to add forcibly the Gitlab Connection on top of existing ones.

**Comment by squalou** [comment]
Afterthought : I'm facing th issue with a job that is 'inside a Folder'
(using Jenkins Folder plugin to tidy up jobs)

Could it be a reason I face the same issue as 'multibranch' ?

[Edit] : just tested, no, it's not due to Folders. Tried without : same issue.

Gitlab pushes a job on jenkins, I get 'No GitLab connection configured' instantly

Still no idea how to 'add properties' instead of replacing all. No idea how any of you managed to have a working job.

**Comment by omehegan** [comment]
This is a known bug. https://github.com/jenkinsci/gitlab-plugin/issues/475

I'm not really sure how we can resolve it at present. Feel free to follow that one for any updates.
