### ISSUE TITLE
Start job after MR is merged/closed

### ISSUE THREAD

**Issue by marcinmantke** [jenkinsci/gitlab-plugin#570]
## Issue
I want to do some action on Jenkins side after MR is merged/closed. It's possible to fire webhooks when MR is created/updated but it's impossible to start job when MR is merged/closed. Am I doing something wrong or such functionality is not implemented?

### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 9.2.2
- **Jenkins version**: 2.63
- **Job type**: Freestyle

**Comment by omehegan** [comment]
This feature was added in https://github.com/jenkinsci/gitlab-plugin/pull/508 but not released yet. Look for a release next week.

**Comment by omehegan** [comment]
This was released today in version 1.4.6 of the plugin.
