### ISSUE TITLE
(bool) Should I see a comment that the build has started?

### ISSUE THREAD

**Issue by ElijahLynn** [jenkinsci/gitlab-plugin#571]
## Issue
I don't see a comment posted to a merge request when the build is triggered. Should I?

### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 8.13.1
- **Jenkins version**: 2.27
- **Job type**: Freestyle. 

### Logs & Traces

_Please include any relevant log that could serve to better understand the source of your issue_
For Jenkins Gitlab Plugin logs, follow instruction in [User Support section](https://github.com/jenkinsci/gitlab-plugin#user-support).
For Gitlab logs, ask an administrator to provide you the relevant Gitlab logs.

### Problem description

_Describe your problem in a meaningful way_:
- Trigger build with push or comment keyword... Build triggers successfully
- Message or status to be posted to GitLab MR as a way of informing user the build has started
- Nothing posted as expected

**Comment by omehegan** [comment]
No, we do not post a comment to the MR that a build has started. You can usually see that one has started (GitLab essentially telling you that it triggered the build). For a Freestyle job, Jenkins will notify GitLab when the job completes, if you have that set up as a post-build action.

If you use Pipeline jobs, you can wrap the build steps in an appropriate block which will signal GitLab more dynamically that different parts of the build have started or finished.

**Comment by ElijahLynn** [comment]
Thanks for this @omehegan!
