### ISSUE TITLE
Need a programatic way to create GitLab API credential in Jenkins

### ISSUE THREAD

**Issue by Chrislevi** [jenkinsci/gitlab-plugin#574]
There is no documentation on how to create GitLab API credential via some kind of api/groovy or such, I've swooped the whole web for a snippet. Is there a way to create Gitlab credential via script?

**Comment by omehegan** [comment]
Not that I am aware of.

**Comment by melissafritcher** [comment]
@Chrislevi Do you mean creating Gitlab API Token credential in Jenkins?

**Comment by Chrislevi** [comment]
@melissafritcher I've managed to find a solution, Im using Jenkins CLI to run 'create-credentials-by-xml' with a Dynamic XML generated by Jinja2 templating.

**Comment by tannerjfco** [comment]
I encountered similar need to create the gitlab api credential via groovy. Below is the solution I managed to figure out, adapted from https://gist.github.com/iocanel/9de5c976cc0bd5011653

```
import jenkins.model.*
import com.cloudbees.plugins.credentials.*
import com.cloudbees.plugins.credentials.common.*
import com.cloudbees.plugins.credentials.domains.*
import com.cloudbees.plugins.credentials.impl.*
import com.dabsquared.gitlabjenkins.connection.*
import hudson.util.Secret

domain = Domain.global()
store = Jenkins.instance.getExtensionList('com.cloudbees.plugins.credentials.SystemCredentialsProvider')[0].getStore()

token = new Secret("my-token")

gitlabToken = new GitLabApiTokenImpl(
  CredentialsScope.GLOBAL,
  "gitlab-token",
  "token for gitlab",
  token
)

store.addCredentials(domain, gitlabToken)
```
