### ISSUE TITLE
128 : Failed to connect to GitLab repository

### ISSUE THREAD

**Issue by Bareliah** [jenkinsci/gitlab-plugin#576]
the environment:

- Jenkins 2.19.2
- GitLab Community Edition 8.17.0
- GitLab Plugin 1.4.5

I'm trying to configure GitLab plugin and create Freestryle project.

1. created a jenkins user in GitLab UI
2. created in the jenkins server ssh keys under /var/lib/jenkins/.ssh , chown jenkins:jenkins new key, chmod 600 private_key and chmod 644 public_key
2. Jenkins : under the credentials, added SSH Username with private key
3. GitLab: added the public_key under SSH Keys
4. GitLab: created Access Tokens with api, read_user rights
5. Jenkins: created GitLab API token with the API token from 4
6. Jenkins: configured under Configure System -> Gitlab connection and the Test Connection was success
7. Jenkins: created Freestyle project - under Source Code Management added Repository URL and the right credentials:

```
Failed to connect to repository : Command "git ls-remote -h git@gitlab.domain.com:CDC/CDC.git HEAD" returned status code 128:
stdout: 
stderr: Permission denied, please try again. 
Permission denied, please try again. 
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password). 
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I can ssh to GitLab Server from Jenkins Server with a regular user.

someone had similar problem and has solution?

**Comment by omehegan** [comment]
The error you are seeing is to do with the Git plugin, not the GitLab plugin (this plugin does not handle cloning the repo and does not use these SSH keys). Make sure that the user you created in GitLab also has access rights to the specific repo/project you are trying to clone.
