### ISSUE TITLE
The jenkins update for 1.4.6 is not working the plugin is not found on website

### ISSUE THREAD

**Issue by sfransen** [jenkinsci/gitlab-plugin#579]
http://mirrors.jenkins-ci.org/plugins/gitlab-plugin/1.4.6/

 doesn't contain the plugin to update to.

### Before submitting an issue I have first:

- [] read the documentation on the [homepage](https://github.com/jenkinsci/gitlab-plugin) 
- [] searched for similar already existing issue

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

### Context
- **Gitlab plugin version**: X.Y.Z
- **Gitlab version**: X.Y.Z
- **Jenkins version**: X.Y.Z
- **Job type**: Pipeline, Freestyle, Matrix, etc.

### Logs & Traces

_Please include any relevant log that could serve to better understand the source of your issue_
For Jenkins Gitlab Plugin logs, follow instruction in [User Support section](https://github.com/jenkinsci/gitlab-plugin#user-support).
For Gitlab logs, ask an administrator to provide you the relevant Gitlab logs.

### Problem description

_Describe your problem in a meaningful way_:
- what were you doing (simple push, merge request, MR with fork, ...)
- what was expected
- what occurred finally

**Comment by sfransen** [comment]
http://mirrors.jenkins-ci.org/plugins/gitlab-plugin/1.4.6/ is a empty folder 
 yet Jenkins thinks there is a plugin to update.
and it fails everytime as there is nothing in folder.

**Comment by chizmeeple** [comment]
Related to: https://issues.jenkins-ci.org/browse/JENKINS-42535?focusedCommentId=305856&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-305856 and

**Comment by omehegan** [comment]
There was a problem with the Jenkins update center last night. It is resolved now.
