### ISSUE TITLE
Add separate gitlabActionType for a tag push event

### ISSUE THREAD

**Issue by bbreijer** [jenkinsci/gitlab-plugin#580]
### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 9.1.0
- **Jenkins version**: 2.68
- **Job type**: Pipeline, but not it holds for all job types

### Problem description

On both `"object_kind": "push"` and `"object_kind": "tag_push"` the `gitlabActionType` is set to `PUSH`. This makes people abuse the `gitlabBefore` variable to determine a tag push while the correct information is available in the payload of the webhook.
Proposed solution: add a `TAG_PUSH` actionType.

**Comment by omehegan** [comment]
I sort of see where this is happening in the code (https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/cause/CauseData.java#L375) but I can't work out how exactly this influences the value of gitlabActionType. If anyone else wants to take this on, they can.

**Comment by bbreijer** [comment]
I think the information is lost in the ActionResolver. [https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/webhook/ActionResolver.java](url).
In `WebHookAction()`, both "Push Hook" and "Tag Push Hook" are handled the same. A distinction there could be the solution.
Another (imo better) solution is to change the point where the actual ActionType is set; in `PushHookTriggerHandlerImpl` which is now the same for both object kinds.

Changing the line `.withActionType(CauseData.ActionType.PUSH)` in `PushHookTriggerHandlerImpl` to something like `.withActionType(hook.getObjectKind().equals("tag_push") ? CauseData.ActionType.TAG_PUSH : CauseData.ActionType.PUSH)` and adding the `TAG_PUSH` type to the enum would be a possible solution.

I can change te code if this helps you, but i don't have any testing abilities. Would you like me to create an (untested) pull-request?

**Comment by omehegan** [comment]
@bbreijer I see what you mean. Yeah if you could at least submit a PR, that would be helpful! It's a small enough change that some manual testing would probably be OK, or maybe someone else can add a unit test.

**Comment by omehegan** [comment]
This has just been released in plugin version 1.5.2. It will be in the update center within a few hours.

**Comment by gempain** [comment]
Is this visible in the UI ? I can see it in the `$actionType` parameter, but is there an additional checkbox to differentiate "push" events from "tag push" events ? If not, I think this could be a good idea to differentiate both in the UI.

**Comment by bbreijer** [comment]
The difference is made in the GitLab-webhook setting and will be transferred to the environment of your Jenkins build.
These are two snippets from a normal push and a tag push:
* ``gitlabActionType=PUSH``
* ``gitlabActionType=TAG_PUSH``

**Comment by gempain** [comment]
Thanks for the info :) Keep up the great work !

**Comment by Lylah** [comment]
Would it be possible to have this implemented in a way that the two are completely distinct from one another?
I would like my Jenkins build to trigger on any push event that is NOT a tag push, and currently the trigger on push is a catch-all. I have looked into workarounds for this, and I'm not finding anything that seem remotely reasonable.

**Comment by omehegan** [comment]
@Lylah there isn't really a good way to do this, because GitLab itself does not distinguish between tag pushes and code pushes. The best you can do is filter in your job on the gitlabActionType variable's value.
