### ISSUE TITLE
Show Merge Requests on "Pull Requests" tab in Blue Ocean

### ISSUE THREAD

**Issue by VitorVRS** [jenkinsci/gitlab-plugin#586]
It would be great if this plugins integrates with blue ocean like GitHub does.

I have to manage RefSpecs to BlueOcean recognize my MR's, but they are reconized in Branches tab, not in Pull Requests tab.

How do i fix that?

My RefSpec: `+refs/merge-requests/*:refs/remotes/origin/mr/* +refs/tags/*:refs/remotes/origin/tags/* +refs/heads/*:refs/remotes/origin/*`

**Comment by omehegan** [comment]
@VitorVRS for issues with Blue Ocean support, we may need to ask the Blue Ocean team for help. To do that, please open an issue at http://issues.jenkins-ci.org and put both gitlab-plugin and blueocean-plugin as components. Also please include a link to this issue for my sake. Thanks!
