### ISSUE TITLE
Automatically cancel a build if a new build from the same merge request arrives

### ISSUE THREAD

**Issue by chinhodado** [jenkinsci/gitlab-plugin#588]
In our workflow, we do a lot of `git commit --amend` based on the merge request review, and each push triggers a new build on Jenkins. We only care about the result of the latest build, so we have to manually cancel the old builds to avoid wasting time.

Is there a way to do this "build cancelling" automatically? The basic idea is, if there's a build coming in from a merge request, then cancel all builds (either ongoing or in the queue) that also came from that merge request.

**Comment by omehegan** [comment]
You could do this with Jenkins Pipeline jobs, if you look at the 'milestone' step they support. Your job would have some milestones, and would check if new builds are in the queue, and cancel itself at that point in favor of those.

I don't foresee us supporting this in the plugin itself.

**Comment by jnt2007** [comment]
hmmm... This is not clear for me. I added milestones after each step into my pipeline. And if I start 2 builds with small time difference (start second build when first in progress) both finishes, noone aborts. In every build milestones passes one by one. Something wrong, but what...?
