### ISSUE TITLE
Webhook test fails in Gitlab 9.2.5 - "Execution expired"

### ISSUE THREAD

**Issue by samling** [jenkinsci/gitlab-plugin#592]
### Context
- **Gitlab plugin version**: 1.4.7
- **Gitlab version**: 9.2.5CE
- **Jenkins version**: 2.60.1
- **Job type**: Freestyle

### Problem description

I have a dockerized Jenkins instance running in AWS tied to an elastic IP. It is communicating back to an in-house Gitlab system via openvpn. I have added Gitlab credentials in the general Jenkins configuration and tested the communication with an added API key - this is successful. Further connection tests (e.g. pinging the server, git clones, etc.) are all successful, including running a manual build job with a branch explicitly specified.

However, in my job I've added a build trigger and checked the "Build when a change is pushed to GitLab" box. This gives me my Gitlab CI service URL of the form: http://elastic-ip:8080/project/my-project. Jenkins is not yet using SSL so I've disabled SSL verification. I've added this endpoint as well as a secret token to the webhook configuration for my repo, but running a test just returns "Hook execution failed: execution expired".

I have direct access to Jenkins but have to go through another team member for Gitlab logs/backend configuration. Is there anything I can do to start with on the Jenkins side that would help figure out which side this issue is on?

**Comment by omehegan** [comment]
Look at the User Support section of https://github.com/jenkinsci/gitlab-plugin and follow the directions for increasing logging from the plugin. Then share what you see in those logs after testing the webhook. Let's see if the hook request is even received by Jenkins.

**Comment by samling** [comment]
@omehegan I can confirm the request is not received by Jenkins. I followed those steps yesterday and tried executing a job after clearing the log (as it gets a lot of branch data from running a manual job), and the log remained blank.

**Comment by omehegan** [comment]
If the request is not received by Jenkins, then you have a network issue of some kind. That was what I suspected, given the 'Execution expired' error from GitLab. That's GitLab timing out trying to access the Jenkins URL you gave it for the hook.

**Comment by samling** [comment]
@omehegan I agree, that was my suspicion too, but in every other respect Jenkins and Gitlab are verifiably connected. I'm able to log into the docker host running Jenkins, execute a shell in the Jenkins container, and ping gitlab and clone repositories as usual from the container. Given how strict our work network is, it's very possible there's some firewall rule preventing this one webhook from working; I'm looking into this now with someone from ops; I'll try to pull some Gitlab logs if we can't find anything in the firewall.

Short of that, is there anything I can do to test whether the webhook endpoint is actually accessible? Hitting it in a browser returns a 404, but my understanding from reading is that GET requests will always return a 404 and that it needs a special header from gitlab to initiate a response.

**Comment by samling** [comment]
@omehegan I'm going to close this; after further investigation it looks like we have some odd NATing going on with our Gitlab server that's causing it to not be able to see the Jenkins server, while the Jenkins server is able to see it. We're tracking down the rule responsible. Thanks for helping me verify.

**Comment by Tenmak** [comment]
Did you find out anything ? I suspect there is some proxy involved in this, but I can't find out anything to correct this issue...

**Comment by gempain** [comment]
Same problem here :)

**Comment by mgunjan** [comment]
I am facing similar problem and i suspect proxy issue as my gitlab instance is sitting behind proxy server. How to configure proxy for webhook to use it on gitlab ?

**Comment by cuky23** [comment]
When I saw this , I issued a network restart / reload and they all started working again. so gitlab timing out due to network makes sense to me.

**Comment by jclinto1** [comment]
Will be firewall rules/networking issue
