### ISSUE TITLE
Webhook triggering several build after update

### ISSUE THREAD

**Issue by ViachaslauKabak** [jenkinsci/gitlab-plugin#594]
## Issue
After Jenkins and plugins update there is an issue:
Webhook is triggered build if comment is set to Merge Request (MR).
User adds single comment ('retest' in our case) and several build are triggered

### Context
- **Gitlab plugin version**: 1.4.7
- **Gitlab version**: 8.17.3
- **Jenkins version**: 2.60.1
- **Job type**: Pipeline

################### Logs & Traces
####Global jenkins log
```
Jul 20, 2017 9:11:22 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/CI_test
Jul 20, 2017 9:11:22 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
branch EPMESPVEL-8265 is not allowed
Jul 20, 2017 9:12:49 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/test_accept
Jul 20, 2017 9:13:10 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/MR_test
Jul 20, 2017 9:13:10 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
MR_test triggered for note.
Jul 20, 2017 9:13:45 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/MR_test
Jul 20, 2017 9:13:45 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
MR_test triggered for note.
Jul 20, 2017 9:14:21 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/MR_test
Jul 20, 2017 9:14:21 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
MR_test triggered for note.
```

------
The same issue with webhook for push events. It started 2 jobs
```
WebHook called with url: /project/CI_test
Jul 20, 2017 9:47:54 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
CI_test triggered for push.
Jul 20, 2017 9:47:57 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/CI_test
Jul 20, 2017 9:48:28 AM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
test_accept #1 completed: SUCCESS
Jul 20, 2017 9:49:06 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/CI_test
Jul 20, 2017 9:49:06 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
CI_test triggered for push.
```

[gitlab_plugin_log.txt](https://github.com/jenkinsci/gitlab-plugin/files/1161425/gitlab_plugin_log.txt)

### Problem description

_Describe your problem in a meaningful way_:
- Webhook from gitlab start jenkins job (depends on comment or push to branch).
- Single build started
- Several builds are triggered

**Comment by ViachaslauKabak** [comment]
After issue investigation I have found that gitlab sending additional Webhook. This is caused gitlab webhook timeout default value = 10s. If Gitlab does not receive the responce from jenkins it will send additional request in some time. 
Changing gitlab_rails['webhook_timeout'] = 100 helped but still need to verify why after update plugin could not give a response in 10s.
thanks

**Comment by omehegan** [comment]
I haven't heard of this problem before. 10s seems like a long time unless your Jenkins server is heavily loaded.
