### ISSUE TITLE
Failed to connect to repository, Host key verification failed

### ISSUE THREAD

**Issue by ghost** [jenkinsci/gitlab-plugin#598]
### Context
- **Gitlab plugin version**: 1.4.7
- **Gitlab version**: 9.4.0-ee
- **Jenkins version**: 2.70
- **Job type**: Freestyle

### Problem description

I can't connect to our GitLab repo from a new job. 

1. I configured GitLab plugin following the instructions under "Configuring access to Gitlab". When I press "Test connection" it says "success", but there's an error message saying "API Token for Gitlab access required"

![image](https://user-images.githubusercontent.com/30043122/28511648-677b3324-704e-11e7-81b7-2d519e1dd5fd.png)

2. I added a new account to my project with *master* role. I added jenkin's machine public ssh key.

3. When I try configure my project, the credentials dropdown only shows "-none-" and the connection can't be established

![image](https://user-images.githubusercontent.com/30043122/28511784-0261097c-704f-11e7-9320-b5c1aa779a16.png)

### Logs & Traces

Logs on Jenkins seem to be able to connect to GitLab

```
Response body: 
Jul 24, 2017 6:56:46 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Call GitLab:
HTTP method: HEAD
URL: https://gitlab.com/api/v3/user
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]
Jul 24, 2017 6:56:49 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Got response from GitLab:
URL: https://gitlab.com/api/v3/user
Status: 200 OK
Response headers: [
Cache-Control = [no-cache],
Content-Length = [755],
Content-Type = [application/json],
Date = [Mon, 24 Jul 2017 06:56:49 GMT],
Server = [nginx],
Strict-Transport-Security = [max-age=31536000],
Vary = [Origin],
X-Frame-Options = [SAMEORIGIN],
X-Request-Id = [673a9f81-81d5-4a83-98d9-fb2d79d146a2],
X-Runtime = [0.103601]
]
```

**Comment by omehegan** [comment]
You are confusing two different types of credentials. The GitLab API key credential is only needed for sending build status to GitLab after a Jenkins job completes. Putting that key in the GitLab configuration area in your first screenshot is one step that is needed. If 'Test Connection' works there, you are all set with this.

The Git SSH credential is needed for cloning repos. That is strictly related to the Git plugin, not the GitLab plugin. If you are having issues getting that to work, consult the documentation for the Git plugin. You may want to try clicking the 'Add' button you see next to that Credentials dropdown, and explicitly creating a Jenkins credential which refers to the Jenkins user's SSH keys on the filesystem. That should solve that problem.

**Comment by ghost** [comment]
Hi Falks,

I got a below-attached error in the image and I don't understand what need to do.

![jkns](https://user-images.githubusercontent.com/36878845/37270755-fe9e01c0-25f5-11e8-8ca0-4470aeb47110.JPG)
