### ISSUE TITLE
Jenkins does not block a build when changing assignee in a Merge Requests

### ISSUE THREAD

**Issue by josh-barker** [jenkinsci/gitlab-plugin#603]
### Context
- **Gitlab plugin version**: 1.4.7
- **Gitlab version**: 9.0.5
- **Jenkins version**: 2.60.1
- **Job type**: Pipeline

### Problem description

I want to trigger builds on merge requests events and use a shared library to simplify pipeline definitions.

Jenkins Configuration:
* Build Trigger Configuration - Git:
  * Only watches for "Opened Merge Request Events"
  * "Rebuild open Merge Requests" is "Push to source"
* Pipeline Script:
  * Loads/uses a shared library
* Inside the shared library, it uses a `checkout` to pull down the code from Gitlab

Gitlab Configuration:
* Project has a webhook integration to the Jenkins job, with `Merge Request Events` and `Note Events`

What I do to show the bug:
* Pull down the project code
* Create a new branch locally
* Make some changes
* Push to Gitlab
* Create Merge Request
  * **Jenkins** runs build
* Change assignee merge request
  * **Jenkins** runs another build

However, I expect Jenkins **not** to rebuild after I have changed the assignee.

After doing some researching and logging, I found that only 1 `BuildData` object was being returned for each build. See `Logs & Traces` for output. 

The relevant source code I've found includes:

* https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/util/BuildUtil.java#L15
* https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/util/BuildUtil.java#L30
* https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/util/BuildUtil.java#L41

I've been able to patch one occurrence by using the following:
```
public static Run<?, ?> getBuildBySHA1IncludingMergeBuilds(Job<?, ?> project, String sha1) {
    for (Run<?, ?> build : project.getBuilds()) {
        for(BuildData data : build.getActions(BuildData.class)) {
            if (data != null
                && data.lastBuild != null
                && data.lastBuild.getMarked() != null
                && data.lastBuild.getMarked().getSha1String().equals(sha1)) {
                return build;
            }
        }
    }
    return null;
}
```

compared with https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/util/BuildUtil.java#L39-L50

### Logs & Traces

From the script console, I can run:
```
import hudson.plugins.git.util.BuildData

job = Jenkins.instance.getItemByFullName('sample_project', org.jenkinsci.plugins.workflow.job.WorkflowJob.class)
job.getBuilds().each { build ->
 println build
 BuildData data = build.getAction(BuildData.class);
 println data
}
```

This shows that it only returns 1 BuildData object, even though multiple exist.

> sample_project #49
> hudson.plugins.git.util.BuildData@2d27426e[scmName=<null>,remoteUrls=[git@my.git.lab.com:pipeline/standard_pipeline.git],buildsByBranchName={...},lastBuild=Build #49 of Revision 099bb1ce2a646dedfed646acd5bc0e18c7ba49b6 (master)]
> sample_project #48
> hudson.plugins.git.util.BuildData@2d26eaf0[scmName=<null>,remoteUrls=[git@my.git.lab.com:pipeline/standard_pipeline.git],buildsByBranchName={...},lastBuild=Build #48 of Revision 099bb1ce2a646dedfed646acd5bc0e18c7ba49b6 (master)]

```
import hudson.plugins.git.util.BuildData

job = Jenkins.instance.getItemByFullName('sample_project', org.jenkinsci.plugins.workflow.job.WorkflowJob.class)
job.getBuilds().each { build ->
  // It is possible for a build to have multiple BuildData actions
  // since we can use the Mulitple SCM plugin.
  println build
  def gitActions = build.getActions(hudson.plugins.git.util.BuildData.class)
  if (gitActions != null) {
    for (action in gitActions) {
      println action
    }
  }
}
```

> sample_project #49
> hudson.plugins.git.util.BuildData@2d27426e[scmName=<null>,remoteUrls=[git@my.git.lab.com:pipeline/standard_pipeline.git],buildsByBranchName={...},lastBuild=Build #49 of Revision 099bb1ce2a646dedfed646acd5bc0e18c7ba49b6 (master)]
> hudson.plugins.git.util.BuildData@7f307e4f[scmName=<null>,remoteUrls=[git@my.git.lab.com:test_cookbooks/sample_project.git],buildsByBranchName={...},lastBuild=Build #49 of Revision d1c432cd836590f1c2d879ece1c3c06a31e8ebeb (origin/feature/g)]
> sample_project #48
> hudson.plugins.git.util.BuildData@2d26eaf0[scmName=<null>,remoteUrls=[git@my.git.lab.com:pipeline/standard_pipeline.git],buildsByBranchName={...},lastBuild=Build #48 of Revision 099bb1ce2a646dedfed646acd5bc0e18c7ba49b6 (master)]
> hudson.plugins.git.util.BuildData@bc8c7da9[scmName=<null>,remoteUrls=[git@my.git.lab.com:test_cookbooks/sample_project.git],buildsByBranchName={...},lastBuild=Build #48 of Revision 76449fc6613323ba8d5d0231cdcfbe93d8b53a29 (origin/feature/f)]

**Comment by omehegan** [comment]
This was released today in version 1.4.8 of the plugin.
