### ISSUE TITLE
Gitlab credentials is not showing in the dropdown

### ISSUE THREAD

**Issue by niksw7** [jenkinsci/gitlab-plugin#605]
On Manage Jenkins -> Configure System, in the Gitlab section, there's a Credentials section that had a drop-down list where I should be able to specify an API Token. The drop down says "-none" and has no other options. If I choose Add -> Jenkins, then under Kind I can select "GitLab API token" and put in the info, and click Add. But the credential I've added does not show up in the drop-down, so I can't select it, and I have the red "API Token for Gitlab access required" message.
I expect to be able to see the API token credential I have added in the drop-down list so I can select it and connect. But it is not there.
As a result I am unable to use the plugin at all.

Here are the versions i am using
jenkins version  2.72
Credentials plugin version 2.1.14
gitlab plugin 1.4.7

There is also an issue marked here
https://issues.jenkins-ci.org/browse/JENKINS-36863

Please let me know if there is any work around for this

**Comment by omehegan** [comment]
Copying and pasting the text from a bug that was filed and fixed year ago is a bit annoying. Just because you are seeing the same behavior doesn't mean it's caused by the same issue as before, so do us a favor and express the problem in your own words.

I'll have to see if we can reproduce this. It may be an issue with changes to the credentials plugin.

**Comment by niksw7** [comment]
The issue is exactly the same, but the cause could be different.  I didn't want to raise a new bug for that same issue.
Here is my quick analysis. I will send a PR for the same.
The UserRemoteConfig in git plugin ignores the `api token` in the dropdown as it checks only for instances of StandardUsernamePasswordCredentials and SSHUserPrivateKey. 
Making GitLabTokenImpl extend any of the above classes does not make sense.
A quick fix is to make UserRemoteConfig in gitplugin is to check for  StandardCredentials than specific StandardUsernamePasswordCredentials.

Do let me know if you have any other thoughts on it


-Nikesh

**Comment by Rukeith** [comment]
I still got this issue.

**Comment by torquemad** [comment]
I'm experiencing this issue, but without the text 'none' displaying in the dropdown

**Comment by niksw7** [comment]
I guess it's It's not fixed yet. @stephenc has commented on below thread for the right way to fix this
https://github.com/jenkinsci/git-plugin/pull/527
Also the gitlab does not support api token.(Not sure what's the status currently)
https://issues.jenkins-ci.org/browse/JENKINS-36863?focusedCommentId=310260&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-310260

**Comment by samirthebti** [comment]
I had the same issue ! my Jenkins instance running  in docker

**Comment by d35t1201** [comment]
This still happens

**Comment by jasonbrianhall** [comment]
Been fighting this issue all day.

**Comment by grzechup** [comment]
I also have this issue

**Comment by 1312655689** [comment]
hi, any update for this issue?
