### ISSUE TITLE
Wrong GitLab Merge Request ID

### ISSUE THREAD

**Issue by rmaheo** [jenkinsci/gitlab-plugin#610]
Related to closed issue #290 

### Context
- **Gitlab version**: 8.12.1
- **Teamcity version** : 10.0.2

### Problem description

I'm requesting .../api/v3/projects/1/merge_requests/**2357** and I have this :

```
id | 2357
-- | --
iid | 2355
project_id | 1
title | "WIP FC-5258 : Oracle Accounting Export"
description | ""
[...]
merge_when_build_succeeds | false
merge_status | "can_be_merged"
[...]
web_url | "http://.../wodh/ten/merge_requests/2355"
```

Data (title, web_url, merge_status, iid etc) from another merge request (2355). 

Everything was running well until 26th july.

**Comment by omehegan** [comment]
I don't really understand the issue. You're getting unexpected data back from the GitLab API? How is this related to the plugin?
