### ISSUE TITLE
Webhook test fails in Gitlab 9.2.5 - "Execution expired"

### ISSUE THREAD

**Issue by dahinton11** [jenkinsci/gitlab-plugin#623]
**Context**

Gitlab plugin version: 1.4.7
Gitlab version: 9.2.4EE
Jenkins version: 2.60
Job type: Freestyle

**Description**
We are having issues hooking up a Jenkins with our GitLab. 
We have followed setups steps located here without success.
Every time it will say execution expired. 

We have set up the link multiple different ways including this jenkinsci and also  including the following: Basic webhook, Jenkins CI and Jenkins CI(deprecated).
We have even set up a Post URL to Jenkins to fire off a job. We can access it via URL with the token and runs great. 

We have attempted connection in the Jenkins job using the repository url and credentials. No error here, we have tried, API Token, SSH and UserName/Password without any luck. All with no error on the connection. 

When tested from GitLab we receive a of "Internal Error" "execution expired" No other message being sent.  We have GitLab Plug logging enabled in Jenkins, but see nothing even getting there. Is there logs on the Gitlab side to see why the connection fails or times out.

**Comment by omehegan** [comment]
You have a network issue between Jenkins and GitLab. This is not a plugin bug.
