### ISSUE TITLE
Is there a way to access the webhooks event from Jenkins side? like  currentBuild.rawBuild.getCauses()?

### ISSUE THREAD

**Issue by jing-cui** [jenkinsci/gitlab-plugin#625]
### Context
- **Gitlab plugin version**: 1.4.7
- **Gitlab version**: GitLab Community Edition 9.3.10
- **Jenkins version**: 2.60.3
- **Job type**: Multibranch Pipeline

### Logs & Traces

println "CAUSE ${currentBuild.rawBuild.getCauses()}"

[Pipeline] echo
CAUSE [jenkins.branch.BranchIndexingCause@8fb302]

### Problem description
we are trying to find out which build trigger triggered our multibranch pipeline build from Gitlab webhooks.  we have set up merge request and tag push triggers... we are trying to differentiate the web hook events to control our build ( a full build based on tag push vs a common build based on MR). How do we access the webhook event from Jenkins side? Does Jenkins side log the Gitlab webhook event info? Jenkins multibranch scan pipeline log doesn't have the event information, not the request header info X-Gitlab-Event: Tag Push Hook etc. 

we have tried in our JenkinsFile 
println "CAUSE ${currentBuild.rawBuild.getCauses()}"

and got the following BranchIndexingCause(multibranch scanning)

[Pipeline] echo
CAUSE [jenkins.branch.BranchIndexingCause@8fb302]

Maybe this should be a Jenkins issue to ask. any help would be greatly appreciated

**Comment by omehegan** [comment]
As of now, the env.gitlabActionType variable will show you whether a build was triggered by a PUSH or MERGE trigger. When #589 is merged, hopefully for the next release, it will add support for TAG_PUSH as being separate from a regular PUSH.

If this answers your question, please close the issue.

**Comment by jing-cui** [comment]
Hi Omehegan, thanks for your help. I tried my multibranch pipeline with the following code, but couldn't get the PUSH or MERGE trigger.     my Jenkins version 2.60.3 and Gitlab plugin 1.4.7. 

```    stage ('Check Build Trigger event') {
            steps {
                    script {
                        switch(env.gitlabActionType) {
                            case 'PUSH':
                                echo "PUSH Event"
                                break
                            case 'MERGE':
                                echo "MERGE Event"
                                break
                            default:
                                echo "Default Value Event"
                        }
                    }
                }
        }```

**Comment by omehegan** [comment]
Why don't you just echo the value of env.gitlabActionType to start with, and see what it contains?

Hmm, it's also possible that we don't set these values when it's a multibranch job...

**Comment by jing-cui** [comment]
The  resolution is Fixed and the status is IN REVIEW. Do we know which version of Jenkins will have this?

https://issues.jenkins-ci.org/browse/JENKINS-45196

Thanks,
Jing

**Comment by jing-cui** [comment]
Hi Omehegan, thanks for your response.
The  resolution for the following issue is Fixed and the status is IN REVIEW. Do we know which version of Jenkins will have this?
https://issues.jenkins-ci.org/browse/JENKINS-45196

**Comment by omehegan** [comment]
Yes I forgot about this limitation. For multibranch jobs I'm not sure if any further plugin work will have to be done to resolve it.

**Comment by jdcskillet** [comment]
We are pretty heavy users of Multibranch pipelines - it seems as if the comments for triggering a build also do not work. Is there an overarching "problem" with multibranch that would preclude these variables from being used in multibranch? I imagine it is a fairly large problem set.

**Comment by omehegan** [comment]
See #704
