### ISSUE TITLE
Hook execution failed: execution expired

### ISSUE THREAD

**Issue by paintingStyle** [jenkinsci/gitlab-plugin#627]
#####  使用 http://localhost:8080/buildByToken/build?job=tyfocgApp&token=6b1cb76736418840a74687ef，将IP地址换成localhost后，gitLab报错Hook executed successfully but returned HTTP 404
该如何解决？谢谢

### Context
- **Gitlab plugin version**: 1.4.8
- **Gitlab version**: 官方最新版本
- **Jenkins version**: 2.7.7

**Comment by paintingStyle** [comment]
#####1, if I use the Build triggers the plug-in Build the when a change is pushed to GitLab GitLab CI Service URL options provide a URL, http://192.168.91.18:8080/project/tyfocgApp

By GitLab, the WebHook function is called: Hook execution failed: execution expired

#####2, use http://192.168.91.18:8080/buildByToken/build? Job =tyfocgApp&token=6b1cb76736418840a74687ef will have the same error message as above: Hook execution failed: execution expired

#####3, use http://localhost:8080/buildByToken/build? Job =tyfocgApp&token= 6b1cb76736418840a74687ef, replace the IP address with localhost
GitLab's WebHook feature:
Hook, successfully, but returned HTTP 404

How to solve it? thank you

**Comment by omehegan** [comment]
You have a network connection issue between GitLab and your Jenkins server.

Do not use 'buildByToken.' That bypasses this plugin completely.

**Comment by JokerDevops** [comment]
I met the same problem. How did you solve it?

**Comment by JokerDevops** [comment]
@omehegan
