### ISSUE TITLE
GitLab API token credential type is missing: cannot create Gitlab connection

### ISSUE THREAD

**Issue by Vince-Cercury** [jenkinsci/gitlab-plugin#630]
### Context
- **Gitlab plugin version**: 1.4.8
- **Gitlab version**:  8.6.9-ee
- **Jenkins version**: 2.79
- **Job type**: Pipeline

### Logs & Traces
See screenshot of the GitLab connection: http://picpaste.com/Screen_Shot_2017-09-21_at_2.10.44_pm-szGLceKU.png
See screenshot of the credential page with only one kind available (GitLab API token is not available): http://picpaste.com/Screen_Shot_2017-09-21_at_2.10.54_pm-zZeOAKyM.png

### Problem description

Just installed the plugin
Go to Jenkins Configure, under GitLab connections
In the dropdown under credentials, click on Add.
The only kind available is "Username with password" (GitLab API token is not available as an option)
Try to add username and password anyway, it does not show up in the Gitlab connection credentials dropdown 

Am I doing something wrong or missing a plugin?

**Comment by omehegan** [comment]
Did you ever resolve this problem? If not, what version of the Credentials plugin are you using?

**Comment by Vince-Cercury** [comment]
I use version 2.1.16 of credentials plugin. Gitlab token still not available

**Comment by omehegan** [comment]
I can't get your original picpaste links to load. You can just drag images to the comment text box and Github will attach them.

You might want to try updating to the latest version of the GitLab plugin.

All I can say is, the option is visible for me:

![screen shot 2018-03-23 at 4 37 30 pm](https://user-images.githubusercontent.com/1775894/37813306-a22e0f9a-2eb8-11e8-85a4-a84487e0fbdb.png)

**Comment by QAAAAAAAA** [comment]
![image](https://user-images.githubusercontent.com/33018205/56205040-4c5e4080-607b-11e9-8866-bdcf938adc98.png)

same issue, @omehegan  please help

Jenkins version: 2.170
GitLab Plugin: 1.5.11
Credentials Plugin: 2.1.18
