### ISSUE TITLE
Support for Personal Access Tokens (Private Tokens deprecated)

### ISSUE THREAD

**Issue by cdbennett** [jenkinsci/gitlab-plugin#635]
### Problem description

GitLab 10.0 release announcement state that Private Tokens are going to be removed in GitLab 10.2 (November 2017) and Personal Access Tokens should be used instead:

> Private Tokens
> Private tokens allow a mechanism to access the API with a token unique to your user account.
> Personal Access Tokens provide more granular access to GitLab via the API and are recommended over using Private Tokens.
> Private Token support will be removed in GitLab 10.2 as we feel they are less secure that Personal Access Tokens.
> Due: September 22nd, 2017. 
 -- [GitLab 10.0 Release Announcement](https://about.gitlab.com/2017/09/22/gitlab-10-0-released/#private-tokens)

The [GitLab API documentation "basic usage"](https://docs.gitlab.com/ee/api/README.html#basic-usage) section seems to be referred to for both Private Token and Personal Access Token authentication.

#### Code change required?
It may be that the Jenkins gitlab-plugin requires no change to support Personal Access Tokens, if they are passed through the same way as Private Tokens.  It sounds like only the process of generating the token differs.

#### Documentation/help update needed
This should be tested and perhaps the documentation or the gitlab-plugin configuration screens/help updated to indicate that Personal Access Tokens can and should be used for current GitLab versions.

**Comment by omehegan** [comment]
@dblessing can you comment on this when you have a chance? Is @cdbennett correct in thinking that passing a Personal Access Token the same way we pass a Private Token today will work? If so I will just update the documentation accordingly.

**Comment by bikebilly** [comment]
@omehegan you should be able to use PATs in the same way you are now using Private Tokens. PATs are very easy to manage, so you can just give it a try creating one with `api` scope.

In case of problems, let me know as soon as possible so we can consider helping in the migration, or even reconsidering the removal of Private Tokens in 10.2.

**Comment by omehegan** [comment]
@bikebilly thanks, I will look into it. Were PATs first introduced in 10.0?

**Comment by bikebilly** [comment]
@omehegan no, they were introduced in GitLab 8.8 :smile: 
https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html#personal-access-tokens

Feel free to ask if you need more help on testing PAT.

**Comment by cdbennett** [comment]
I tested this and indeed the Personal Access Tokens seem to be working with Jenkins and the GitLab Plugin.
