### ISSUE TITLE
Jenkins spinning up thousands of jobs from all branches vs just newly opened ones.

### ISSUE THREAD

**Issue by smd1000** [jenkinsci/gitlab-plugin#637]
### Context
- **Gitlab plugin version**: 1.4.8
- **Gitlab version**: 9.3.5
- **Jenkins version**: 2.73.1
- **Job type**: Pipeline and Freestyle

### Problem description

- I have a pipeline job setup to listen for Open merge requests from a branch, and to trigger a downstream build based on file pattern. All new branches should be able to trigger this build, however, when jenkins sees a new open merge request, it spawns thousands of jobs vs just that one MR.

So, the basic workflow _should_ be this:

*A dev opens an MR against master. This branch could be named anything. 
*Gitlab triggers the `MergeRequestEvent` pipeline. All branches are allowed to trigger this "Super Job"
*The `MergeRequestEvent` job triggers a downstream build based on file-pattern.
*Only NEW branches that have an MR opened against master should be able to trigger a build.

**Comment by omehegan** [comment]
This sounds like a configuration problem. I would need to see the configuration of the job that GitLab triggers before I could say anything more, but I doubt this is a plugin issue.

**Comment by smd1000** [comment]
Hi, thanks for the quick response. I'm sure you're right.  Here's my config in the `MergeRequestEvent` "super-job". The project is a mono-repo, which contains a number of sub modules. Each sub-module has it's own job (although that can be reduced) whose job is triggered by pattern matching whichever file changed so `mono-repo/job1/file.xm` should trigger `job1` which only builds `job1`.

![screen shot 2017-10-10 at 11 37 06 am](https://user-images.githubusercontent.com/20912574/31410129-dab0b902-adc2-11e7-94ca-abab713aa31b.png)

![screen shot 2017-10-10 at 11 37 19 am](https://user-images.githubusercontent.com/20912574/31410144-e133c10c-adc2-11e7-872a-4f422334c30d.png)

![screen shot 2017-10-10 at 11 41 18 am](https://user-images.githubusercontent.com/20912574/31410160-e77a3b2c-adc2-11e7-8d92-a930f5d69bf8.png)

**Comment by omehegan** [comment]
This is going to trigger a build of the job1 project for every file it finds in the job1 directory. It doesn't sound like that is what you want. Either way, this is not a plugin bug.
