### ISSUE TITLE
1.5.0 fails to accept merge requests when using the API V4

### ISSUE THREAD

**Issue by nbarrientos** [jenkinsci/gitlab-plugin#652]
### Context
- **Gitlab plugin version**: 1.5.0
- **Gitlab version**: 9.5
- **Jenkins version**: 2.73.2

### Logs & Traces

```
Oct 30, 2017 2:22:40 PM
com.dabsquared.gitlabjenkins.publisher.GitLabAcceptMergeRequestPublisher
perform
SEVERE: Failed to accept merge request for project '8348'
javax.ws.rs.NotFoundException: HTTP 404 Not Found
```

### Problem description

We have the impression that when asking the plugin to use the V4 API, at the time of merging a merge request, the ID of the MR passed via the URL is the global one, making the request fail.

This looks correct in terms of how the URL is composed and the variables used:

```java

    @PUT
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Path("/projects/{projectId}/merge_requests/{mergeRequestIid}/merge")
    @Override
    void acceptMergeRequest(@PathParam("projectId") Integer projectId,
                            @PathParam("mergeRequestIid") Integer mergeRequestIid,
                            @FormParam("merge_commit_message") String mergeCommitMessage,
                            @FormParam("should_remove_source_branch") boolean shouldRemoveSourceBranch);
```

However the value of ```mergeRequestIid``` is not the internal identifier but the global one. The GitLab logs kind of confirm this theory.

Could you please try to reproduce this behaviour?

Thanks.

**Comment by Argelbargel** [comment]
I'll look into it tonight or tomorrow...

**Comment by Argelbargel** [comment]
I can confirm this is a bug. We thought it would be enough to simply change the calls to the api made from the plugin but we have to adapt the code selecting the merge-request-id, too. Will implement this asap.
