### ISSUE TITLE
Build status for commit in Gitlab not happening

### ISSUE THREAD

**Issue by yuvgeek** [jenkinsci/gitlab-plugin#662]
### Context
- **Gitlab plugin version**: 1.5.1
- **Gitlab version**: Using gitlab.com (I can't find)
- **Jenkins version**: 2.60.3
- **Job type**: Freestyle

### Problem description

_Describe your problem in a meaningful way_:
- what were you doing (simple push, merge request, MR with fork, ...)
Commit a file to repo. Jenkins build image and job success. Added job for Publish build status to Gitlab commit 

- what was expected
Build status for commit in Gitlab

- what occurred finally
Nothing happens.

**Comment by Argelbargel** [comment]
I can confirm the problem, but i've got no idea, why reporting the status won't work with gitlab.com :/

**Comment by omehegan** [comment]
@dblessing can you offer any insight here? I'm never sure what to do with folks who are integrating with gitlab.com.

**Comment by omehegan** [comment]
@yuvgeek is this still an issue for you?

**Comment by yuvgeek** [comment]
No issue. It's working.

**Comment by rachit-gupta** [comment]
I am facing an issue where I have 2 projects on gitlab. For one of the projects, publish build status to gitlab is working as expected, but for the other project, it is not working. Both the projects and the Jenkins job are set up similarly.

**Comment by omehegan** [comment]
@rachit-gupta please create a new issue for this. Follow the directions in https://github.com/jenkinsci/gitlab-plugin#getting-help to enable debug logging and attach logs after you reproduce the failure.
