### ISSUE TITLE
Automatic project creation should work with Jenkins Folders

### ISSUE THREAD

**Issue by gguillotin** [jenkinsci/gitlab-plugin#663]
### Context
- **Gitlab plugin version**: 1.5.1
- **Gitlab version**: 10.1.1
- **Jenkins version**: 2.32.3
- **Job type**: Freestyle

### Problem description

We are using Gitlab plugin in order to trigger builds automatically and create jobs on branches creations.
It used to work as expected. But we are now trying to use this for jobs in folders (using the Cloudbee"s Folders plugin).

Integration is working OK, except that new jobs are always created in root of Jenkins.

For example, if I have https://jenkins.domain/job/MyFolder/job/MyJob, configured to look at the master branch of my Gitlab project, when I create a new branch from master (that I call "test"), the following is created : https://jenkins.domain/job/MyJob_test. Not in the right folder.

But, if I do a search in Jenkins for "MyJob", here is what I get : 
 - MyJob
 - MyJob_test
 - MyFolder MyJob
 - MyFolder/MyJob_test

The last link is not working. It seems to be related to the "/" added to it.

Am I missing something ?

**Comment by omehegan** [comment]
@gguillotin does the method shown in #686 work for you?

**Comment by omehegan** [comment]
@gguillotin ping?
