### ISSUE TITLE
External Pipelines not shown

### ISSUE THREAD

**Issue by joerg-wille** [jenkinsci/gitlab-plugin#665]
## Issue
I have 2 gitlab projects, both use a webhook to trigger an external jenkins pipeline via jenkins gitlab plugin. The only difference is that the first project is a “Jenkins Pipeline Project” and the other is a “Jenkins Multibranch Project”. In first project I can see the result of the external pipeline in gitlab, in the second not.
(I have also asked this [question in the gitlab troubleshooting forum](https://forum.gitlab.com/t/external-pipelines-not-shown/12588) )

### Context
- **Gitlab plugin version**: 1.5.1
- **Gitlab CE version**: 10.1.3
- **Jenkins version**: 2.73.3
- **Job type**: Multibranch Pipeline Project with Declarative Syntax

Do I need to configure the gitlab project somehow differently?
Or do I need to configure the jenkins-multibranch project somehow differently?
Has anyone successfully configured a Jenkinsfile ans -project, which updates gitlab status in the gitlab pipeline view?

**Comment by omehegan** [comment]
@joerg-wille I suspect this is due to #704.

**Comment by omehegan** [comment]
Actually I may be wrong about that. Can you share the configuration of your Multibranch project? If you are just saying that build status is not appearing in GitLab for that project type, it should work.
