### ISSUE TITLE
gitlab global settings "test connection" fails unconditionally

### ISSUE THREAD

**Issue by a2f0** [jenkinsci/gitlab-plugin#669]
### Context
- **Gitlab plugin version**: 1.4.8 & 1.5.1
- **Gitlab version**: https://gitlab.com
- **Jenkins version**: 2.73.3 & 2.60.3
- **Job type**:  N/A

### Logs & Traces

```
Nov 16, 2017 6:30:01 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Call GitLab:
HTTP method: HEAD
URL: https://gitlab.com/api/v3/user
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]
Nov 16, 2017 6:30:02 PM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Got response from GitLab:
URL: https://gitlab.com/api/v3/user
Status: 400 Bad Request
Response headers: [
Cache-Control = [no-cache],
Connection = [keep-alive],
Content-Type = [text/html]
]
Response body: 
```

### Problem description

This problem is easily reproducible.  I have a feeling it is related Gitlab updating their platform today as my Gitlab connection was working fine but broke suddenly today.  The issue can be reproduced by:

1. Do a clean pull of the jenkins docker image
2. Install the gitlab plugin upon first setup
3. Configure an API key credential in https://gitlab.com
4. In Jenkins global setting, configure the credential and https://gitlab.com and click "Test Connection".  This will generate an ERROR.  The com.dabsquared debug log generated by this failure is above.  I get the same results with using the v4 api on the 1.5.1 plugin.

**Comment by omehegan** [comment]
Maybe related to https://github.com/jenkinsci/gitlab-plugin/issues/608 ? Need @dblessing or someone from GitLab to take a look.

**Comment by a2f0** [comment]
Thank you for your support @omehegan & @dblessing.  Whatever problem this is/was has appeared to go away on its own.  I am resolving this issue.
