### ISSUE TITLE
Error does not appear if a problem during MR accept

### ISSUE THREAD

**Issue by ViachaslauKabak** [jenkinsci/gitlab-plugin#675]
## Issue
While accept there is an error that MR squash was failed. But plugin did not return any error.

### Context
- **Gitlab plugin version**: 1.4.8
- **Gitlab version**: 8.17.3-ee
- **Jenkins version**: 2.73.2
- **Job type**: Pipeline

### logs
logs from gitlab
```
ERROR -> MergeRequests::SquashService error (velcom/hyb-velcom!864): Failed to apply patch with `/opt/gitlab/embedded/bin/git diff --binary 5596174cbb1d694518f332e2833b182e670367d8...7da2eb7171101c3760a9b940d6f9cc0c47598d9d | /opt/gitlab/embedded/bin/git apply --index`:
ERROR -> MergeRequests::SquashService error (?????????????/???-?????!864): error: patch failed: <FILE>:10
error: <FILE>: patch does not apply
<stdin>:464: new blank line at EOF.
+
<stdin>:499: new blank line at EOF.
+
<stdin>:556: new blank line at EOF.
+
<stdin>:620: new blank line at EOF.
+
```
### Problem description

While accepting MR the option to squash commits is turned on. MR cannot be accepted (Failed to squash. Should be done manually). But the pipeline "accepted" MR without any error or notification.
Expected: any error appear
What is actually: MR is not accepted and nobody knows about this

**Comment by omehegan** [comment]
I don't understand what behavior you are seeing on the Jenkins side. You accept the MR in GitLab, then squash fails. Does Jenkins trigger a build or not?
