### ISSUE TITLE
Search the whole build records leading to Jenkins hang

### ISSUE THREAD

**Issue by KorosuYoo** [jenkinsci/gitlab-plugin#676]
### Context
- **Gitlab plugin version**: 1.5.1
- **Gitlab version**: 9.5.9
- **Jenkins version**: 2.46.2
- **Job type**: Pipeline

### Logs & Traces
many logs like this:
```
Nov 29, 2017 3:22:52 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/UI/UI-package/major-release/gauth/gauth-package
Nov 29, 2017 3:22:51 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/UI/go/ui-api_MR
Nov 29, 2017 3:22:51 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/UI/UI-package/major-release/inventory/inventory-package
Nov 29, 2017 3:22:51 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/UI/UI-package/major-release/ui_api/ui_api-package
Nov 29, 2017 3:22:51 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/UI/go/inventory_MR
Nov 29, 2017 3:22:51 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/UI/go/Auth_MR
Nov 29, 2017 3:22:51 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
```
### Problem description
I set many MR webhooks on one single project on gitlab, so when a MR created/merged/updated the webhooks will concurrently trigger many jenkins jobs. My problem is these high concurrent jobs will make jenkins hanging, and I find that Jenkins concurrency building strategy isnot work for these jobs. These jobs donot go into the waiting queue at the first.It is not make sense.

**Comment by Argelbargel** [comment]
Okay, do i understand you correctly - you've set up multiple webhooks for your project ("UI") and each webhook (correctly) triggers a project in jenkins? 
As far as i understand the code, this plugin simply triggers the build - queue-management etc. should not be affected by this plugin. I myself use gitlab/jenkins in a similar manner and the jobs get properly queued if the number of executors is exhausted (running to many builds concurrently also stalls our jenkins, though).
So i'd propose that you either try to restrict the number of executors on your nodes or use another plugin like [Build Blocker](https://wiki.jenkins.io/display/JENKINS/Build+Blocker+Plugin) or [Throttle Concurrent Builds](https://wiki.jenkins.io/display/JENKINS/Throttle+Concurrent+Builds+Plugin) to restrict the number of builds running concurrently

**Comment by KorosuYoo** [comment]
@Argelbargel I think I find the root cause: https://github.com/jenkinsci/gitlab-plugin/blob/2a5493962d6cf0f873f10752c9a06ccdc20b36b1/src/main/java/com/dabsquared/gitlabjenkins/util/BuildUtil.java#L40  
Here is a function named "getBuildBySHA1IncludingMergeBuilds". It is called by the function named "isLastCommitNotYetBuild" which is in: https://github.com/jenkinsci/gitlab-plugin/blob/c92e972426f313374ff3e537f31e859633f1d17d/src/main/java/com/dabsquared/gitlabjenkins/trigger/handler/merge/MergeRequestHookTriggerHandlerImpl.java
It will check the MR ever builded.So when there are many webhook jobs(maybe 10+) in one gitlab project, and each of these jobs have many build records(maybe 10,000+) ,it will take long time to search more than 10 * 10,000 = 100,000 build records for one MR request. During the searching, Jenkins home page can not be visited. It seems Jenkins hang.

**Comment by omehegan** [comment]
This could be a problem, but if you are keeping 10,000 build records for your jobs, that's a bad practice which is going to cause numerous other performance headaches (I speak from experience). There probably isn't an easy way to make this check more performant in a use case like that.
