### ISSUE TITLE
Pipeline ref name incorrect for tag push events

### ISSUE THREAD

**Issue by gempain** [jenkinsci/gitlab-plugin#677]
### Context
- **Gitlab plugin version**: 1.5.2
- **Gitlab version**: 10.2.2
- **Jenkins version**: 2.73.3
- **Job type**: Freestyle

### Problem description

When a build is triggered by a tag push event, the CI job branch name that appears in Gitlab CI is wrong:
![pipeline](https://user-images.githubusercontent.com/13135149/33368255-76199968-d4f1-11e7-8acc-a1f24fa7821c.png)
I would expect `refs/tags/<tag-name>` to be `<tag-name>`.

This has two consequences:
- it conflicts with Gitlab CI native behavior: for a tagged commit, CI jobs use the tag name as job branch name:
![pipeline_gitlab_ci](https://user-images.githubusercontent.com/13135149/33368463-0cf05746-d4f2-11e7-8743-e7fdb99eb5e7.png)
- when you click the title, it should take you to `<gitlab-url>/<repo-path>/commits/<tag-name>`, but it actually takes you to `<gitlab-url>/<repo-path>/commits/refs/tags/<tag-name>`, which returns a 404.

Edit: here is an even better example:
<img width="993" alt="screen shot 2017-12-01 at 00 58 50" src="https://user-images.githubusercontent.com/13135149/33461466-e087907e-d632-11e7-8b7a-2f0014fa0e05.png">

**Comment by omehegan** [comment]
I suspect this is an issue with how we return data to GitLab for builds triggered by tags. Needs investigation.

**Comment by omehegan** [comment]
Released in version 1.5.7.

**Comment by rililinx** [comment]
Hi. I faced with it in:
 gitlab plugin version: 1.5.10
Gitlab version: 11.2.3
Jenkins version: 2.138.2
Job type: Freestyle
