### ISSUE TITLE
Git plugin's refspec and branch specifier conflict with Gitlab plugin's branch filtering

### ISSUE THREAD

**Issue by gempain** [jenkinsci/gitlab-plugin#681]
### Context
- **Gitlab plugin version**: 1.5.2
- **Gitlab version**: 10.2.2
- **Jenkins version**: 2.73.3
- **Job type**: Freestyle

### Problem description

Git filter branches seems to conflict with Gitlab plugin's branch filtering. 

I have setup a job with the following configuration:
**Source Code' Management (git)**
- **Refspec:** +refs/heads/dev:refs/remotes/origin/dev
- **Branch Specifier:** origin/dev

**GitLab plugin**
- **Build on successful pipelines:** checked (true)
- **Allowed branches**: Allow all branches to trigger this job

This result in my job being triggered by both pushes on `dev` and `master`. It therefore seems that the git **refspec** and **branch specifiers** from the Git plugin are being ignored. The only solution I found is to just use **Filter branches by name** and enter `dev` and autocomplete.

**Comment by omehegan** [comment]
@gempain I don't think this is a bug. It's true that the GitLab plugin does not check anything in terms of what you enter in the branch specifier for the Git plugin. The GitLab plugin just triggers builds based on the webhooks that GitLab sends it. If you want to only trigger for certain branches, you need to use 'Filter branches by name,' as you have figured out. Entering a branch specifier in the Git plugin config only controls what branches will be fetched from the repo when you clone.

Please reopen if you think I have misunderstood.

**Comment by gempain** [comment]
@omehegan Thanks for the answer, you got it right :) But now I have another question for you: is it possible to filter branches using wildcards ? That would be great. For example, I'd like to run a job for `dev` and `release/*` and `feature/*`. Is that possible ?

**Comment by omehegan** [comment]
@gempain yes. This is described in the 'Branch filtering' section of the README. https://github.com/jenkinsci/gitlab-plugin#branch-filtering  You will probably want to use the regex filter.
