### ISSUE TITLE
Build Triggers option get reset 

### ISSUE THREAD

**Issue by cs-mahmoud-khateeb** [jenkinsci/gitlab-plugin#682]
When I check the option "Build when a change is pushed to GitLab. GitLab CI Service URL: <URL>" in "Build Triggers", it works only once, then when I come back to check, I find the checkbox unchecked.

**Comment by karlgb** [comment]
You didn't include any versioning info as described in User Support, but I could not duplicate this issue. Are you sure you clicked Save after configuring the job..?

**Comment by omehegan** [comment]
Yes, this was a bug in old versions of the plugin. Please let us know what version you are using, and update to the latest if possible.

**Comment by f00f** [comment]
I second @omehegan response. I had observed this behaviour until recently (which is why I found this ticket), but it's fixed for me now (running GitLab plugin 1.5.2 now).
