### ISSUE TITLE
Clarification on how auth works?

### ISSUE THREAD

**Issue by kraftman** [jenkinsci/gitlab-plugin#685]
For some reason gitlab isn't accepting my jenkins credentials for one project (it used to be fine and works for other projects):
```
'stderr: GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.'
```
When I change the Credentials dropdown to 'none' it works fine, which is odd because i thought that was what jenkins uses to authenticate with gitlab.

I found this ticket:
https://issues.jenkins-ci.org/plugins/servlet/mobile#issue/JENKINS-36863
which says the credentials aren't used for the connection, and to check the docs, but I've read the docs and I can't see anywhere how it authenticates. It says you can optionally connect the plugin to gitlab to fetch extra information, but does this also provide credentials for git projects if none are specified?

**Comment by omehegan** [comment]
@kraftman can you clarify whether you are referring to credentials used for cloning a repo, or credentials used for Jenkins to send build status to GitLab? If you are referring to the former, that is unrelated to this plugin.

**Comment by kraftman** [comment]
Ahh it's the former, I assumed since you set the gitlab connection at the top it used those credentials to clone. Thanks for the info.
