### ISSUE TITLE
Hook executed successfully (HTTP 200) but pipeline not triggered 

### ISSUE THREAD

**Issue by benfab** [jenkinsci/gitlab-plugin#687]
Hello,

When using Declarative Pipeline Syntax,  GitLab executes successfully push hooks, but the pipeline isn't triggered on Jenkins. Nevertheless, the pipeline is triggered when I am not using the Declarative Pipeline Syntax (Jenkins Build Trigger box).

I am using the pipeline from example the repo readme, see below:

```
pipeline {
    agent any
    post {
      failure {
        updateGitlabCommitStatus name: 'build', state: 'failed'
      }
      success {
        updateGitlabCommitStatus name: 'build', state: 'success'
      }
    }
    
    options {
      gitLabConnection('mygitlabconnection')
    }
    triggers {
        gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All')
    }
    stages {
      stage("build") {
        steps {
          echo "hello world"
        }
      }
    }
  
}
```
### Context
- **Gitlab plugin version**: 1.5.2
- **Gitlab version**: GitLab Community Edition 9.5.5
- **Jenkins version**: 2.73.1
- **Job type**: Pipeline (Declarative Pipeline Syntax)

### Logs and traces ##

On GitLab, the response body from Jenkins is empty.
On the plugin logs, there is nothing else than the request body from GitLab.

I would appreciate any help or tips to investigate this issue further.
Thank you!

**Comment by omehegan** [comment]
@benfab I would need to see the actual Jenkins logs (see the User Support section of the README on how to enable full logging) to understand what happened. If the plugin receives the webhook but does not trigger a job, it should log the reason.
