### ISSUE TITLE
${gitlabSourceBranch} incorrectly shows "master" on MergeRequest hooks

### ISSUE THREAD

**Issue by adveres** [jenkinsci/gitlab-plugin#688]
## Issue
Upon opening a merge request, I submit a generic webhook to Jenkins to start a project build. The documentation is unspecific on which environment variable is the branch being built, and I swear is inconsistent on whether it's `${gitlabBranch}` or `${gitlabSourceBranch}` (why are there two?).

The only documentation I seem to able to find is:
* This other bug about it: https://github.com/jenkinsci/gitlab-plugin/issues/330 so my Jenkins job does indeed have a String parameter for `gitlabSourceBranch`, defaulted to `master`.
* The [README](https://github.com/jenkinsci/gitlab-plugin#parameterized-builds) which has no details about what gets put into each environment variable; it simply lists them.

What I'm trying to do:
1. I would like to conditionally deploy when the source branch is `master` (ie: I've just merged to master, so build it then do a deploy. [This is blocked by a separate bug](https://github.com/jenkinsci/gitlab-plugin/issues/636).).
2. Set the build name to show the branch that was built.
3. If I just click "Build with Parameters" in Jenkins, have it do the `master` build/deploy flow.

### Context
- **Gitlab plugin version**: 1.5.2
- **Gitlab version**: 10.1.4-ee
- **Jenkins version**: 2.95
- **Job type**: Freestyle (maven)

### Logs & Traces
On the GitLab side this is the POST body (I've trimmed anything that didn't seem pertinent):
```json
{
  "object_kind": "merge_request",

  "object_attributes": {
    "target_branch": "master",
    "source_branch": "foo",
    "title": "test pipeline foo",
    "created_at": "2017-12-15 16:17:54 UTC",
    "updated_at": "2017-12-15 16:17:54 UTC",
    "state": "opened",
    "merge_status": "unchecked",
    "ref_fetched": true,
    "source": {
      "default_branch": "master",
    },
    "target": {
      "default_branch": "master",
    },
    "last_commit": {
      "id": "e134f338fe65b66b30bb24b3fe71ae776897bf1f",
      "message": "test pipeline foo\n",
      "timestamp": "2017-12-15T11:14:10-05:00",
    },
    "action": "open"
  }
}

```

On Jenkins these are the environment variables I get:
```bash
gitlabActionType=MERGE
gitlabBranch=foo     # Why does this exist??
gitlabMergeRequestState=opened
gitlabMergeRequestTitle=test pipeline foo
gitlabMergedByUser=averes
gitlabSourceBranch=master    #THIS SEEMS WRONG, should be foo
gitlabTargetBranch=master
```

### Problem description

_Describe your problem in a meaningful way_:
- **what were you doing**
  - I opened a new merge request from branch `foo`->`master`
- **what was expected**
  - I expect that on the Jenkins side `${gitlabSourceBranch}` is `foo`
  - [The code even suggests that should be the case](https://github.com/jenkinsci/gitlab-plugin/blob/f5b171343ca1d1c3a8b21e3b157d212ad6e54127/src/main/java/com/dabsquared/gitlabjenkins/cause/CauseData.java#L116) because the POST has `"source_branch": "foo"`.
- **what occurred finally**
  - `${gitlabSourceBranch}` is `master`, but `${gitlabBranch}` is `foo`.
  - No documentation really exists on which env var I'm supposed to use.

**Comment by omehegan** [comment]
@adveres gitlabBranch exists because in a push webhook there are no source and target branch fields. I'm not sure why gitlabSourceBranch is getting set incorrectly in your case. It is clearly a bug, they should be equivalent.

**Comment by omehegan** [comment]
Oh, try removing the gitlabSourceBranch job parameter... or don't default it to master.

**Comment by adveres** [comment]
Based on https://github.com/jenkinsci/gitlab-plugin/issues/330, I need the parameter to exist.  I suppose defaulting it to "master", as I was, may not be necessary.

## Testing done

### In Jenkins:
* Job parameter `gitlabSourceBranch ` made to be empty by default.
* Branch Specifier (blank for 'any'): `origin/${gitlabSourceBranch}`
* Add a pre-build shell step that calls `env | sort`

### Made a MR in Gitlab, which posted (I cut out not pertinent information):

```
Request headers:
Content-Type: application/json
X-Gitlab-Event: Merge Request Hook

Request body:
{
  "object_kind": "merge_request",
  "object_attributes": {
    "target_branch": "development",
    "source_branch": "foo",
    "title": "Testing jenkins pipeline",
    "created_at": "2018-01-17 15:52:07 UTC",
    "updated_at": "2018-01-17 15:52:07 UTC",
    "state": "opened",
    "merge_status": "unchecked",
    "description": "Why:\ngitlab issue test: https://github.com/jenkinsci/gitlab-plugin/issues/688",
      "default_branch": "master"
    },
    "target": {
      "default_branch": "master"
    }
}
```

### And in Jenkins job I got these env vars:

```
10:52:38 gitlabActionType=MERGE
10:52:38 gitlabBranch=foo
10:52:38 gitlabMergeRequestState=opened
10:52:38 gitlabMergeRequestTitle=Testing jenkins pipeline
10:52:38 gitlabMergedByUser=averes
10:52:38 gitlabTargetBranch=development
```

## Conclusion
So, interestingly, `gitlabBranch` is set correctly to `foo`, but `gitlabSourceBranch` is missing from the environment, because it was an empty parameter, perhaps?

It does seem to work, as it built my `foo` branch.  Is there any possibility on just making the docs clearer on what to do when parameterizing a build?  I suppose it's only because I want to be able to run the job manually *and* from GitLab triggers. However it was inconsistent if I pre-filled the parameter - so maybe that bears investigation.

-----

Thank you! And I like your avatar :)

**Comment by omehegan** [comment]
@adveres yes, the bug you reference was specific to someone who wanted to be able to trigger the build both manually and through webhooks. In that case you do need to create a parameter for the job. If you ONLY want to trigger with webhooks, the parameter is unnecessary. And I think that some changes in Jenkins (maybe since that time) caused parameter values to supersede the env var values that are set by the webhook. That would explain why you always got 'master' even for webhook-triggered builds. I agree that there is a doc improvement needed here, I will take that.

**Comment by adveres** [comment]
Thank you, @omehegan !
