### ISSUE TITLE
Link to gitlab merge request url in getShortDescription posted to jenkins

### ISSUE THREAD

**Issue by clkao** [jenkinsci/gitlab-plugin#69]
It'd be helpful if the builds in jenkins have the urls of the merge requests that trigger the build.

**Comment by Nakilon** [comment]
I use http://wiki.jenkins-ci.org/display/JENKINS/Description+Setter+Plugin with following parameters:
```
GitLab Merge Request #(\d+) : (.+)
<a href="https://git.improvemedia.ru/marvin/MarvinProject/merge_requests/\1">\2</a>
```

**Comment by jpappe** [comment]
:+1: to this. I currently have a bunch of tests that run via GitLab Merge Request Builder Plugin which does link to the merge request. I'm playing around with migrating to this plugin and it would be a welcome addition.
