### ISSUE TITLE
Gitlab dosn't get report from Jenkins about builds status

### ISSUE THREAD

**Issue by dorgolan** [jenkinsci/gitlab-plugin#690]
### Context
- **Gitlab plugin version**:1.5.2
- **Gitlab version**: 10.0.5-ee
- **Jenkins version**: 2.73.2
- **Job type**: Freestyle

There is no relevant logs that i can point of on Gitlab server/Jenkins server. 

### Problem description
after any build that finish to run on Jenkins (simple push, merge request...), the build dosn`t report to Gitlab  job result . (failed/success with link to the job.)
- what was expected: to see job result on Gitlab UI.

The other side Gitlab-Jenkins sync is good. for example, when we open merge request on Gitlab, Gitlab trigger Jenkins job like we expected. the problem is that when this job is finish, he dosnt give Gitlab any information regarding the result of the job. developer cant know (through Gitlab) if job started, aborted, succeeded or failed).

**Comment by ttsalonen** [comment]
Have you added the "Publish build status to GitLab commit" post-build action to the job?

**Comment by idkCpp** [comment]
- **GitLab plugin version:** 1.5.2
- **Jenkins version:** 2.89.2
- **GitLab version:** 10.3.3 CE
- **Job type:** Maven Project

I configured Jenkins and GitLab like mentioned [on the wiki](https://github.com/jenkinsci/gitlab-plugin/wiki/Setup-Example). But somehow on the GitLab side there is nothing that indicates any of the Jenkins actions...

**Comment by omehegan** [comment]
Reopen if you have set up the publish post-build step and it still isn't working.
