### ISSUE TITLE
Snippet Generator for pipeline triggers broken

### ISSUE THREAD

**Issue by philmcardle** [jenkinsci/gitlab-plugin#692]
### Environment
- **Gitlab plugin version**: 1.5.2
- **Jenkins version**: Jenkins LTS ver. 2.89.2

### Issue

The only other report I can see for this is a series of comments on #417, starting [here](https://github.com/jenkinsci/gitlab-plugin/issues/417#issuecomment-276300663), but I can't find a standalone issue on GitHub or JIRA.

As per linked comment, the snippet generator generates `pipelineTriggers([<object of type com.dabsquared.gitlabjenkins.GitLabPushTrigger>])` for any configuration of the pipeline triggers section for GitLab ("Build when a change is pushed to GitLab, unknown URL"), making it very difficult to get started with the plugin when using pipeline.

**Comment by TobiX** [comment]
That should have been fixed by https://github.com/jenkinsci/gitlab-plugin/commit/b34d64be43db55a56c32dfd6c4c163c0ec372e77 - but that doesn't seem the work...

**Comment by omehegan** [comment]
@philmcardle are you using regular Pipeline jobs, or Multibranch Pipeline? For regular Pipeline jobs, you can just click the 'Build when a change is pushed to GitLab' box and configure accordingly. For Multibranch Pipelines, you don't need to create a trigger. As per the README, "Unlike other job types, there is no 'Trigger' setting required for a Multibranch job configuration; just create a webhook in GitLab for push requests which points to http://JENKINS_URL/project/PROJECT_NAME or http://JENKINS_URL/project/FOLDER/PROJECT_NAME if the project in inside a folder in Jenkins."

Please let me know if that helps.

**Comment by TobiX** [comment]
@omehegan Well, but that doesn't help if you configure the Job properties from the Pipeline script itself, since it will be overwritten on every build...

Currently I'm using this syntax:
```
                [
                        $class               : 'GitLabPushTrigger',
                        branchFilterType     : 'NameBasedFilter',
                        triggerOnPush        : true,
                        triggerOnMergeRequest: false,
                        ciSkip               : true,
                        includeBranchesSpec  : branchName,
                        excludeBranchesSpec  : '',
                        setBuildDescription  : true
                ]
```

**Comment by philmcardle** [comment]
As @TobiX, I'm using the properties step in a regular pipeline job.

**Comment by omehegan** [comment]
OK, I guess I can see some use cases for configuring the properties even in regular Pipeline jobs (code reuse, etc.).

**Comment by danilaml** [comment]
There is a nice plugin configuration in settings but I haven't figured out how to turn it into declarative pipline syntax descriptions. README is really lacking with only `gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All')`. No Idea how to configure advanced options and it really differs from code elsewhere.

**Comment by anton-johansson** [comment]
Seems unrelated to the OP's issue, but the title matches my issue(s) too, so I'll post it here.

When I use the snippet generator för the trigger part, I get the following error message:
```
no public field ‘acceptMergeRequestOnSuccess’ (or getter method) found in class com.dabsquared.gitlabjenkins.GitLabPushTrigger
```

When I use the snippet generator för `acceptGitLabMR`, I get this:
```
no public field ‘useMRDescription’ (or getter method) found in class com.dabsquared.gitlabjenkins.workflow.AcceptGitLabMergeRequestStep
```

**Comment by amdokamal** [comment]
Hi. I see similar behavior (Jenkins 2.186, Gitlab Plugin 1.5.13) in **Snippet Generator**:
```java
properties([gitLabConnection('JenkinsDevopsGit'), 
   pipelineTriggers([<object of type com.dabsquared.gitlabjenkins.GitLabPushTrigger>])])
```
failing which people have to study `gitlab-plugin` code to find all parameter values. For example, `triggerOpenMergeRequestOnPush`: _<never | source | both>_, I've found in `GitLabPushTrigger.java`.

**Comment by kdopen** [comment]
Can confirm the snippet generator issue (Jenkins 2.2.29, Plugin 1.5.13).

* Launch Declarative Snippet generator
* Select "triggers" and "Gitlab"
* Without changing anything just click "generate"

Result is `no public field ‘acceptMergeRequestOnSuccess’ (or getter method) found in class com.dabsquared.gitlabjenkins.GitLabPushTrigger`.

Significantly, the options presented in the UI (even with ADVANCED expanded) do not include one for this parameter. I suspect that is the cause.
