### ISSUE TITLE
Gitlab plugin ignores NO_PROXY field of HTTP proxy settings

### ISSUE THREAD

**Issue by asmorkalov** [jenkinsci/gitlab-plugin#697]
My Jenkins setup operates with set of intranet and internet resources. Internet access requires proxy settings. I added proxy configuration to Jenkins settings and also add all local resources to NO_PROXY list. With the configuration Gitlab plugin reports HTTP 401 error on each HTTP request to local Gitlab. Plugin works correctly, If I totally disable proxy.

The issue is localized at https://github.com/jenkinsci/gitlab-plugin/blob/316b8bebb8927081547d31333ec76e1c97b98f25/src/main/java/com/dabsquared/gitlabjenkins/gitlab/api/impl/ResteasyGitLabClientBuilder.java#L98

But it looks like RestEasyClientBuilder does not support NO_RPOXY. I'm ready to contribute fix, if you have any hint how to implement NO_PROXY logic.

**Comment by Argelbargel** [comment]
Hi, i‘ll look into it. Just to be sure, the correct way would be to not just check whether a proxy was configured at all but whether a proxy should be used for a specific resource identified by an url?

**Comment by asmorkalov** [comment]
Yes, you are right. NO_PROXY option specifies list of hosts to be connected directly without proxy, etc localhost.

**Comment by asmorkalov** [comment]
@Argelbargel the proposed patch does not resolve the issue. It looks looks like we have some miscommunication.
Jenkins has proxy settings for proxy address, port, credentials and no_proxy field. The no_proxy field works like `no_proxy` environment variable in Linux and its logic is pretty simple: if target host for connection then direct connection is used, otherwise connection is established via proxy.

**Comment by Argelbargel** [comment]
Hmmm... That is exactly what the patch should do - take  a look at the test in GitLabConnectionConfigTest#doCheckConnection_noProxy(). 

There i configure jenkins' proxy-settings to use 0.0.0.0 as proxy (which will always fail as seen in doCheckConnection_proxy()) and use no proxy for requests to localhost. As the connection succeeds this should indicate that connections to hosts in the no_proxy field do not use the proxy.

I did some manual testing using the docker-images and this seemed to work correctly. If this does not work for your setup could you add some screenshots of where you configure the proxy-settings (this change depends on the settings made in the plugin-manager /pluginManager/advanced).

**Comment by omehegan** [comment]
@asmorkalov can you give us some more feedback on your issue? I'll hold off merging the proposed fix to make sure it resolves the problem.

**Comment by asmorkalov** [comment]
@Argelbargel I'll return to the issue on the next week. I want to try it in my setup and provide feedback. Thanks a lot!

**Comment by omehegan** [comment]
@asmorkalov ping?
