### ISSUE TITLE
Build gets triggered Irrespective of branch

### ISSUE THREAD

**Issue by LahariGuntha** [jenkinsci/gitlab-plugin#699]
Hi,

 I have code at some repository and my repository has a  master and branch  named branch1...
I have to trigger a job in jenkins whenever there is a change in the 'branch1' branch not in the master...
I have configured gitlab properly...
For this I have set the "Branch Specifier" as /refs/head/branch1 ....In this case it has to watch the changes in the branch that we have specified and should trigger a jenkins job...but it is triggering  the job even when there is change in the master...

What are all the other options that we have inorder for my use case to work??

**Comment by karlgb** [comment]
The "Branch Specifier" is the branch to be built. To control which branches trigger the build, you'll want to configure options in the "Build Triggers" section of the job (click the Advanced button to expose more options for that section). There are several fields to consider, but the idea is to filter the Allowed branches to "branch1" which will achieve what you want.

**Comment by omehegan** [comment]
@karlgb is correct. If you have further issues in #702 please follow up there.
