### ISSUE TITLE
Gitlab plugin updates library commit status instead of project

### ISSUE THREAD

**Issue by yagnik** [jenkinsci/gitlab-plugin#706]
## Issue
When using multibranch pipeline, if you have such scenario:
```
- use library that loads implicitly 
- update gitlab status (pending)
- clone actual repo
- update gitlab status (success)
```

In this case pending status ends up going to the library repo as opposed to the actual repo.
From the code

### Context
- **Gitlab plugin version**: 1.5.2
- **Gitlab version**: 9.5.5
- **Jenkins version**: 2.89.2
- **Job type**: Multibranch pipeline

**Comment by omehegan** [comment]
@yagnik I think this is a known issue, to do with how we figure out where to send the status - in a Multibranch project it's based on the repo clone, not the JSON payload we get from GitLab. IMO the best we can do is add something to the documentation to say that you should not send status until you have cloned the actual working repo. What do you think?

**Comment by yagnik** [comment]
@omehegan would you mind helping me understand how we decide which repo ?
I got a little confused in the code, I expected multibranch to also have the git repo details and use that over the library. 

Is there something specific missing in the multibranch pipeline that we need to send status before clone ?

**Comment by omehegan** [comment]
@yagnik the plugin figures out where to send the status update by looking at what repo was last cloned. So I think you will not be able to send status to the right place until you have cloned your actual project repo; before that, status will be sent to your global library repo instead, which is obviously not what you want.

**Comment by yagnik** [comment]
Yep, thanks for clarifying!
