### ISSUE TITLE
gitlabMergedByUser sometimes not present

### ISSUE THREAD

**Issue by sebastienbonami** [jenkinsci/gitlab-plugin#715]
### Context
- **Gitlab plugin version**: 1.5.3
- **Gitlab version**: 10.4.3
- **Jenkins version**: 2.89.4
- **Job type**: Freestyle

### Problem description
In Jenkins, I want to get the author's username of the MR that triggered the job. Sometimes, the *gitlabMergedByUser* environment variable don't exist. Is *gitlabMergedByUser* supposed to be the author of the MR? If so, it should always be there so we have a bug here.

**Comment by omehegan** [comment]
@sebastienbonami can you see any difference between cases where the variable is set and ones where it is not?

Please enable the additional logging described in the User Support section of the README, and then attach logs from a case where the variable was not set. I especially want to see the JSON payload from GitLab, to see if there is something unusual about it.

**Comment by omehegan** [comment]
@sebastienbonami ping?

**Comment by sebastienbonami** [comment]
@omehegan I can't see any difference between cases where the variable is set or not. It looks random for me.

Here's the log of an example where the variable _gitlabMergedByUser_ was not set. _gitlabMergeRequestAssignee_ was not set either (**sbonami** was the author and also the assignee of the MR).

```
Note: {
  "object_kind" : "note",
  "user" : {
    "name" : "Sébastien Bonami",
    "username" : "sbonami",
    "avatar_url" : "http://git.foobar.com/uploads/-/system/user/avatar/10/2733db4.jpg"
  },
  "project_id" : 89,
  "project" : {
    "id" : 89,
    "name" : "test",
    "description" : "",
    "web_url" : "http://git.foobar.com/sbonami/test",
    "avatar_url" : null,
    "git_ssh_url" : "git@git.foobar.com:sbonami/test.git",
    "git_http_url" : "http://git.foobar.com/sbonami/test.git",
    "namespace" : "sbonami",
    "visibility_level" : 0,
    "path_with_namespace" : "sbonami/test",
    "default_branch" : "master",
    "ci_config_path" : null,
    "homepage" : "http://git.foobar.com/sbonami/test",
    "url" : "git@git.foobar.com:sbonami/test.git",
    "ssh_url" : "git@git.foobar.com:sbonami/test.git",
    "http_url" : "http://git.foobar.com/sbonami/test.git"
  },
  "object_attributes" : {
    "id" : 57188,
    "note" : "Jenkins please retry a build",
    "noteable_type" : "MergeRequest",
    "author_id" : 10,
    "created_at" : "2018-04-10 20:36:50 UTC",
    "updated_at" : "2018-04-10 20:36:50 UTC",
    "project_id" : 89,
    "attachment" : null,
    "line_code" : null,
    "commit_id" : "",
    "noteable_id" : 4798,
    "system" : false,
    "st_diff" : null,
    "updated_by_id" : null,
    "type" : null,
    "position" : null,
    "original_position" : null,
    "resolved_at" : null,
    "resolved_by_id" : null,
    "discussion_id" : "295236a86afb9c1499091d3e7c6e4ae1246b7fdc",
    "change_position" : null,
    "resolved_by_push" : null,
    "url" : "http://git.foobar.com/sbonami/test/merge_requests/11#note_57188"
  },
  "repository" : {
    "name" : "test",
    "url" : "git@git.foobar.com:sbonami/test.git",
    "description" : "",
    "homepage" : "http://git.foobar.com/sbonami/test"
  },
  "merge_request" : {
    "assignee_id" : 10,
    "author_id" : 10,
    "created_at" : "2018-04-10 20:36:06 UTC",
    "description" : "",
    "head_pipeline_id" : null,
    "id" : 4798,
    "iid" : 11,
    "last_edited_at" : null,
    "last_edited_by_id" : null,
    "merge_commit_sha" : null,
    "merge_error" : null,
    "merge_params" : {
      "force_remove_source_branch" : "1"
    },
    "merge_status" : "can_be_merged",
    "merge_user_id" : null,
    "merge_when_pipeline_succeeds" : false,
    "milestone_id" : null,
    "source_branch" : "test3",
    "source_project_id" : 89,
    "state" : "opened",
    "target_branch" : "master",
    "target_project_id" : 89,
    "time_estimate" : 0,
    "title" : "3",
    "updated_at" : "2018-04-10 20:36:09 UTC",
    "updated_by_id" : 10,
    "url" : "http://git.foobar.com/sbonami/test/merge_requests/11",
    "source" : {
      "id" : 89,
      "name" : "test",
      "description" : "",
      "web_url" : "http://git.foobar.com/sbonami/test",
      "avatar_url" : null,
      "git_ssh_url" : "git@git.foobar.com:sbonami/test.git",
      "git_http_url" : "http://git.foobar.com/sbonami/test.git",
      "namespace" : "sbonami",
      "visibility_level" : 0,
      "path_with_namespace" : "sbonami/test",
      "default_branch" : "master",
      "ci_config_path" : null,
      "homepage" : "http://git.foobar.com/sbonami/test",
      "url" : "git@git.foobar.com:sbonami/test.git",
      "ssh_url" : "git@git.foobar.com:sbonami/test.git",
      "http_url" : "http://git.foobar.com/sbonami/test.git"
    },
    "target" : {
      "id" : 89,
      "name" : "test",
      "description" : "",
      "web_url" : "http://git.foobar.com/sbonami/test",
      "avatar_url" : null,
      "git_ssh_url" : "git@git.foobar.com:sbonami/test.git",
      "git_http_url" : "http://git.foobar.com/sbonami/test.git",
      "namespace" : "sbonami",
      "visibility_level" : 0,
      "path_with_namespace" : "sbonami/test",
      "default_branch" : "master",
      "ci_config_path" : null,
      "homepage" : "http://git.foobar.com/sbonami/test",
      "url" : "git@git.foobar.com:sbonami/test.git",
      "ssh_url" : "git@git.foobar.com:sbonami/test.git",
      "http_url" : "http://git.foobar.com/sbonami/test.git"
    },
    "last_commit" : {
      "id" : "e864ef9522c465b863bdaaa489a11d84a70fea63",
      "message" : "3",
      "timestamp" : "2018-04-10T16:36:00-04:00",
      "url" : "http://git.foobar.com/sbonami/test/commit/e864ef9522c465b863bdaaa489a11d84a70fea63",
      "author" : {
        "name" : "Sébastien Bonami",
        "email" : "sebastien.bonami@foobar.com"
      }
    },
    "work_in_progress" : false,
    "total_time_spent" : 0,
    "human_total_time_spent" : null,
    "human_time_estimate" : null
  }
}
```
Thanks!

**Comment by omehegan** [comment]
The example JSON you included above is from a comment event, not a merge request event. That is probably why it doesn't populate the gitlabeMergedByUser variable. You may want to change your webhook config in GitLab to not send comment events.

**Comment by sebastienbonami** [comment]
@omehegan You're right, *gitlabMergedByUser* seems to be only absent when it's a comment event. However, I want to use comment events to retry builds.

My question remains: Is *gitlabMergedByUser* supposed to be the author of the MR? If so, it should be renamed to *gitlabMergeRequestAuthor* and I don't see why it's not set for comment events.

Thanks.

**Comment by omehegan** [comment]
@sebastienbonami the code for this is a bit hard for me to decipher, but from what I can tell gitlabMergedByUser is set by the `username` value from the webhook, and that is described here: https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#merge-request-events  It is not clear to me whether the value of that is, as you said, actually the author of the MR, or the person who actually merged it. The GitLab reference docs do not explain the possible states for these keys, so it can be hard to figure this out. In theory GitLab could send different values depending on the action of the webhook (close, merge, etc.). 

@m9abbas you wrote the code which added these env vars. Can you answer this question?

**Comment by m9abbas** [comment]
@omehegan `gitlabMergedByUser` is the identifier of the user who accepted the merge request

**Comment by omehegan** [comment]
@m9abbas do you mean the user who clicked "Merge" in GitLab?

**Comment by m9abbas** [comment]
@omehegan Yes it is the user who clicked on "Merge" or "Close"

**Comment by omehegan** [comment]
@sebastienbonami I think the above answers your question. And I think for your use case, gitlabUserName may work.

**Comment by jenniferhuang** [comment]
I still have this issue:
gitlabMergeRequestLastCommit: xxxxxxxxx.    (this is right)
but ,the following variable always are null when we read it like ${env.gitlabMergeRequestTitle}
gitlabMergedByUser: null
gitlabMergeRequestTitle: null
gitlabMergeRequestId: null
