### ISSUE TITLE
builds for gitlab hook job being combined

### ISSUE THREAD

**Issue by john-forrest** [jenkinsci/gitlab-plugin#716]
### Context
- **Gitlab plugin version**: 1.5.3
- **Gitlab version**: 10.4.3
- **Jenkins version**: 2.89.4
- **Job type**: Pipeline

### Problem description

If several builds are fired on the same hook job in quick succession, Jenkins is combining them - even though they relate to different repositories and should never be combined.

I support a subsystem where a library is formed using over 20 different repos. The repos are compiled individually and are linked together using cmake packages, When one of these packages are replaced (following an MR acceptance) we compile not only that repository, but also all other repos that use it. The dependency graph depends on the version and is discovered dynamically at build time. We use the same "module push" job for almost all our modules - doubt it is important but the job runs a central Jenkinsfile in yet another repo, since they all run the same and it is easier to maintain that way. When one of the push builds is running, since they potentially all update binary versions of packages, we block other such builds using the Build Blocker plugin - so things do not get mixed up. Builds can last anything from 20 min to 2 hours, depending on which package is being rebuilt - really on how many packages there are "downstream" in the dependency graph.

It does not happen often, but we recently had a scenario where about 15 MRs were merged almost simultaneously - it was a very simple change that was applied separately in each repository. What should have happened is that we got 15 build jobs, but actually the first one started building and subsequent ones combined together - so we only had two. As said, these were supposed to be builds for different git repositories so are not really combinable.

Typically we should only hit this scenario if there three or more merge acceptances in quick succession. In our local process, this does not happen that often but could - especially as the team looking after the code gets larger. I need to somehow fix this behaviour. I would be quite happy if somebody pointed out an option I'd missed to not combine/collapse jobs, but as it stands this looks like a bug.

BTW we have another job for merge requests, again shared between many repositories. It is quite normal to get multiple versions of those jobs at the same time, although those jobs don't block. We've not noticed the issue on those jobs.

I have a way to rebuild manually, and am having to do this if I spot the problem. I might have to set up a timed job to rebuild everything just in case something is missed. However, it is not an ideal scenario - I prefer to rebuild on demand.

**Comment by omehegan** [comment]
@john-forrest so you have many different GitLab repos all set up with webhooks that trigger the same Jenkins job? And that is a Pipeline job? If so I think this might be a "feature" of Pipeline. Is there any chance you are using a `milestone` step in the pipeline? See https://wiki.jenkins.io/display/JENKINS/Pipeline+Milestone+Step+Plugin  Unfortunately for this use case you may need to disable the concurrency of the Pipeline job in order to avoid this issue. But I would need to see some Jenkins logs to know for sure what is happening.

**Comment by stchar** [comment]
@john-forrest, If gitlab-plugin have an option to notify any repository you want right from the pipeline would that make your life better?

**Comment by john-forrest** [comment]
I'm not sure. Issue I suspect is that the parameters are virtually the same for each push job. I don't see this on MR jobs. How do they differ?

**Comment by stchar** [comment]
@john-forrest ,
I can only suggest to capture some logs from `hudson.model.Queue` class
I believe you'll be interested in capturing of this line
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Queue.java#L722

PS. This could be tough =)

**Comment by omehegan** [comment]
If we're not talking about an issue with this plugin anymore, please close this issue. Otherwise my previous questions to @john-forrest stand.

**Comment by john-forrest** [comment]
I am going to close this although the issue is still there. Not really in a position to deal with the request - it is outside my area and unfortunately don't have the time to deal with it :(

**Comment by john-forrest** [comment]
I'm going to re-open this as the issue has unfortunately become a problem for us.

I've been doing some some digging and I noticed this issue on subversion which sounded similar: https://issues.jenkins-ci.org/browse/JENKINS-18534

I think the potential issue is that the reponame (the target repo name?) has to be setup in the "equals" statement. I notice that project and projectId appear in the equals statement for class PushHook - I am guessing that is the key class here, but only a guess. However, I see no places where they are set. I'm assuming if they are null then the comparison would be fine.

Can anybody state whether these properties are supposed to be Jenkins projects or gitlab projects? IF the latter, where should they be set?

**Comment by omehegan** [comment]
@john-forrest I asked some questions in https://github.com/jenkinsci/gitlab-plugin/issues/716#issuecomment-375194866 which you haven't answered. As a general rule this plugin should trigger a new build for each hook request it gets from GitLab. If those triggered builds get combined/collapsed together, it is most likely that Jenkins is doing this because it regards them as identical. I need to see more about how your job is configured (send me a config.xml and the Pipeline code for the job) to understand. You can also enable debug logging for the plugin by following the User Support section of the README, to see what it is doing.

**Comment by john-forrest** [comment]
@omehegan Thanks for getting back. I am now 100% sure that the problem relates to the jobs not being seen as different by Jenkins, but I doubt it is Jenkins as opposed to the plugin. The combining occurs before the pipeline is run (one the pipeline does run, things are OK) so I doubt it is that. More likely, as I alluded to, it is the way the jobs are compared with "equals". This comparison needs to include some extra fields, c.f. the repo name. Given the svn bug I quoted, this is almost certainly the plugin.
The config.xml is attached. I will see if I can generate some debug stuff, but I think it would have to be in a few days - we are currently busy and I don't want to stop the system working.
[config.zip](https://github.com/jenkinsci/gitlab-plugin/files/2145930/config.zip)
At one point I tried adding an extra string using an environment variable  but it makes no difference - I believe the variable is not expanded at that point. That bit is still there (see UNIQUE_STRING) although I could remove it and probably should.

**Comment by omehegan** [comment]
@john-forrest a five-year-old bug in a different plugin is really not much evidence that your issue is related to this plugin. AFAICT it's just a guess on your part without looking at this plugin's code to see how it works, right? Jenkins does have logic that is used in certain cases to skip builds that appear identical, and naturally the evaluation there would happen before the build was "started." 

Let me know what you find once you have enabled the debug logging.

**Comment by john-forrest** [comment]
OK Some logs. I sanitised these partly - replacing names and mail addresses. I hope this helps you. There were three pushes related to MR merges on (and I think this was the order) unified-test-service!27, ontology-based-classification!12 and document-expert-system!400. The last did not run: it was combined into the ontology-based-classification run. Let me know if you need more info.
[clashjob.zip](https://github.com/jenkinsci/gitlab-plugin/files/2150034/clashjob.zip)

**Comment by john-forrest** [comment]
@omehegan I think I've provided the feedback you were after. Let me know if you want more.

**Comment by omehegan** [comment]
This log is not easy to read, it looks like you have webhooks for four different Jenkins jobs set up from the document-expert-system repo. I'm struggling to figure out which Jenkins job is showing the combined build behavior.

**Comment by omehegan** [comment]
Also, when 10-15 webhooks come in at one time and trigger a bunch of different jobs, the logs from all of those get interleaved and it's very difficult to associate various log lines with different events.

**Comment by omehegan** [comment]
@john-forrest I am guessing that module-merge-request is the Jenkins job where you're seeing builds from different MRs get combined? 

If document-expert-system and ontology-based-classification are two completely different repos, I don't even understand how you would know that a build of one is being "combined" with another. Can you elaborate on that?

Can you possibly share the Jenkinsfile you are using for the job in question?

**Comment by omehegan** [comment]
Reopen if you want to discuss further, I need more info before I can debug this.
