### ISSUE TITLE
Add ability to specify pointer to secretToken in gitlab trigger rather than secretToken itself

### ISSUE THREAD

**Issue by eversC** [jenkinsci/gitlab-plugin#717]
It'd be nice to be able to set the secretToken value somewhere (e.g. env var or jenkins cred) that's not a 'magic value' in code/Jenkinsfile

gitlab-plugin users could then set e.g. an env var name or jenkins cred Id in the gitlab trigger in the Jenkinsfile, instead of the secretToken itself.

**Comment by omehegan** [comment]
@eversC what about making it a variable published by a Pipeline global library? Then a Jenkins admin could control who has access to it, and it would be usable within Pipeline jobs.

**Comment by eversC** [comment]
@omehegan sounds good (only downside I can think of is that it'd be an additional store of a secret in source code)

**Comment by omehegan** [comment]
@eversC well, you can also set it globally instead of per-project. And for all job types except Multibranch, you can set it in the job config UI rather than in your Pipeline code. The original intent of the "secret token" auth mechanism was to limit who could trigger builds on the Jenkins host, so one team could not trigger another team's jobs. Moving the token into the credentials API might defeat that purpose, because you're a little bit more limited in the access control you can set up for the credentials system.

**Comment by omehegan** [comment]
@eversC what do you think about my last comment? I'm just not sure that this feature request makes sense. Or perhaps you could accomplish it by storing the token in the Jenkins Credentials store using the "secret text" credential type.

**Comment by eversC** [comment]
hi @omehegan your comment clarifies things, thanks. And I agree, based on what you've said it doesn't seem this feature request makes sense.

I see a 'trigger with job DSL' section has been added to the README in a08fc040dded1b6446e433b777461d866de3825d, with reference to `System.getenv("API_TOKEN")` -- would it make sense to add this to the triggers block in the "Declarative Pipeline jobs" section of the README as well?

**Comment by omehegan** [comment]
@eversC actually, when I read that, I'm not sure what's being done there. I think the API_TOKEN is being set as an env var before Jenkins is launched. @benkeil can you elaborate on that?

**Comment by benkeil** [comment]
Yes, we deploy Jenkins with Helm in Kubernetes and set the API_TOKEN environment Variable in the deployment. You can also use there what ever you want

**Comment by omehegan** [comment]
@benkeil thanks, I should update the doc a little bit then so that people don't get confused, as that is a fairly specific way of passing that credential around.

**Comment by peter-janssen** [comment]
It is still confusing to me. I understand your remark about the purpose of the secret token but I'm not sure if it is perceived as such by everyone. However it took my a while to figure out I cannot inject the token through the credentials plugin into the trigger, either directly or through the jobs environment variables.
