### ISSUE TITLE
Jenkins invalid token

### ISSUE THREAD

**Issue by kgoedert** [jenkinsci/gitlab-plugin#718]
I had and installation of jenkins version 2.46.2 and gitlab plugin version 1.4.5. The version of gitlab is 9.1.2.
I had webhooks configured, without any authentication and it worked perfectly.

Now I update my jenkins to version 2.89.4 and gitlab plugin to version 1.5.3. Gitlab is still version 9.1.2.
My webhooks no longer work. When I test them from gitlab I get 

Hook executed successfully but returned HTTP 401 <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 401 Invalid token</title> </head> <body><h2>HTTP ERROR 401</h2> <p>Problem accessing /project/myProject. Reason: <pre> Invalid token</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/> </body> </html>

Are these versions incompatible? Or does any other configuration need to be made?

**Comment by omehegan** [comment]
I recently rewrote a lot of the documentation, including the parts that explain how to configure or disable authentication. Take a look here: https://github.com/jenkinsci/gitlab-plugin#gitlab-to-jenkins-authentication  Please reopen if that does not help resolve your issue.

**Comment by pierre-verhaeghe** [comment]
Hi,
In my company we just did an upgrade to jenkins 2.150.1 and gitlab 11.5.4. We have two kind of projects : maven projects and multi-branch pipelines.
For multi-branch pipelines everything is working as before. The security is off and webhook returns status 200.
But for maven projects we observe the exact same behavior as descrived above. 

> Error 401 Invalid token

I tried a lot of different configurations as explained in the documentation but nothing works.
What could explain the differences between the 2 kind of projects ?

**Comment by omehegan** [comment]
@pierre-verhaeghe first, the plugin is not tested with Maven jobs, and may not work with them. Surprisingly enough, I don't think it has ever come up in the years I have maintained this plugin. Maven jobs are a sort of unusual type, so it would not surprise me if there were differences.

Second, I am aware of an issue where Multibranch Pipeline jobs *ignore* the incoming secret token, if configured, and always trigger. See #700. So, it is possible that you have a secret token configured somewhere and it is only checked for your Maven jobs. See https://github.com/jenkinsci/gitlab-plugin#gitlab-to-jenkins-authentication to try and track that down.

**Comment by pierre-verhaeghe** [comment]
Thanks for your reply,

I checked the request headers and payload in gitlab. I don't see any secret token.
Headers are exactly the same for pipelines or maven projects :  

>  Content-Type: application/json
>  X-Gitlab-Event: Push Hook

I did a test with a Freestyle job and it's working as well. I will try with the other kind of projects. 
Br,

**Comment by omehegan** [comment]
@pierre-verhaeghe can you check your Maven job and make sure that, under "Build when a change is pushed to GitLab," under the Advanced button, there is no "Secret token" configured? Perhaps even click "Clear" there just to make sure.

**Comment by pierre-verhaeghe** [comment]
@omehegan 
I've already tried this. Same result.
We have the same thing with workflow jobs.

**Comment by pierre-verhaeghe** [comment]
Hi Owen,
My apologies, I didn't see the maven jobs were using a template job (EZ template plugin). So even when removing it from the child project, token was always overidden by the parent template. It's fixed now. Thanks a lot for your support.
