### ISSUE TITLE
Merge Request comments on parametrized build

### ISSUE THREAD

**Issue by bougar** [jenkinsci/gitlab-plugin#719]
## Issue
It would be useful in my case add comments on a GitLab when a parameterize is trigger. The pipeline Job show that the proper method is executed, but the comments is only added when the build is trigger with a webHook. I guess this behavior is normal, but I am not sure.
Note: I have configured all the parameters which are necessary in a MR.

### Context
- **Gitlab plugin version**: 1.5.3
- **Gitlab version**: Web version
- **Jenkins version**: 2.6.3
- **Job type**: Pipeline

**Comment by omehegan** [comment]
This can't really be done - when you trigger the job manually, Jenkins has no way to know what Merge Request the commit it is building is associated with.
