### ISSUE TITLE
Automatic project creation should work with (Multibranch-)Pipeline projects as template

### ISSUE THREAD

**Issue by ChristianCiach** [jenkinsci/gitlab-plugin#720]
I think the automatic project creation is an awesome feature, but unfortunately, it only does seem to work with Freestyle-projects used as templates.

Maybe I am doing something wrong, as I don't fully understand all configuration options for automatic project creation. (I think the documentation is a bit lacking in this regard). 

As we are converting all our projects to use pipelines defined as Jenkinsfile at the root of the projects, it would be awesome if a pipeline-project configured this way could be used as a template.

**Comment by omehegan** [comment]
I have no idea what you are referring to. What does this have to do with the GitLab plugin?

**Comment by ChristianCiach** [comment]
Sorry, this issue was supposed to be posted at elvanja/jenkins-gitlab-hook-plugin . 

But actually, my use case would be better solved by Argelbargel/gitlab-branch-source-plugin, which is supposed to be merged into the gitlab-plugin with #499. I will just wait for this :)

**Comment by bmaehr** [comment]
@ChristianCiach https://github.com/jenkinsci/gitlab-hook-plugin/pull/43
