### ISSUE TITLE
Allow sending commit status for skipped stages

### ISSUE THREAD

**Issue by aklemp** [jenkinsci/gitlab-plugin#721]
### Context
- **Gitlab plugin version**: 1.5.3
- **Gitlab version**: 10.5.2-ce.0
- **Jenkins version**: 2.89.4
- **Job type**: Pipeline (declarative)

### Logs & Traces

n/a

### Problem description

_Describe your problem in a meaningful way_:
- I'm using the step `updateGitlabCommitStatus` like this in the post block of a stage:
```updateGitlabCommitStatus name: STAGE_NAME, state: 'success'```
- It would be really nice and helpful if GitLab could also be informed about skipped stages with a state like `skipped`.
- The enumeration `BuildState` does not support any meaningful value for skipped stages.
- There are lots of GitLab feature requests for skipped jobs and stages. So GitLab itself probably requires such a commit status. There is one specific issue planned for version 10.7: https://gitlab.com/gitlab-org/gitlab-ce/issues/37397.
- As a side note, the skipped stage cannot simply be ignored when also using `gitlabBuilds` because it would be left in state `running` or `pending` which is started automatically.

**Comment by aklemp** [comment]
Currently, triggering `updateGitlabCommitStatus` is not really supported by Jenkins descriptive pipelines: https://issues.jenkins-ci.org/browse/JENKINS-49944

However, in scripted pipelines, the skipped status could be used.

**Comment by WoodenDoors** [comment]
I just ran into the same thing and also saw that there currently is an open pull request, that looks like it might fix this for scripted pipelines, which can use `updateGitlabCommitStatus` ( #786 ).

**Comment by omehegan** [comment]
@WoodenDoors yes, I have just merged that, I will try to release it this week.

**Comment by omehegan** [comment]
Will be released in 1.5.7 of the plugin.
