### ISSUE TITLE
secretToken must be configurable via job dsl 

### ISSUE THREAD

**Issue by benkeil** [jenkinsci/gitlab-plugin#722]
We need the feature to set the `secretToken` via job dsl in order to use a predefined token.

**Comment by omehegan** [comment]
@g-dx can you comment on this?

**Comment by benkeil** [comment]
There is already a solution: https://stackoverflow.com/questions/49150758/how-can-i-set-the-secret-token-for-gitlab-plugin-with-jenkins-job-dsl/49162807#49162807

**Comment by benkeil** [comment]
The documentation with the trigger part is wrong.

**Comment by omehegan** [comment]
@benkeil I recently refactored the documentation a lot. Right now it does not mention job DSL at all. Where do you think this information should be added? A new section? I don't use job DSL.

**Comment by benkeil** [comment]
A new section sounds good. I think a lot of people use Job DSL and it‘s easier to find.

**Comment by omehegan** [comment]
@benkeil do you think you could submit a PR with an example from your experience? You can see that I have split up config examples into sections for git clone, job trigger, and build status. It seems like we would want Job DSL examples for the trigger and build status at least. Not sure about the git clone.
