### ISSUE TITLE
End-point return 404 / Webhook return 500

### ISSUE THREAD

**Issue by smutel** [jenkinsci/gitlab-plugin#730]
### Context
- **Gitlab plugin version**: 1.5.3
- **Gitlab version**: 10.5.6
- **Jenkins version**: 2.112
- **Job type**: Multibranch Pipeline

### Logs & Traces

**In the jenkins side:**
HTTP ERROR 404 Problem accessing /project/universe/. Reason: Not Found Powered by Jetty:// 9.4.z-SNAPSHOT

**In the gitlab side:**
HTTP ERROR 500 Whoops, something went wrong on our end.

### Problem description

- In jenkins, create a multibranch project named universe in a folder
- In jenkins, create a multibranch project named universe in the root
- Try to setup the webhook in gitlab with end-point below:
  - https://jenkins/project/universe
  - https://jenkins/project/folder/universe
- Got the errors above

**Comment by bhicks-usa** [comment]
I have this exact same problem, discovered today despite everything working normally yesterday. I also have the same versions as OP.

Jenkins Plugins updated yesterday:
Credentials-Binding
JDK-tool

I tried rolling back those updated plugins and Jenkins itself to the previous version and I still have this same problem.

**Comment by omehegan** [comment]
Please enable the additional logging described in the User Support section of the README, and attach the resulting logs from Jenkins when you try to use the webhook.

It isn't really clear to me what you have configured or where you are seeing these errors. For example, you say you see the 404 error on the Jenkins side, but GitLab is what should be accessing that URL, not Jenkins.

**Comment by smutel** [comment]
I tried to get the end-point on my web browser. I got 404 not found and this in the log.
I assume that it's normal, the end-point is not accepting GET (it will be great to answer to get with a message: Gitlab end-point version ....).

```
Mar 22, 2018 3:35:05 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/CIO-CICD/universe
Mar 22, 2018 3:35:05 AM FINE com.dabsquared.gitlabjenkins.webhook.ActionResolver
GET is not supported for this project universe
```

I tried to test the end-point from gitlab, I have the error message 500 but I don't have anything in the gitlab plugin logs so perhaps the bug is on the gitlab side. Yesterday I upgraded both jenkins and gitlab. @bhicks-usa , did you update gitlab yesterday also?
In gitlab production.log, when I call the end-point, I have this:
```
URI::InvalidURIError (URI::InvalidURIError):
  lib/gitlab/proxy_http_connection_adapter.rb:14:in `connection'
  app/services/web_hook_service.rb:73:in `make_request'
  app/services/web_hook_service.rb:26:in `execute'
  app/models/hooks/web_hook.rb:10:in `execute'
  app/services/test_hooks/base_service.rb:22:in `block in execute'
  app/services/test_hooks/base_service.rb:19:in `catch'
  app/services/test_hooks/base_service.rb:19:in `execute'
  app/controllers/projects/hooks_controller.rb:41:in `test'
  lib/gitlab/i18n.rb:47:in `with_locale'
  lib/gitlab/i18n.rb:53:in `with_user_locale'
  app/controllers/application_controller.rb:325:in `set_locale'
  lib/gitlab/middleware/multipart.rb:95:in `call'
  lib/gitlab/request_profiler/middleware.rb:14:in `call'
  lib/gitlab/middleware/go.rb:17:in `call'
  lib/gitlab/etag_caching/middleware.rb:11:in `call'
  lib/gitlab/middleware/read_only.rb:31:in `call'
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'
```

I am quite sure that this end-point worked two days ago (before the updates).

**Comment by smutel** [comment]
Related to this: https://gitlab.com/gitlab-org/omnibus-gitlab/issues/3307

**Comment by omehegan** [comment]
FYI GitLab is tracking this on their side at https://gitlab.com/gitlab-org/gitlab-ce/issues/44480.
