### ISSUE TITLE
[feature] Add Merge Request Label in Environment Variables

### ISSUE THREAD

**Issue by Zava2012** [jenkinsci/gitlab-plugin#736]
### Context
- **Gitlab plugin version**: 1.5.5
- **Gitlab version**: 10.6.2
- **Jenkins version**: 2.107.1 LTS
- **Job type**: Freestyle

### Feature description

It would be useful to parse the label (or multiple labels) as an environment variable to Jenkins. This feature can be found many uses because 
An example of the name environment variable: **gitlabMergeRequestLabel** (or **gitlabMergeRequestLabels**).
Thanks in advance!

**Comment by omehegan** [comment]
I would prefer to solve this via #708. That encompasses mapping the whole JSON payload into the env map.

**Comment by Zava2012** [comment]
@omehegan, i'm sorry. 
I remember seeing this issue, but yesterday I was looking for and couldn't find. Sorry for the carelessness.
