### ISSUE TITLE
Access to jenkins fails after Gitlab plugin installation and restart

### ISSUE THREAD

**Issue by scheung38** [jenkinsci/gitlab-plugin#738]
I am running Jenkins inside one of the docker official jenkins images

https://hub.docker.com/_/jenkins/

so initially used this 
var/jenkins_home/secrets/initialAdminPassword

and then proceeded to define

User
Password
etc

then once inside Jenkins I wanted to install Gitlab webhook plugin and it says need to restart after installation, but upon restart, using the same 

User
Password

created above it, but now says Error in login to Jenkins???

**Comment by Zava2012** [comment]
Hi, @scheung38! This issue is not related to the plugin.
But i can help you if you answer two questions:
1) What command you used to start the container?
2) How did you restart Jenkins?

**Comment by omehegan** [comment]
Please don't discuss issues that aren't related to the plugin here, it just spams all the maintainers with irrelevant stuff.
