### ISSUE TITLE
Post-build step "GitLab commit status publisher" fails

### ISSUE THREAD

**Issue by omermazig-zz** [jenkinsci/gitlab-plugin#739]
### Context
- **Gitlab plugin version**: 1.5.5
- **Gitlab version**:  10.6.2-ee
- **Jenkins version**: 2.107.1
- **Job type**: Freestyle

### Logs & Traces

```
13:57:03 Started by user Tiny Inspektor
13:57:03 Building in workspace /var/lib/jenkins/workspace/tiny_kivy_widgets_tests
13:57:03 ERROR: undefined method `split' for nil:NilClass (NoMethodError)
13:57:03 /var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/models/gitlab_notifier.rb:167:in `repo_namespace'
13:57:03 /var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/models/gitlab_notifier.rb:27:in `prebuild'
13:57:03 /var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:8:in `prebuild'
13:57:03 /var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:22:in `boolean_result'
13:57:03 /var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:7:in `prebuild'
13:57:03 
13:57:03 Finished: FAILURE
```

### Problem description

I have installed the GitLab plugin, and configured the "Gitlab Notifier Configuration" part in jenkins configuration (Gitlab URL - https://gitlab.com, Gitlab Token - The long Access token I got from GitLab [only api allowed]), and when I add "GitLab commit status publisher" as a post-build the job fails with the above mentioned exception (passes when I remove it).

This is weird because I use the same Access Token in the configuration of the "Gitlab" part of the jenkins configuration (same access token - a Jenkins Credentials object which contains the Access token), and it works (Test Connection is successful and jobs are triggered by commits in the repo).

**Comment by omehegan** [comment]
Your log lines relate to the GitLab Hook Plugin, which is not the same as this plugin. And from what I can tell, you have configured the other plugin, not this one. If you want to use this one, I suggest you uninstall the other(s) so as not to create confusion.
