### ISSUE TITLE
Wrong Gitlab API call when trying to push commit status from multibranch pipeline

### ISSUE THREAD

**Issue by hervedevos** [jenkinsci/gitlab-plugin#741]
### Context
- **Gitlab plugin version**: 1.5.3
- **Gitlab version**: 10.4.3
- **Jenkins version**: 2.114
- **Job type**: Multibranch pipeline

### Logs & Traces

Gitlab plugin logs:
```
Apr 05, 2018 11:34:02 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Apr 05, 2018 11:34:02 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater addGitLabBranchBuild
Retrieving the gitlab project id from remote url https://mydomain.com/gitlab/testgroup/testproject.git
Apr 05, 2018 11:34:02 AM FINEST com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClientBuilder
Call GitLab:
HTTP method: GET
URL: https://mydomain.com/gitlab/api/v4/projects/testgroup%2Ftestproject/repository/commits/519eb4513ac605669ebe773af8a35476aaca816a
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]
Apr 05, 2018 11:34:02 AM FINEST com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClientBuilder
Got response from GitLab:
URL: https://mydomain.com/gitlab/api/v4/projects/testgroup%2Ftestproject/repository/commits/519eb4513ac605669ebe773af8a35476aaca816a
Status: 404 Not Found
```

### Problem description

When Jenkins multibranch pipeline tries to push gitlab commit status when a Jenkins pipeline ends, Gitlab API call is wrong. Instead of calling `/gitlab/api/v4/projects/<project_id>/repository/...`, the call is made to `/gitlab/api/v4/projects/<group>%2F<project>/repository/...` , this call lead to a 404 response from Gitlab API.

This issue is not encountered in a single branch pipeline

**Comment by omehegan** [comment]
@Argelbargel since you wrote the v3/v4 API code (I realize it was not a huge change), just wondering if you have any thoughts on this. I can't imagine why our API call would be different for a multibranch job... although... My understanding is that multibranch jobs don't use much or any of the data that comes from the GitLab hook (I'm a little unclear on this), so maybe for that type of job we have a different process for determining the API endpoint?

**Comment by Argelbargel** [comment]
I think this whole `%2F` is caused by the new sub-groups-feature in newer gitlab-versions. Before Gitlab 10 there could only be one group with the projects below. I do not quite get why escaping the slashes breaks the api-calls now, but i'll look into it...

**Comment by hervedevos** [comment]
I found the issue, this is not related to gitlab plugin.
I was using rewrite rules within nginx configuration. it appears that rewrite rules decode URL and Gitlab was receiving unencoded URLs from nginx proxy_pass.

I changed my nginx configuration so that I dont need to rewrite anymore.

**Comment by abouquet** [comment]
Hi, @hervedevos, can you explain me what you did in nginx ? I guess i got the same issue as you

**Comment by hervedevos** [comment]
@abouquet At first I followed this topic that allows to dynamicaly resolve DNS records : https://tenzer.dk/nginx-with-dynamic-upstreams/
Problem of this approach is that I was using nginx rewrite rule, and nginx rewrite rule unencode URL. therefore i removed it. I no longer have dynamic upstream DNS resolving, but at least its not impacting Gitlab API
