### ISSUE TITLE
cannot configure rebuildOpenMergeRequest using job-dsl

### ISSUE THREAD

**Issue by c5c86a** [jenkinsci/gitlab-plugin#745]
## Issue

triggers/gitlabPush/rebuildOpenMergeRequest('both') but the created job has value 'never'.

https://issues.jenkins-ci.org/browse/JENKINS-50654

### Context

Tested at the current latest jenkins (with latest plugins) and gitlab.

- **Gitlab plugin version**: latest
- **Gitlab version**: latest
- **Jenkins version**: latest
- **Job type**:  Freestyle

**Comment by isurugiu** [comment]
I have experienced the same issue but I think job-dsl guys could take this one.

**Comment by c5c86a** [comment]
at the following ticket they told me to open it here.

https://issues.jenkins-ci.org/browse/JENKINS-50654

**Comment by omehegan** [comment]
The Job DSL maintainer is handling this in the Jira ticket you linked to. He can't reproduce the issue.
