### ISSUE TITLE
Allow jenkins pipeline to notify vary of gitlab repositories.

### ISSUE THREAD

**Issue by stchar** [jenkinsci/gitlab-plugin#746]
## Feature Request
Let user to notify any gitlab project on any gitlab instance right from the pipeline. 

This is useful when you're automating a system test so you can get/create build artifacts from different sub-systems (client, server, test-automation-harness, simulators which are stored in different repositories) and then orchestrate them in a one pipeline. We usually create branches with the same name across several repositories (just like in android projects) and then test entire feature all together.

In this case several gitlab projects may trigger one or several jenkins instances so in pipeline i'm taking care which gitlab instance to notify.

**Comment by omehegan** [comment]
Released in 1.5.7.
