### ISSUE TITLE
Source Branch Regex	

### ISSUE THREAD

**Issue by sebastienbonami** [jenkinsci/gitlab-plugin#751]
With this plugin, we can filter branches by regex using the "Target Branch Regex" option, but there's no "Source Branch Regex" option. Is there a special reason for that?

I'm currently looking at the code and I will try to implement a "Source Branch Regex" option since I need it for my use case.

**Comment by breisig** [comment]
This feature is greatly needed. Hope it gets included before the next release.

**Comment by omehegan** [comment]
This was released today in 1.5.10.
