### ISSUE TITLE
Gitlab MergeRequestHook - ObjectAttributes - Action is Null

### ISSUE THREAD

**Issue by ilushka85** [jenkinsci/gitlab-plugin#752]
## Issue
Gitlab MergeRequestHook - ObjectAttributes - Action is Null and enum does not support reopen action.
### Problem description
Integrating the plugin in another tool the conversion from json to enum is wrong in the gitlab plugin code.  Because of this the enum ends up being null instead of a proper value.

**Comment by omehegan** [comment]
I don't understand what you are trying to do here. Can you please elaborate?
