### ISSUE TITLE
gitlab doesnt trigger build on jenkins

### ISSUE THREAD

**Issue by prawen** [jenkinsci/gitlab-plugin#753]
### Context
- **Gitlab plugin version**: 1.5.5
- **Gitlab version**: gitlab.com
- **Jenkins version**: 2.107.2
- **Job type**: Freestyle

### Logs & Traces

No logs are recorded in this case

### Problem description

Hello, I'm facing issue with gitlab webhook. I have a webhook which triggers job on jenkins upon a specific comment on merge request page on gitlab. It used to work fine till this evening and all of a sudden it stopped working. If I manually test webhook from gitlab for some events, it is hooked successfully. And I'm able to see that event in log on jenkins as well. But comment is not working and no log on jenkins. Any help would be highly appreciated. I have tried upgrading jenkins and plugin. Still I'm not getting any response in jenkins when a comment is made on merge request page on gitlab.com

**Comment by danibram** [comment]
same here

**Comment by prawen** [comment]
Now it has started working all of a sudden. May I know what is happening?

**Comment by omehegan** [comment]
Sounds like an issue with gitlab.com not sending the webhook data to your Jenkins. If nothing is logged by the plugin at all, then the issue is on their end. The plugin is not supported by GitLab Inc.

**Comment by danibram** [comment]
Yes, sorry for that, but sometimes not work for us and sometimes yes, should be the internet connection. Makes more sense.
Thank you for your time
