### ISSUE TITLE
 "Ignore SSL Certificate Errors" has no effect

### ISSUE THREAD

**Issue by jtzl** [jenkinsci/gitlab-plugin#77]
I am experiencing this issue in Jenkins, even after selecting "ignore ssl errors":
```
javax.servlet.ServletException: java.lang.Error: javax.net.ssl.SSLHandshakeException:
You can disable certificate checking by setting ignoreCertificateErrors on GitlabHTTPRequestor.
SSL Error: java.security.cert.CertificateException: No name matching myfqdn.tld found
```
Jenkins 1.610
Gitlab plugin version 1.1.21
java version "1.7.0_79" OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by sameetn** [comment]
Has any solution been found yet for this?

**Comment by maiksensi** [comment]
:+1: experiencing the same....

**Comment by omehegan** [comment]
Are you all experiencing this when you "test" the connection from the config UI, or in actual usage scenarios as well?

**Comment by coder-hugo** [comment]
This will be fixed by #203 but IMHO it's a bad idea to ignore SSL certificate errors. If you do this you can use just plain HTTP. Cause using SSL and ignore all SSL errors by default makes the communication not more secure than a communication over HTTP. A man-in-the-middle can provide you any SSL certificate and you still think you are communicating just with the real server.

**Comment by sameetn** [comment]
I agree with your statement. However this is for an internal install of gitlab and ask such not exposed to the outside world.

**Comment by omehegan** [comment]
If it's internal, why use SSL at all?

**Comment by coder-hugo** [comment]
Just cause it's internal is no reason for not using SSL. But if you use SSL you should use it correctly by using certificates signed by a trusted (internal) CA and install this CA to the keystore of your JRE that runs jenkins. Otherwise you shouldn't SSL neither for external nor for internal use.

**Comment by sameetn** [comment]
That is exactly what I had done. It worked for all the other stuff we did. But for some reason, it was still failing for this plugin. We ultimately ended up solving this by paying for CA certs from verisign due to a different software limitation. But thanks for solving this.
