### ISSUE TITLE
Plugin does not trigger build

### ISSUE THREAD

**Issue by Haitianisgood** [jenkinsci/gitlab-plugin#773]
ENV:
 gitlab 8.13.0
 gitlab plugin 1.5.6
 jenkins: 2.107.3

I config all it need.when send a  Merge Request,and jenkins have accepted this request,but not build!

jenkins log:
```
INFO: WebHook called with url: /project/test
Jun 04, 2018 10:51:58 AM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/test
```
but it is worked when I changed plugin to 1.4.3(I hava other jenkins of useing 1.4.3)

**Comment by longquangao** [comment]
ENV:
gitlab 10.8.1
gitlab plugin 1.5.6
jenkins: 2.107.3

Hook execution failed: URL is blocked Requests to localhost are not allowed

**Comment by stchar** [comment]
@omehegan, how do you decide what version of Jenkins and other plugins to support?

**Comment by karlskewes** [comment]
We are not using merge requests but the webhook is trigger builds for us on commits.

**Comment by rmstyrczula** [comment]
@longquangao That is different issue, with GitLab's settings.

Go to `YOUR_GITLAB_URL/admin/application_settings`, scroll down to `Outbound Requests` and enable `Allow requests to the local network from hooks and services`

----

As an aside, things work fine for me:
gitlab  10.8.3
gitlab plugin 1.5.6
jenkins 2.107.3

It is likely gitlab 8.13 being unsupported, not jenkins.

**Comment by omehegan** [comment]
@stchar I don't really make any decisions about versions of Jenkins etc. to support. It isn't normally a concern. What I do care about is that we support the current and previous major releases of GitLab. So GitLab 11.0 has just come out, my main concern will be that we keep supporting 10.0 and 11.0, and if there are problems with 9.0 we might decide not to fix them.

**Comment by omehegan** [comment]
@Haitianisgood please follow the instructions in the User Support section of the README to increase debug logging for the plugin, and then attach those logs after you reproduce this issue. It should tell us why the build was not triggered. Most likely you need a small change to your job config here.

**Comment by relax-admin** [comment]
@rmstyrczula I looked for a day and finally found the perfect solution here. Your solution is so handsome.

**Comment by MuchContact** [comment]
Almost same situation!
## ENV:
jenkins: 2.128
gitlab plugin: 1.5.5 
gitlab: GitLab Community Edition 10.6.3
Jenkins have accepted gitlab comment requests, but not build! At the same time, when pushing code, jenkins job can be triggered.  
`Allow requests to the local network from hooks and services` is enabled, but not work!
## Jenkins logs when commenting on gitlab commits as follow:
```
Aug 02, 2018 10:56:34 PM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/comment
Aug 02, 2018 10:57:04 PM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/comment
```
## Jenkins logs when pushing on gitlab as follow:
```
Aug 02, 2018 11:08:54 PM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /project/comment
Aug 02, 2018 11:08:54 PM com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
INFO: comment triggered for push.
Aug 02, 2018 11:09:03 PM hudson.model.Run execute
INFO: comment #3 main build action completed: SUCCESS
```
## Gitlab webhook config
![image](https://user-images.githubusercontent.com/4156404/43815193-257b4642-9b01-11e8-9603-521cee2b0866.png)

<img width="855" alt="gitlab-webhook" src="https://user-images.githubusercontent.com/4156404/43815182-1896bd3a-9b01-11e8-940e-22ce14863799.png">

**Comment by omehegan** [comment]
@MuchContact please take a screenshot of your webhook configuration page in GitLab and attach it to this ticket.

**Comment by MuchContact** [comment]
@omehegan  already upload pictures, please have a look. Finally I use [generic-webhook-plugin](https://github.com/jenkinsci/generic-webhook-trigger-plugin) instead, and make it.

**Comment by omehegan** [comment]
@MuchContact how have you configured the GitLab trigger in the job? To have the build trigger with comments, you need to use the following:
![screen shot 2018-08-08 at 3 52 40 pm](https://user-images.githubusercontent.com/1775894/43818724-3fc371e2-9b23-11e8-8af3-1aaf03e4eda7.png)

**Comment by MuchContact** [comment]
@omehegan yeah, I had configured 'comment(regex) for triggering a build', it's a prefix-matching pattern, I just copy the `regex content` and comment like "`<regex content>` my comment", I'm sure the configure and comment are both ok.

**Comment by omehegan** [comment]
@MuchContact but did you also check the 'Comments' check box? 

Can you follow the instructions in the User Support section of the README to enable debug logging from the plugin? Then try to reproduce the issue (comment on an MR which should trigger a build) and add the debug logs here. It should show the JSON payload with note contents, and hopefully some log entries about why the job was/wasn't triggered.

**Comment by MuchContact** [comment]
@omehegan Ok, I will try later

**Comment by netheosgithub** [comment]
I encounter the same problem. When adding a comment on gitlab (matching regex), jenkins logs a message :
`c.d.g.t.h.AbstractWebHookTriggerHandler#handle: Source branch xxxx or target branch validation is not allowed`

Indeed, the target branch was forbidden in jenkins job config : this is our main integration branch, and  we do not want to rebuild it because we never use merge commits.

Question : why do you consider both source and target branches for taking decision (I would expect only the source branch matters) ?
