### ISSUE TITLE
Rebuild job on Target push

### ISSUE THREAD

**Issue by damiendurant** [jenkinsci/gitlab-plugin#775]
### Context
- **Gitlab version**: 10.7
- **Jenkins version**: 2.89.3
- **Job type**: Pipeline

### Problem description

Hi,

I have configured a gitlab webhook on Merge Request event. On the corresponding jenkins job configuration I have set : rebuild job on push on source and target branch.

The job is triggered when the MergeRequest is openned, when a commit is done on the source branch, but not when a commit is done on the target branch.

Is it normal ? 
Thanks

**Comment by omehegan** [comment]
Please follow the instructions in the User Support section of the README to increase debug logging for the plugin, and then attach those logs after you reproduce this issue.

**Comment by omehegan** [comment]
Also what version of the plugin are you using?
