### ISSUE TITLE
Retesting MRs when one is merged

### ISSUE THREAD

**Issue by NathanHazout** [jenkinsci/gitlab-plugin#776]
## Issue
Let's say you have 2 open Merge Requests. Both passed jenkins tests.
You merge them both, one after the other.

However, the resulting merge is actually in failing state. Jenkins ran on both of those MRs before the other was merged.

Is this expected behavior? 
Can accepting a MR somehow invalidate the state of all the other MRs until jenkins runs again?

### Context
- **Gitlab plugin version**: N/A (I'm not an admin)
- **Gitlab version**: GitLab Community Edition 9.4.0
- **Jenkins version**: Jenkins ver. 2.107.3

**Comment by dblessing** [comment]
This isn’t really something Jenkins can handle with GitLab. If you want to
enforce this you can change to fast-forward or semi-linear merge strategy
which will require a rebase on master prior to merge. This would ensure
your tests are passing using latest master. Without this strategy you will
have to manually rebase against master and push again to get tests to run
again.

GitLab are exploring a merge train type feature that would put merged into
a queue after accepting the MR. Each would be merged to master in turn if
tests pass at each stage. Until then, there’s not really anything this
plugin can do to help the situation.

**Comment by NathanHazout** [comment]
Thanks

"change to fast-forward or semi-linear merge strategy"

Do you have documentation on this?

Are you saying it will automatically rebase? Or are you saying it will prevent merges to be approved unless it's up to date to master?

**Comment by omehegan** [comment]
@nasht00 I think https://docs.gitlab.com/ee/user/project/merge_requests/#semi-linear-history-merge-requests is what you would want. Please close this issue if you're all set.

@dblessing thanks for replying about this!
