### ISSUE TITLE
Gitlab can't send POST request to Jenkins - 401

### ISSUE THREAD

**Issue by Jezza** [jenkinsci/gitlab-plugin#777]
### Context
- **Gitlab plugin version**: 1.5.6
- **Gitlab version**: Community Edition 10.8.4
- **Jenkins version**: 2.107.3
- **Job type**: Freestyle

### Logs & Traces

Nothing appears in jenkins, but I do get this in gitlab:
```
Hook executed successfully but returned HTTP 401 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
```

### Problem description

I followed the instructions at https://github.com/jenkinsci/gitlab-plugin#gitlab-to-jenkins-authentication
I've disabled auth, used the global oauth method, use per project method, etc.
Everything responds with 401.

It could have something to do with the server using https.
That being said, I've tried using the http url, and I get the same response.
If I were to naively guess, I would assume that the gitlab plugin doesn't even get the chance to auth the request before it's rejected by the jenkins server.
I've taken a look at the logs, and I've found nothing that remotely resembles a rejected request in the jenkins log.
I can take another look, as I might have missed it the first time.
They are on two different machines, so it is possible that the network is doing something funky.

**Comment by yogurtnaturalny** [comment]
Hi

We have same problem with GitLab 10.8 and Jenkins Jenkins ver. 2.107.3 and plugin 1.5.6

**Comment by Jezza** [comment]
I found the issue.
It was entirely our network.
The admins had put in a rule in the http configuration, that required a user be authenticated before being able to access it.
We fixed this just by whitelisting the gitlab server.

**Comment by omehegan** [comment]
@yogurtnaturalny this would have to be a problem with auth between Jenkins and GitLab. If you have followed the steps in https://github.com/jenkinsci/gitlab-plugin#gitlab-to-jenkins-authentication then I would suggest you look for other factors, e.g. what happened with @Jezza.
