### ISSUE TITLE
Jenkins doesn't trigger enough merge request builds

### ISSUE THREAD

**Issue by haminhcong** [jenkinsci/gitlab-plugin#779]
## Issue

Hi everyone. Today, t had a issue when use merge request build. 
Can you help me resolve this issue? Thankyou very much.

### Context
- **Gitlab plugin version**: 1.5.3
- **Gitlab version**: 10.7.0
- **Jenkins version**: 1.609.3
- **Job type**: Pipeline
### Problem description

My gitlab project has 3 branches: **master**, **bug2** and **bug3**. After push commit to **bug2** branch, i created two merge requests:
- One merge request from **bug2** to **master**.
- One merge request from **bug2** to **bug3**.

In Jenkins side, i setup one Jenkins pipeline Job trigger merge request when push commit to source or target branch. Then i push new commits to **bug2** branch.

I expected that my jenkins job will run two builds for two merge requests above, however only one merge request build is triggered, although gitlab-plugin run scheduleBuild() two times for two merge requests:

### Logs & Traces

```log
Jun 09, 2018 3:29:48 PM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /jenkins/project/JavaWS
Jun 09, 2018 3:29:48 PM com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
INFO: JavaWS triggered for merge request.
Jun 09, 2018 3:30:01 PM com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
INFO: WebHook called with url: /jenkins/project/JavaWS
Jun 09, 2018 3:30:01 PM com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle
INFO: JavaWS triggered for merge request.
Jun 09, 2018 3:30:13 PM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: JavaWS #14 completed: SUCCESS
```

**Comment by omehegan** [comment]
@haminhcong this is an interesting use case, it does sound like what you have set up should work the way you expect. Can you follow the instructions in the User Support section of the README to increase debug logging for the plugin, and then attach those logs after you reproduce this issue? It should show if Jenkins or the plugin decided not to trigger a build for one of the hooks it received.
