### ISSUE TITLE
Failed status is not set when failed in a post section

### ISSUE THREAD

**Issue by theirix** [jenkinsci/gitlab-plugin#784]
##### Context
- **Gitlab plugin version**: 1.5.6
- **Gitlab version**: 10.8.3
- **Jenkins version**: 2.121.1
- **Job type**: Multibranch Pipeline

### Logs & Traces

Pipeline log excerpt:
```
[Pipeline] sh
[backend_develop-LZN7DHB6UKRHDRRH2CCD3BV5ARG4ZEIW7NXDJVNJ6OHEVLAEFCFQ] Running shell script
+ sudo -i -u deploy systemctl --user is-active celery
active
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] echo
Warnings
[Pipeline] warnings
[WARNINGS] Parsing warnings in console log with parser PYLint
Skipping warnings blame since pipelines do not have an SCM link.%n
[WARNINGS] Computing warning deltas based on reference build #558
[WARNINGS] Ignore new warnings since this is the first valid build
[WARNINGS] Plug-in Result: Failed - <a href="warningsResult">3 warnings</a> of <a href="warningsResult/HIGH">priority High</a> exceed the threshold of 0 by 3
[Pipeline] echo
Post
[Pipeline] junit
Recording test results
[Pipeline] archiveArtifacts
Archiving artifacts
[Pipeline] emailext
Sending email to: REDACTED
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // gitlabCommitStatus
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: FAILURE
```

### Problem description

Steps:
- make a pipeline (see excerpt) with a post section that can fail
- run a build for the commit
- see the build is failed in Jenkins
- see the commit is succeeded in GitLab

If a Warnings plugin sets a build status to failure in Post pipeline stage (it can be based on a warnings threshold), Giltab plugin does not update build status to failed. Jenkins shows this build as failed.

Exactly the same configuration correctly reports failed when any stage except the post section was failing.

This kind of Pipeline fragment does not set failed status:
```groovy
// ...
pipeline {
  agent { label "${ciEnv}" }

  options {
    gitLabConnection('gitlab')
    gitlabCommitStatus(name: 'jenkins')
    disableConcurrentBuilds()
  }
  stages {  
   // ...
  }
  post {
    always {
      warnings canComputeNew: false,
        canRunOnFailed: true,
        canResolveRelativePaths: false,
        categoriesPattern: '',
        consoleParsers: [[parserName: 'PYLint']],
        defaultEncoding: '',
        excludePattern: '',
        includePattern: '',
        messagesPattern: '',
        healthy: '',
        unHealthy: '',
        failedTotalHigh: '0',
        failedTotalNormal: '',
        unstableTotalHigh: '0',
        unstableTotalNormal: ''

      junit "**/junit.xml"
      archiveArtifacts artifacts: "*.whl"

      // notification
      emailext body: '$DEFAULT_CONTENT', recipientProviders: [[$class: 'CulpritsRecipientProvider']], subject: '$DEFAULT_SUBJECT'
    }
  }
```

**Comment by omehegan** [comment]
I think this may be by design. The point of the 'post' section is that these steps are not related to the build and test of your code. Indeed, if archiving your junit artifacts or emailing someone fails, why would you want that surfaced in GitLab? I think if you want that to be captured by the gitlabCommitStatus option, you should move those into the build stages.

**Comment by theirix** [comment]
@omehegan, good point, it can be done in stages, I'll try to move it here.

But if Jenkins provides an ability for plugins to set build status in a post section, there can be a typical situation that a build fails while the stages succeded. Static Analysis plugins (warnings in particular) is a good example.

**Comment by omehegan** [comment]
@theirix have you looked at the plugin's documentation for Delcarative syntax? https://github.com/jenkinsci/gitlab-plugin#declarative-pipeline-jobs  It actually shows explicitly sending success and failure using `post` steps. That may be the solution you should use.

**Comment by theirix** [comment]
Seems like a failure in the `success`/`always` block can be handled in a `failure` block which can call the `updateGitlabCommitStatus`. It solves the initial problem, thanks!
