### ISSUE TITLE
multibranch pipeline credentials setting

### ISSUE THREAD

**Issue by lmzhangucsd** [jenkinsci/gitlab-plugin#787]
In the Jenkins UI, when I select configure and add source from git, I can't choose the credentials(gitlab API token) that I configured previously in global Jenkins settings.

gitlab version: 9.4.7-ee
gitlab plugin version: 1.5.6

**Comment by rozhok** [comment]
Same for me, but for GitLab Enterprise Edition 11.0.1-ee, Jenkins 2.128.

This blocks plugin usage.

**Comment by omehegan** [comment]
It sounds like you are trying to configure your branch source for a Pipeline Multibranch job. Is that right? If so it makes no sense to use the GitLab API token as a credential. That token is only for sending build status back to GitLab when the job runs. You need to be using git user credentials which are set up to be able to clone a repo, i.e. an SSH key.

**Comment by rozhok** [comment]
Oops, seems that my issue is different, created separate one.
For this one @omehegan you're right, @rzhang-nevermore you should create GitLab Login/Password credentials for the fetching data from git.

**Comment by lmzhangucsd** [comment]
@omehegan thanks for the clarification. I have another question though, if I want my multi-branch pipeline to be triggered to run every time I push new commits/or merge request to gitlab repo, how can I achieve that?

**Comment by omehegan** [comment]
@rzhang-nevermore https://github.com/jenkinsci/gitlab-plugin#pipeline-multibranch-jobs-1
