### ISSUE TITLE
Unable to locate GitLab plugin configuration in Global Settings

### ISSUE THREAD

**Issue by rozhok** [jenkinsci/gitlab-plugin#788]
### Context
- **Gitlab plugin version**: 1.5.6
- **Jenkins version**: 2.129

### Problem description

Looking to the [readme](https://github.com/jenkinsci/gitlab-plugin#jenkins-to-gitlab-authentication), I have to configure GitLab plugin settings in the Global Settings section of Jenkins: 

> On the Global Configuration page in Jenkins, in the GitLab configuration section, supply the GitLab host URL, e.g. http://your.gitlab.server

But I can't find it.

**Comment by omehegan** [comment]
When you go to Manage Jenkins -> Configure System, somewhere on that page you should see this:

![screen shot 2018-06-29 at 9 46 37 am](https://user-images.githubusercontent.com/1775894/42065951-63b9485e-7b81-11e8-9b0e-4de5ca708e90.png)

If you do not, then the plugin is not installed or is failing to be loaded when Jenkins starts.

**Comment by rozhok** [comment]
Oops, my bad. Looked into the wrong page.
