### ISSUE TITLE
Automatically manage webhooks

### ISSUE THREAD

**Issue by danielfbm** [jenkinsci/gitlab-plugin#792]
## Issue
Feature request: Automatically manage webhooks for projects

### Context
- **Gitlab plugin version**: 1.5.7
- **Gitlab version**: 10.4.7
- **Jenkins version**: 2.129
- **Job type**: Pipeline

### Logs & Traces

_Please include any relevant log that could serve to better understand the source of your issue_
For Jenkins Gitlab Plugin logs, follow instruction in [User Support section](https://github.com/jenkinsci/gitlab-plugin#user-support).
For Gitlab logs, ask an administrator to provide you the relevant Gitlab logs.

### Problem description
Feature request
- Creating Jenkins pipelines and manually creating webhooks are a tedious and prone to user error
My suggestion:
- Add a global configuration to enable automatically manage webhooks (GitHub plugin can do this)
- If the job uses the Gitlab trigger option could automatically create the webhook on the first run?

**Comment by witokondoria** [comment]
This is part of the [gitlab-branch-source-plugin](https://github.com/Argelbargel/gitlab-branch-source-plugin) functionalities, that will be eventually included on this plugin

**Comment by omehegan** [comment]
Definitely would be nice to have. I would think the way to implement this would be at the job configuration level, where a config save could check and update the webhooks accordingly. You would need to do it here in order to catch job renames and other changes like that.

**Comment by omehegan** [comment]
Will be included when #499 is resolved.
