### ISSUE TITLE
NullPointerException in Trigger for "Build on successful pipeline events"

### ISSUE THREAD

**Issue by Persi** [jenkinsci/gitlab-plugin#794]
## Issue
NullPointerException on using Gitlab pipeline events.

### Context
- **Gitlab plugin version**: 1.5.8
- **Gitlab version**: 10.2.5
- **Jenkins version**: 2.129
- **Job type**: Pipeline

### Gitlab hook sent data
[JSON Data](https://pastebin.com/RsDTcAyT)

### Occured exception:
[Stacktrace](https://pastebin.com/bcLy7xnU)

### Problem description

I am using a gitlab-ci Pipeline als CI Pipeline for my project. To deploy the artifact, created by the gitlab-ci pipeline, on a system in another environment, I need to use a Jenkins pipeline. So I tried to configure my Jenkins job for Gitlab hooks, by using the Gitlab plugin. If I send an event from Gitlab to Jenkins on any push, the Jenkins pipeline is started correctly. But I need to start my Jenkins pipeline only after the gitlab-ci pipeline succeeded, so I only send Pipeline Events from Gitlab. I have configured in the Gitlab plugin configuration for my pipeline project, to allow all branches to trigger the build.

The pipeline events from Gitlab cause a NullPointerException in Jenkins, so the Jenkins pipeline is not triggered.

**Comment by omehegan** [comment]
The NPE occurs here:
https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/trigger/handler/pipeline/PipelineHookTriggerHandlerImpl.java#L66

Is it possible there is an issue with how you have configured the branch filtering? You said you have set it to allow all branches. Can you show this configuration?

**Comment by Persi** [comment]
Hi @omehegan,

I did a short look into the sources as well, that is why I mentioned the branch filtering config.
I tried different filtering settings, from filtering by branchname, as well as regex and at least allow all. The NPE occured with every setting.

The config looks like following: [XML](https://pastebin.com/FUnAY4dh)
In the job configuration it looks like the following: [Screen](https://pasteboard.co/Ht9HHv4.png)

**Comment by omehegan** [comment]
I will have to try and find time to reproduce this. Can you follow the instructions in the User Support section of the README, to capture some additional debug logs and attach them after reproducing the problem?

**Comment by Persi** [comment]
This is some kind of strange. The logger is only printing the received JSON and says it was triggered, but the job is not triggered. I just POST the mentioned JSON above with HTTP Header "X-Gitlab-Event: Pipeline Hook". If I let Gitlab send the POST, the log output looks the same, but Gitlab is receiving the above Exception in the response.

Logoutput looks like the following: [Output](https://pastebin.com/5nFUpnhU)

**Edit:**
I could find the occured Exception in the catalina.log of my Tomcat. Seems like it's not handled by the Logger, or Rootlogger. Look like that: [Catalina Logoutput](https://pastebin.com/TfephpVJ)

**Comment by omehegan** [comment]
I spent some time digging in the plugin code around this, but could not make sense of what might be wrong. I will mark this as a bug, but I don't know when or if it will be fixed.

**Comment by Persi** [comment]
@omehegan I took a deeper look into the plugin code as well and I think I found the root cause of the NPE.

In the GitLabPushTrigger class all onPost methods except `onPost(final PipelineHook hook)` check if the branch filter is set and otherwise call `initializeBranchFilter`. So I think if you would add this check to the above onPost method the bug could be fixed.

I'll try to reproduce the bug in a small testenvironment and if I can reproduce it I would fix it and open a Pull Request.

**Comment by omehegan** [comment]
@Persi this sounds like a good guess as to what the problem is. I don't have any experience with GitLab pipelines myself, so if you can test and create a fix that would be great. You can use the Docker test env that is included with this plugin if that is easier for you; see the README for guidance on that.

**Comment by omehegan** [comment]
This was released today in 1.5.10.

**Comment by 943739901** [comment]
I just encountered this problem. https://issues.jenkins-ci.org/browse/INFRA-2085

**Comment by 943739901** [comment]
@omehegan
