### ISSUE TITLE
post build actions in pipeline

### ISSUE THREAD

**Issue by norricorp** [jenkinsci/gitlab-plugin#802]
### Context
- **Gitlab plugin version**: 1.5.7
- **Gitlab version**: 11.0.3
- **Jenkins version**: 2.1.30
- **Job type**: Pipeline,

This is a request more than an issue.
When I am using the plugin with a Jenkins freestyle or maven job, I can use the plugin functionality on post build steps to update GitLab. 
Looking through the docs on the plugin, I can not do that with pipeline. Instead I have to write code for that functionality. And I can understand why - everything should be code. Except that Jenkins allows me to configure SCM graphically and then pickup the Jenkinsfile from SCM for the rest of the job (build, test, deploy).
So is this a Jenkins design decision that pipeline jobs consist of general, build triggers, advanced and pipeline? Hence no post build actions?

And I notice that the declarative code that I add to the Jenkinsfile (post success/failure, gitlabconnection, triggers) is also in the General / Build Triggers section of the GUI when setting up a pipeline. So do I actually need those values in my Jenkinsfile?

**Comment by omehegan** [comment]
This is not really a plugin issue, it's a matter of how Jenkins implements Pipeline. Pipeline jobs do not have a concept of "post-build" really. Declarative Pipeline does have a concept of "things you do after everything else, if successful/unsuccessful," but that is optional.
