### ISSUE TITLE
Filter branches seems not working

### ISSUE THREAD

**Issue by Xiangao2018** [jenkinsci/gitlab-plugin#804]
Hi
### Context
- **Gitlab plugin version**: 1.29.2
- **Gitlab version**: 7.11.4
- **Jenkins version**: 2.132
- **Job type**:  Freestyle

### Problem description

- what were you doing (simple push, merge request, MR with fork, ...)

I use jenkins & gitlab to build my project, i write a build shell, and now Gitlab can trigger jenkins to  excute shell, but what i want is whenever develop change, build again. and other branch ignore,

I use `Filter branches by name`, and try use `.*develop`. `develop` , it give me warming 

*Following patterns don't match any branch in source repository:*

![](https://ws1.sinaimg.cn/large/006tKfTcgy1ftcup9oy9mj313j0mkq5y.jpg)

`Filter branches by regex` also not working for me 

![](https://ws4.sinaimg.cn/large/006tKfTcgy1ftcurite2fj30qy028wej.jpg)

- what was expected

I expect only develop branch change trigger the build shell, and other branch not excute build shell 

- what occurred finally
Now it seems not correct. Because Not matter what branch is changed , build shell excute everyTime 

Englist is not my Native language， If exist some error, please  forgive me !

**Comment by omehegan** [comment]
@Rsenjoyer GitLab 7.11.4 was released in May 2015, the current stable release is 11.1. I can't officially support using the plugin with versions of GitLab older than 9.0. It's possible that the version you are on simply doesn't send us the necessary information, or in the format that we expect, to support this feature.

You said that you are using version 1.29.2 of the plugin, but there is no such version. The latest is 1.5.9. Can you confirm which version you are using?

**Comment by Xiangao2018** [comment]
@omehegan  thks  for your reply,  my company use gitlab. i check again. gitlab version **GitLab 7.11.4 b725318**, maybe is too old

as for Gitlab plugin version, I am so sorry, I made a mistake.

![](https://ws4.sinaimg.cn/large/006tNc79gy1ftkzab4ukaj30pj07l0tj.jpg)

Gitlab Authentication plugin: 1.4
Gitlab Hook Plugin: 1.4.2
GitLab Logo Plugin: 1.0.3
Gitlab Merge Request Builder：  2.0.0
GitLab Plugin： 1.5.8

i have no right to update gitlab version, and i am deep in this trouble, Can you give me some suggestion?

**Comment by omehegan** [comment]
1. I assume you have made sure that the git project you have configured in this Jenkins build actually has a 'develop' branch.
2. Can you show with a screenshot how you have configured the git SCM/clone of that repo in your Jenkins job?
3. Can you show a screenshot of the GitLab webhooks you have configured to trigger the Jenkins job?

**Comment by Xiangao2018** [comment]
@omehegan  

Jenkins  Git
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fto4dm5e91j31fq0o8dim.jpg)

Jenkins Build
![](https://ws4.sinaimg.cn/large/006tKfTcgy1fto4en39n5j31fi0ragox.jpg)
![](https://ws1.sinaimg.cn/large/006tKfTcgy1fto4f2xzynj31f00qo41i.jpg)

Gitlabe webHooks
![](https://ws3.sinaimg.cn/large/006tKfTcgy1fto49h7705j31ii0x2jw4.jpg)


That's all  Thks

**Comment by omehegan** [comment]
@Rsenjoyer your webhook config is not correct. Notice how the URL you are using in the webhook is not the same as the one in the Jenkins UI (where in the UI it says 'GitLab webhook URL'). The URL you are using bypasses the plugin completely, and just triggers a generic Jenkins build of your job. Change the URL and you should be all set.

**Comment by Xiangao2018** [comment]
@omehegan  thank you, you Save my life.  It works 

my older url also can trigger build, and I  don't know why, because i only choose **Build when a change is pushed to GitLab**

Anyway, it works well. thks again.
