### ISSUE TITLE
Webhook triggering multiple requests at jenkins with a merge request checklist

### ISSUE THREAD

**Issue by annicarol** [jenkinsci/gitlab-plugin#808]
### Context
- **Gitlab plugin version**: 1.3
- **Gitlab version**: GitLab Community Edition 10.4.0
- **Jenkins version**: Jenkins ver. 2.27
- **Job type**: Multibranch Pipeline

### Problem description

We have merge request with a template that is our checklist. This checklist has some checkboxes that we need to verify before merge the code.
And we have a webhook that triggers jenkins job when a merge request is created.

When we create one merge request and right after do some changes in this checklist, the webhook is triggering multiple requests to jenkins. 

Is there a way to use the template as checklist and the webhook not considers these updates?
We check the webhook to triggers only on "Merge Request events", because when the merge request is created, we want that this webhook just trigger this job only once a time.

Gitlab webhook Integration Settings:  
"Comments" 
"Merge requests events"

Jenkins Build Triggers Settings: 
Opened Merge Request Events
Rebuild open Merge Requests on push to source branch
Comments with "jenkins:retry" regex

**Comment by omehegan** [comment]
@annicarol the version of the plugin you are using (if you are really on 1.3.0) is two years old, I would recommend that you upgrade to the latest. There have been some changes in available options for triggering on MRs which might help you. Specifically, triggering on 'comment' events is now an option you can enable or disable. I have a feeling that these check box changes in your MR may be sending the equivalent of MR comment events, which Jenkins could ignore.

Can you follow the instructions under the User Support section of the README to increase the plugin's log level? Then check something in an MR checklist, capture the logs which the plugin shows from that event, and add them to this issue. That will show what type of MR status is being sent.

**Comment by annicarol** [comment]
hey @omehegan because our tools belong to our private customer.. I'll check with them to update the plugin and soon I'll have the answer... thank you!

**Comment by annicarol** [comment]
I don't know if this file will help but here is, also the multibranch logs.
I set the gitlab logging level to FINEST.

**Comment by omehegan** [comment]
@annicarol the attached logs do not contain anything from the plugin. You would only see those logs in the Jenkins log recorder web UI.

**Comment by annicarol** [comment]
Hey @omehegan I am going to check if I have permission to get these logs and send to you soon.

**Comment by annicarol** [comment]
Hey guys I set the log level to ALL.. and see some things about our code in logs for Multibranch.. Please check if these logs will help.[]

**Comment by omehegan** [comment]
@annicarol that log does not have anything from the plugin. You need to either copy and paste the logs from the log recorder UI in Jenkins, or look for a dedicated log file in JENKINS_HOME/logs/custom/.
