### ISSUE TITLE
Feature: Multiple jobs configurable

### ISSUE THREAD

**Issue by avalon12** [jenkinsci/gitlab-plugin#81]
I would love to see the possibility to use more than one Jenkins Job with this awesome plugin. We have different types of jobs for different branches in GIT that we would like to use.

**Comment by bassrock** [comment]
@avalon12  this should actually be possible already, just add a new web hook that triggers on merge requests and pushes that points to the same jenkins url

**Comment by avalon12** [comment]
@bassrock We tried that, this gives some very weird results. The project URL from Gitlab CI plugin that we used to configure gitlab with seems to give back a different result than the actual build result in some cases. I think it is because a matching Commit hash is found in a previous build on the job linked to Gitlab CI.

**Comment by bassrock** [comment]
Hm ok. Well happy to accept any merge request that will fix this.

**Comment by omehegan** [comment]
@avalon12 are you still seeing this issue? I'm pretty sure that the commit SHA is used as a key universally in the plugin, so when it finds >1 build that checked out the same SHA the returned result could be something unexpected.
