### ISSUE TITLE
Feature request build virtual merge request. Merge feature branch local in master and build the future merge

### ISSUE THREAD

**Issue by jensamberg** [jenkinsci/gitlab-plugin#816]
Hello,

It can be usefull if it will be possible when a merge request was submitted that the plugin can build 
the result of the merge into the master that it is clear that the master can be build before the feature branch is merged into master

**Comment by omehegan** [comment]
The plugin is not responsible for any git operations; it only handles allowing GitLab to trigger a build, and sending the result of that build back to GitLab. You can and should use the Git plugin to perform a merge-before-build on MRs if you want this functionality. It is described for Freestyle jobs at https://github.com/jenkinsci/gitlab-plugin#freestyle-jobs and you can create the same thing for Pipeline jobs as well.
