### ISSUE TITLE
trigger on push not working correctly

### ISSUE THREAD

**Issue by lmzhangucsd** [jenkinsci/gitlab-plugin#820]
I have a multibranch pipeline job, I set up the webhook in gitlab correctly and the test return a HTTP 200. but when I add `triggerOnPush: false` in the `properties` inside my Jenkinsfile, but Jenkins still triggers on a push to the repo. Also I have `triggerOnMergeRequest: true` set, but it didn't trigger on merge request.

Jenkins version: 2.121.1
gitlab version: 9.4.7-ee

**Comment by lmzhangucsd** [comment]
this is my jenkinsfile, I followed directly throught this: https://github.com/jenkinsci/gitlab-plugin#pipeline-multibranch-jobs-1
```
properties([
    gitLabConnection('gitlab-master'),
    pipelineTriggers([
        [
            $class: 'GitLabPushTrigger',
            branchFilterType: 'All',
            triggerOnPush: false,
            triggerOnMergeRequest: true,
            triggerOpenMergeRequestOnPush: "never",
            triggerOnNoteRequest: true,
            noteRegex: "Jenkins please retry a build",
            skipWorkInProgressMergeRequest: true,
            ciSkip: false,
            setBuildDescription: true,
            addNoteOnMergeRequest: true,
            addCiMessage: true,
            addVoteOnMergeRequest: true,
            acceptMergeRequestOnSuccess: false,
            branchFilterType: "NameBasedFilter",
            includeBranchesSpec: "test",
            excludeBranchesSpec: "",
        ]
    ])
])

node {
  checkout scm
  addGitLabMRComment(comment: "this commit passed the test, can proceed with merge!")
}
```

**Comment by lmzhangucsd** [comment]
and when I tick the `Merge Request events` option in gitlab, and create a test merge-request, I got this error in gitlab: `Error 409 Merge Request Hook is not supported for this project`

**Comment by katanacrimson** [comment]
This is relevant from the readme:

https://github.com/jenkinsci/gitlab-plugin#pipeline-multibranch-jobs

> Note: There is no way to pass external data from GitLab to a Pipeline Multibranch job, so the GitLab environment variables are not populated for this job type. GitLab will just trigger branch indexing for the Jenkins project, and Jenkins will build branches accordingly without needing e.g. the git branch env var. **Due to this, the plugin just listens for GitLab Push Hooks for multibranch pipeline jobs; merge Request hooks are ignored.**

https://github.com/jenkinsci/gitlab-plugin#pipeline-multibranch-jobs-1

> Unlike other job types, there is no 'Trigger' setting required for a Multibranch job configuration; just create a webhook in GitLab for push requests which points to the project's webhook URL. When GitLab POSTs to this URL, it will trigger branch indexing for the Jenkins project, and Jenkins will handle starting any builds necessary.

You really cannot control multibranch SCM via the trigger definitions in the way you're attempting.  You need a different job type for that.

**Comment by omehegan** [comment]
@rzhang-nevermore yes, @damianb has this right. It's working as designed (for now). I'm going to create a feature request to improve this.

**Comment by calvinatnvidia** [comment]
@omehegan What is the correct way to receive Merge Request hooks from GitLab to a multi-branch pipeline at this time? Is there a way at all?

**Comment by omehegan** [comment]
@calvinatnvidia there is no way right now, see the recent discussion in https://github.com/jenkinsci/gitlab-plugin/issues/416.
