### ISSUE TITLE
Could not set up multiple triggers using Gitlab plugin

### ISSUE THREAD

**Issue by KKoovalsky** [jenkinsci/gitlab-plugin#822]
### Context
- **Gitlab plugin version**: 1.5.6
- **Gitlab version**: gitlab.com
- **Jenkins version**: 2.121.2
- **Job type**: Pipeline, Multibranch

### Problem description

Hi,
Is it possible to define multiple job triggers started by Gitlab plugin?

I want to achieve such behaviour that a build triggers on an open merge request to `master` branch and other build triggers on a push to a branch whose name ends with `-rc[number]`.

I tried to achieve that in such a way:
```
pipelineTriggers([
    [
        $class: 'GitLabPushTrigger',
        triggerOnPush: true,
        triggerOnMergeRequest: false,
        ...
        branchFilterType: "RegexBasedFilter",
        targetBranchRegex: '^.*-rc[0-9]+$',
    ],
    [
        $class: 'GitLabPushTrigger',
        triggerOnPush: false,
        triggerOnMergeRequest: true,
        triggerOpenMergeRequestOnPush: "source",
        ...
        branchFilterType: "NameBasedFilter",
        includeBranchesSpec: "master",
        excludeBranchesSpec: "",
    ]
])
```
but it doesn't seem to work.
In the multibranch job, when I go to the branch which is being built, I can see that in the `Configure` tab the latter configuration has been applied.
How can I set up multiple triggers using the plugin?

**Comment by omehegan** [comment]
@KKoovalsky if you are using a Multibranch job, currently the plugin does not support triggering these on Merge Request hooks, only Push hooks. It will ignore the MR hooks. I would like to see that change but I have not yet had time to try. I think that is the root of your problem.

An alternative solution would be for you to create separate regular Pipeline job for each branch, then you can configure them to use the MR trigger if you want, and you can use the branch name filtering to only build the branches you want. Your repo would then have multiple webhooks configured which point to each job, and Jenkins would filter the requests accordingly.

Sorry that solution is not ideal...
