### ISSUE TITLE
How is it possible to get the build status also on a git submodule?

### ISSUE THREAD

**Issue by jensamberg** [jenkinsci/gitlab-plugin#833]
Hello,

I am using the gitlab-plugin and it works fine. Good work. 
Also it is possilbe to publish the build status back to GitLab.

But how is it possible also publish the build status to the git submodule?

**Comment by omehegan** [comment]
@jensamberg I am not sure I understand the workflow you are asking about. I am imagining a project which uses some git submodules. A commit to the parent project triggers a build, which uses the submodules. Why would the build status of the submodules be of interest in this case? I would expect the submodules to have their own build jobs for validation, which would be triggered only when those modules change. Can you describe your environment and what you would like to see in more detail?

**Comment by jensamberg** [comment]
@omehegan in general you are right. We do it now so. However what I initial want was that I can return the build status to more then one git repro what I can define manual. Actual from this plugin there 
![832a4503-cec2-4c66-a1e4-d4de10fe16c8](https://user-images.githubusercontent.com/22682327/45708260-3342ef00-bb81-11e8-96f7-2a82b3afa940.png)

**Comment by omehegan** [comment]
@jensamberg I see. Unfortunately there is no way to do that with this plugin. The plugin determines what repo to send the build result to based on the repo which triggered the build. So in your case that would be the parent repo, not the submodules. You could perform another GitLab API call yourself, using curl or something, to send the status to other repos. But it is outside the scope of this plugin.

Incidentally, based on the screenshot you shared, I think you may be using an old version of the plugin. The latest version is 1.5.9, I would recommend that you upgrade to that if possible.
