### ISSUE TITLE
Posting Commit status from approved Merge request 

### ISSUE THREAD

**Issue by AntoineConffx** [jenkinsci/gitlab-plugin#834]
### Context
- **Gitlab plugin version**: 1.5.9
- **Gitlab version**: CE v11.1.4
- **Jenkins version**: 2.138
- **Job type**: Pipeline

### Logs & Traces
I can attach logs if necessary

## What works.
I can currently build Merge Requests using webhooks and the build status correctly posts on the pipelines/merge request page. 
## What doesn't work
The issue is that I can't seem to get the build status from the merge request to carry over to the commit page when the merge request is finally built and merged to the target branch.
The triggers I have enabled on the gitlab project config are:
  -  Merge request hook and Notes.
On Jenkins side, I enabled the following triggers: 
  - Opened merge request and comments.

Is it possible to get the build status from the Merge request carry over to the commit page when Merge request is approved (merged) without triggering another build ?

**Comment by omehegan** [comment]
@AntoineConffx I don't think this is possible. The plugin only sends build status once per build, and I believe it sends it back to GitLab to different endpoints depending on how the build was triggered. For example, if triggered by an MR, the result is send to the MR API endpoint. If triggered by a commit, it sends it to the commit endpoint. This in turn affects how the status is displayed in GitLab. Carrying over the status as you describe would, I think, effectively require GitLab to copy that status from the MR commit to the final merge commit that goes into the target branch.

**Comment by AntoineConffx** [comment]
@omehegan 
I see. So I would need to trigger another build on master itself to get the commit status.

Another question if its okay to keep it in the same issue.
I current have 2 jobs for Gitlab projects. Both are setup to be triggered via webhook listening for merge request and comments.
One of those projects can be built manually and it successfully posts the commit status to the master branch (Forcing master branch on manual builds), while the other fails to commit status updates with an error related to missing Build action in gitlabCommitStatus retrieveGitlabProjectIds.
How would I go on about fixing an issue like that ? I've compared the build.xml files of both projects and they're the same.

**Comment by omehegan** [comment]
@AntoineConffx for your second question, I would need to see logs with the exact error. Can you open a new issue and attach those?

**Comment by AntoineConffx** [comment]
@omehegan 
Sure thing, Will close this issue. 
Thanks
