### ISSUE TITLE
Gitlab MR status pending if there is a merge conflict

### ISSUE THREAD

**Issue by fontealpina** [jenkinsci/gitlab-plugin#838]
### Context
- **Gitlab plugin version**: 1.5.9
- **Gitlab version**: 11.1.6-ee
- **Jenkins version**: 2.138.1
- **Job type**: Pipeline, Freestyle, Matrix, etc.

### Logs & Traces
![mr_pending](https://user-images.githubusercontent.com/10811370/45811913-ad34be80-bcce-11e8-97af-2a7d4e99ce18.png)

### Problem description
- what were you doing:   
Push on a opened Merge Request NOT marked as WIP
- what occurred:  
A job on jenkins it has been triggered, this job fails and the MR pipeline status is set as pending(orange icon)
- what would be expected:  
I would expect that in case of a merge conflict in the merge request, the jenkins job is not triggered,    
or if it is, then the mr pipeline status is set as failed.

**Comment by omehegan** [comment]
> I would expect that in case of a merge conflict in the merge request, the jenkins job is not triggered, or if it is, then the mr pipeline status is set as failed.

GitLab figures out that there is a merge conflict, but triggers the MR webhook anyway. Jenkins will always build in that case, so you would need GitLab to not send the hook or to set the pipeline status differently. Not a plugin issue.

**Comment by fontealpina** [comment]
@omehegan but why isn't set as failed and got stuck in a pending status?

**Comment by omehegan** [comment]
@fontealpina I'm guessing it was a Pipeline job, and there wasn't a try/catch/finally block to catch the failure and send a final status update to GitLab.
