### ISSUE TITLE
Inverse filter branches.

### ISSUE THREAD

**Issue by afterdesign** [jenkinsci/gitlab-plugin#84]
Hi.
We have 2 builds. One of them is based on ```master``` branch and this build has higher priority and needs to be stable all the time.

The second build is for any other branch.
We are creating new branches for each feature we are creating so I would like to ignore master in the second build.

Option to inverse filter branches behaviour would be awesome for us.

Thanx for awesome job !

**Comment by bassrock** [comment]
Happy to accept any merge requests for this.

**Comment by WonderCsabo** [comment]
This was fixed i think, now we have an exclude filter.

**Comment by omehegan** [comment]
Yes, this was fixed, there is an exclude option now.
