### ISSUE TITLE
Plugin unable to pull desired tag if both BRANCH and TAG have commit SHA

### ISSUE THREAD

**Issue by yuyan-seik** [jenkinsci/gitlab-plugin#842]
### Context
- **Gitlab plugin version**: 1.5.6
- **Gitlab version**:  9.4.1
- **Jenkins version**: Jenkins ver. 2.138.1
- **Job type**: Multibranch Pipeline

### Problem description

Usually, we will create a tag when we commit to the master branch. Our Jenkins gitlab plugin will be configured to pull based on the tag version.
The master branch commit SHA and the tag commit SHA will be the same which I am not sure is this normal. 
Then here comes our issue, the plugin will pull the master branch instead of tag version.

To temporary solve this issue, I have to recommit the master branch with dummy changes to ensure the commit SHA is different from the tag version I wanted to pull.

Is there any way to make sure it pulled from the tag instead of branch?

**Comment by hho** [comment]
Use an annotated tag (own hash) instead of a lightweight tag (points to commit hash).
Recommended reading: https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by omehegan** [comment]
@yuyan-seik I think @hho's answer is correct, did that work for you? I think this is more of a Git issue than a GitLab plugin issue.
