### ISSUE TITLE
gitcommitstatus issue

### ISSUE THREAD

**Issue by ghost** [jenkinsci/gitlab-plugin#846]
node('iMac_KPlus') {
    stage('Pull Code') {
        checkout([$class: 'GitSCM', 
        branches: [[name: 'feature/google-analytics']], 
        doGenerateSubmoduleConfigurations: false, 
        extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: '']], 
        submoduleCfg: [], 
        userRemoteConfigs: [[credentialsId: 'myCre', url: 'myURL']]])
    }

ansiColor('xterm') {
    stage('Build and tests') {
        // Build and Test
        sh '''
        export PATH=/usr/local/bin:$PATH
        export LANG=en_US.UTF-8
        export LANGUAGE=en_US.UT
        if [ -f "Podfile.lock" ] ; then
            rm Podfile.lock 
        fi
        if [ -f "Pods" ] ; then
            rm -rf Pods
        fi

        #curl -sSL https://get.rvm.io | bash
        
        #sudo bundle install

        pod install
        #bundle exec fastlane scan
        '''

        //xcodeBuild appURL: '', assetPackManifestURL: '', buildDir: '', bundleID: '', bundleIDInfoPlistPath: '', cfBundleShortVersionStringValue: '', cfBundleVersionValue: '', cleanBeforeBuild: false, configuration: 'Debug', developmentTeamID: '', developmentTeamName: '', displayImageURL: '', fullSizeImageURL: '', ipaExportMethod: 'ad-hoc', ipaName: '', ipaOutputDirectory: '', keychainName: '', keychainPath: '', keychainPwd: '', logfileOutputDirectory: '', provisioningProfiles: [[provisioningProfileAppId: '', provisioningProfileUUID: '']], sdk: '', symRoot: '', target: '', thinning: '', xcodeProjectFile: '', xcodeProjectPath: '', xcodeSchema: 'FingerStyleForMe', xcodeWorkspaceFile: 'FingerStyleForMe', xcodebuildArguments: 'test -destination "platform=IOS Simulator,name=iPhone 6,OS=12.0" '
        // Publish test restults.
        //junit 'test-reports/*.xml'
    }
}

    stage ('Notify') {
        // Send slack notification
        gitlabBuilds(builds: ["Notify"]) {
            gitlabCommitStatus(name: 'Notify') {
                updateGitlabCommitStatus name: 'Notify', state: 'success'
            }
        }
    }
}

the status does not show in git lab, but build success

**Comment by jgeorgeson** [comment]
Not one of the plugin maintainers, but I believe that `gitlabBuilds` would go in the `options` section of the pipeline.

```groovy
options {
  gitlabBuilds(builds: ["build"]) 
}
```

This puts a job named `build` in I think `Running` state. Then you would use not both but one of `gitlabCommitStatus` or `updateGitlabCommitStatus`. The `gitlabCommitStatus` step reports the collective success or failure of the steps within it. It's good for when you put multiple builds in the `gitlabBuilds`, like one per stage.

```groovy
    stages {
        stage('Build') {
            steps {
                gitlabCommitStatus(name: 'build') {
                    // Check out revision that was used to fetch the Jenkinsfile running the pipeline
                    checkout scm
                    // Run groovy script, we can access the full Groovy sandbox and approved classes this way
                    script {
                        // Save the build timestamp and commit hash
                        startdate = new Date().format("yyyyMMddHHmmss")
                        shortCommit = sh(returnStdout: true, script: "git rev-parse --short=10 HEAD").trim()
                    }
                }
            }
        }
```

While the `updateGitlabCommitStaus` step is a self-contained type of update, well suited to use in `post`.

```groovy
    post {
        failure {
            updateGitlabCommitStatus name: 'build', state: 'failed'
        }
        success {
            updateGitlabCommitStatus name: 'build', state: 'success'
        }
    }
```

In either case you want to make sure that every build you listed in `gitlabBuilds` is updated either in a stage or in post.

**Comment by omehegan** [comment]
@jgeorgeson thanks for replying to this, you nailed it :)

@thanatgo123 see above.
