### ISSUE TITLE
Unable to clone with GitLab API token

### ISSUE THREAD

**Issue by keestux** [jenkinsci/gitlab-plugin#847]
### Context
- **Gitlab plugin version**: 1.5.10
- **Gitlab version**: 11.2.3
- **Jenkins version**: 2.147
- **Job type**: Pipeline

### Logs & Traces

The job has this in the log

```
Cloning the remote Git repository
Cloning repository https://git.ijzerbout.nl/mygroup/testrepo.git
 > git init /src/mygroup/jenkins/nightly/2/checkout # timeout=10
Fetching upstream changes from https://git.ijzerbout.nl/mygroup/testrepo.git
 > git --version # timeout=10
 > git fetch --tags --progress https://git.ijzerbout.nl/mygroup/testrepo.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://git.ijzerbout.nl/mygroup/testrepo.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://git.ijzerbout.nl/mygroup/testrepo.git/'
```

### Problem description

- in GitLab an API token was created. This is added as a `GitLab API token` in Jenkins credentials.
- in Jenkins / Configure System in the GitLab section a connection is created with https url. Clicking Test Connection shows Success
- in the Pipeline job a Credentials Parameter is added, type is GitLab API token, name GITLAB_TOKEN

The relevant section of the Pipeline script 
```
    stages {
        stage('Checkout') {
            steps {
                script {
                    if (!fileExists(checkoutDir)) {
                        new File(checkoutDir).mkdir()
                    }
                }

                dir(checkoutDir) {
                    // Pull the source and test a merge
                    checkout changelog: true, poll: true, scm: [
                        $class: 'GitSCM',
                        branches: [[name: "origin/master*"]],
                        doGenerateSubmoduleConfigurations: false,
                        submoduleCfg: [],
                        userRemoteConfigs: [[
                            credentialsId: "${GITLAB_TOKEN}",
                            name: 'origin',
                            url: "https://git.ijzerbout.nl/mygroup/testrepo.git"
                        ]]
                    ]
                }
            }
        }
```

Besides verifying with Test Connection in Configure System, I have also checked the token using the following url, and that works too.
```
git clone https://gitlab-ci-token:mysecrettoken@git.ijzerbout.nl/mygroup/testrepo.git
```

What am I doing wrong in the Pipeline script?

**Comment by omehegan** [comment]
This is not a GitLab plugin issue (this plugin only handles triggering jobs and sending results back to GitLab - cloning is handled by the Git plugin). It's possible you are not using the credentials wrapper correctly in your Pipeline script, because you are not explicitly setting up HTTP Basic Auth as far as I can see. But I don't have experience using that for GitLab cloning, I have only ever used SSH with keys. You would need to raise this with the Git plugin maintainer.

**Comment by keestux** [comment]
OK, thanks for looking anyway

**Comment by matheusrizzo** [comment]
I had the same error and I had to do a lot of things to solve it.
First, I would like to say that my pipeline was connecting to github normally.

I suggest you follow some steps:

1 - First check if your Jenkins is Up to date
2 - Check if all plugins are Up to dated, especially the git/git labs plugins (see my gitlabs list)
	Git client; Git; Git server; Gitlab API; Gitlab Authentication; Gilab Branch Source; Gitlab logo; Gitlab Merge Request; Gitlab;
3 - I generated ssh keys. In some websites I read that there are some problems with version of ssh. In my case, I generated using this command: (ssh-keygen -t ed25519 -C "jenkins key")
4 - I configured the keys in jenkins credentials. Basically, you need to add a "ssh username with private key". You will copy the generated private key text and past inside jenkins credentials.
5 - before I coded my pipeline, I tried to use a common job. Im my case, this worked fine. 
6 - When I tried to create a pipeline, I received the same error. So, I used the a jenkins tool (link pipeline syntax in the pipelines configuration screen). I realized that to connect gitlab there are specific lines to be added. So, adding this lines, I solved my problem.
See my example below:
checkout([
		$class: 'GitSCM', 
		branches: [[name: '*/master']], 
		browser: [
			$class: 'GitLab', 
			repoUrl: 'git@mygitlabwebsite.com/project/example.git'
		], 
		extensions: [], 
		userRemoteConfigs: [[
			credentialsId: 'usr_created_on_jenkins_credentials', 
			url: 'git@mygitlabwebsite.com/project/example.git'
		]]
	])
