### ISSUE TITLE
passing environment variables in "Add note with build status on GitLab merge requests"

### ISSUE THREAD

**Issue by zumacinsmity** [jenkinsci/gitlab-plugin#848]
## Issue
Don't know how to pass information generated in a build step to GitLab

### Context
- **Gitlab plugin version**: 1,4,6
- **Gitlab version**: ? (don't know how to tell)
- **Jenkins version**: 2.121.1
- **Job type**: Pipeline, Freestyle, Matrix, etc.

### Problem description

_Describe your problem in a meaningful way_:
The quick help says "(with support environment variables)".  I do not know what that means.  I am trying to pass the results of a code coverage job during the build step.  I don't see any way to get the contents of an environment variable from that step nor the contents of a file generated in that step to pass back in the custom messages on success, failure, etc.

**Comment by omehegan** [comment]
@zumacinsmity go to /help in your GitLab instance to see the version. Version 1.4.6 of the plugin is over a year old, I would recommend that you update.

In a non-Pipeline job, there is no easy way to take data from a build step and push it to GitLab in a note. Changes to the environment variables inside a shell script build step don't persist outside of that shell. That's a limitation of Jenkins. You might be able to accomplish this by creating a string parameter for the job, then writing something to its env var during the build, and then using that parameter in the comment post-build step. But I'm not positive it would work.

If you used a Pipeline job, it would be easier to capture the results from the job in a variable and then reuse that in a `addGitLabMRComment()` step.

**Comment by ukuko** [comment]
finally found an answer to my issue. I will migrate to pipeline then. 
I suggest to put this information on the README.md.
