### ISSUE TITLE
MR Validation : communication between Jenkins et Gitlab

### ISSUE THREAD

**Issue by gbsop** [jenkinsci/gitlab-plugin#850]
### Context
- **Gitlab plugin version**: 1.5.9
- **Gitlab version**: 11.2.3-ee
- **Jenkins version**: 2.130
- **Job type**: Pipeline

### Problem description

Hi
- On a MR validation, we are using Jenkins CI from GitlabEE (configured with push event and MR event) to launch a build on Jenkins. 
- At the end of the build, the build make a push on GitlabEE. To avoid a loop, the push made by jenkins contains in the comment [skip-ci].
When we were with Jenkins 2.73.3 and GitlabEE 11.2.3-ee , this worked fine : 
- MR validation from feature to develop ==> jenkins build is launch
- MR validation from develop to master ==> jenkins build is launch
When we updated Jenkins to 2.130 (and even to 2.138.1), with GitlabEE staying at 11.2.3-ee : 
- MR validation from feature to develop ==> jenkins build is launched
- MR validation from develop to master ==> jenkins build is NOT launched
We don't know where the issue comes from.
Could you help us making it work ? (Launch the jenkins build also when we have a MR validation from develop to master). Is there a special to configure that so that it would work ?

before migration : Jenkins 2.73.3 avec le plugin GitLab 1.5.2 et GitlabEE 11.2.3-ee ==> operation OK

Thank you
Regards

**Comment by omehegan** [comment]
@gbsop I am not sure why an upgrade to Jenkins, if you did not change the plugin version, would break this functionality. Can you follow the instructions in https://github.com/jenkinsci/gitlab-plugin#getting-help to enable debug logging? Then reproduce this issue, and paste the logs here. That should help us see why the plugin is not always triggering the build.
