### ISSUE TITLE
GitLab Web Hook failed Hook executed successfully but returned HTTP 401 

### ISSUE THREAD

**Issue by asagi687** [jenkinsci/gitlab-plugin#851]
**First:**
・My Jenkins is working on docker container.
・GitLab is installed in "Redmine Certified by Bitnami" instance of AWS 
(use port 80 for Redmine and 8888 for GitLab) .

**Issue:**
When I try 
URL：http://JENKINS_URL/project/PROJECT_NAME on webhook,

I get this massage.

![image](https://user-images.githubusercontent.com/44489808/47548976-93257600-d935-11e8-8a18-4726d9e27f6a.png)

・I try also 
   https://JENKINS_USER_ID:JENKINS_API_TAKEN@JENKINS_URL/project/PROJECT_NAME,
   but it did not work.
・Both checked and unchecked the "Enable SSL verification" did not work.

**Version:**
- **Gitlab plugin version**: 1.5.10
- **GitlabCE version**: 11.3.0
- **Jenkins version**: 2.107.3
- **Job type**: Freestyle

Is this error caused by wrong setting of Nginx?
Or related on other network connecting error?

Please give me some advice.

**Comment by omehegan** [comment]
@asagi687 have you followed the directions at https://github.com/jenkinsci/gitlab-plugin#gitlab-to-jenkins-authentication? Does this user have Job/Build permissions in Jenkins? You can try enabling debug logging by following the directions here: https://github.com/jenkinsci/gitlab-plugin#getting-help and see if that helps show what the issue is.

**Comment by baymac** [comment]
Hi @omehegan I tried whatever you suggested but I am also getting the same error. I am running a Ubuntu VM with Jenkins instance in Azure.
![Screenshot from 2019-03-29 05-04-36](https://user-images.githubusercontent.com/23079344/55199521-4c87c080-51e0-11e9-9900-5e36e7e4c2a6.png)

**Comment by jhonalexander0809** [comment]
> @asagi687 have you followed the directions at https://github.com/jenkinsci/gitlab-plugin#gitlab-to-jenkins-authentication? Does this user have Job/Build permissions in Jenkins? You can try enabling debug logging by following the directions here: https://github.com/jenkinsci/gitlab-plugin#getting-help and see if that helps show what the issue is.

Thanks for your comment!

this solution served for me
https://github.com/jenkinsci/gitlab-plugin#gitlab-to-jenkins-authentication

Using in webhook:
https://USERID:APITOKEN@JENKINS_URL/project/YOUR_JOB

**Comment by Tammeny** [comment]
I got :
```
Hook executed successfully but returned HTTP 405 <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
```

**Comment by Sevelantis** [comment]
> > @asagi687 have you followed the directions at https://github.com/jenkinsci/gitlab-plugin#gitlab-to-jenkins-authentication? Does this user have Job/Build permissions in Jenkins? You can try enabling debug logging by following the directions here: https://github.com/jenkinsci/gitlab-plugin#getting-help and see if that helps show what the issue is.
> 
> Thanks for your comment!
> 
> this solution served for me
> https://github.com/jenkinsci/gitlab-plugin#gitlab-to-jenkins-authentication
> 
> Using in webhook:
> https://USERID:APITOKEN@JENKINS_URL/project/YOUR_JOB

Does it need to be 'https' in order to work ? 'http' doesnt work for me and 'https' gives error:
`
Hook execution failed: SSL_connect returned=1 errno=0 state=error: wrong version number
`
