### ISSUE TITLE
I can not run Jobs using GitLab webhooks in multibranch pipelines

### ISSUE THREAD

**Issue by miguelconde91** [jenkinsci/gitlab-plugin#852]
I can not run Jobs using GitLab webhooks, please help me because everything look fine, I follow step by step and any result.

Jenkins version: 2.121.3
Gitlab Plugin version: 1.5.10
And I'm using gitlab.com

I am trying to execute my jobs in my multibranch pipelines from Gitlab using the documentation described here, so I followed the next steps:

1- Create a new repository in GitLab with a Jenkinsfile like this:

```
properties([gitLabConnection('BlueOceanTech GitLab Connection')])
pipeline {
	agent {label 'master'}
	stages {
		stage('Deploy Master') {
			when {expression { env.BRANCH_NAME == 'master' }}
				steps {
				  sh '''
                                   #!/bin/bash
                                   echo Deploying in master....
                                   '''
				}
		}
	}
}
```

2- Create a new task in Jenkins, a multibranch pipeline (DOT_test-webhook). Scan branch, my Jenkinsfile was found in my master and dev branchs

3- Create a webhook in GitLab, I'm using authentication and Role-based Strategy like authorization mechanism, so my URL for the webhook is:
https://myjenkinsuser:myapitoken@my.jenkins.com/project/DOT_test-webhook and my trigger is Push Events with Enable SSL verification and Save it.

4- On the Global Configuration page in Jenkins, in the GitLab configuration section I have completed all the data, and the 'Test Connection' button is Success.

The issue is when I'm trying to execute a test or with a commit, the Gitlab execution is ok, response status 200, but in Jenkins the jobs is not executed. How I can debug or found the error. 

Important:
-My jenkins is behind a nginx server with proxypass.
-My jobs are always inside Views.
-All my jobs are multibranch pipelines.
-Using this line I can run a Job:
curl -X POST https://myjenkinsuser:password@my.jenkins.com/view/CDT/job/CDT_tek-task-pm/job/master/build

**Comment by heamaral** [comment]
I'm also having this issue, the response status code of webhook is 200 but Jenkins doesn't trigger the job.

**Comment by miguelconde91** [comment]
I have not been able to find a solution yet

**Comment by omehegan** [comment]
@miguelconde91 please enable the debug logging as described in https://github.com/jenkinsci/gitlab-plugin#getting-help and then attach logs to this issue after you reproduce the problem. They should tell us why they plugin is not triggering your job.

**Comment by ShankarSumanth** [comment]
Can you check if the solution helps?
https://github.com/jenkinsci/gitlab-plugin/issues/533#issuecomment-440122433

**Comment by faikabouthalja** [comment]
I'am having this issue , test with pipeline event returns code 200 but no build is launched on Jenkins and when new pipeline event happens I see return code 200 when pipeline is still running but when it finish on success and is supposed to trigger Jenkins Job  I get return code 500 and error seems to be in response body: java.lang.NullPointerException: sourceProjectId must not be null.

**Comment by humble-race-condition** [comment]
This still does not work.

**Comment by artem-kosenko** [comment]
+1 **does not work at all**. The plugin configured "gitlab-webhook/post" web-hook, GitLab triggers it as expected, I can see related messages in the Multibranch Pipeline Events.... But the project is not triggered to rescan the repository and start build on related MR. Very strange. Who know how to debug this?
