### ISSUE TITLE
Use a red cross icon for build failure in postbuild step "Add note ... GitLab merge requests"

### ISSUE THREAD

**Issue by geoffroyjabouley** [jenkinsci/gitlab-plugin#856]
## Issue
When publishing a Note on GitLab for a failed build, icon used is ❎ (: negative_squared_cross_mark :).
Proposal is to use by default icon :x: (: x :) instead

### Context
- **Gitlab plugin version**: 1.5.5
- **Gitlab version**: 11.4.6
- **Jenkins version**: 2.107.2
- **Job type**: Freestyle/Matrix

### Logs & Traces

N/A

### Problem description
| | |
|-|-|
|Was|:negative_squared_cross_mark: Jenkins Build FAILURE|
|Would be| :x: Jenkins Build FAILURE|

Note: it can also be achieved per job configuration, using a custom message for failed build...

**Comment by omehegan** [comment]
We discussed this in #582 but I closed that as part of a cleanup. Maybe we should just reopen and merge it :)

**Comment by wesbland** [comment]
Oh God yes. A quick scroll through the issue tells you nothing about the build status when they're all the same shape and color.

**Comment by ukuko** [comment]
I would definitively support this change. This is confusing and not intuitive (just look what gerrit does).
