### ISSUE TITLE
Webhook seems to run, can see it in the log but build never starts

### ISSUE THREAD

**Issue by carlos4242** [jenkinsci/gitlab-plugin#861]
### Context
- **Gitlab plugin version**: 1.5.10
- **Gitlab version**: CE 11.4.4
- **Jenkins version**: 2.138.2
- **Job type**: Freestyle

#### On the gitlab side:

```
Request URL: POST http://--REDACTED--:8081/project/Mobile/iOS%20Merge%20Requests 200

Trigger: Merge Request Hook

Elapsed time: 0.01 sec

Request time: 8 minutes ago

Request headers:
Content-Type: application/json
X-Gitlab-Event: Merge Request Hook
X-Gitlab-Token: --REDACTED--
Request body:
{
  "object_kind": "merge_request",
  "event_type": "merge_request",
  "user": {
    "name": "--REDACTED--",
    "username": "--REDACTED--",
    "avatar_url": "--REDACTED--"
  },
  "project": {
    "id": 721,
    "name": "iOSMobileClient",
    "description": "",
    "web_url": "--REDACTED--",
    "avatar_url": null,
    "git_ssh_url": "--REDACTED--t",
    "git_http_url": "--REDACTED--",
    "namespace": "MOBILE-FRONTEND",
    "visibility_level": 0,
    "path_with_namespace": "MOBILE-FRONTEND/iOSMobileClient",
    "default_branch": "develop",
    "ci_config_path": null,
    --REDACTED--
  },
 --REDACTED--
}
Response headers:
Connection: close
Date: Thu, 29 Nov 2018 14:50:57 GMT
X-Content-Type-Options: nosniff
Server: Jetty(9.4.z-SNAPSHOT)
Response body:
```

#### On the Jenkins side, in the Gitlab plugin:

```
Nov 29, 2018 2:39:19 PM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic
WebHook called with url: /project/Mobile/iOS%20Merge%20Requests
Nov 29, 2018 2:39:19 PM FINE com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction
Push: {
  "object_kind" : "push",
  "event_name" : "push",
  "before" : "94aa477795b33fe7a68e9e67ca10b52ec108670e",
  "after" : "b26fcbea695249038f7e3ccb8aa60faf2b533cbe",
  "ref" : "refs/heads/develop",
  "checkout_sha" : "b26fcbea695249038f7e3ccb8aa60faf2b533cbe",
  "message" : null,
  "user_id" : 149,
  "user_name" : "--REDACTED--",
  "user_username" : "--REDACTED--",
  "user_email" : "--REDACTED--",
  "user_avatar" : "--REDACTED--",
  "project_id" : 721,
  "project" : {
    "id" : 721,
    "name" : "iOSMobileClient",
    "description" : "",
    "web_url" : "--REDACTED--",
    "avatar_url" : null,
    --REDACTED--
  },
  "commits" : [ {
    --REDACTED--
  } ],
  "total_commits_count" : 3,
  "repository" : {
    "name" : "iOSMobileClient",
    "url" : "--REDACTED--",
    "description" : "",
    "homepage" : "--REDACTED--",
    "git_http_url" : "--REDACTED--",
    "git_ssh_url" : "--REDACTED--",
    "visibility_level" : 0
  }
}
```

*But no sign of a build starting, ever.*

### Problem description

Following the instructions here: https://github.com/jenkinsci/gitlab-plugin
and referencing a blog piece here: https://medium.com/@teeks99/continuous-integration-with-jenkins-and-gitlab-fa770c62e88a

I tried to set up our GitLab to kick off a test Jenkins job on creation of a merge request.

The web hook seems to have been set up correctly and when testing it returns status code 200 from Jenkins, plus you can see the results in the log on Jenkins, but the build never starts!

**Comment by carlos4242** [comment]
Update: it started working without any obvious reason why! Perhaps the issue is some more logging of what might be the issue? One thing I changed soon before that was credentials for Jenkins to access gitlab, which looked a bit off beforehand. But that didn’t seem to immediately fix it. Possibly 12 hours later, overnight, it started to run Jenkins builds in response to gitlab events. Maybe some logging of what the logic is doing on the Jenkins plugin side? Like when set to finest logging, it should say “received a message from gitlab but skipped building because XYZ”.

**Comment by sfransen** [comment]
I have the problem of the wehlook not working for most of my jenkins jobs. I get this error 
branch baker or baker is not allowed
 if I do a filter using 
Filter branches by regex  Target Branch Regex
(.*baker.*)
 I get a error if I downgrade to 1.5.10 all is working fine again.
1.5.11 don't work right  unless I have to change my Regex if I do what is the new format to use

**Comment by omehegan** [comment]
@carlos4242 if the plugin actively chooses not to trigger a job because of some configuration (branch filters, or the ref was already built, for example), it always logs this. But I have seen an issue like yours when the job did not actually have the GitLab trigger configured. In other words, "Build when a change is pushed to GitLab" was not checked. It could have been something that simple. Please reopen if you have this issue again, and attach your job's config.xml file.

**Comment by omehegan** [comment]
@sfransen this is strange because nothing regex-related was changed between .10 and .11. But your issue sounds unrelated to this, so please open a new one. When you do, attach debug logs as described at https://github.com/jenkinsci/gitlab-plugin#getting-help.
