### ISSUE TITLE
gitlabMergeRequestState should be set for comments on MRs

### ISSUE THREAD

**Issue by freidenker** [jenkinsci/gitlab-plugin#862]
with merge request comment(gitlab note hook) trigger jenkins job buiding, can not get `gitlabMergeRequestState`, but `gitlabSourceBranch` is ok

**Comment by omehegan** [comment]
This is because the Note hook is generalized and applies to various resources, not just Merge Requests. The plugin only sets gitlabMergeRequestState when it comes from an MR hook. I will mark this as a feature request but I don't know when it might get added. A PR would be welcome :)
