### ISSUE TITLE
Use of when buildingTag does not work in Declarative pipeline

### ISSUE THREAD

**Issue by dtronche** [jenkinsci/gitlab-plugin#864]
## Issue
For our project we are using gitlab-ce and Jenkins to build docker images. I'm using a Pipeline Jenkinsfile to build my docker
I suppose my jenkins job is correctly configured since the build is triggered each time I push a commit or a tag into my gitlab project
In my pipeline, I have a stage I wish to be called only when a tag is pushed
I added the following line
`when {  buildingTag() }`
But every time I push a tag in gitlab, I have the message _Stage skipped due to when conditional_

Here is the Jenkinsfile I'm using:

```
pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                gitlabCommitStatus(name:"build") {
                  script { 
                     docker.withRegistry('Nexus URL', 'docker-pull-id') {
                        app = docker.build("my-project","--my proxy options") 
                     }
                  }
                }
            }
        }
        stage('Push image') {
         steps {
            script { 
                docker.withRegistry('Nexus URL', 'docker-push-id') {
                       app.push("latest")
                }
            }
          }
       }
       stage('Push tag image') {
	when {	  buildingTag()	}
           steps {
               script { 
                   docker.withRegistry('Nexus URL', 'docker-pull-id')') {
                       app.push("tag")
                   }
               }
           }
       }
   }
}

```
The only way I have manage to make tag works is by using a scripted pipeline similar to the one described [here](https://wiki.jenkins.io/display/JENKINS/Git+Tag+Message+Plugin)

I don't think I'm trying something exceptional so it is probably a configuration issue on my side but I have no idea what is wrong. 

### Context
- **Gitlab plugin version**: 1.5.11
- **Gitlab CE version**: 11.2.0
- **Jenkins version**: 2.153
- **Job type**: Pipeline

**Comment by omehegan** [comment]
I've never heard of the `when { buildingTag() }` feature. I just looked it up and I see that it's just part of Pipeline itself. I don't think this failure is related to the plugin. I don't understand how buildingTag() is set, but I would guess it comes from the git plugin. I would open a bug at https://issues.jenkins-ci.org/secure/Dashboard.jspa
