### ISSUE TITLE
Question: What should be used as branch specifier when using branch filter?

### ISSUE THREAD

**Issue by dot3dash4dot** [jenkinsci/gitlab-plugin#888]
### Context
- **Gitlab plugin version**: 1.5.0
- **Gitlab version**: 8.17.4
- **Jenkins version**: 2.121.3
- **Job type**: Freestyle

### Problem description

I have a job set up with "Build when a change is pushed to Gitlab" > "Allowed Branches" > "Filter branches by name" set to, for example:

master,release/branch2

What should I then set the Git "Branches to build"/"Branch Specifier" setting to in order to get the job to build from the branch that triggered the job by getting through the filter? Currently it works as expected if I set it to:

:origin/master|origin/release/branch2

but that obviously means I have to define my branch list twice. Is there a better way?

Thanks

**Comment by omehegan** [comment]
@jimmyjudas you use the variable that is set by the plugin. See https://github.com/jenkinsci/gitlab-plugin#git-configuration
