### ISSUE TITLE
Gitlab webhook does not trigger a build on jenkins

### ISSUE THREAD

**Issue by Opalo** [jenkinsci/gitlab-plugin#907]
I've a group of multibranch pipeline jobs generated with the following piece groovy script:

```
[
      'repo1',
      'repo2',
].each { service ->

  multibranchPipelineJob(service) {

    displayName(service)

    branchSources {
      git {
        remote("git@gitlab.com:whatever/${service}.git")
        credentialsId('gitlab-ssh-key')
      }
    }

    orphanedItemStrategy {
      discardOldItems {
        daysToKeep(0)
        numToKeep(30)
      }
    }

    triggers {
      periodic(5)
    }

  }
}
```
and in each repo a `Jenkinsfile` that looks as follows:

```
#!/usr/bin/env groovy

properties([
      gitLabConnection('ci@gitlab.com'),
      pipelineTriggers([
            [
                  $class               : 'GitLabPushTrigger',
                  triggerOnPush        : true,
                  triggerOnMergeRequest: true,
            ]
      ]),
      disableConcurrentBuilds(),
      overrideIndexTriggers(false)
])

node {

  def sbtHome = tool name: 'sbt-0.13.15', type: 'org.jvnet.hudson.plugins.SbtPluginBuilder\$SbtInstallation'

  stage('Checkout') {
    checkout scm
  }

  stage('Build') {
    sh "'${sbtHome}/bin/sbt' clean compile"
  }

  stage('Test') {
    sh "'${sbtHome}/bin/sbt' test"
  }

  if (env.BRANCH_NAME == 'develop' || env.BRANCH_NAME == 'master') {
    stage('Publish') {
      sh "'${sbtHome}/bin/sbt' publish"
    }
  }
}
```
It all works correctly. The seeder project generates all the folders from the first script and all the branches for given repo are built correctly.

Unfortunately I've problems with triggering a build for any branch after commit + push has been made to gitlab.

I've jenkins configured correctly - I mean the gitlab plugin, there is a connection and it all works well.

I've also added a webhook on the gitlab side and it also runs correctly. After a test push is sent I receive 200 OK from jenkins and I do see in logs that scanning the branches has started and detected the changes correctly. Unfortunately the build for the changed branch does not start. Here's an extract from branch scan log:

```
  Checking branch ci
      ‘Jenkinsfile’ found
    Met criteria
Changes detected: ci (a7b9ae2f930b0b10d52bb42f1ecf96a68bba4a30 → 39a4c1a65051d5e90079feec14ad22455a77c58e)
Did not schedule build for branch: ci
```
I'm 100% sure that this not a problem with communication between my jenkins instance and gitlab account. I see the webhook being triggered after push to gitlab, I see the request being send and branch scan being run. Changes are also detected but why on earth the job isn't started? I've also read the docs thoroughly and have it all configured correctly.

Jenkins version: 2.150.3
Gitlab version: 11.8.1-ee
Gitlab plugin version: 1.5.11
Job type: Multibranch pipeline

This is a repost from [here](https://stackoverflow.com/questions/54956947/gitlab-webhook-does-not-trigger-a-build-on-jenkins). I've already spent almost 6 days trying various solutions to no avail.

**Comment by nadavbuc** [comment]
I am having a somewhat similar issue:
for the test case i used 3 repostories:
bla-service good-service third-service
in each repo i have setup some branch
bla-service:aaa
good-service:bbb
third-service:ccc
they are all configured in gitlab to trigger the same jenkins pipeline job
iv'e setup a script to push to all of them one by one (with less than a second of difference between them)
all jobs ran

i've changed branch name bbb to aaa so now its as follows:
bla-service:aaa
good-service:aaa
third-service:ccc

ran the script and only two jobs ran
finally i tested with all repos with same branch name
only one job ran

the pipeline doesn't run if branch is identical on the web hook request, even if the repository is different

this looks like a bug
tested on 1.5.10

**Comment by Opalo** [comment]
Thanks for the input @nadavbuc. Also, yup, it looks like a bug.

**Comment by Opalo** [comment]
It seems that after upgrading jenkins to v.2.164.1 it all started working correctly.
