### ISSUE TITLE
Git clone fails https://repo/project.git using a downloaded certificate

### ISSUE THREAD

**Issue by JackTiger** [jenkinsci/gitlab-plugin#943]
### Before submitting an issue I have first:

- [] read the documentation on the [homepage](https://github.com/jenkinsci/gitlab-plugin) 
- [] searched for similar already existing issue
- [] confirmed that my GitLab webhook is using the http://JENKINS_URL/project endpoint and not the http://JENKINS_URL/job endpoint

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

### Context
- **Gitlab plugin version**: X.Y.Z
- **Gitlab version**: X.Y.Z
- **Jenkins version**: X.Y.Z
- **Job type**: Pipeline, Freestyle, Matrix, etc.

### Logs & Traces

_Please include any relevant log that could serve to better understand the source of your issue_
For Jenkins Gitlab Plugin logs, follow instruction in [User Support section](https://github.com/jenkinsci/gitlab-plugin#user-support).
For Gitlab logs, ask an administrator to provide you the relevant Gitlab logs.

### Problem description

_Describe your problem in a meaningful way_:
- what were you doing (simple push, merge request, MR with fork, ...)
- what was expected
- what occurred finally

**Comment by JackTiger** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-22675

**Comment by MarkEWaite** [comment]
Not enough information on this issue report for any further progress.  [JENKINS-22675](https://issues.jenkins.io/browse/JENKINS-22675) was resolved 5 years before this issue was submitted.
