### ISSUE TITLE
Not triggering on -Tag push events-

### ISSUE THREAD

**Issue by netzwerch** [jenkinsci/gitlab-plugin#96]
I noticed the following behaviour (with Jenkins 1.609.1, GitLab Plugin 1.1.24, GitLab 7.12.2):

1. When pushing regular commits (git push), the build gets started and everything is fine.
2. When pushing tags (git push --tags), no action happens.

Thats sad, cause I'd really like to use the only-on-tag build function. Does someone have an idea how to fix that?

See my Jenkins log below for more clues

**Log after selecting *Push events* only**
```
Jul 22, 2015 5:03:26 PM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: /build

Jul 22, 2015 5:03:26 PM FINE com.dabsquared.gitlabjenkins.GitLabWebHook
data: {
    "object_kind": "push",
    ...
}

Jul 22, 2015 5:03:26 PM FINE com.dabsquared.gitlabjenkins.GitLab
Connecting to Gitlab server (http://gitlab:10080)

Jul 22, 2015 5:03:26 PM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$1 run
sample.project triggered for push.

Jul 22, 2015 5:03:26 PM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$1 createActions
GitLab Push Request from branch master.

Jul 22, 2015 5:03:26 PM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$1 createActions
Trying to get name and URL for job: sample.project using project sample.project (push)

Jul 22, 2015 5:03:26 PM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$1 run
GitLab Push Request detected in sample.project. Triggering  #55
```

**Log after selecting *Tag push events* only**
```
Jul 22, 2015 4:52:35 PM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: /build

Jul 22, 2015 4:52:35 PM FINE com.dabsquared.gitlabjenkins.GitLabWebHook
data: {
    "object_kind": "tag_push",
    ...
}

Jul 22, 2015 4:52:35 PM FINE com.dabsquared.gitlabjenkins.GitLab
Connecting to Gitlab server (http://gitlab:10080)
```

**Comment by omehegan** [comment]
With the current version of the plugin, a build will trigger if:
- Jenkins job is configured to build on push
- You create a tag webhook in GitLab
- You do a 'git push --tags'

If the Jenkins job is not configured to build on push, it won't build when a tag is created/pushed. Is that the functionality you want @netzwerch? Jenkins job only runs when a tag is pushed?

**Comment by mattiasb** [comment]
@omehegan Hm I have all three above set in my job and builds won't trigger on just tag pushes. 

GitLab 8.1.4
Jenkins 1.656
gitlab-plugin 1.1.32
git-plugin 2.4.4
git-tag-message-plugin 1.4 (to get the tag as an env-var)

**Comment by omehegan** [comment]
Can you look at the Jenkins log and see what it says when you push? It should tell us if it is receiving anything and, if so, why it is ignoring it.

**Comment by mattiasb** [comment]
Sure, will do that first thing tomorrow!

**Comment by mattiasb** [comment]
I get this:

```
apr 19, 2016 7:18:18 FM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic

WebHook called with url: 
```

**Comment by omehegan** [comment]
Surely there are a few more relevant lines...

**Comment by mattiasb** [comment]
No. Everything before that is from the day before.

EDIT: unless there is a way to turn on more debugging in Jenkins? (Didn't think of that).

**Comment by mattiasb** [comment]
Ok so the issue was that I had a branchfilter set to "develop, master, release/*". Sorry for the noise.

**Comment by dreadwarrior** [comment]
@mattiasb I'm currently facing the same issue and I'd like to ask you where did you set up the branchfilter? Currently, I use a Jenkins pipeline `checkout` with filtering on `refs/heads/master` and `refs/tags/*`, but I can't make it to read the GIT_TAG_NAME from the `Git Tag Message Plugin`.

**Comment by vitorhas** [comment]
@mattiasb Hello there! I'm facing the same issue and I would like to ask what solution you did to solve this? Did you just remove all the branches in branch specifier in job? Thanks

**Comment by itskaranshah** [comment]
Did anyone figured it out?

**Comment by hellojukay** [comment]
i have the same problem
