### ISSUE TITLE
add ability to flush the cached connection

### ISSUE THREAD

**Issue by Ladicek** [jenkinsci/gitlab-plugin#963]
### Context
- **Gitlab plugin version**: 1.5.12
- **Gitlab version**: GitLab Community Edition 11.10.1
- **Jenkins version**: 2.121.3
- **Job type**: Freestyle (but that should be irrelevant)

Today, I experienced a situation where Jenkins wasn't able to submit build status to GitLab, saying `Failed to update Gitlab commit status for project '19795': HTTP 401 Unauthorized`.

I revoked the access token on GitLab side, created a new token, and performed an in-place update of the token in the Jenkins credentials associated with the GitLab connection I have defined in my Jenkins. The error persisted.

I looked into the GitLab plugin source code (= this repo) and eventually found that if the connection has been created once, it's cached for subsequent use: https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/connection/GitLabConnection.java#L48 Using the Jenkins script console, I confirmed that the cached client uses the old token.

### Feature request

I now understand that I should probably have removed the GitLab connection entirely and create a new one, but that can hardly be considered intuitive.

Instead, I'd like to propose a new feature: next to the `Test Connection` button, add another one, called e.g. _Clear Connection Cache_ (perhaps with a help text that includes something like "this is useful when you update the credentials"). This button would set the `apiCache` field to `null`, forcing creation of a new client. (It should also dispose all resources that the client holds, but I don't know anything about that.)

**Comment by arechavarria** [comment]
#1712 This pull request addresses this need.The same thing happened to me, but using AWS Secret Manager, the credential is cached and causes interactions with the API to generate a 401, if the credential were to change in the vault.
