### ISSUE TITLE
Building different job depends on branch

### ISSUE THREAD

**Issue by Grogdunn** [jenkinsci/gitlab-plugin#97]
Hi,
my is not a real issues, but is a good question (to add into README).
In my Jenkins I have a different Job for different branch, master and release branches build the software for internal test and for customer deploy respectively.

With this plugin how I can trigger from one repo two jobs depending on pushed branch?

Thanks a lot,
Grogdunn

**Comment by markus-mnm** [comment]
Some of our projects have different (and odd) work flows depending on the branch.

Master gets deployed to DEV, a "version-*" branch gets automatically deployed to UAT, but has to be manually pushed to production systems.
Any other branch only gets build on merge requests.

The master build job has an include filter of "master"
The version build job has an include filter of "version_"
And the other-branches job has an include filter of "_" and an exclude filter of "master, version*"

I know this is a bit late but maybe it will help someone else.
