### ISSUE TITLE
user_username not present in gitlab plugin

### ISSUE THREAD

**Issue by bbreijer** [jenkinsci/gitlab-plugin#973]
### Context
- **Gitlab plugin version**: 1.5.12
- **Gitlab version**: 12.2.4
- **Jenkins version**: 2.193
- **Job type**: All (Pipeline, Freestyle, Matrix, etc.)

### Logs & Traces

Gitlab webhook payload: https://docs.gitlab.com/ee/user/project/integrations/webhooks.html

### Problem description

_The username (not Full name) is provided in the webhook, but not available in jenkins_:
- The environment of Jenkins does not contain the username of the user who triggered the build, but only the full name.
- The username is available in the webhook as `user_username`

For convenience i provided a pull request with this addition.

**Comment by markjacksonfishing** [comment]
Fixed with https://github.com/jenkinsci/gitlab-plugin/pull/969

**Comment by zdtsw** [comment]
Could you point out which release includes this fix? 
I am currently on 1.5.13 and it does not work for me, looking thro release notes, could not indicate which version exactly I should install, from 1.5.14 till 1.5.17

Thanks!

**Comment by bbreijer** [comment]
@zdtsw There was an issue with the release (i don't know if it is fixed already).
You can also download the package which is the result of the CI build and upload it manually using the advance tab (this is what i did). The CI build of this issue is not available anymore (https://ci.jenkins.io/job/Plugins/job/gitlab-plugin/job/PR-969/12/display/redirect), but any recent CI build should work.

@markyjackson-taulia Is there any news on the release impediment?

**Comment by zdtsw** [comment]
@bbreijer Tested on the last commit( 1bf706bc807051da7fc4e0843bf4e306888ff743) 's artifacts, it works so well!
But I need to get a proper release for my production server.  :D
Wait a bit for @markyjackson-taulia

**Comment by chenlujjj** [comment]
@bbreijer Hi, any update on this issue ? BTW, where can I get the CI build artifacts ?

**Comment by bbreijer** [comment]
@chenlujjj I'am not sure if there is any progress on the release impediment, could you elaborate on this @markyjackson-taulia ?

I think the last artefact can be found on the Jenkins instance of this plugin: https://ci.jenkins.io/job/Plugins/job/gitlab-plugin/job/master/ it is from Februari.

**Comment by chenlujjj** [comment]
@bbreijer Thanks for your reply. I will try the newest successful CI build artifact.
