### ISSUE TITLE
Branch delete push event missing

### ISSUE THREAD

**Issue by morpheus133** [jenkinsci/gitlab-plugin#976]
Because correction of #294 it is not possible to handle push request when delete is happen.
But some time it is needed to, delete jobs, tests, etc. in case of a branch delete.
Suggestions to correction:
-  Revert correction and everybody handle branch deletion in his own job (check before and after)
- Make it configurable in the plugin to handle branch deletion.

**Comment by markjacksonfishing** [comment]
Merged and preparing a release
