### ISSUE TITLE
about "Filter branches by regex"

### ISSUE THREAD

**Issue by panda7168** [jenkinsci/gitlab-plugin#981]
I need to use "Filter branches by regex" in "branchFilterType". How do I use parameters to define "Filter branches by regex" and "Target Branch Regex"?

It seems that there is a "RegexBasedFilter" corresponding to "Filter branches by regex"? But "Target Branch Regex" was not found.

**Comment by eryajf** [comment]
I have the same doubts about this issue.

**Comment by eryajf** [comment]
After testing, I found that the syntax rules for using regular filtering branches in pipeline are as follows:

```
triggers{
    gitlab( triggerOnPush: true,
    triggerOnMergeRequest: true,
    branchFilterType: "RegexBasedFilter",
    sourceBranchRegex: "test.*",
    secretToken: "${env.git_token}")
}
```
