### ISSUE TITLE
Understanding the plugin

### ISSUE THREAD

**Issue by jmStrickl** [jenkinsci/gitlab-plugin#986]
There we no where to ask this question, but where does this plugin get triggered from Gitlab. I'm just trying to understand the basic path of the program but I can't due to the complexity. So I would appreciate if anyone could point me in a good direction. Thank you.

**Comment by Saucistophe** [comment]
I'm not sure what information you would need that are not in the [README](https://github.com/jenkinsci/gitlab-plugin).

You have to setup Jenkins to talk to Gitlab, setup Gitlab to talk to Jenkins, then when you commit to gitlab, gitlab handles the jenkins builds and provides a heap of MR-related variables.

Do you have any particular question or part of the process that eludes you?
