### ISSUE TITLE
Plugin not resolving status of skipped step

### ISSUE THREAD

**Issue by Bryksin** [jenkinsci/gitlab-plugin#999]
When a stage is skipped due to `when` expression, GitLab plugin status keep waiting for that stage to report own build status

example: 
```
        stage("Publish to Artifactory") {
            when {
                brnach 'master'
            }
            steps {
                gitlabCommitStatus(name: 'Publish to Artifactory') {
                    script {
                        def server = Artifactory.server ARTIFACTORY_SERVER_ID
                        def uploadSpec = """{
                            "files": [
                                {
                                    "pattern": "${CLONED_REPO_PATH_HOST}/${ARTIFACT_PATH}/${ARTIFACT_FULL_NAME}",
                                    "target": "${ARTIFACTORY_PATH}/${ARTIFACT_VERSION}/"
                                }
                            ]
                        }"""
                        server.upload(uploadSpec)
                    }
                }
            }
        }
```

In that example stage will not be executed for any non-master branch, however, GitLab will not resolve merge request as build reporter will keep waiting for the status of the skipped step

What is the best approach to resolve it?

**Comment by wannadream** [comment]
I think the code below is what you are looking for.

`stage("e2e-test") {
            steps {
                script {
                    def action = "${env.gitlabActionType}"
                    if (action != "MERGE") {
                        updateGitlabCommitStatus(name: 'e2e-test', state: 'skipped')
                    } else {
                        gitlabCommitStatus('e2e-test') {
                           // do something
                        }
                    }
                }
            }
        }`

However, current plugin is a little behind. It will throw an exception as below.

`java.lang.IllegalArgumentException: No enum constant com.dabsquared.gitlabjenkins.gitlab.api.model.BuildState.skipped`

GitLab should have added 'skipped' status. https://docs.gitlab.com/ee/api/pipelines.html
Jenkins plugin once had it and them removed it. Not sure about the reason. https://github.com/jenkinsci/gitlab-plugin/commit/e341bc72dc41e93cf16fe6b2ec6531b08fe3ef37

**Comment by theiamdude** [comment]
This option was there between 1.5.7 and 1.5.9. From 1.5.10 onwards, it's gone missing.
I have raised a PR to add the config back in the plugin in future release #1015

**Comment by varrix** [comment]
Any progress on this?

**Comment by mindrunner** [comment]
I know, this plugin lacks a maintainer, but it seems this feature was merged and there has not been a release since a year or so. 

What can we do to release the current state of the source to jenkins-plugins?
